/**
 * `onus test --assumptions` (language spec §20.2, §20.6): each `verify` block
 * runs with capabilities the environment supplies. The environment is a
 * `test module` whose public zero-parameter functions return capabilities
 * (typically `fake`s); root capabilities of `std.io` come from the runtime
 * when the environment does not provide them. A verify parameter with no
 * source is E0603.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Context } from '../context.js';
import { diagnostic } from '../report/diagnostic.js';
import type { DefId, ModuleRecord } from '../resolve/defs.js';
import { stripRefinements } from '../types/type.js';
import type { EmittedModule } from './emit.js';

export interface AssumptionPlan {
  readonly env: ModuleRecord | null;
  /** Capability definition → the environment function producing it. */
  readonly producers: ReadonlyMap<DefId, DefId>;
}

const ROOTS: ReadonlySet<string> = new Set(['std.io.Files', 'std.io.Env', 'std.io.Net', 'std.io.Clock']);

/** The environment's producers: public zero-parameter functions returning a capability. Effects: none. */
export function planAssumptions(ctx: Context, env: ModuleRecord | null): AssumptionPlan {
  const producers = new Map<DefId, DefId>();
  if (env !== null) {
    for (const item of env.module.items) {
      if (item.kind !== 'FnDecl' || !item.vis.pub || item.params.length > 0) continue;
      const def = ctx.resolve.defOf.get(item.id);
      const sig = def === undefined ? undefined : ctx.types.signatures.get(def);
      if (def === undefined || sig === undefined) continue;
      const ret = stripRefinements(sig.ret);
      if (ret.k === 'capability' && !producers.has(ret.def)) producers.set(ret.def, def);
    }
  }
  return { env, producers };
}

/**
 * Checks that every verify parameter has a source: an environment producer or
 * a root capability. Effects: reports E0603.
 */
export function checkAssumptionPlan(ctx: Context, plan: AssumptionPlan, emitted: readonly EmittedModule[]): boolean {
  let ok = true;
  for (const m of emitted) {
    for (const v of m.verifies) {
      for (const p of v.params) {
        if (plan.producers.has(p.capability) || ROOTS.has(ctx.resolve.qualifiedName(p.capability))) continue;
        ok = false;
        const span = ctx.resolve.node(p.node).span;
        ctx.sink.report(diagnostic({ code: 'E0603', span, def: v.def.split('.').pop() ?? null, context: [`no environment function returns \`${ctx.resolve.qualifiedName(p.capability)}\` for verify parameter \`${p.name}\`${plan.env === null ? '; give one with a `test module` (onus.json `test.env` or --env)' : ` in \`${plan.env.name}\``}`] }));
      }
    }
  }
  return ok;
}

/** One verification result as the launcher prints it. */
export interface VerifyOutcome {
  readonly key: string;
  readonly claim: string;
  readonly def: string;
  readonly at: string;
  readonly result: 'passed' | 'failed';
  readonly detail: string;
}

/**
 * Writes `run_assumptions.js` into `outDir`: constructs each parameter and
 * runs every verify function, printing one JSON array of outcomes.
 * Preconditions: `checkAssumptionPlan` passed.
 * Effects: writes a file.
 */
export function writeAssumptionsLauncher(ctx: Context, outDir: string, emitted: readonly EmittedModule[], plan: AssumptionPlan, runtime: string): string {
  const t = ctx.resolve;
  const lines: string[] = ['// Generated by onus: runs every verify block against the environment (§20.2).', `import * as $rt from ${JSON.stringify(runtime)};`];
  const alias = new Map<string, string>();
  const importOf = (name: string): string => {
    let a = alias.get(name);
    if (a === undefined) {
      a = `$m${alias.size}`;
      alias.set(name, a);
      lines.push(`import * as ${a} from ${JSON.stringify(`./${name.split('.').join('/')}.js`)};`);
    }
    return a;
  };
  const calls: string[] = [];
  for (const m of emitted) {
    for (const v of m.verifies) {
      const mod = importOf(m.module.name);
      const args = v.params.map((p) => {
        const producer = plan.producers.get(p.capability);
        if (producer !== undefined && plan.env !== null) return `${p.name}: ${importOf(plan.env.name)}.${t.def(producer).name}()`;
        return `${p.name}: $rt.io.${t.def(p.capability).name}.root()`;
      });
      calls.push(`run(${JSON.stringify({ key: v.key, claim: v.claim, def: v.def, at: v.at })}, () => ${mod}.${v.name}({ ${args.join(', ')} }));`);
    }
  }
  lines.push(
    'const results = [];',
    'function run(info, f) {',
    '  try {',
    "    const ok = f() === true;",
    "    results.push({ ...info, result: ok ? 'passed' : 'failed', detail: ok ? '' : 'the block yielded false' });",
    '  } catch (e) {',
    "    results.push({ ...info, result: 'failed', detail: e instanceof Error ? e.message : String(e) });",
    '  }',
    '}',
    ...calls,
    "process.stdout.write(JSON.stringify(results) + '\\n');",
    '$rt.io.closeAll();',
  );
  const path = join(outDir, 'run_assumptions.js');
  writeFileSync(path, `${lines.join('\n')}\n`);
  return path;
}

/** Parses the launcher's output. Effects: none. */
export function parseOutcomes(text: string): VerifyOutcome[] {
  const parsed: unknown = JSON.parse(text.trim().split('\n').pop() ?? '[]');
  if (!Array.isArray(parsed)) return [];
  return parsed.flatMap((x: unknown) => (isOutcome(x) ? [x] : []));
}

function isOutcome(v: unknown): v is VerifyOutcome {
  return typeof v === 'object' && v !== null && 'key' in v && 'result' in v && (v.result === 'passed' || v.result === 'failed');
}
