/**
 * `onus build` and `onus run` (impl spec §6): runs the pipeline through the
 * contracts pass, emits every loaded module into the output directory, and
 * for `run` executes the entry module's `main` with the root capabilities
 * it names, in one step.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Context } from '../context.js';
import type { DefId } from '../resolve/defs.js';
import { runPipeline } from '../driver.js';
import { emitModule, type EmittedModule, type EmitOptions } from './emit.js';

export interface BuildOptions {
  readonly outDir: string;
  readonly ts: boolean;
  /** Also emit every `verify` block as a function (`onus test --assumptions`). */
  readonly verify?: boolean;
  /** Negate the guards of this property's generators (`onus test --mutate`, §20.4). */
  readonly negateGuard?: DefId;
}

export interface BuildResult {
  readonly emitted: readonly EmittedModule[];
  /** Path of the launcher for the entry module's `main`, when it has one. */
  readonly launcher: string | null;
}

/** The runtime package's entry point, as an absolute path generated code can import. Effects: none. */
export function runtimeEntry(): string {
  return fileURLToPath(import.meta.resolve('@onus/runtime'));
}

/**
 * Emits every module of `ctx` into `outDir`.
 * Preconditions: `runPipeline(ctx, 'contracts')` reported no diagnostics.
 * Effects: writes files under `outDir`.
 */
export function emitAll(ctx: Context, opts: BuildOptions): BuildResult {
  const ext = opts.ts ? 'ts' : 'js';
  const runtime = runtimeEntry();
  const emitted: EmittedModule[] = [];
  mkdirSync(opts.outDir, { recursive: true });
  writeFileSync(join(opts.outDir, 'package.json'), '{\n  "type": "module"\n}\n');
  // Generated tests run with `vitest run --root <outDir> --config <outDir>/vitest.config.mjs`.
  writeFileSync(join(opts.outDir, 'vitest.config.mjs'), `export default { test: { include: ['**/*.examples.test.${ext}'], environment: 'node' } };\n`);
  if (opts.ts) {
    writeFileSync(
      join(opts.outDir, 'tsconfig.json'),
      JSON.stringify(
        {
          compilerOptions: { strict: true, module: 'NodeNext', moduleResolution: 'NodeNext', target: 'ES2022', lib: ['ES2022'], types: ['node'], noEmit: true, skipLibCheck: true },
          include: ['**/*.ts'],
        },
        null,
        2,
      ),
    );
  }
  let launcher: string | null = null;
  const entry = ctx.resolve.modules[0] ?? null;
  for (const m of ctx.resolve.modules) {
    const emitOpts: EmitOptions = { ts: opts.ts, runtime, ...(opts.verify === true ? { verify: true } : {}), ...(opts.negateGuard === undefined ? {} : { negateGuard: opts.negateGuard }) };
    // A program's test run is its own examples: the standard library's run with the library, not with every program.
    const raw = emitModule(ctx, m, emitOpts);
    const out: EmittedModule = m.isStd && entry !== null && !entry.isStd ? { ...raw, tests: null } : raw;
    emitted.push(out);
    const path = join(opts.outDir, ...m.name.split('.')) + `.${ext}`;
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, out.code);
    if (out.tests !== null) writeFileSync(join(opts.outDir, ...m.name.split('.')) + `.examples.test.${ext}`, out.tests);
    if (entry !== null && m.id === entry.id && out.main !== null && !opts.ts) {
      launcher = join(opts.outDir, `run_${m.name.replace(/\./g, '_')}.js`);
      const rel = `./${m.name.split('.').join('/')}.js`;
      writeFileSync(
        launcher,
        `// Generated by onus: launches ${m.name}.main.\nimport * as $rt from ${JSON.stringify(runtime)};\nimport { main } from ${JSON.stringify(rel)};\nprocess.exitCode = $rt.runMain(main, ${JSON.stringify(out.main)}, process.argv.slice(2));\n`,
      );
    }
  }
  return { emitted, launcher };
}

/**
 * Builds `ctx` (already holding the entry file) and returns the result, or
 * null when the pipeline reported diagnostics.
 * Effects: those of the pipeline and `emitAll`.
 */
export function build(ctx: Context, opts: BuildOptions): BuildResult | null {
  runPipeline(ctx, 'paths');
  if (ctx.sink.hasErrors()) return null;
  return emitAll(ctx, opts);
}

/**
 * Runs a built launcher with `args`.
 * Effects: spawns node; inherits stdio.
 */
export function runLauncher(launcher: string, args: readonly string[]): number {
  const r = spawnSync(process.execPath, [resolve(launcher), ...args], { stdio: 'inherit' });
  return r.status ?? 1;
}
