/**
 * The JavaScript emitter (impl spec §6): renders the target-neutral form of
 * `ir.ts` as one ES module per Onus module, plus the module's vitest file
 * and `verify` functions. Conventions:
 *
 *   - declared functions take one object of named parameters; function
 *     values are positional, so a declared function used as a value gets an
 *     adapter;
 *   - a function with `inout` parameters returns `[result, ...inout]`;
 *   - `try` unwinds with `EarlyReturn`, caught by the enclosing function;
 *   - `match` is a labelled block of pattern tests in arm order;
 *   - records are plain objects, variants carry `tag`;
 *   - a bounded type parameter `T: I` becomes a hidden dictionary argument;
 *   - a runtime check is `$rt.check(cond, obligationRef)`.
 *
 * Under `--emit ts` (fixture suite only) the same emitter writes TypeScript
 * whose types derive from the Onus types; it must pass `tsc --strict`.
 */
import type { Value } from '../consteval/values.js';
import type { Context } from '../context.js';
import type { Def, DefId, ModuleId, ResolveTables } from '../resolve/defs.js';
import type { Signature, TypeTables } from '../types/tables.js';
import { stripRefinements, type ConstValue, type Type } from '../types/type.js';
import type { EmitOptions, EmittedModule } from './emit.js';
import type { IrBlock, IrDecoder, IrExpr, IrFn, IrGen, IrImpl, IrModule, IrStmt, IrTests, IrVerify, ObRef } from './ir.js';

const RESERVED = new Set([
  'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do', 'else', 'enum', 'export', 'extends',
  'false', 'finally', 'for', 'function', 'if', 'import', 'in', 'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this', 'throw', 'true',
  'try', 'typeof', 'var', 'void', 'while', 'with', 'yield', 'let', 'static', 'implements', 'interface', 'package', 'private', 'protected', 'public',
  'arguments', 'eval', 'undefined', 'NaN', 'Infinity',
]);

const GLOBAL_TYPES = new Set(['Error', 'Map', 'Set', 'Object', 'Array', 'Promise', 'Date', 'Function', 'Symbol', 'Number', 'String', 'Boolean', 'Record', 'Partial', 'Readonly', 'Required', 'Pick', 'Omit']);

const ATOM = 20;
const CALL = 17;
const UNARY = 14;
const MUL = 12;
const ADD = 11;
const CMP = 9;
const EQ = 8;
const AND = 4;
const OR = 3;
const ARROW = 2;

interface Piece {
  readonly code: string;
  readonly prec: number;
}

function piece(code: string, prec: number): Piece {
  return { code, prec };
}

function at(p: Piece, min: number): string {
  return p.prec >= min ? p.code : `(${p.code})`;
}

class Writer {
  private readonly lines: string[] = [];
  private depth = 0;

  line(s = ''): void {
    this.lines.push(s === '' ? '' : `${'  '.repeat(this.depth)}${s}`);
  }

  indent(): void {
    this.depth += 1;
  }

  dedent(): void {
    this.depth -= 1;
  }

  block(open: string, body: () => void, close = '}'): void {
    this.line(open);
    this.indent();
    body();
    this.dedent();
    this.line(close);
  }

  text(): string {
    return this.lines.join('\n');
  }
}

/** What the emitter knows about the function whose body it is writing. */
interface FnCtx {
  readonly inout: readonly string[];
  readonly ret: Type;
}

/**
 * Emits one lowered module.
 * Effects: none (returns text).
 */
export function emitJs(ctx: Context, ir: IrModule, opts: EmitOptions): EmittedModule {
  return new JsEmitter(ctx, ir, opts).run();
}

class JsEmitter {
  private readonly t: ResolveTables;
  private readonly ty: TypeTables;
  private readonly m: IrModule['module'];
  private w = new Writer();
  private readonly imports = new Map<ModuleId, string>();
  private readonly obDecls: string[] = [];
  private readonly obRefs = new Map<string, string>();
  private selfAlias: string | null = null;
  private fn: FnCtx | null = null;
  /** How a bare assertion renders: as a vitest expectation, or as an early `return false`. */
  private assertMode: 'expect' | 'return-false' = 'return-false';

  constructor(
    ctx: Context,
    private readonly ir: IrModule,
    private readonly opts: EmitOptions,
  ) {
    this.t = ctx.resolve;
    this.ty = ctx.types;
    this.m = ir.module;
  }

  run(): EmittedModule {
    for (const item of this.ir.items) this.item(item);
    const verifies = this.ir.verifies.map((v) => this.verifyFunction(v));
    const body = this.w.text();
    const head = new Writer();
    head.line(`// Generated by onus from module ${this.m.name}. Do not edit.`);
    head.line(`import * as $rt from ${JSON.stringify(this.opts.runtime)};`);
    for (const [id, alias] of this.imports) head.line(`import * as ${alias} from ${JSON.stringify(this.relativeImport(id))};`);
    if (this.opts.ts && this.m.module.test) head.line('');
    head.line('');
    for (const d of this.obDecls) head.line(d);
    if (this.obDecls.length > 0) head.line('');
    const tests = this.ir.tests === null ? null : this.testsFile(this.ir.tests);
    return { module: this.m, code: `${head.text()}${body}\n`, tests, main: this.ir.main, verifies };
  }

  // -------------------------------------------------------------------------
  // Naming
  // -------------------------------------------------------------------------

  private relativeImport(id: ModuleId): string {
    const from = this.m.name.split('.');
    const to = this.t.moduleOf(id).name.split('.');
    const ups = from.length - 1;
    const prefix = ups === 0 ? './' : '../'.repeat(ups);
    return `${prefix}${to.join('/')}.js`;
  }

  private alias(id: ModuleId): string {
    if (id === this.m.id && this.selfAlias !== null) return this.selfAlias;
    const existing = this.imports.get(id);
    if (existing !== undefined) return existing;
    const alias = `$${this.t.moduleOf(id).name.replace(/\./g, '_')}`;
    this.imports.set(id, alias);
    return alias;
  }

  private local(name: string): string {
    return RESERVED.has(name) ? `${name}_` : name;
  }

  private typeName(name: string): string {
    return GLOBAL_TYPES.has(name) ? `${name}_` : name;
  }

  /** A module-level name, qualified by its module's alias when it lives elsewhere. */
  private qualified(module: ModuleId, name: string): string {
    const base = this.local(name);
    if (module === this.m.id && this.selfAlias === null) return base;
    return `${this.alias(module)}.${base}`;
  }

  private obRef(o: ObRef): string {
    const key = `${o.kind}|${o.text}|${o.at}|${o.def}`;
    const existing = this.obRefs.get(key);
    if (existing !== undefined) return existing;
    const name = `$ob${this.obRefs.size + 1}`;
    this.obRefs.set(key, name);
    const literal = `{ kind: ${JSON.stringify(o.kind)}, text: ${JSON.stringify(o.text)}, at: ${JSON.stringify(o.at)}, def: ${JSON.stringify(o.def)} }`;
    this.obDecls.push(this.opts.ts ? `const ${name}: $rt.ObligationRef = ${literal};` : `const ${name} = ${literal};`);
    return name;
  }

  // -------------------------------------------------------------------------
  // Types (TypeScript mode)
  // -------------------------------------------------------------------------

  private tsType(t: Type): string {
    const s = stripRefinements(t);
    switch (s.k) {
      case 'prim':
        switch (s.name) {
          case 'Int':
          case 'Float':
          case 'Duration':
            return 'number';
          case 'Bool':
            return 'boolean';
          case 'Text':
            return 'string';
          case 'Unit':
            return 'undefined';
          case 'Bytes':
            return 'Uint8Array';
          case 'TypeInfo':
            return '$rt.TypeInfo';
          case 'Spec':
            return 'unknown';
        }
        break;
      case 'record':
      case 'union': {
        const def = this.t.def(s.def);
        const args = s.args.filter((a) => a.k === 'type').map((a) => (a.k === 'type' ? this.tsType(a.type) : ''));
        const name = def.module === this.m.id && this.selfAlias === null ? this.typeName(def.name) : `${this.alias(def.module)}.${this.typeName(def.name)}`;
        return args.length > 0 ? `${name}<${args.join(', ')}>` : name;
      }
      case 'opaque': {
        const q = this.t.qualifiedName(s.def);
        const targs = s.args.filter((a) => a.k === 'type').map((a) => (a.k === 'type' ? this.tsType(a.type) : ''));
        switch (q) {
          case 'std.list.List':
            return `readonly ${wrap(targs[0] ?? 'unknown')}[]`;
          case 'std.grid.Grid':
            return `$rt.grid.Grid<${targs[0] ?? 'unknown'}>`;
          case 'std.map.Map':
            return `$rt.map.Map<${targs[0] ?? 'unknown'}, ${targs[1] ?? 'unknown'}>`;
          case 'std.sql.Select':
            return `$rt.sql.Select<${targs[0] ?? 'unknown'}>`;
          case 'std.sql.Param':
            return '$rt.sql.Param';
          case 'std.sql.Statement':
            return '$rt.sql.Statement';
          default:
            return 'unknown';
        }
      }
      case 'capability': {
        const q = this.t.qualifiedName(s.def);
        if (q.startsWith('std.io.')) return `$rt.io.${this.t.def(s.def).name}`;
        if (q === 'std.sql.Db') return '$rt.sql.Db';
        return '$rt.Capability';
      }
      case 'fn':
        return `(${s.params.map((p) => `${this.local(p.name)}: ${this.tsType(p.type)}`).join(', ')}) => ${this.tsReturn(s.ret, s.params.filter((p) => p.inout).map((p) => p.type))}`;
      case 'param':
        return this.t.def(s.def).name;
      case 'typeinfo':
        return '$rt.TypeInfo';
      case 'spec':
        return 'unknown';
      case 'error':
        return 'never';
      case 'refined':
        return 'never';
    }
    return 'never';
  }

  private tsParams(params: readonly { readonly name: string; readonly type: Type }[], extra: readonly string[]): string {
    const fields = [...extra, ...params.map((p) => `${this.local(p.name)}: ${this.tsType(p.type)}`)];
    return fields.length === 0 ? 'Record<string, never>' : `{ ${fields.join('; ')} }`;
  }

  /** In TypeScript output, keeps a union-typed value at its declared type (see `$rt.widen`). */
  private widened(code: string, declared: Type): string {
    if (!this.opts.ts) return code;
    const s = stripRefinements(declared);
    return s.k === 'union' ? `$rt.widen<${this.tsType(declared)}>(${code})` : code;
  }

  private tsReturn(ret: Type, inout: readonly Type[]): string {
    const r = this.tsType(ret);
    return inout.length === 0 ? r : `[${[r, ...inout.map((t) => this.tsType(t))].join(', ')}]`;
  }

  private tsTypeParams(sig: Signature | null, extraDefs: readonly DefId[] = []): string {
    const names = [...(sig?.tparams.filter((p) => p.k === 'type').map((p) => this.t.def(p.def).name) ?? []), ...extraDefs.map((d) => this.t.def(d).name)];
    return names.length > 0 ? `<${names.join(', ')}>` : '';
  }

  private tsIfaceDict(iface: Def, target: Type): string {
    const name = iface.module === this.m.id ? this.typeName(iface.name) : `${this.alias(iface.module)}.${this.typeName(iface.name)}`;
    return `${name}<${this.tsType(target)}>`;
  }

  // -------------------------------------------------------------------------
  // Items
  // -------------------------------------------------------------------------

  private item(item: IrModule['items'][number]): void {
    switch (item.k) {
      case 'fn':
        this.fnDecl(item);
        return;
      case 'const': {
        const type = this.opts.ts ? `: ${this.tsType(item.type)}` : '';
        this.w.line(`export const ${this.local(item.def.name)}${type} = ${this.expr(item.value).code};`);
        this.w.line('');
        return;
      }
      case 'alias':
        if (this.opts.ts) {
          this.w.line(`export type ${this.typeName(item.def.name)} = ${this.tsType(item.type)};`);
          this.w.line('');
        }
        return;
      case 'intrinsic-type': {
        if (!this.opts.ts) return;
        const params = item.params.map((p) => this.t.def(p).name);
        const generic = params.length > 0 ? `<${params.join(', ')}>` : '';
        const q = this.t.qualifiedName(item.def.id);
        const body =
          q === 'std.list.List' ? `readonly ${params[0] ?? 'unknown'}[]` :
          q === 'std.grid.Grid' ? `$rt.grid.Grid<${params[0] ?? 'unknown'}>` :
          q === 'std.map.Map' ? `$rt.map.Map<${params[0] ?? 'unknown'}, ${params[1] ?? 'unknown'}>` :
          q === 'std.sql.Select' ? `$rt.sql.Select<${params[0] ?? 'unknown'}>` :
          q === 'std.sql.Param' ? '$rt.sql.Param' :
          q === 'std.sql.Statement' ? '$rt.sql.Statement' : 'unknown';
        this.w.line(`export type ${this.typeName(item.def.name)}${generic} = ${body};`);
        this.w.line('');
        return;
      }
      case 'record': {
        if (!this.opts.ts) return;
        this.w.block(`export interface ${this.typeName(item.def.name)}${this.tsTypeParams(null, item.params)} {`, () => {
          for (const f of item.fields) this.w.line(`readonly ${this.local(f.name)}: ${this.tsType(f.type)};`);
        });
        this.w.line('');
        return;
      }
      case 'union': {
        if (!this.opts.ts) return;
        const variants = item.variants.map((v) => `{ readonly tag: ${JSON.stringify(v.def.name)}${v.fields.map((f) => `; readonly ${this.local(f.name)}: ${this.tsType(f.type)}`).join('')} }`);
        this.w.line(`export type ${this.typeName(item.def.name)}${this.tsTypeParams(null, item.params)} =`);
        this.w.indent();
        variants.forEach((v, i) => this.w.line(`| ${v}${i === variants.length - 1 ? ';' : ''}`));
        this.w.dedent();
        this.w.line('');
        return;
      }
      case 'interface': {
        if (!this.opts.ts) return;
        this.w.block(`export interface ${this.typeName(item.def.name)}${item.tparam === null ? '' : `<${item.tparam}>`} {`, () => {
          for (const f of item.fns) {
            this.w.line(`readonly ${this.local(f.def.name)}: (args: ${this.tsParams(f.sig.params, [])}) => ${this.tsReturn(f.sig.ret, f.sig.params.filter((p) => p.inout).map((p) => p.type))};`);
          }
        });
        this.w.line('');
        return;
      }
      case 'impl':
        this.impl(item);
        return;
      case 'capability':
        if (this.opts.ts) {
          this.w.line(`export type ${this.typeName(item.def.name)} = $rt.Capability;`);
          this.w.line('');
        }
        return;
    }
  }

  private impl(item: IrImpl): void {
    for (const f of item.fns) this.fnDecl(f);
    const entries = item.entries.map((e) => `${this.local(e.name)}: ${e.fn.name}`);
    const type = this.opts.ts ? `: ${this.tsIfaceDict(item.iface, item.target)}` : '';
    this.w.line(`export const ${item.dictName}${type} = { ${entries.join(', ')} };`);
    this.w.line('');
  }

  private fnDecl(f: IrFn): void {
    const sig = f.sig;
    // `std.sql.select` also receives the compiler-generated row decoder (§18.2).
    const isSelect = f.intrinsic !== null && this.t.qualifiedName(f.def.id) === 'std.sql.select';
    const paramNames = [...f.dictParams.map((d) => d.name), ...f.constParams.map((c) => this.local(c.name)), ...f.params.map((p) => this.local(p.name)), ...(isSelect ? ['$decode'] : [])];
    const destructure = paramNames.length === 0 ? '$args' : `{ ${paramNames.join(', ')} }`;
    let tsSig: string;
    if (this.opts.ts) {
      const rowType = sig.tparams.find((p) => p.k === 'type');
      const extra = [
        ...f.dictParams.map((d) => `${d.name}: ${this.tsIfaceDict(this.t.def(d.iface), { k: 'param', def: d.def })}`),
        ...f.constParams.map((c) => `${this.local(c.name)}: ${this.tsType(c.type)}`),
      ];
      const decodeParam = isSelect && rowType !== undefined ? `; $decode?: $rt.sql.Decoder<${this.t.def(rowType.def).name}>` : '';
      const params = this.tsParams(f.params, extra);
      tsSig = `${this.tsTypeParams(sig)}(${destructure}: ${decodeParam === '' ? params : params.replace(/ }$/, `${decodeParam} }`)}): ${this.tsReturn(f.ret, f.params.filter((p) => p.inout).map((p) => p.type))}`;
    } else {
      tsSig = `(${destructure})`;
    }
    if (f.intrinsic !== null) {
      const args = [...f.constParams.map((c) => c.name), ...f.params.map((p) => p.name)].map((n) => this.local(n));
      if (isSelect) args.push('$decode ?? null');
      this.w.block(`export function ${f.name}${tsSig} {`, () => this.w.line(`return $rt.${f.intrinsic?.ns ?? ''}.${f.intrinsic?.name ?? ''}(${args.join(', ')});`));
      this.w.line('');
      return;
    }
    if (f.body === null) return;
    const body = f.body;
    this.fn = { inout: f.params.filter((p) => p.inout).map((p) => p.name), ret: f.ret };
    this.w.block(`export function ${f.name}${tsSig} {`, () => {
      this.block(f.entry);
      this.withEarlyReturn(f.earlyReturn, () => this.block(body));
    });
    this.w.line('');
    this.fn = null;
  }

  private withEarlyReturn(earlyReturn: boolean, emit: () => void): void {
    if (!earlyReturn) {
      emit();
      return;
    }
    this.w.block('try {', emit, '} catch ($e) {');
    this.w.indent();
    this.w.line('if ($e instanceof $rt.EarlyReturn) return $e.value;');
    this.w.line('throw $e;');
    this.w.dedent();
    this.w.line('}');
  }

  // -------------------------------------------------------------------------
  // Statements
  // -------------------------------------------------------------------------

  private block(b: IrBlock): void {
    for (const s of b) this.stmt(s);
  }

  private stmt(s: IrStmt): void {
    switch (s.k) {
      case 'let': {
        const type = this.opts.ts ? `: ${this.tsType(s.type)}` : '';
        this.w.line(`${s.mutable ? 'let' : 'const'} ${this.local(s.name)}${type} = ${this.widened(this.expr(s.value).code, s.type)};`);
        return;
      }
      case 'assign':
        this.w.line(`${this.local(s.name)} = ${this.expr(s.value).code};`);
        return;
      case 'return': {
        const value = this.expr(s.value).code;
        const fn = this.fn;
        if (fn === null || fn.inout.length === 0) {
          this.w.line(`return ${value};`);
          return;
        }
        this.w.line(`return [${value}${fn.inout.map((p) => `, ${this.local(p)}`).join('')}];`);
        return;
      }
      case 'if':
        this.w.block(`if (${this.expr(s.cond).code}) {`, () => this.block(s.then), s.else ? '} else {' : '}');
        if (s.else) {
          const e = s.else;
          this.w.indent();
          this.block(e);
          this.w.dedent();
          this.w.line('}');
        }
        return;
      case 'match': {
        const mType = this.opts.ts ? `: ${this.tsType(s.type)}` : '';
        this.w.line(`const ${s.tmp}${mType} = ${this.widened(this.expr(s.scrutinee).code, s.type)};`);
        const label = `${s.tmp}$match`;
        this.w.block(`${label}: {`, () => {
          for (const arm of s.arms) {
            this.w.block(`if (${arm.test === null ? 'true' : this.expr(arm.test).code}) {`, () => {
              for (const b of arm.bindings) this.w.line(`const ${this.local(b.name)} = ${this.expr(b.value).code};`);
              if (arm.guard) {
                this.w.block(`if (${this.expr(arm.guard).code}) {`, () => {
                  this.block(arm.body);
                  this.w.line(`break ${label};`);
                });
              } else {
                this.block(arm.body);
                this.w.line(`break ${label};`);
              }
            });
          }
          this.w.line('$rt.unreachable();');
        });
        return;
      }
      case 'loop':
        this.w.block(`while (${this.expr(s.cond).code}) {`, () => this.block(s.body));
        return;
      case 'for-range': {
        const name = this.local(s.name);
        const nt = this.opts.ts ? ': number' : '';
        this.w.block(`for (let ${name}${nt} = ${this.expr(s.lo).code}; ${name} < ${at(this.expr(s.hi), CMP + 1)}; ${name}++) {`, () => this.block(s.body));
        return;
      }
      case 'for-each':
        this.w.block(`for (const ${this.local(s.name)} of ${this.expr(s.list).code}) {`, () => this.block(s.body));
        return;
      case 'check':
        this.w.line(`$rt.check(${this.expr(s.cond).code}, ${this.obRef(s.ob)});`);
        return;
      case 'assert':
        if (this.assertMode === 'expect') this.w.line(`expect(${this.expr(s.cond).code}).toBe(true);`);
        else this.w.line(`if (!(${this.expr(s.cond).code})) return false;`);
        return;
      case 'expr': {
        const code = this.expr(s.expr).code;
        if (code !== '') this.w.line(`${code};`);
        return;
      }
      case 'call-inout': {
        const names = s.targets.map((x) => this.local(x.name));
        const tmps = names.map((n) => `${n}$`);
        this.w.line(`const [${s.result === null ? '' : this.local(s.result.name)}, ${tmps.join(', ')}] = ${this.expr(s.call).code};`);
        names.forEach((n, i) => this.w.line(`${n} = ${tmps[i] ?? n};`));
        return;
      }
      case 'unreachable':
        this.w.line('$rt.unreachable();');
        return;
      case 'comment':
        this.w.line(`// ${s.text}`);
        return;
      case 'reject':
        this.w.line(`if (!(${this.expr(s.cond).code})) throw new $rt.sql.Rejected($row, ${JSON.stringify(s.column)});`);
        return;
    }
  }

  /** A row decoder (§18.2): the record from the raw row's columns, then its refinements as `reject`s. */
  private decoder(d: IrDecoder): string {
    const it = this.local(d.it);
    const fields = d.fields.map((f) => `${this.local(f.name)}: $rt.sql.column(raw, ${JSON.stringify(f.name)}, ${JSON.stringify(f.kind)}, $row)`).join(', ');
    const sig = this.opts.ts ? `(raw: Readonly<Record<string, unknown>>, $row: number): ${this.tsType(d.type)}` : '(raw, $row)';
    const itType = this.opts.ts ? `: ${this.tsType(d.type)}` : '';
    return `${sig} => { const ${it}${itType} = { ${fields} }; ${this.inline(d.checks)} return ${it}; }`;
  }

  /** Renders statements into a single line, for check lists inside expressions. */
  private inline(stmts: IrBlock): string {
    const inner = new Writer();
    const outer = this.w;
    this.w = inner;
    this.block(stmts);
    this.w = outer;
    return inner.text().split('\n').map((l) => l.trim()).filter((l) => l !== '').join(' ');
  }

  /** Renders a block into indented lines for an arrow function body. */
  private nested(emit: () => void): string {
    const inner = new Writer();
    const outer = this.w;
    this.w = inner;
    inner.indent();
    emit();
    this.w = outer;
    return inner.text();
  }

  // -------------------------------------------------------------------------
  // Expressions
  // -------------------------------------------------------------------------

  private expr(e: IrExpr): Piece {
    switch (e.k) {
      case 'int':
        return piece(e.v.toString(), e.v < 0n ? UNARY : ATOM);
      case 'float':
        return piece(String(e.v), e.v < 0 ? UNARY : ATOM);
      case 'text':
        return piece(JSON.stringify(e.v), ATOM);
      case 'bool':
        return piece(e.v ? 'true' : 'false', ATOM);
      case 'unit':
        return piece('undefined', ATOM);
      case 'local':
        return piece(this.local(e.name), ATOM);
      case 'global':
        return piece(this.qualified(e.def.module, e.def.name), ATOM);
      case 'fnref': {
        const names = e.sig.params.map((p) => this.local(p.name));
        const typed = this.opts.ts ? e.sig.params.map((p) => `${this.local(p.name)}: ${this.tsType(p.type)}`) : names;
        return piece(`(${typed.join(', ')}) => ${this.qualified(e.def.module, e.name)}({ ${names.join(', ')} })`, ARROW);
      }
      case 'call': {
        const callee = e.target.k === 'fn' ? this.qualified(e.target.def.module, e.target.name) : `${at(this.expr(e.target.dict), CALL)}.${this.local(e.target.name)}`;
        const parts: string[] = [];
        let di = 0;
        let ci = 0;
        for (const p of e.sig.tparams) {
          if (p.k === 'type' && p.bound !== null) parts.push(`$dict_${this.t.def(p.def).name}: ${this.expr(e.dicts[di] ?? { k: 'unit' }).code}`), (di += 1);
          else if (p.k === 'const') parts.push(`${this.local(this.t.def(p.def).name)}: ${this.expr(e.consts[ci] ?? { k: 'unit' }).code}`), (ci += 1);
        }
        e.sig.params.forEach((p, i) => parts.push(`${this.local(p.name)}: ${this.expr(e.args[i] ?? { k: 'unit' }).code}`));
        if (e.decoder !== undefined) parts.push(`$decode: ${this.decoder(e.decoder)}`);
        return piece(`${callee}({ ${parts.join(', ')} })`, CALL);
      }
      case 'call-value':
        return piece(`${at(this.expr(e.callee), CALL)}(${e.args.map((a) => this.expr(a).code).join(', ')})`, CALL);
      case 'record':
        return piece(`{ ${e.fields.map((f) => `${this.local(f.name)}: ${this.expr(f.value).code}`).join(', ')} }`, ATOM);
      case 'variant':
        return piece(`{ ${[`tag: ${JSON.stringify(e.def.name)}`, ...e.fields.map((f) => `${this.local(f.name)}: ${this.expr(f.value).code}`)].join(', ')} }`, ATOM);
      case 'update':
        return piece(`{ ...${at(this.expr(e.base), CALL)}, ${e.fields.map((f) => `${this.local(f.name)}: ${this.expr(f.value).code}`).join(', ')} }`, ATOM);
      case 'field':
        return piece(`${at(this.expr(e.object), CALL)}.${this.local(e.name)}`, CALL);
      case 'list':
        return piece(`[${e.elems.map((x) => this.expr(x).code).join(', ')}]`, ATOM);
      case 'concat': {
        const l = this.expr(e.left);
        const r = this.expr(e.right);
        if (e.text) return piece(`${at(l, ADD)} + ${at(r, ADD + 1)}`, ADD);
        return piece(`[...${at(l, CALL)}, ...${at(r, CALL)}]`, ATOM);
      }
      case 'intop': {
        const l = this.expr(e.left);
        const r = this.expr(e.right);
        if (e.ob !== null) {
          const fnName = { '+': 'add', '-': 'sub', '*': 'mul', '/': 'div', '%': 'rem' }[e.op];
          return piece(`$rt.int.${fnName}(${l.code}, ${r.code}, ${this.obRef(e.ob)})`, CALL);
        }
        if (e.op === '/') return piece(`Math.trunc(${at(l, MUL)} / ${at(r, MUL + 1)})`, CALL);
        const prec = e.op === '+' || e.op === '-' ? ADD : MUL;
        return piece(`${at(l, prec)} ${e.op} ${at(r, prec + 1)}`, prec);
      }
      case 'floatop': {
        const prec = e.op === '+' || e.op === '-' ? ADD : MUL;
        return piece(`${at(this.expr(e.left), prec)} ${e.op} ${at(this.expr(e.right), prec + 1)}`, prec);
      }
      case 'neg': {
        const v = this.expr(e.operand);
        if (e.ob !== null) return piece(`$rt.int.neg(${v.code}, ${this.obRef(e.ob)})`, CALL);
        return piece(`-${at(v, UNARY)}`, UNARY);
      }
      case 'cmp':
        return piece(`${at(this.expr(e.left), CMP + 1)} ${e.op} ${at(this.expr(e.right), CMP + 1)}`, CMP);
      case 'eq': {
        const l = this.expr(e.left);
        const r = this.expr(e.right);
        if (e.prim) return piece(`${at(l, EQ + 1)} ${e.negate ? '!==' : '==='} ${at(r, EQ + 1)}`, EQ);
        const eq = `$rt.eq(${l.code}, ${r.code})`;
        return e.negate ? piece(`!${eq}`, UNARY) : piece(eq, CALL);
      }
      case 'not':
        return piece(`!${at(this.expr(e.operand), UNARY)}`, UNARY);
      case 'and':
        return piece(e.operands.map((o) => at(this.expr(o), AND + 1)).join(' && '), AND);
      case 'or':
        return piece(e.operands.map((o) => at(this.expr(o), OR + 1)).join(' || '), OR);
      case 'implies':
        return piece(`!${at(this.expr(e.left), UNARY)} || ${at(this.expr(e.right), OR + 1)}`, OR);
      case 'is-variant':
        return piece(`${at(this.expr(e.subject), CALL)}.tag === ${JSON.stringify(e.variant.name)}`, EQ);
      case 'try': {
        const operand = this.expr(e.operand).code;
        if (e.else === null) {
          if (e.option && e.outerOption) return piece(`$rt.unwrapOption(${operand})`, CALL);
          return piece(`$rt.unwrap(${operand})`, CALL);
        }
        const name = this.local(e.else.name ?? '_');
        const raw = this.expr(e.else.value).code;
        // An arrow function returning an object literal needs the literal parenthesised.
        const body = raw.startsWith('{') ? `(${raw})` : raw;
        if (e.raw) return piece(`$rt.${e.option ? 'unwrapOptionOr' : 'unwrapOr'}(${operand}, (${name}) => ${body})`, CALL);
        if (e.option) return piece(`$rt.unwrapOptionElse(${operand}, (${name}) => ${body})`, CALL);
        return piece(`$rt.unwrapElse(${operand}, (${name}) => ${body})`, CALL);
      }
      case 'recover': {
        const saved = this.fn;
        this.fn = saved === null ? null : { inout: [], ret: { k: 'error' } };
        const text = this.nested(() => {
          this.block(e.body);
          this.w.line(`return ${this.expr(e.value).code};`);
        });
        this.fn = saved;
        return piece(`$rt.recover(() => {\n${text}\n})`, CALL);
      }
      case 'quantifier': {
        let domain: string;
        switch (e.domain.k) {
          case 'bools':
            domain = '[true, false]';
            break;
          case 'range':
            domain = `$rt.range(${this.expr(e.domain.lo).code}, ${this.expr(e.domain.hi).code})`;
            break;
          case 'list':
            domain = this.expr(e.domain.expr).code;
            break;
          case 'oklist':
            domain = `$rt.okList(${this.expr(e.domain.expr).code})`;
            break;
        }
        const nt = this.opts.ts ? `: ${this.tsType(e.binder)}` : '';
        const body = e.where === null ? this.expr(e.body).code : `${at(this.expr(e.where), OR + 1)} ? ${at(this.expr(e.body), ARROW + 1)} : ${e.quant === 'forall' ? 'true' : 'false'}`;
        return piece(`$rt.${e.quant}(${domain}, (${this.local(e.name)}${nt}) => ${body})`, CALL);
      }
      case 'closure': {
        const ft = e.fnType;
        const params = e.params.map((p) => this.local(p.name));
        const sigText = this.opts.ts && ft !== null
          ? `(${ft.params.map((p) => `${this.local(p.name)}: ${this.tsType(p.type)}`).join(', ')}): ${this.tsReturn(ft.ret, ft.params.filter((p) => p.inout).map((p) => p.type))}`
          : `(${params.join(', ')})`;
        const saved = this.fn;
        this.fn = { inout: e.params.filter((p) => p.inout).map((p) => p.name), ret: ft?.ret ?? { k: 'error' } };
        const text = this.nested(() => {
          this.block(e.entry);
          this.withEarlyReturn(e.earlyReturn, () => this.block(e.body));
        });
        this.fn = saved;
        return piece(`${sigText} => {\n${text}\n}`, ARROW);
      }
      case 'fake':
        return piece(`$rt.Capability.__fake(${JSON.stringify(e.kind)}, { ${e.fields.map((f) => `${this.local(f.name)}: ${this.expr(f.value).code}`).join(', ')} }, $rt.FAKE_TOKEN)`, CALL);
      case 'checked': {
        // A variant literal's checks read its fields, so the callback is typed with the member, not the union.
        const itType = this.opts.ts ? `: ${e.value.k === 'variant' ? this.variantMemberType(e.value.def) : this.tsType(e.type)}` : '';
        return piece(`$rt.checked(${this.expr(e.value).code}, (${e.it}${itType}) => { ${this.inline(e.checks)} })`, CALL);
      }
      case 'typeinfo':
        return piece(`$rt.typeInfo(${JSON.stringify(e.name)}, [${e.fields.map((f) => `{ name: ${JSON.stringify(f.name)}, type_name: ${JSON.stringify(f.type_name)} }`).join(', ')}])`, CALL);
      case 'const':
        return piece(this.constLiteral(e.value), ATOM);
      case 'value':
        return piece(this.valueLiteral(e.value), ATOM);
      case 'dict':
        return piece(e.module === this.m.id && this.selfAlias === null ? e.name : `${this.alias(e.module)}.${e.name}`, ATOM);
      case 'dict-param':
        return piece(e.name, ATOM);
      case 'snapshot':
        return piece(`$rt.snapshot(${this.expr(e.value).code})`, CALL);
    }
  }

  /** The TypeScript object type of one variant. */
  private variantMemberType(variant: Def): string {
    const fields = (this.ty.fields.get(variant.id) ?? []).map((f) => `; readonly ${this.local(f.name)}: ${this.tsType(f.type)}`).join('');
    return `{ readonly tag: ${JSON.stringify(variant.name)}${fields} }`;
  }

  private constLiteral(v: ConstValue): string {
    switch (v.k) {
      case 'int':
      case 'duration':
        return v.v.toString();
      case 'float':
        return String(v.v);
      case 'bool':
        return v.v ? 'true' : 'false';
      case 'text':
        return JSON.stringify(v.v);
      case 'unit':
        return 'undefined';
      case 'variant':
        return `{ tag: ${JSON.stringify(this.t.def(v.def).name)} }`;
      case 'sym':
        return this.local(this.t.def(v.def).name);
      case 'error':
        return 'undefined';
    }
  }

  private valueLiteral(v: Value): string {
    switch (v.k) {
      case 'int':
      case 'float':
      case 'duration':
        return String(v.v);
      case 'bool':
        return v.v ? 'true' : 'false';
      case 'text':
        return JSON.stringify(v.v);
      case 'unit':
        return 'undefined';
      case 'bytes':
        return `new Uint8Array([${[...v.v].join(', ')}])`;
      case 'list':
        return `[${v.items.map((x) => this.valueLiteral(x)).join(', ')}]`;
      case 'record':
        return `{ ${[...v.fields].map(([n, x]) => `${this.local(n)}: ${this.valueLiteral(x)}`).join(', ')} }`;
      case 'variant': {
        const parts = [`tag: ${JSON.stringify(this.t.def(v.def).name)}`, ...[...v.fields].map(([n, x]) => `${this.local(n)}: ${this.valueLiteral(x)}`)];
        return `{ ${parts.join(', ')} }`;
      }
      case 'typeinfo': {
        if (v.owner.k !== 'def') return `$rt.typeInfo(${JSON.stringify(v.owner.k === 'prim' ? v.owner.name : '?')}, [])`;
        const d = this.t.def(v.owner.def);
        const fields = (this.ty.fields.get(v.owner.def) ?? []).map((f) => `{ name: ${JSON.stringify(f.name)}, type_name: ${JSON.stringify(typeSlug(this.t, f.type))} }`);
        return `$rt.typeInfo(${JSON.stringify(d.name)}, [${fields.join(', ')}])`;
      }
    }
  }

  // -------------------------------------------------------------------------
  // Generated tests (§5.2, §3.6) and verify functions (§20.2)
  // -------------------------------------------------------------------------

  private testsFile(tests: IrTests): string {
    const inner = new Writer();
    const outer = this.w;
    this.w = inner;
    const savedImports = new Map(this.imports);
    this.imports.clear();
    this.selfAlias = '$self';
    this.imports.set(this.m.id, '$self');
    const obSaved = this.obDecls.splice(0);
    const obRefsSaved = new Map(this.obRefs);
    this.obRefs.clear();
    inner.line(`import { test, expect, afterAll } from 'vitest';`);
    inner.line(`import * as fc from 'fast-check';`);
    this.fn = null;
    for (const ex of tests.examples) {
      this.assertMode = 'expect';
      inner.block(`test(${JSON.stringify(ex.name)}, () => {`, () => this.block(ex.body), '});');
    }
    this.assertMode = 'return-false';
    for (const p of tests.properties) {
      const gens = p.params.map((param) => this.generator(param.gen));
      const names = p.params.map((param) => this.local(param.name));
      inner.block(`test(${JSON.stringify(p.label)}, () => {`, () => {
        inner.block(`fc.assert(fc.property(${gens.join(', ')}, (${names.join(', ')}) => {`, () => {
          this.block(p.body);
          inner.line('return true;');
        }, '}));');
      }, '});');
    }
    const head = new Writer();
    head.line(`// Generated by onus: tests of module ${this.m.name}.`);
    head.line(`import * as $rt from ${JSON.stringify(this.opts.runtime)};`);
    for (const [id, alias] of this.imports) head.line(`import * as ${alias} from ${JSON.stringify(id === this.m.id ? `./${this.m.name.split('.').pop() ?? ''}.js` : this.relativeImport(id))};`);
    head.line('');
    for (const d of this.obDecls) head.line(d);
    inner.line(`afterAll(() => $rt.coverage.flush());`);
    const text = `${head.text()}\n${inner.text()}\n`;
    this.w = outer;
    this.selfAlias = null;
    this.imports.clear();
    for (const [k, v] of savedImports) this.imports.set(k, v);
    this.obDecls.splice(0, this.obDecls.length, ...obSaved);
    this.obRefs.clear();
    for (const [k, v] of obRefsSaved) this.obRefs.set(k, v);
    return text;
  }

  /** A fast-check generator. */
  private generator(g: IrGen): string {
    const base = this.baseGenerator(g.base);
    if (g.filters.length === 0) return base;
    const it = g.filters[0]?.it ?? '$it';
    const cond = g.filters.map((f) => at(this.expr(f.cond), AND + 1)).join(' && ');
    return `${base}.filter((${it}) => ${cond})`;
  }

  private baseGenerator(b: IrGen['base']): string {
    switch (b.k) {
      case 'int':
        return 'fc.integer({ min: -1000000, max: 1000000 })';
      case 'float':
        return 'fc.double({ noNaN: true, noDefaultInfinity: true })';
      case 'duration':
        return 'fc.integer({ min: 0, max: 1000000000 })';
      case 'bool':
        return 'fc.boolean()';
      case 'text':
        return 'fc.string()';
      case 'unit':
      case 'unknown':
        return 'fc.constant(undefined)';
      case 'list':
        return `fc.array(${this.generator(b.elem)}, { maxLength: 8 })`;
      case 'record':
        return `fc.record({ ${b.fields.map((f) => `${this.local(f.name)}: ${this.generator(f.gen)}`).join(', ')} })`;
      case 'union':
        return `fc.oneof(${b.variants.map((v) => `fc.record({ tag: fc.constant(${JSON.stringify(v.name)})${v.fields.length > 0 ? `, ${v.fields.map((f) => `${this.local(f.name)}: ${this.generator(f.gen)}`).join(', ')}` : ''} })`).join(', ')})`;
    }
  }

  private verifyFunction(v: IrVerify): EmittedModule['verifies'][number] {
    const destructure = v.params.length === 0 ? '$args' : `{ ${v.params.map((p) => this.local(p.name)).join(', ')} }`;
    this.fn = { inout: [], ret: { k: 'prim', name: 'Bool' } };
    this.assertMode = 'return-false';
    this.w.block(`export function ${v.name}(${destructure}) {`, () => {
      this.withEarlyReturn(v.earlyReturn, () => {
        this.block(v.body);
        this.w.line('return true;');
      });
    });
    this.w.line('');
    this.fn = null;
    return { name: v.name, key: v.key, claim: v.claim, def: v.def, at: v.at, params: v.params };
  }
}

function wrap(t: string): string {
  return /^[A-Za-z0-9_.$<>, ]+$/.test(t) ? t : `(${t})`;
}

function typeSlug(t: ResolveTables, type: Type): string {
  const s = stripRefinements(type);
  switch (s.k) {
    case 'prim':
      return s.name;
    case 'record':
    case 'union':
    case 'opaque':
    case 'capability':
      return `${t.def(s.def).name}${s.args.map((a) => (a.k === 'type' ? `_${typeSlug(t, a.type)}` : '')).join('')}`;
    case 'param':
      return t.def(s.def).name;
    default:
      return 'X';
  }
}
