/**
 * The native emitter (impl spec §6, M11; language spec §19): renders the
 * target-neutral form of `ir.ts` as LLVM IR text for `clang` to compile and
 * link against the C runtime in `packages/runtime/native/`.
 *
 * Representation:
 *   - `Int`/`Duration` are `i64`, `Float` is `double`, `Bool` is `i1`;
 *   - everything else is a pointer: `Text` to `{ len, bytes }`, records to
 *     an array of 64-bit slots, variants to `{ tag, slots... }`, lists and
 *     grids to runtime objects. A slot holds any value bit-for-bit, so
 *     generic code (type parameters, intrinsics) moves slots and the caller
 *     converts at the boundary;
 *   - `inout` parameters are pointers to the caller's slot;
 *   - a `proved` obligation emits nothing; a `checked` one is a branch to
 *     `onus_panic`; `Int` arithmetic uses the overflow intrinsics; `try` is
 *     a branch that returns the error from the enclosing function.
 *
 * Programs reaching a construct outside the v0 native subset are refused
 * with `E0800 primitive unavailable on target` (§19.1): closures and
 * function values, interfaces, quantifiers at runtime, `recover`, `fake`,
 * `TypeInfo`, `old(...)`, structural equality on aggregates, `Map`, `Bytes`,
 * `sql`, and `Text` operations that need grapheme tables.
 */
import type { Context } from '../context.js';
import type { Def, DefId, ResolveTables } from '../resolve/defs.js';
import type { Span } from '../source.js';
import type { TypeTables } from '../types/tables.js';
import { stripRefinements, type Type } from '../types/type.js';
import type { IrBlock, IrExpr, IrFn, IrModule, IrStmt, ObRef } from './ir.js';

/** A construct the native backend does not compile in v0, at the definition that uses it. */
export interface Unsupported {
  readonly def: string;
  readonly span: Span;
  readonly what: string;
}

export interface NativeProgram {
  readonly ll: string;
  readonly unsupported: readonly Unsupported[];
  /** The entry module's `main`, when it has one. */
  readonly hasMain: boolean;
  /** Example names, module-qualified, in run order. */
  readonly examples: readonly string[];
}

type LlType = 'i64' | 'double' | 'i1' | 'ptr';

interface Val {
  readonly v: string;
  readonly t: LlType;
}

class UnsupportedError extends Error {
  constructor(readonly what: string) {
    super(what);
  }
}

/**
 * Emits one program: every lowered module, an entry `main`, and an examples
 * runner selected by `--onus-examples`.
 * Effects: none (returns text).
 */
export function emitNative(ctx: Context, modules: readonly IrModule[], entry: IrModule | null): NativeProgram {
  return new NativeEmitter(ctx, modules, entry).run();
}

class NativeEmitter {
  private readonly t: ResolveTables;
  private readonly ty: TypeTables;
  private readonly globals: string[] = [];
  private readonly strings = new Map<string, string>();
  private readonly texts = new Map<string, string>();
  private readonly declared = new Set<string>();
  private readonly fns: string[] = [];
  private readonly unsupported: Unsupported[] = [];
  private readonly examples: { name: string; fn: string }[] = [];
  private counter = 0;
  // Per-function state.
  private lines: string[] = [];
  private allocas: string[] = [];
  private locals = new Map<string, { ptr: string; t: LlType; type: Type }>();
  private block = 'entry';
  private terminated = false;
  private fnRetLl: LlType | 'void' = 'i64';

  constructor(
    ctx: Context,
    private readonly modules: readonly IrModule[],
    private readonly entry: IrModule | null,
  ) {
    this.t = ctx.resolve;
    this.ty = ctx.types;
  }

  run(): NativeProgram {
    for (const m of this.modules) {
      for (const item of m.items) {
        if (item.k === 'fn') this.fnItem(m, item);
        else if (item.k === 'impl') for (const f of item.fns) this.fnItem(m, f);
        else if (item.k === 'const') this.constItem(m, item.def, item.type, item.value);
      }
      if (m.tests !== null) {
        for (const ex of m.tests.examples) this.exampleFn(m, ex.name, ex.body);
      }
    }
    const hasMain = this.entry !== null && this.entry.main !== null;
    this.mainFn();
    const head = [
      '; Generated by onus (native target). Do not edit.',
      ...this.globals,
      ...[...this.declared].sort(),
      'declare void @onus_panic(ptr, ptr, ptr, ptr)',
      'declare void @onus_unreachable()',
      'declare ptr @onus_alloc(i64)',
      'declare ptr @onus_rt_text_concat(ptr, ptr)',
      'declare i1 @onus_rt_text_eq(ptr, ptr)',
      'declare ptr @onus_rt_list_new(i64)',
      'declare i64 @onus_rt_list_len(ptr)',
      'declare i64 @onus_rt_list_get(ptr, i64)',
      'declare void @onus_rt_list_set(ptr, i64, i64)',
      'declare ptr @onus_rt_list_concat(ptr, ptr)',
      'declare ptr @onus_args(i32, ptr)',
      'declare i32 @onus_start(i32, ptr)',
      'declare i32 @onus_finish(ptr)',
      'declare void @onus_report_example(ptr, i1)',
      'declare i32 @onus_examples_done()',
      'declare ptr @onus_root(ptr)',
      'declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)',
      'declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)',
      'declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)',
      '',
    ];
    return { ll: `${head.join('\n')}\n${this.fns.join('\n')}`, unsupported: this.unsupported, hasMain, examples: this.examples.map((e) => e.name) };
  }

  // -------------------------------------------------------------------------
  // Names, types, constants
  // -------------------------------------------------------------------------

  private fnName(module: string, name: string): string {
    return `@"${module}.${name}"`;
  }

  private tmp(): string {
    this.counter += 1;
    return `%t${this.counter}`;
  }

  private label(prefix: string): string {
    this.counter += 1;
    return `${prefix}${this.counter}`;
  }

  private ll(type: Type): LlType {
    const s = stripRefinements(type);
    switch (s.k) {
      case 'prim':
        switch (s.name) {
          case 'Int':
          case 'Duration':
          case 'Unit':
            return 'i64';
          case 'Float':
            return 'double';
          case 'Bool':
            return 'i1';
          case 'Text':
            return 'ptr';
          case 'Bytes':
          case 'TypeInfo':
          case 'Spec':
            throw new UnsupportedError(`\`${s.name}\` values`);
        }
        break;
      case 'record':
      case 'union':
      case 'capability':
        return 'ptr';
      case 'opaque': {
        const q = this.t.qualifiedName(s.def);
        if (q === 'std.list.List' || q === 'std.grid.Grid') return 'ptr';
        throw new UnsupportedError(`\`${this.t.def(s.def).name}\` values`);
      }
      case 'param':
        return 'i64';
      case 'fn':
        throw new UnsupportedError('function values');
      case 'typeinfo':
      case 'spec':
        throw new UnsupportedError(`\`${s.k}\` values`);
      case 'error':
      case 'refined':
        return 'i64';
    }
    return 'i64';
  }

  /** A value as a 64-bit slot. */
  private toSlot(v: Val): string {
    switch (v.t) {
      case 'i64':
        return v.v;
      case 'double': {
        const r = this.tmp();
        this.emit(`${r} = bitcast double ${v.v} to i64`);
        return r;
      }
      case 'i1': {
        const r = this.tmp();
        this.emit(`${r} = zext i1 ${v.v} to i64`);
        return r;
      }
      case 'ptr': {
        const r = this.tmp();
        this.emit(`${r} = ptrtoint ptr ${v.v} to i64`);
        return r;
      }
    }
  }

  /** A slot read as `t`. */
  private fromSlot(slot: string, t: LlType): Val {
    switch (t) {
      case 'i64':
        return { v: slot, t };
      case 'double': {
        const r = this.tmp();
        this.emit(`${r} = bitcast i64 ${slot} to double`);
        return { v: r, t };
      }
      case 'i1': {
        const r = this.tmp();
        this.emit(`${r} = icmp ne i64 ${slot}, 0`);
        return { v: r, t };
      }
      case 'ptr': {
        const r = this.tmp();
        this.emit(`${r} = inttoptr i64 ${slot} to ptr`);
        return { v: r, t };
      }
    }
  }

  /** Converts a value to the representation of `to` (slot for type parameters). */
  private coerce(v: Val, to: LlType): Val {
    if (v.t === to) return v;
    return this.fromSlot(this.toSlot(v), to);
  }

  private cstring(s: string): string {
    const existing = this.strings.get(s);
    if (existing !== undefined) return existing;
    const name = `@s${this.strings.size + 1}`;
    const bytes = new TextEncoder().encode(s);
    this.globals.push(`${name} = private unnamed_addr constant [${bytes.length + 1} x i8] c"${escapeBytes(bytes)}\\00"`);
    this.strings.set(s, name);
    return name;
  }

  private textConst(s: string): string {
    const existing = this.texts.get(s);
    if (existing !== undefined) return existing;
    const name = `@txt${this.texts.size + 1}`;
    const bytes = new TextEncoder().encode(s);
    this.globals.push(`${name} = private unnamed_addr constant { i64, [${bytes.length + 1} x i8] } { i64 ${bytes.length}, [${bytes.length + 1} x i8] c"${escapeBytes(bytes)}\\00" }`);
    this.texts.set(s, name);
    return name;
  }

  private declare(sig: string): void {
    this.declared.add(sig);
  }

  private emit(line: string): void {
    this.lines.push(`  ${line}`);
  }

  private startBlock(name: string): void {
    this.lines.push(`${name}:`);
    this.block = name;
    this.terminated = false;
  }

  private br(target: string): void {
    if (this.terminated) return;
    this.emit(`br label %${target}`);
    this.terminated = true;
  }

  private condBr(cond: string, then: string, otherwise: string): void {
    this.emit(`br i1 ${cond}, label %${then}, label %${otherwise}`);
    this.terminated = true;
  }

  private alloca(name: string, t: LlType, type: Type): string {
    const ptr = `%"${name}.addr${this.counter += 1}"`;
    this.allocas.push(`  ${ptr} = alloca ${t}`);
    this.locals.set(name, { ptr, t, type });
    return ptr;
  }

  private panic(ob: ObRef): void {
    this.emit(`call void @onus_panic(ptr ${this.cstring(ob.kind)}, ptr ${this.cstring(ob.text)}, ptr ${this.cstring(ob.at)}, ptr ${this.cstring(ob.def)})`);
    this.emit('unreachable');
    this.terminated = true;
  }

  private variantIndex(union: DefId, variant: DefId): number {
    const i = (this.ty.variants.get(union) ?? []).indexOf(variant);
    return i < 0 ? 0 : i;
  }

  private unionDefOf(type: Type): DefId | null {
    const s = stripRefinements(type);
    return s.k === 'union' ? s.def : null;
  }

  // -------------------------------------------------------------------------
  // Functions
  // -------------------------------------------------------------------------

  private beginFn(): void {
    this.lines = [];
    this.allocas = [];
    this.locals = new Map();
    this.block = 'entry';
    this.terminated = false;
  }

  private finishFn(header: string, tail: string): void {
    this.fns.push(header, ...this.allocas, ...this.lines, tail, '}', '');
  }

  private fnItem(m: IrModule, f: IrFn): void {
    if (f.intrinsic !== null || f.body === null) return;
    const name = this.fnName(m.module.name, f.name);
    try {
      if (f.dictParams.length > 0) throw new UnsupportedError('functions with interface-bounded type parameters');
      this.beginFn();
      const params: string[] = [];
      const stores: { name: string; t: LlType; type: Type; inout: boolean }[] = [];
      for (const c of f.constParams) {
        const t = this.ll(c.type);
        params.push(`${t} %"p.${c.name}"`);
        stores.push({ name: c.name, t, type: c.type, inout: false });
      }
      for (const p of f.params) {
        const t = this.ll(p.type);
        params.push(`${p.inout ? 'ptr' : t} %"p.${p.name}"`);
        stores.push({ name: p.name, t, type: p.type, inout: p.inout });
      }
      const ret = this.ll(f.ret);
      this.fnRetLl = ret;
      for (const s of stores) {
        if (s.inout) this.locals.set(s.name, { ptr: `%"p.${s.name}"`, t: s.t, type: s.type });
        else {
          const ptr = this.alloca(s.name, s.t, s.type);
          this.emit(`store ${s.t} %"p.${s.name}", ptr ${ptr}`);
        }
      }
      this.blockStmts(f.entry);
      this.blockStmts(f.body);
      if (!this.terminated) this.emit(ret === 'i64' ? 'ret i64 0' : ret === 'double' ? 'ret double 0.0' : ret === 'i1' ? 'ret i1 0' : 'ret ptr null');
      this.finishFn(`define ${ret} ${name}(${params.join(', ')}) {`, '');
    } catch (e) {
      if (!(e instanceof UnsupportedError)) throw e;
      this.unsupported.push({ def: this.t.qualifiedName(f.def.id), span: f.def.span, what: e.what });
    }
  }

  private constItem(m: IrModule, def: Def, type: Type, value: IrExpr): void {
    const name = this.fnName(m.module.name, def.name);
    try {
      const t = this.ll(type);
      const literal = value.k === 'value' ? value.value : null;
      if (literal !== null && (literal.k === 'int' || literal.k === 'duration')) this.globals.push(`${name} = constant i64 ${Math.trunc(literal.v)}`);
      else if (literal !== null && literal.k === 'float') this.globals.push(`${name} = constant double ${doubleLiteral(literal.v)}`);
      else if (literal !== null && literal.k === 'bool') this.globals.push(`${name} = constant i1 ${literal.v ? 1 : 0}`);
      else if (literal !== null && literal.k === 'text') this.globals.push(`${name} = constant ptr ${this.textConst(literal.v)}`);
      else throw new UnsupportedError(`\`const\` items of type ${t === 'ptr' ? 'an aggregate' : type.k}`);
    } catch (e) {
      if (!(e instanceof UnsupportedError)) throw e;
      this.unsupported.push({ def: this.t.qualifiedName(def.id), span: def.span, what: e.what });
    }
  }

  private exampleFn(m: IrModule, name: string, body: IrBlock): void {
    const fn = `@"${m.module.name}.example.${name}"`;
    try {
      this.beginFn();
      this.fnRetLl = 'i1';
      this.blockStmts(body);
      if (!this.terminated) this.emit('ret i1 1');
      this.finishFn(`define i1 ${fn}() {`, '');
      this.examples.push({ name: `${m.module.name}.${name}`, fn });
    } catch (e) {
      if (!(e instanceof UnsupportedError)) throw e;
      const def = this.t.membersOf(m.module.id).tests.get(name);
      this.unsupported.push({ def: `${m.module.name}.${name}`, span: def === undefined ? m.module.module.span : this.t.def(def).span, what: e.what });
    }
  }

  /** `main(argc, argv)`: the program, or every example under `--onus-examples`. */
  private mainFn(): void {
    this.beginFn();
    this.fnRetLl = 'i64';
    this.emit('%mode = call i32 @onus_start(i32 %argc, ptr %argv)');
    this.emit('%isExamples = icmp eq i32 %mode, 1');
    this.condBr('%isExamples', 'examples', 'program');
    this.startBlock('examples');
    for (const ex of this.examples) {
      const ok = this.tmp();
      this.emit(`${ok} = call i1 ${ex.fn}()`);
      this.emit(`call void @onus_report_example(ptr ${this.cstring(ex.name)}, i1 ${ok})`);
    }
    this.emit('%exampleCode = call i32 @onus_examples_done()');
    this.emit('ret i32 %exampleCode');
    this.terminated = true;
    this.startBlock('program');
    const entry = this.entry;
    if (entry === null || entry.main === null) {
      this.emit('ret i32 0');
    } else {
      const mainFn = entry.items.find((i): i is IrFn => i.k === 'fn' && i.def.name === 'main');
      if (mainFn === undefined) this.emit('ret i32 0');
      else {
        const args: string[] = [];
        for (const p of mainFn.params) {
          const root = entry.main.roots[p.name];
          if (p.name === entry.main.args) args.push('ptr %args');
          else if (root !== undefined) args.push(`ptr ${this.rootCall(root)}`);
          else args.push('ptr null');
        }
        this.emit('%args = call ptr @onus_args(i32 %argc, ptr %argv)');
        // Root calls were emitted by rootCall in order; assemble the call.
        this.emit(`%result = call ${this.ll(mainFn.ret)} ${this.fnName(entry.module.name, mainFn.name)}(${args.join(', ')})`);
        this.emit('%code = call i32 @onus_finish(ptr %result)');
        this.emit('ret i32 %code');
      }
    }
    this.terminated = true;
    this.finishFn('define i32 @main(i32 %argc, ptr %argv) {', '');
  }

  private rootCall(kind: string): string {
    const r = this.tmp();
    this.emit(`${r} = call ptr @onus_root(ptr ${this.cstring(kind)})`);
    return r;
  }

  // -------------------------------------------------------------------------
  // Statements
  // -------------------------------------------------------------------------

  private blockStmts(b: IrBlock): void {
    for (const s of b) {
      if (this.terminated) return;
      this.stmt(s);
    }
  }

  private stmt(s: IrStmt): void {
    switch (s.k) {
      case 'let': {
        const t = this.ll(s.type);
        const v = this.coerce(this.expr(s.value), t);
        const ptr = this.alloca(s.name, t, s.type);
        this.emit(`store ${t} ${v.v}, ptr ${ptr}`);
        return;
      }
      case 'assign': {
        const local = this.locals.get(s.name);
        if (local === undefined) throw new Error(`unknown local ${s.name}`);
        const v = this.coerce(this.expr(s.value), local.t);
        this.emit(`store ${local.t} ${v.v}, ptr ${local.ptr}`);
        return;
      }
      case 'return': {
        if (this.fnRetLl === 'void') {
          this.emit('ret void');
          this.terminated = true;
          return;
        }
        const v = this.coerce(this.expr(s.value), this.fnRetLl);
        this.emit(`ret ${v.t} ${v.v}`);
        this.terminated = true;
        return;
      }
      case 'if': {
        const c = this.coerce(this.expr(s.cond), 'i1');
        const thenL = this.label('then');
        const elseL = this.label('else');
        const endL = this.label('endif');
        this.condBr(c.v, thenL, s.else === null ? endL : elseL);
        this.startBlock(thenL);
        this.blockStmts(s.then);
        this.br(endL);
        if (s.else !== null) {
          this.startBlock(elseL);
          this.blockStmts(s.else);
          this.br(endL);
        }
        this.startBlock(endL);
        return;
      }
      case 'match': {
        const t = this.ll(s.type);
        const v = this.coerce(this.expr(s.scrutinee), t);
        const ptr = this.alloca(s.tmp, t, s.type);
        this.emit(`store ${t} ${v.v}, ptr ${ptr}`);
        const endL = this.label('endmatch');
        for (const arm of s.arms) {
          const bodyL = this.label('arm');
          const nextL = this.label('next');
          if (arm.test !== null) {
            const c = this.coerce(this.expr(arm.test), 'i1');
            this.condBr(c.v, bodyL, nextL);
          } else this.br(bodyL);
          this.startBlock(bodyL);
          for (const b of arm.bindings) {
            const bt = this.ll(b.type);
            const bv = this.coerce(this.expr(b.value), bt);
            const bp = this.alloca(b.name, bt, b.type);
            this.emit(`store ${bt} ${bv.v}, ptr ${bp}`);
          }
          if (arm.guard !== null) {
            const g = this.coerce(this.expr(arm.guard), 'i1');
            const guardedL = this.label('guarded');
            this.condBr(g.v, guardedL, nextL);
            this.startBlock(guardedL);
          }
          this.blockStmts(arm.body);
          this.br(endL);
          this.startBlock(nextL);
        }
        this.emit('call void @onus_unreachable()');
        this.emit('unreachable');
        this.terminated = true;
        this.startBlock(endL);
        return;
      }
      case 'loop': {
        const condL = this.label('loop');
        const bodyL = this.label('body');
        const endL = this.label('endloop');
        this.br(condL);
        this.startBlock(condL);
        const c = this.coerce(this.expr(s.cond), 'i1');
        this.condBr(c.v, bodyL, endL);
        this.startBlock(bodyL);
        this.blockStmts(s.body);
        this.br(condL);
        this.startBlock(endL);
        return;
      }
      case 'for-range': {
        const lo = this.coerce(this.expr(s.lo), 'i64');
        const hi = this.coerce(this.expr(s.hi), 'i64');
        const ptr = this.alloca(s.name, 'i64', { k: 'prim', name: 'Int' });
        this.emit(`store i64 ${lo.v}, ptr ${ptr}`);
        const condL = this.label('for');
        const bodyL = this.label('body');
        const endL = this.label('endfor');
        this.br(condL);
        this.startBlock(condL);
        const i = this.tmp();
        this.emit(`${i} = load i64, ptr ${ptr}`);
        const c = this.tmp();
        this.emit(`${c} = icmp slt i64 ${i}, ${hi.v}`);
        this.condBr(c, bodyL, endL);
        this.startBlock(bodyL);
        this.blockStmts(s.body);
        if (!this.terminated) {
          const cur = this.tmp();
          this.emit(`${cur} = load i64, ptr ${ptr}`);
          const next = this.tmp();
          this.emit(`${next} = add i64 ${cur}, 1`);
          this.emit(`store i64 ${next}, ptr ${ptr}`);
        }
        this.br(condL);
        this.startBlock(endL);
        return;
      }
      case 'for-each': {
        const list = this.coerce(this.expr(s.list), 'ptr');
        const len = this.tmp();
        this.emit(`${len} = call i64 @onus_rt_list_len(ptr ${list.v})`);
        const idx = this.alloca('$idx', 'i64', { k: 'prim', name: 'Int' });
        this.emit(`store i64 0, ptr ${idx}`);
        const et = this.ll(s.type);
        const elem = this.alloca(s.name, et, s.type);
        const condL = this.label('foreach');
        const bodyL = this.label('body');
        const endL = this.label('endforeach');
        this.br(condL);
        this.startBlock(condL);
        const i = this.tmp();
        this.emit(`${i} = load i64, ptr ${idx}`);
        const c = this.tmp();
        this.emit(`${c} = icmp slt i64 ${i}, ${len}`);
        this.condBr(c, bodyL, endL);
        this.startBlock(bodyL);
        const slot = this.tmp();
        this.emit(`${slot} = call i64 @onus_rt_list_get(ptr ${list.v}, i64 ${i})`);
        const ev = this.fromSlot(slot, et);
        this.emit(`store ${et} ${ev.v}, ptr ${elem}`);
        const next = this.tmp();
        this.emit(`${next} = add i64 ${i}, 1`);
        this.emit(`store i64 ${next}, ptr ${idx}`);
        this.blockStmts(s.body);
        this.br(condL);
        this.startBlock(endL);
        return;
      }
      case 'check': {
        const c = this.coerce(this.expr(s.cond), 'i1');
        const okL = this.label('ok');
        const failL = this.label('fail');
        this.condBr(c.v, okL, failL);
        this.startBlock(failL);
        this.panic(s.ob);
        this.startBlock(okL);
        return;
      }
      case 'assert': {
        const c = this.coerce(this.expr(s.cond), 'i1');
        const okL = this.label('ok');
        const failL = this.label('fail');
        this.condBr(c.v, okL, failL);
        this.startBlock(failL);
        this.emit('ret i1 0');
        this.terminated = true;
        this.startBlock(okL);
        return;
      }
      case 'expr':
        this.expr(s.expr);
        return;
      case 'call-inout': {
        const v = this.expr(s.call);
        if (s.result !== null) {
          const t = this.ll(s.result.type);
          const ptr = this.alloca(s.result.name, t, s.result.type);
          this.emit(`store ${t} ${this.coerce(v, t).v}, ptr ${ptr}`);
        }
        return;
      }
      case 'unreachable':
        this.emit('call void @onus_unreachable()');
        this.emit('unreachable');
        this.terminated = true;
        return;
      case 'comment':
        this.emit(`; ${s.text}`);
        return;
    }
  }

  // -------------------------------------------------------------------------
  // Expressions
  // -------------------------------------------------------------------------

  private expr(e: IrExpr): Val {
    switch (e.k) {
      case 'int':
        return { v: e.v.toString(), t: 'i64' };
      case 'float':
        return { v: doubleLiteral(e.v), t: 'double' };
      case 'text':
        return { v: this.textConst(e.v), t: 'ptr' };
      case 'bool':
        return { v: e.v ? '1' : '0', t: 'i1' };
      case 'unit':
        return { v: '0', t: 'i64' };
      case 'local': {
        const local = this.locals.get(e.name);
        if (local === undefined) throw new Error(`unknown local ${e.name}`);
        const r = this.tmp();
        this.emit(`${r} = load ${local.t}, ptr ${local.ptr}`);
        return { v: r, t: local.t };
      }
      case 'global': {
        const t = this.ll(e.type);
        const r = this.tmp();
        this.emit(`${r} = load ${t}, ptr ${this.fnName(this.t.moduleOf(e.def.module).name, e.def.name)}`);
        return { v: r, t };
      }
      case 'call':
        return this.call(e);
      case 'record': {
        const fields = this.ty.fields.get(e.def.id) ?? [];
        const obj = this.tmp();
        this.emit(`${obj} = call ptr @onus_alloc(i64 ${8 * Math.max(1, fields.length)})`);
        for (const f of e.fields) {
          const idx = fields.findIndex((x) => x.name === f.name);
          this.storeSlot(obj, idx < 0 ? 0 : idx, this.toSlot(this.expr(f.value)));
        }
        return { v: obj, t: 'ptr' };
      }
      case 'variant': {
        const union = e.def.parent;
        const fields = this.ty.fields.get(e.def.id) ?? [];
        const obj = this.tmp();
        this.emit(`${obj} = call ptr @onus_alloc(i64 ${8 * (1 + fields.length)})`);
        this.storeSlot(obj, 0, String(union === null ? 0 : this.variantIndex(union, e.def.id)));
        for (const f of e.fields) {
          const idx = fields.findIndex((x) => x.name === f.name);
          this.storeSlot(obj, 1 + (idx < 0 ? 0 : idx), this.toSlot(this.expr(f.value)));
        }
        return { v: obj, t: 'ptr' };
      }
      case 'update': {
        const fields = this.ty.fields.get(e.def.id) ?? [];
        const base = this.coerce(this.expr(e.base), 'ptr');
        const obj = this.tmp();
        this.emit(`${obj} = call ptr @onus_alloc(i64 ${8 * Math.max(1, fields.length)})`);
        fields.forEach((_, i) => this.storeSlot(obj, i, this.loadSlot(base.v, i)));
        for (const f of e.fields) {
          const idx = fields.findIndex((x) => x.name === f.name);
          this.storeSlot(obj, idx < 0 ? 0 : idx, this.toSlot(this.expr(f.value)));
        }
        return { v: obj, t: 'ptr' };
      }
      case 'field': {
        const obj = this.coerce(this.expr(e.object), 'ptr');
        const owner = e.owner;
        if (owner === null) throw new UnsupportedError('field access on a value of unknown shape');
        const fields = this.ty.fields.get(owner.id) ?? [];
        const idx = fields.findIndex((f) => f.name === e.name);
        const base = owner.kind === 'variant' ? 1 : 0;
        return this.fromSlot(this.loadSlot(obj.v, base + (idx < 0 ? 0 : idx)), this.ll(e.type));
      }
      case 'list': {
        const list = this.tmp();
        this.emit(`${list} = call ptr @onus_rt_list_new(i64 ${e.elems.length})`);
        e.elems.forEach((x, i) => this.emit(`call void @onus_rt_list_set(ptr ${list}, i64 ${i}, i64 ${this.toSlot(this.expr(x))})`));
        return { v: list, t: 'ptr' };
      }
      case 'concat': {
        const l = this.coerce(this.expr(e.left), 'ptr');
        const r = this.coerce(this.expr(e.right), 'ptr');
        const out = this.tmp();
        this.emit(`${out} = call ptr @${e.text ? 'onus_rt_text_concat' : 'onus_rt_list_concat'}(ptr ${l.v}, ptr ${r.v})`);
        return { v: out, t: 'ptr' };
      }
      case 'intop':
        return this.intop(e.op, this.coerce(this.expr(e.left), 'i64'), this.coerce(this.expr(e.right), 'i64'), e.ob);
      case 'floatop': {
        const l = this.coerce(this.expr(e.left), 'double');
        const r = this.coerce(this.expr(e.right), 'double');
        const op = { '+': 'fadd', '-': 'fsub', '*': 'fmul', '/': 'fdiv', '%': 'frem' }[e.op];
        const out = this.tmp();
        this.emit(`${out} = ${op} double ${l.v}, ${r.v}`);
        return { v: out, t: 'double' };
      }
      case 'neg': {
        if (e.float) {
          const v = this.coerce(this.expr(e.operand), 'double');
          const out = this.tmp();
          this.emit(`${out} = fneg double ${v.v}`);
          return { v: out, t: 'double' };
        }
        return this.intop('-', { v: '0', t: 'i64' }, this.coerce(this.expr(e.operand), 'i64'), e.ob);
      }
      case 'cmp': {
        const out = this.tmp();
        if (e.float) {
          const l = this.coerce(this.expr(e.left), 'double');
          const r = this.coerce(this.expr(e.right), 'double');
          this.emit(`${out} = fcmp ${{ '<': 'olt', '<=': 'ole', '>': 'ogt', '>=': 'oge' }[e.op]} double ${l.v}, ${r.v}`);
        } else {
          const l = this.coerce(this.expr(e.left), 'i64');
          const r = this.coerce(this.expr(e.right), 'i64');
          this.emit(`${out} = icmp ${{ '<': 'slt', '<=': 'sle', '>': 'sgt', '>=': 'sge' }[e.op]} i64 ${l.v}, ${r.v}`);
        }
        return { v: out, t: 'i1' };
      }
      case 'eq': {
        const s = stripRefinements(e.type);
        if (s.k !== 'prim') throw new UnsupportedError('structural equality on records, variants and lists');
        const out = this.tmp();
        if (s.name === 'Float') {
          const l = this.coerce(this.expr(e.left), 'double');
          const r = this.coerce(this.expr(e.right), 'double');
          this.emit(`${out} = fcmp ${e.negate ? 'une' : 'oeq'} double ${l.v}, ${r.v}`);
        } else if (s.name === 'Text') {
          const l = this.coerce(this.expr(e.left), 'ptr');
          const r = this.coerce(this.expr(e.right), 'ptr');
          const eq = this.tmp();
          this.emit(`${eq} = call i1 @onus_rt_text_eq(ptr ${l.v}, ptr ${r.v})`);
          this.emit(`${out} = ${e.negate ? `xor i1 ${eq}, 1` : `and i1 ${eq}, 1`}`);
        } else {
          const l = this.toSlot(this.expr(e.left));
          const r = this.toSlot(this.expr(e.right));
          this.emit(`${out} = icmp ${e.negate ? 'ne' : 'eq'} i64 ${l}, ${r}`);
        }
        return { v: out, t: 'i1' };
      }
      case 'not': {
        const v = this.coerce(this.expr(e.operand), 'i1');
        const out = this.tmp();
        this.emit(`${out} = xor i1 ${v.v}, 1`);
        return { v: out, t: 'i1' };
      }
      case 'and':
        return this.shortCircuit(e.operands, true);
      case 'or':
        return this.shortCircuit(e.operands, false);
      case 'implies':
        return this.shortCircuit([{ k: 'not', operand: e.left }, e.right], false);
      case 'is-variant': {
        const subject = this.coerce(this.expr(e.subject), 'ptr');
        const union = this.unionDefOf(e.type) ?? e.variant.parent;
        const tag = this.loadSlot(subject.v, 0);
        const out = this.tmp();
        this.emit(`${out} = icmp eq i64 ${tag}, ${union === null ? 0 : this.variantIndex(union, e.variant.id)}`);
        return { v: out, t: 'i1' };
      }
      case 'try':
        return this.tryExpr(e);
      case 'checked': {
        const t = this.ll(e.type);
        const v = this.coerce(this.expr(e.value), t);
        const ptr = this.alloca(e.it, t, e.type);
        this.emit(`store ${t} ${v.v}, ptr ${ptr}`);
        this.blockStmts(e.checks);
        return v;
      }
      case 'const': {
        const c = e.value;
        if (c.k === 'int' || c.k === 'duration') return { v: c.v.toString(), t: 'i64' };
        if (c.k === 'bool') return { v: c.v ? '1' : '0', t: 'i1' };
        if (c.k === 'float') return { v: doubleLiteral(c.v), t: 'double' };
        if (c.k === 'text') return { v: this.textConst(c.v), t: 'ptr' };
        throw new UnsupportedError(`${c.k} type arguments`);
      }
      case 'value': {
        const c = e.value;
        if (c.k === 'int' || c.k === 'duration') return { v: String(Math.trunc(c.v)), t: 'i64' };
        if (c.k === 'bool') return { v: c.v ? '1' : '0', t: 'i1' };
        if (c.k === 'float') return { v: doubleLiteral(c.v), t: 'double' };
        if (c.k === 'text') return { v: this.textConst(c.v), t: 'ptr' };
        throw new UnsupportedError('aggregate compile-time values');
      }
      case 'fnref':
      case 'call-value':
      case 'closure':
        throw new UnsupportedError('function values and closures');
      case 'dict':
      case 'dict-param':
        throw new UnsupportedError('interfaces');
      case 'quantifier':
        throw new UnsupportedError('quantifiers evaluated at runtime');
      case 'recover':
        throw new UnsupportedError('`recover`');
      case 'fake':
        throw new UnsupportedError('`fake`');
      case 'typeinfo':
        throw new UnsupportedError('`TypeInfo`');
      case 'snapshot':
        throw new UnsupportedError('`old(...)` in a checked postcondition');
    }
  }

  private loadSlot(obj: string, idx: number): string {
    const p = this.tmp();
    this.emit(`${p} = getelementptr i64, ptr ${obj}, i64 ${idx}`);
    const v = this.tmp();
    this.emit(`${v} = load i64, ptr ${p}`);
    return v;
  }

  private storeSlot(obj: string, idx: number, slot: string): void {
    const p = this.tmp();
    this.emit(`${p} = getelementptr i64, ptr ${obj}, i64 ${idx}`);
    this.emit(`store i64 ${slot}, ptr ${p}`);
  }

  private shortCircuit(operands: readonly IrExpr[], isAnd: boolean): Val {
    const endL = this.label('sc');
    const incoming: string[] = [];
    for (let i = 0; i < operands.length; i++) {
      const o = operands[i];
      if (o === undefined) continue;
      const v = this.coerce(this.expr(o), 'i1');
      if (i === operands.length - 1) {
        incoming.push(`[ ${v.v}, %${this.block} ]`);
        this.br(endL);
        break;
      }
      const nextL = this.label('scnext');
      incoming.push(`[ ${isAnd ? '0' : '1'}, %${this.block} ]`);
      if (isAnd) this.condBr(v.v, nextL, endL);
      else this.condBr(v.v, endL, nextL);
      this.startBlock(nextL);
    }
    this.startBlock(endL);
    const out = this.tmp();
    this.emit(`${out} = phi i1 ${incoming.join(', ')}`);
    return { v: out, t: 'i1' };
  }

  private intop(op: '+' | '-' | '*' | '/' | '%', l: Val, r: Val, ob: ObRef | null): Val {
    const out = this.tmp();
    if (op === '/' || op === '%') {
      if (ob !== null) {
        const zero = this.tmp();
        this.emit(`${zero} = icmp eq i64 ${r.v}, 0`);
        const okL = this.label('divok');
        const failL = this.label('divfail');
        this.condBr(zero, failL, okL);
        this.startBlock(failL);
        this.panic(ob);
        this.startBlock(okL);
      }
      this.emit(`${out} = ${op === '/' ? 'sdiv' : 'srem'} i64 ${l.v}, ${r.v}`);
      return { v: out, t: 'i64' };
    }
    if (ob === null) {
      this.emit(`${out} = ${{ '+': 'add', '-': 'sub', '*': 'mul' }[op]} i64 ${l.v}, ${r.v}`);
      return { v: out, t: 'i64' };
    }
    const pair = this.tmp();
    this.emit(`${pair} = call { i64, i1 } @llvm.${{ '+': 'sadd', '-': 'ssub', '*': 'smul' }[op]}.with.overflow.i64(i64 ${l.v}, i64 ${r.v})`);
    this.emit(`${out} = extractvalue { i64, i1 } ${pair}, 0`);
    const overflow = this.tmp();
    this.emit(`${overflow} = extractvalue { i64, i1 } ${pair}, 1`);
    const okL = this.label('arith');
    const failL = this.label('overflow');
    this.condBr(overflow, failL, okL);
    this.startBlock(failL);
    this.panic(ob);
    this.startBlock(okL);
    return { v: out, t: 'i64' };
  }

  private call(e: Extract<IrExpr, { k: 'call' }>): Val {
    if (e.target.k !== 'fn') throw new UnsupportedError('interface dispatch through a dictionary');
    const def = e.target.def;
    const sig = e.sig;
    const retLl = this.ll(e.type);
    const args: string[] = [];
    if (def.intrinsic) {
      // Runtime primitives take and return 64-bit slots; `inout` parameters are pointers to slots.
      const q = this.t.qualifiedName(def.id);
      const cname = `@onus_${q.split('.').slice(1).join('_')}`;
      const paramTypes: string[] = [];
      for (const c of e.consts) {
        args.push(`i64 ${this.toSlot(this.expr(c))}`);
        paramTypes.push('i64');
      }
      sig.params.forEach((p, i) => {
        const a = e.args[i];
        if (a === undefined) return;
        if (p.inout) {
          args.push(`ptr ${this.addressOf(a)}`);
          paramTypes.push('ptr');
        } else {
          args.push(`i64 ${this.toSlot(this.expr(a))}`);
          paramTypes.push('i64');
        }
      });
      this.declare(`declare i64 ${cname}(${paramTypes.join(', ')})`);
      const out = this.tmp();
      this.emit(`${out} = call i64 ${cname}(${args.join(', ')})`);
      return this.fromSlot(out, retLl);
    }
    const module = this.t.moduleOf(def.module).name;
    for (const c of e.consts) {
      const v = this.expr(c);
      args.push(`${v.t} ${v.v}`);
    }
    sig.params.forEach((p, i) => {
      const a = e.args[i];
      if (a === undefined) return;
      if (p.inout) args.push(`ptr ${this.addressOf(a)}`);
      else {
        const v = this.coerce(this.expr(a), this.ll(p.type));
        args.push(`${v.t} ${v.v}`);
      }
    });
    const calleeRet = this.ll(sig.ret);
    const out = this.tmp();
    this.emit(`${out} = call ${calleeRet} ${this.fnName(module, e.target.name)}(${args.join(', ')})`);
    return this.coerce({ v: out, t: calleeRet }, retLl);
  }

  /** The address of an `inout` argument's slot: the local's storage, whose element type must be the slot type. */
  private addressOf(a: IrExpr): string {
    if (a.k !== 'local') throw new UnsupportedError('an `inout` argument that is not a variable');
    const local = this.locals.get(a.name);
    if (local === undefined) throw new Error(`unknown local ${a.name}`);
    if (local.t !== 'i64' && local.t !== 'ptr') throw new UnsupportedError(`\`inout\` arguments of type ${local.t}`);
    return local.ptr;
  }

  private tryExpr(e: Extract<IrExpr, { k: 'try' }>): Val {
    const operand = this.coerce(this.expr(e.operand), 'ptr');
    const tag = this.loadSlot(operand.v, 0);
    const isOk = this.tmp();
    this.emit(`${isOk} = icmp eq i64 ${tag}, 0`);
    const okL = this.label('tryok');
    const failL = this.label('tryfail');
    this.condBr(isOk, okL, failL);
    this.startBlock(failL);
    if (e.raw) {
      const v = this.coerce(this.expr(e.else?.value ?? { k: 'bool', v: false }), 'i1');
      this.emit(`ret i1 ${v.v}`);
    } else if (e.else === null) {
      if (e.option && !e.outerOption) throw new UnsupportedError('`try` on an Option inside a function returning Result without an `else`');
      // The same error (or `None`) is the function's result.
      this.emit(`ret ptr ${operand.v}`);
    } else {
      if (e.else.name !== null) {
        const et = this.ll(e.else.errorType);
        const err = this.fromSlot(this.loadSlot(operand.v, 1), et);
        const ptr = this.alloca(e.else.name, et, e.else.errorType);
        this.emit(`store ${et} ${err.v}, ptr ${ptr}`);
      }
      const converted = this.toSlot(this.expr(e.else.value));
      const result = this.tmp();
      this.emit(`${result} = call ptr @onus_alloc(i64 16)`);
      this.storeSlot(result, 0, '1');
      this.storeSlot(result, 1, converted);
      this.emit(`ret ptr ${result}`);
    }
    this.terminated = true;
    this.startBlock(okL);
    if (e.option && e.else === null && e.outerOption) {
      // `Some` carries its value in slot 1 like `Ok`.
    }
    return this.fromSlot(this.loadSlot(operand.v, 1), this.ll(e.type));
  }
}

function escapeBytes(bytes: Uint8Array): string {
  let out = '';
  for (const b of bytes) {
    if (b >= 0x20 && b < 0x7f && b !== 0x22 && b !== 0x5c) out += String.fromCharCode(b);
    else out += `\\${b.toString(16).padStart(2, '0').toUpperCase()}`;
  }
  return out;
}

/** An exact LLVM double literal: the IEEE bits in hexadecimal. */
function doubleLiteral(v: number): string {
  const buf = new DataView(new ArrayBuffer(8));
  buf.setFloat64(0, v);
  const hi = buf.getUint32(0).toString(16).padStart(8, '0');
  const lo = buf.getUint32(4).toString(16).padStart(8, '0');
  return `0x${hi}${lo}`.toUpperCase().replace('0X', '0x');
}
