// Generated by onus from module cli. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $std_list from "./std/list.js";
import * as $std_map from "./std/map.js";
import * as $std_text from "./std/text.js";
import * as $std_io from "./std/io.js";
import * as $nativebuild from "./nativebuild.js";
import * as $ledger from "./ledger.js";
import * as $context from "./context.js";
import * as $std_int from "./std/int.js";
import * as $loader from "./loader.js";
import * as $json from "./json.js";
import * as $diagjson from "./diagjson.js";
import * as $diagtext from "./diagtext.js";
import * as $obligations from "./obligations.js";
import * as $loc from "./loc.js";
import * as $check from "./check.js";
import * as $build from "./build.js";
import * as $irtext from "./irtext.js";
import * as $lowerir from "./lowerir.js";
import * as $interface from "./interface.js";
import * as $idiff from "./idiff.js";
import * as $pathreport from "./pathreport.js";
import * as $pathtext from "./pathtext.js";

const $ob1 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:77:40", def: "parse_args" };
const $ob2 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:78:74", def: "parse_args" };
const $ob3 = { kind: "overflow", text: "i + 2 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:79:13", def: "parse_args" };
const $ob4 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:82:15", def: "parse_args" };
const $ob5 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:85:15", def: "parse_args" };
const $ob6 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:94:11", def: "parse_args" };
const $ob7 = { kind: "overflow", text: "n - width within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:136:38", def: "pad" };
const $ob8 = { kind: "overflow", text: "syntax_errors + 1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:362:23", def: "fmt_command" };
const $ob9 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:616:18", def: "interface_command" };
const $ob10 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/cli.onus:682:24", def: "path_command" };
export const usage = "usage:\n  onus check <file.onus>... [--json] [--root <dir>] [--stdlib <dir>] [--to <pass>] [--budget <ms>] [--ledger] [--no-cache]\n      report every diagnostic; exit 1 if any. Passes: parse, canonical, load, resolve, types, consteval, effects, contracts, claims, capabilities, verify, paths\n  onus fmt <file.onus>... [--stdout]\n      rewrite files in canonical form\n  onus build <entry.onus> [--out <dir>] [--emit js|ir] [--target js|native|wasm] [--root <dir>] [--stdlib <dir>] [--runtime <path>]\n      check, then emit JavaScript for every module into <dir> (default: <entry dir>/out); --target native compiles\n      an executable with clang into <dir>/native (§19); --emit ir prints the target-neutral form\n  onus run <entry.onus> [--out <dir>] [--target js|native|wasm] [-- args...]\n      build, then run the entry module's main\n  onus interface <file.onus> [--json] [--diff <old-interface.json>] [--root <dir>] [--stdlib <dir>] [--budget <ms>] [--no-cache]\n      check, then print the entry module's interface: canonical source with bodies elided, or the §11.1 JSON;\n      with --diff, the changes since a previous interface document (§11.1, §15.1)\n  onus path <file.onus> [<name>] [--json] [--root <dir>] [--stdlib <dir>] [--budget <ms>] [--no-cache]\n      check, then print the §9.1 report of the entry module's paths (or of the named one)\n  test, review, loop and next: run the TypeScript `onus` until M15.5\nThe standard library is --stdlib or ONUS_STDLIB; the runtime for build and run is --runtime or ONUS_RUNTIME.\n";

export const passes = ["parse", "canonical", "load", "resolve", "types", "consteval", "effects", "contracts", "claims", "capabilities", "verify", "paths"];

export function skip($args) {
  return undefined;
}

export function is_value_flag({ name }) {
  return name === "root" || name === "stdlib" || name === "to" || name === "out" || name === "emit" || name === "budget" || name === "offset" || name === "diff" || name === "against" || name === "env" || name === "target" || name === "runtime";
}

export function parse_args({ argv }) {
  let command = { tag: "None" };
  let files = $std_list.builder({  });
  let flags = $std_map.dict({  });
  let values = $std_map.dict({  });
  let i = 0;
  while (i < $std_list.len({ xs: argv })) {
    const a = $std_list.get({ xs: argv, i: i });
    if ($std_text.starts_with({ t: a, prefix: "--" }) && $std_text.count({ t: a }) >= 2) {
      const name = $std_text.slice({ t: a, from: 2, to: $std_text.count({ t: a }) });
      if (is_value_flag({ name: name }) && $rt.int.add(i, 1, $ob1) < $std_list.len({ xs: argv })) {
        const [, values$1] = $std_map.set({ d: values, key: name, value: $std_list.get({ xs: argv, i: $rt.int.add(i, 1, $ob2) }) });
        values = values$1;
        i = $rt.int.add(i, 2, $ob3);
      } else {
        if (is_value_flag({ name: name })) {
          i = $rt.int.add(i, 1, $ob4);
        } else {
          const [, flags$2] = $std_map.set({ d: flags, key: name, value: true });
          flags = flags$2;
          i = $rt.int.add(i, 1, $ob5);
        }
      }
    } else {
      if (command.tag === "None") {
        command = { tag: "Some", value: a };
      } else {
        const [, files$3] = $std_list.push({ b: files, x: a });
        files = files$3;
      }
      i = $rt.int.add(i, 1, $ob6);
    }
  }
  return { command: command, files: $std_list.finish({ b: files }), flags: flags, values: values };
}

export function flag({ args, name }) {
  return $std_map.contains({ d: args.flags, key: name });
}

export function value({ args, name }) {
  return $std_map.find({ d: args.values, key: name });
}

export function value_or({ args, name, fallback }) {
  const $m5 = $std_map.find({ d: args.values, key: name });
  $m5$match: {
    if ($m5.tag === "Some") {
      const value = $m5.value;
      return value;
      break $m5$match;
    }
    if ($m5.tag === "None") {
      return fallback;
      break $m5$match;
    }
    $rt.unreachable();
  }
}

export function or_empty({ o }) {
  const $m6 = o;
  $m6$match: {
    if ($m6.tag === "Some") {
      const value = $m6.value;
      return value;
      break $m6$match;
    }
    if ($m6.tag === "None") {
      return "";
      break $m6$match;
    }
    $rt.unreachable();
  }
}

export function is_pass({ name }) {
  return $std_list.contains({ xs: passes, x: name });
}

export function plural({ n }) {
  if (n === 1) {
    return "";
  }
  return "s";
}

export function pad({ t, n }) {
  const width = $std_text.count({ t: t });
  if (width >= n) {
    return t;
  }
  return t + $std_text.repeat({ t: " ", n: $rt.int.sub(n, width, $ob7) });
}

export function usage_error({ console }) {
  $std_io.eprint({ console: console, text: usage });
  return { tag: "Err", error: { tag: "Other", detail: "usage" } };
}

export function setup({ args, files, env }) {
  let root = ".";
  if ($std_list.len({ xs: args.files }) > 0) {
    root = $nativebuild.dir_of({ path: $std_list.get({ xs: args.files, i: 0 }) });
  }
  const $m9 = value({ args: args, name: "root" });
  $m9$match: {
    if ($m9.tag === "Some") {
      const value = $m9.value;
      root = value;
      break $m9$match;
    }
    if ($m9.tag === "None") {
      skip({  });
      break $m9$match;
    }
    $rt.unreachable();
  }
  let stdlib = value({ args: args, name: "stdlib" });
  if (stdlib.tag === "None") {
    stdlib = $std_io.get_env({ env: env, name: "ONUS_STDLIB" });
  }
  let budget = 500;
  const $m10 = value({ args: args, name: "budget" });
  $m10$match: {
    if ($m10.tag === "Some") {
      const value = $m10.value;
      budget = parse_budget({ t: value });
      break $m10$match;
    }
    if ($m10.tag === "None") {
      skip({  });
      break $m10$match;
    }
    $rt.unreachable();
  }
  let cache = { tag: "Some", value: root + "/.onus/cache" };
  if (flag({ args: args, name: "no-cache" })) {
    cache = { tag: "None" };
  }
  const led = $ledger.read_ledger({ files: files, dir: root + "/.onus/ledger" });
  let ctx = $context.new_context({ root: value({ args: args, name: "root" }), stdlib: stdlib });
  ctx = { ...ctx, assumptions: led.assumptions, coverage: led.coverage, mutations: led.mutations };
  return { ctx: ctx, vopts: { z3_path: { tag: "None" }, budget_ms: budget, cache_dir: cache, dump_dir: { tag: "None" } }, root: root };
}

export function parse_budget({ t }) {
  const $m18 = $std_int.parse({ t: t });
  $m18$match: {
    if ($m18.tag === "Some") {
      const value = $m18.value;
      if (value > 0) {
        return value;
      }
      return 500;
      break $m18$match;
    }
    if ($m18.tag === "None") {
      return 500;
      break $m18$match;
    }
    $rt.unreachable();
  }
}

export function or_null({ o }) {
  const $m19 = o;
  $m19$match: {
    if ($m19.tag === "Some") {
      const value = $m19.value;
      return value;
      break $m19$match;
    }
    if ($m19.tag === "None") {
      return { tag: "JNull" };
      break $m19$match;
    }
    $rt.unreachable();
  }
}

export function read_entries({ ctx, files, paths }) {
  try {
    for (const p of paths) {
      const text = $rt.unwrap($std_io.read({ files: files, path: p }));
      const [$r21, ctx$4] = $loader.add_file({ ctx: ctx, path: p, text: text });
      ctx = ctx$4;
      if ($r21.tag === "None") {
        return [{ tag: "Err", error: { tag: "Other", detail: p + " is too long" } }, ctx];
      }
    }
    return [{ tag: "Ok", value: undefined }, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, ctx];
    throw $e;
  }
}

export function diag_count({ ctx }) {
  return $std_list.built({ b: ctx.diagnostics });
}

export function emit_diagnostics({ ctx, console, tab, as_json }) {
  for (const d of $std_list.finish({ b: ctx.diagnostics })) {
    if (as_json) {
      $std_io.print({ console: console, text: $json.compact({ j: $diagjson.to_json({ ctx: ctx, tab: tab, d: d }) }) + "\n" });
    } else {
      $std_io.print({ console: console, text: $diagtext.to_text({ ctx: ctx, tab: tab, d: d }) + "\n" });
    }
  }
  return undefined;
}

export function print_ledger({ ctx, console, tab }) {
  const $hi25 = ctx.obligation_count;
  for (let i = 0; i < $hi25; i++) {
    const o = $context.get_obligation({ ctx: ctx, id: i });
    if (o.at_file === 0) {
      let by = "";
      const $m26 = o.by;
      $m26$match: {
        if ($m26.tag === "Some") {
          const value = $m26.value;
          by = "  [" + value + "]";
          break $m26$match;
        }
        if ($m26.tag === "None") {
          skip({  });
          break $m26$match;
        }
        $rt.unreachable();
      }
      $std_io.print({ console: console, text: pad({ t: $obligations.status_text({ s: o.status }), n: 8 }) + " " + pad({ t: $obligations.kind_text({ k: o.kind }), n: 16 }) + " " + $loc.location_text({ ctx: ctx, tables: tab, file: o.at_file, span: o.at_span }) + "  " + $context.get_def({ ctx: ctx, id: o.def }).name + ": " + o.text + by + "\n" });
    }
  }
  return undefined;
}

export function entry_module({ ctx }) {
  const $hi27 = ctx.module_count;
  for (let mid = 0; mid < $hi27; mid++) {
    const $m28 = $std_map.find({ d: ctx.modules, key: mid });
    $m28$match: {
      if ($m28.tag === "Some") {
        const value = $m28.value;
        if (value.file === 0) {
          return { tag: "Some", value: mid };
        }
        break $m28$match;
      }
      if ($m28.tag === "None") {
        skip({  });
        break $m28$match;
      }
      $rt.unreachable();
    }
  }
  return { tag: "None" };
}

export function errors_result({ ctx, console, as_json }) {
  const n = diag_count({ ctx: ctx });
  const line = $std_int.to_text({ x: n }) + " error" + plural({ n: n });
  if (!as_json) {
    $std_io.print({ console: console, text: line + "\n" });
  }
  return { tag: "Err", error: { tag: "Other", detail: line } };
}

export function check_command({ args, files, console, process, env }) {
  try {
    if ($std_list.len({ xs: args.files }) === 0) {
      return usage_error({ console: console });
    }
    const to = value_or({ args: args, name: "to", fallback: "paths" });
    if (!is_pass({ name: to })) {
      $std_io.eprint({ console: console, text: "onus: unknown pass `" + to + "`; expected one of " + $std_text.join({ parts: passes, sep: ", " }) + "\n" });
      return { tag: "Err", error: { tag: "Other", detail: "unknown pass" } };
    }
    const s = setup({ args: args, files: files, env: env });
    let ctx = s.ctx;
    const [$r35, ctx$5] = read_entries({ ctx: ctx, files: files, paths: args.files });
    ctx = ctx$5;
    $rt.unwrap($r35);
    const [, ctx$6] = $check.run_passes({ ctx: ctx, to: $check.pass_index({ name: to }), files: files, console: console, process: process, vopts: s.vopts });
    ctx = ctx$6;
    const tab = $loc.line_tables({ ctx: ctx });
    const as_json = flag({ args: args, name: "json" });
    emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
    if (flag({ args: args, name: "ledger" })) {
      print_ledger({ ctx: ctx, console: console, tab: tab });
    }
    if (!$context.clean({ ctx: ctx })) {
      return errors_result({ ctx: ctx, console: console, as_json: as_json });
    }
    return { tag: "Ok", value: undefined };
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return $e.value;
    throw $e;
  }
}

export function fmt_command({ args, files, console }) {
  try {
    if ($std_list.len({ xs: args.files }) === 0) {
      return usage_error({ console: console });
    }
    let ctx = $context.new_context({ root: { tag: "None" }, stdlib: { tag: "None" } });
    const [$r39, ctx$7] = read_entries({ ctx: ctx, files: files, paths: args.files });
    ctx = ctx$7;
    $rt.unwrap($r39);
    const $hi40 = $context.file_count({ ctx: ctx });
    for (let f = 0; f < $hi40; f++) {
      const [, ctx$8] = $loader.canonical({ ctx: ctx, file: f });
      ctx = ctx$8;
    }
    const tab = $loc.line_tables({ ctx: ctx });
    let syntax_errors = 0;
    for (const d of $std_list.finish({ b: ctx.diagnostics })) {
      if (d.code !== "E0001") {
        $std_io.print({ console: console, text: $diagtext.to_text({ ctx: ctx, tab: tab, d: d }) + "\n" });
        syntax_errors = $rt.int.add(syntax_errors, 1, $ob8);
      }
    }
    if (syntax_errors > 0) {
      return { tag: "Err", error: { tag: "Other", detail: $std_int.to_text({ x: syntax_errors }) + " syntax error" + plural({ n: syntax_errors }) } };
    }
    const $hi43 = $context.file_count({ ctx: ctx });
    for (let f = 0; f < $hi43; f++) {
      const $m44 = $std_map.find({ d: ctx.canonical, key: f });
      $m44$match: {
        if ($m44.tag === "Some") {
          const value = $m44.value;
          const source = $context.file_at({ ctx: ctx, id: f });
          if (flag({ args: args, name: "stdout" })) {
            $std_io.print({ console: console, text: value });
          } else {
            if (value !== source.text) {
              $rt.unwrap($build.write_file({ files: files, path: source.path, text: value }));
            }
          }
          break $m44$match;
        }
        if ($m44.tag === "None") {
          skip({  });
          break $m44$match;
        }
        $rt.unreachable();
      }
    }
    return { tag: "Ok", value: undefined };
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return $e.value;
    throw $e;
  }
}

export function io_error_text({ e }) {
  const $m46 = e;
  $m46$match: {
    if ($m46.tag === "NotFound") {
      const path = $m46.path;
      return "not found: " + path;
      break $m46$match;
    }
    if ($m46.tag === "Denied") {
      const path = $m46.path;
      return "permission denied: " + path;
      break $m46$match;
    }
    if ($m46.tag === "Other") {
      const detail = $m46.detail;
      return detail;
      break $m46$match;
    }
    $rt.unreachable();
  }
}

export function run_program({ process, console, program, args }) {
  const $m47 = $std_io.run({ process: process, program: program, args: args, stdin: "", timeout_ms: 0 });
  $m47$match: {
    if ($m47.tag === "Ok") {
      const value = $m47.value;
      $std_io.print({ console: console, text: value.stdout });
      $std_io.eprint({ console: console, text: value.stderr });
      if (value.status !== 0) {
        return { tag: "Err", error: { tag: "Other", detail: "exit status " + $std_int.to_text({ x: value.status }) } };
      }
      return { tag: "Ok", value: undefined };
      break $m47$match;
    }
    if ($m47.tag === "Err") {
      const error = $m47.error;
      $std_io.eprint({ console: console, text: "onus run: cannot run " + program + ": " + io_error_text({ e: error }) + "\n" });
      return { tag: "Err", error: error };
      break $m47$match;
    }
    $rt.unreachable();
  }
}

export function runtime_dir_of({ runtime }) {
  if ($std_text.contains({ t: runtime, needle: "/" })) {
    return { tag: "Some", value: $nativebuild.dir_of({ path: $nativebuild.dir_of({ path: runtime }) }) + "/native" };
  }
  return { tag: "None" };
}

export function build_command({ args, files, console, process, env, run }) {
  try {
    if ($std_list.len({ xs: args.files }) === 0) {
      return usage_error({ console: console });
    }
    const entry = $std_list.get({ xs: args.files, i: 0 });
    const rest = $std_list.slice({ xs: args.files, from: 1, to: $std_list.len({ xs: args.files }) });
    const emit = value_or({ args: args, name: "emit", fallback: "js" });
    if (emit === "ts") {
      $std_io.eprint({ console: console, text: "onus: --emit ts is the TypeScript oracle output; the TypeScript `onus` produces it\n" });
      return { tag: "Err", error: { tag: "Other", detail: "--emit ts" } };
    }
    if (emit !== "js" && emit !== "ir") {
      $std_io.eprint({ console: console, text: "onus: --emit takes js or ir\n" });
      return { tag: "Err", error: { tag: "Other", detail: "--emit" } };
    }
    const target = value_or({ args: args, name: "target", fallback: "js" });
    if (target !== "js" && target !== "native" && target !== "wasm") {
      $std_io.eprint({ console: console, text: "onus: --target takes js, native or wasm\n" });
      return { tag: "Err", error: { tag: "Other", detail: "--target" } };
    }
    const s = setup({ args: args, files: files, env: env });
    let ctx = s.ctx;
    const [$r60, ctx$9] = read_entries({ ctx: ctx, files: files, paths: [entry] });
    ctx = ctx$9;
    $rt.unwrap($r60);
    const out_dir = value_or({ args: args, name: "out", fallback: $nativebuild.dir_of({ path: entry }) + "/out" });
    let runtime = "@onus/runtime";
    const $m61 = $std_io.get_env({ env: env, name: "ONUS_RUNTIME" });
    $m61$match: {
      if ($m61.tag === "Some") {
        const value = $m61.value;
        runtime = value;
        break $m61$match;
      }
      if ($m61.tag === "None") {
        skip({  });
        break $m61$match;
      }
      $rt.unreachable();
    }
    runtime = value_or({ args: args, name: "runtime", fallback: runtime });
    const [, ctx$10] = $check.run_passes({ ctx: ctx, to: 11, files: files, console: console, process: process, vopts: s.vopts });
    ctx = ctx$10;
    const tab = $loc.line_tables({ ctx: ctx });
    const as_json = flag({ args: args, name: "json" });
    if (emit === "ir") {
      emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
      if (!$context.clean({ ctx: ctx })) {
        return { tag: "Err", error: { tag: "Other", detail: "diagnostics" } };
      }
      const $hi64 = ctx.module_count;
      for (let mid = 0; mid < $hi64; mid++) {
        const $m65 = $std_map.find({ d: ctx.modules, key: mid });
        $m65$match: {
          if ($m65.tag === "Some") {
            const value = $m65.value;
            if (!value.is_std) {
              $std_io.print({ console: console, text: $irtext.print_ir({ ctx: ctx, m: $lowerir.lower_module({ ctx: ctx, m: value, tables: tab, opts: { verify_all: false, negate_guard: { tag: "None" } } }) }) });
            }
            break $m65$match;
          }
          if ($m65.tag === "None") {
            skip({  });
            break $m65$match;
          }
          $rt.unreachable();
        }
      }
      return { tag: "Ok", value: undefined };
    }
    if (target === "native" || target === "wasm") {
      if (!$context.clean({ ctx: ctx })) {
        emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
        return { tag: "Err", error: { tag: "Other", detail: "diagnostics" } };
      }
      const [$r71, ctx$11] = $nativebuild.build_native({ ctx: ctx, files: files, process: process, env: env, tab: tab, out_dir: out_dir, runtime_dir: runtime_dir_of({ runtime: runtime }), target: target });
      ctx = ctx$11;
      const built = $rt.unwrap($r71);
      emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
      if (!$context.clean({ ctx: ctx }) || built.exe.tag === "None") {
        return { tag: "Err", error: { tag: "Other", detail: "native build failed" } };
      }
      const exe = or_empty({ o: built.exe });
      $std_io.eprint({ console: console, text: "onus build: wrote " + exe + "\n" });
      if (!run) {
        return { tag: "Ok", value: undefined };
      }
      if (!built.has_main) {
        $std_io.eprint({ console: console, text: "onus run: " + entry + " declares no `pub fn main`\n" });
        return { tag: "Err", error: { tag: "Other", detail: "no main" } };
      }
      if (target === "wasm") {
        return run_program({ process: process, console: console, program: "node", args: [...[$nativebuild.dir_of({ path: exe }) + "/run_wasm.mjs"], ...rest] });
      }
      return run_program({ process: process, console: console, program: exe, args: rest });
    }
    if (!$context.clean({ ctx: ctx })) {
      emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
      return { tag: "Err", error: { tag: "Other", detail: "diagnostics" } };
    }
    const built_js = $rt.unwrap($build.emit_all({ ctx: ctx, files: files, opts: { out_dir: out_dir, runtime: runtime, verify_all: false, negate_guard: { tag: "None" } } }));
    emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
    if (!run) {
      return { tag: "Ok", value: undefined };
    }
    const $m82 = built_js.launcher;
    $m82$match: {
      if ($m82.tag === "None") {
        $std_io.eprint({ console: console, text: "onus run: " + entry + " declares no `pub fn main`\n" });
        return { tag: "Err", error: { tag: "Other", detail: "no main" } };
        break $m82$match;
      }
      if ($m82.tag === "Some") {
        const value = $m82.value;
        return run_program({ process: process, console: console, program: "node", args: [...[value], ...rest] });
        break $m82$match;
      }
      $rt.unreachable();
    }
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return $e.value;
    throw $e;
  }
}

export function is_interface_document({ j }) {
  return $json.at({ j: j, key: "module" }).tag === "JString" && $json.has({ j: j, key: "hash" }) && $json.at({ j: j, key: "items" }).tag === "JArray";
}

export function interface_command({ args, files, console, process, env }) {
  try {
    if ($std_list.len({ xs: args.files }) === 0) {
      return usage_error({ console: console });
    }
    const entry = $std_list.get({ xs: args.files, i: 0 });
    const s = setup({ args: args, files: files, env: env });
    let ctx = s.ctx;
    const [$r85, ctx$12] = read_entries({ ctx: ctx, files: files, paths: [entry] });
    ctx = ctx$12;
    $rt.unwrap($r85);
    const [, ctx$13] = $check.run_passes({ ctx: ctx, to: 11, files: files, console: console, process: process, vopts: s.vopts });
    ctx = ctx$13;
    const tab = $loc.line_tables({ ctx: ctx });
    const as_json = flag({ args: args, name: "json" });
    emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
    if (!$context.clean({ ctx: ctx })) {
      return { tag: "Err", error: { tag: "Other", detail: "diagnostics" } };
    }
    let mod = $rt.int.neg(1, $ob9);
    const $m88 = entry_module({ ctx: ctx });
    $m88$match: {
      if ($m88.tag === "Some") {
        const value = $m88.value;
        mod = value;
        break $m88$match;
      }
      if ($m88.tag === "None") {
        $std_io.eprint({ console: console, text: "onus interface: " + entry + " is not a module\n" });
        return { tag: "Err", error: { tag: "Other", detail: "not a module" } };
        break $m88$match;
      }
      $rt.unreachable();
    }
    const doc = $interface.interface_of({ ctx: ctx, mod: mod });
    const $m91 = value({ args: args, name: "diff" });
    $m91$match: {
      if ($m91.tag === "Some") {
        const value = $m91.value;
        const old_text = $rt.unwrap($std_io.read({ files: files, path: value }));
        const old_doc = or_null({ o: $json.parse({ t: old_text }) });
        if (!is_interface_document({ j: old_doc })) {
          $std_io.eprint({ console: console, text: "onus: " + value + " is not an interface document\n" });
          return { tag: "Err", error: { tag: "Other", detail: "not an interface document" } };
        }
        const d = $idiff.interface_diff({ before: old_doc, after: doc });
        if (as_json) {
          $std_io.print({ console: console, text: $json.pretty({ j: $idiff.diff_json({ d: d }) }) + "\n" });
        } else {
          $std_io.print({ console: console, text: $idiff.diff_text({ d: d }) });
        }
        if (d.breaking) {
          return { tag: "Err", error: { tag: "Other", detail: "breaking" } };
        }
        return { tag: "Ok", value: undefined };
        break $m91$match;
      }
      if ($m91.tag === "None") {
        skip({  });
        break $m91$match;
      }
      $rt.unreachable();
    }
    if (as_json) {
      $std_io.print({ console: console, text: $json.pretty({ j: doc }) + "\n" });
    } else {
      $std_io.print({ console: console, text: $interface.interface_text({ ctx: ctx, mod: mod }) });
    }
    return { tag: "Ok", value: undefined };
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return $e.value;
    throw $e;
  }
}

export function path_command({ args, files, console, process, env }) {
  try {
    if ($std_list.len({ xs: args.files }) === 0) {
      return usage_error({ console: console });
    }
    const entry = $std_list.get({ xs: args.files, i: 0 });
    let wanted = { tag: "None" };
    if ($std_list.len({ xs: args.files }) > 1) {
      wanted = { tag: "Some", value: $std_list.get({ xs: args.files, i: 1 }) };
    }
    const s = setup({ args: args, files: files, env: env });
    let ctx = s.ctx;
    const [$r100, ctx$14] = read_entries({ ctx: ctx, files: files, paths: [entry] });
    ctx = ctx$14;
    $rt.unwrap($r100);
    const [, ctx$15] = $check.run_passes({ ctx: ctx, to: 11, files: files, console: console, process: process, vopts: s.vopts });
    ctx = ctx$15;
    const tab = $loc.line_tables({ ctx: ctx });
    const as_json = flag({ args: args, name: "json" });
    emit_diagnostics({ ctx: ctx, console: console, tab: tab, as_json: as_json });
    let entry_mod = $rt.int.neg(1, $ob10);
    const $m101 = entry_module({ ctx: ctx });
    $m101$match: {
      if ($m101.tag === "Some") {
        const value = $m101.value;
        entry_mod = value;
        break $m101$match;
      }
      if ($m101.tag === "None") {
        skip({  });
        break $m101$match;
      }
      $rt.unreachable();
    }
    let reports = $std_list.builder({  });
    for (const k of $std_map.keys({ d: ctx.analyses })) {
      const $m102 = $std_map.find({ d: ctx.analyses, key: k });
      $m102$match: {
        if ($m102.tag === "Some") {
          const value = $m102.value;
          if (value.mod === entry_mod) {
            let chosen = true;
            if (wanted.tag === "Some") {
              chosen = $context.get_def({ ctx: ctx, id: value.def }).name === or_empty({ o: wanted });
            }
            if (chosen) {
              const [, reports$16] = $std_list.push({ b: reports, x: $pathreport.path_report({ ctx: ctx, tab: tab, a: value }) });
              reports = reports$16;
            }
          }
          break $m102$match;
        }
        if ($m102.tag === "None") {
          skip({  });
          break $m102$match;
        }
        $rt.unreachable();
      }
    }
    const found = $std_list.finish({ b: reports });
    if (wanted.tag === "Some" && $std_list.len({ xs: found }) === 0 && $context.clean({ ctx: ctx })) {
      $std_io.eprint({ console: console, text: "onus path: no path `" + or_empty({ o: wanted }) + "` in " + entry + "\n" });
      return { tag: "Err", error: { tag: "Other", detail: "no such path" } };
    }
    for (const r of found) {
      if (as_json) {
        $std_io.print({ console: console, text: $json.pretty({ j: r }) + "\n" });
      } else {
        $std_io.print({ console: console, text: $pathtext.path_text({ r: r }) });
      }
    }
    if (!$context.clean({ ctx: ctx })) {
      return { tag: "Err", error: { tag: "Other", detail: "diagnostics" } };
    }
    return { tag: "Ok", value: undefined };
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return $e.value;
    throw $e;
  }
}

export function main({ args, files, console, process, env }) {
  const a = parse_args({ argv: args });
  const $m108 = a.command;
  $m108$match: {
    if ($m108.tag === "None") {
      return usage_error({ console: console });
      break $m108$match;
    }
    if ($m108.tag === "Some") {
      const value = $m108.value;
      if (value === "check") {
        return check_command({ args: a, files: files, console: console, process: process, env: env });
      }
      if (value === "fmt") {
        return fmt_command({ args: a, files: files, console: console });
      }
      if (value === "build") {
        return build_command({ args: a, files: files, console: console, process: process, env: env, run: false });
      }
      if (value === "run") {
        return build_command({ args: a, files: files, console: console, process: process, env: env, run: true });
      }
      if (value === "interface") {
        return interface_command({ args: a, files: files, console: console, process: process, env: env });
      }
      if (value === "path") {
        return path_command({ args: a, files: files, console: console, process: process, env: env });
      }
      return usage_error({ console: console });
      break $m108$match;
    }
    $rt.unreachable();
  }
}

