// Generated by onus from module constant. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $std_map from "./std/map.js";
import * as $evaluator from "./evaluator.js";
import * as $lower from "./lower.js";
import * as $defs from "./defs.js";
import * as $walk from "./walk.js";
import * as $std_float from "./std/float.js";
import * as $values from "./values.js";
import * as $parser from "./parser.js";
import * as $std_list from "./std/list.js";

const $ob1 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:27:20", def: "or_neg" };
const $ob2 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:58:20", def: "ctor_def" };
const $ob3 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:62:19", def: "ctor_def" };
const $ob4 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:68:20", def: "callee_def" };
const $ob5 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:73:19", def: "callee_def" };
const $ob6 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:280:17", def: "eval_pred" };
const $ob7 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:302:17", def: "eval_pred" };
const $ob8 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:322:13", def: "eval_pred" };
const $ob9 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:365:13", def: "eval_value" };
const $ob10 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:374:13", def: "eval_value" };
const $ob11 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:391:17", def: "eval_value" };
const $ob12 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:407:13", def: "eval_value" };
const $ob13 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:418:13", def: "eval_value" };
const $ob14 = { kind: "overflow", text: "a + b within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:505:9", def: "compare" };
const $ob15 = { kind: "overflow", text: "a - b within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:512:9", def: "compare" };
const $ob16 = { kind: "overflow", text: "a * b within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:519:9", def: "compare" };
const $ob17 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/constant.onus:599:13", def: "requires_verdict" };
export const budget = 100000;

export function skip($args) {
  return undefined;
}

export function or_neg({ o }) {
  const $m1 = o;
  $m1$match: {
    if ($m1.tag === "Some") {
      const value = $m1.value;
      return value;
      break $m1$match;
    }
    if ($m1.tag === "None") {
      return $rt.int.neg(1, $ob1);
      break $m1$match;
    }
    $rt.unreachable();
  }
}

export function bool_of({ o }) {
  const $m2 = o;
  $m2$match: {
    if ($m2.tag === "None") {
      return { tag: "None" };
      break $m2$match;
    }
    if ($m2.tag === "Some") {
      const value = $m2.value;
      const $m4 = value;
      $m4$match: {
        if ($m4.tag === "BoolV") {
          const v = $m4.v;
          return { tag: "Some", value: v };
          break $m4$match;
        }
        if (true) {
          return { tag: "None" };
          break $m4$match;
        }
        $rt.unreachable();
      }
      break $m2$match;
    }
    $rt.unreachable();
  }
}

export function fields_or({ o }) {
  const $m7 = o;
  $m7$match: {
    if ($m7.tag === "Some") {
      const value = $m7.value;
      return value;
      break $m7$match;
    }
    if ($m7.tag === "None") {
      return [];
      break $m7$match;
    }
    $rt.unreachable();
  }
}

export function find_field({ fs, name }) {
  for (const f of fs) {
    if (f.name === name) {
      return { tag: "Some", value: f };
    }
  }
  return { tag: "None" };
}

export function ctor_def({ ctx, k }) {
  const $m10 = $std_map.find({ d: ctx.refs, key: k });
  $m10$match: {
    if ($m10.tag === "None") {
      return $rt.int.neg(1, $ob2);
      break $m10$match;
    }
    if ($m10.tag === "Some") {
      const value = $m10.value;
      const $m11 = value;
      $m11$match: {
        if ($m11.tag === "DefRes") {
          const def = $m11.def;
          return def;
          break $m11$match;
        }
        if (true) {
          return $rt.int.neg(1, $ob3);
          break $m11$match;
        }
        $rt.unreachable();
      }
      break $m10$match;
    }
    $rt.unreachable();
  }
}

export function callee_def({ ctx, k }) {
  const $m12 = $std_map.find({ d: ctx.refs, key: k });
  $m12$match: {
    if ($m12.tag === "None") {
      return $rt.int.neg(1, $ob4);
      break $m12$match;
    }
    if ($m12.tag === "Some") {
      const value = $m12.value;
      const $m13 = value;
      $m13$match: {
        if ($m13.tag === "DefRes") {
          const def = $m13.def;
          return def;
          break $m13$match;
        }
        if ($m13.tag === "CompanionRes") {
          const owner = $m13.owner;
          const fn_def = $m13.fn_def;
          return fn_def;
          break $m13$match;
        }
        if (true) {
          return $rt.int.neg(1, $ob5);
          break $m13$match;
        }
        $rt.unreachable();
      }
      break $m12$match;
    }
    $rt.unreachable();
  }
}

export function eval_const({ ev, ctx, e, env, file }) {
  ev = { ...ev, file: file };
  const [$r16, ev$1, ctx$1] = $evaluator.eval_expr({ fuel: $evaluator.max_depth, ev: ev, ctx: ctx, e: e, env: env });
  ev = ev$1;
  ctx = ctx$1;
  const $m15 = $r16;
  $m15$match: {
    if ($m15.tag === "Ok") {
      const value = $m15.value;
      return [{ tag: "Some", value: value }, ev, ctx];
      break $m15$match;
    }
    if ($m15.tag === "Err") {
      return [{ tag: "None" }, ev, ctx];
      break $m15$match;
    }
    $rt.unreachable();
  }
}

export function const_discharge({ ctx, o }) {
  const src = or_neg({ o: o.source });
  if (src < 0) {
    return [{ tag: "None" }, ctx];
  }
  let ev = $evaluator.new_ev({ file: o.at_file });
  ev = { ...ev, budget: budget };
  const $m21 = o.kind;
  $m21$match: {
    if ($m21.tag === "Refinement") {
      const [$r22, ev$2, ctx$2] = refinement_verdict({ ev: ev, ctx: ctx, o: o, src: src });
      ev = ev$2;
      ctx = ctx$2;
      return [$r22, ctx];
      break $m21$match;
    }
    if ($m21.tag === "Requires") {
      const [$r23, ev$3, ctx$3] = requires_verdict({ ev: ev, ctx: ctx, o: o, src: src });
      ev = ev$3;
      ctx = ctx$3;
      return [$r23, ctx];
      break $m21$match;
    }
    if (true) {
      return [{ tag: "None" }, ctx];
      break $m21$match;
    }
    $rt.unreachable();
  }
}

export function refinement_verdict({ ev, ctx, o, src }) {
  const value_e = $std_map.find({ d: ctx.expr_nodes, key: o.at });
  const pred_e = $std_map.find({ d: ctx.where_exprs, key: src });
  if (value_e.tag === "None" || pred_e.tag === "None") {
    return [{ tag: "None" }, ev, ctx];
  }
  let env = $std_map.dict({  });
  const $m26 = $std_map.find({ d: ctx.ctor_of, key: o.at });
  $m26$match: {
    if ($m26.tag === "Some") {
      const value = $m26.value;
      const [$r27, ev$4, ctx$4, env$4] = sibling_env({ ev: ev, ctx: ctx, ctor: value, file: o.at_file, env: env });
      ev = ev$4;
      ctx = ctx$4;
      env = env$4;
      if (!$r27) {
        return [{ tag: "None" }, ev, ctx];
      }
      break $m26$match;
    }
    if ($m26.tag === "None") {
      skip({  });
      break $m26$match;
    }
    $rt.unreachable();
  }
  const [$r29, ev$5, ctx$5] = eval_const({ ev: ev, ctx: ctx, e: expr_or({ o: value_e }), env: $std_map.dict({  }), file: o.at_file });
  ev = ev$5;
  ctx = ctx$5;
  const it_v = $r29;
  if (it_v.tag === "None") {
    return [{ tag: "None" }, ev, ctx];
  }
  const [$r31, ev$6, ctx$6] = eval_pred({ fuel: $evaluator.max_depth, ev: ev, ctx: ctx, e: expr_or({ o: pred_e }), env: env, it_v: value_or_unit({ o: it_v }), file: $lower.pred_file({ k: src }) });
  ev = ev$6;
  ctx = ctx$6;
  return [$r31, ev, ctx];
}

export function expr_or({ o }) {
  const $m32 = o;
  $m32$match: {
    if ($m32.tag === "Some") {
      const value = $m32.value;
      return value;
      break $m32$match;
    }
    if ($m32.tag === "None") {
      return { tag: "Hole", span: { start: 0, end: 0 } };
      break $m32$match;
    }
    $rt.unreachable();
  }
}

export function value_or_unit({ o }) {
  const $m35 = o;
  $m35$match: {
    if ($m35.tag === "Some") {
      const value = $m35.value;
      return value;
      break $m35$match;
    }
    if ($m35.tag === "None") {
      return { tag: "UnitV" };
      break $m35$match;
    }
    $rt.unreachable();
  }
}

export function sibling_env({ ev, ctx, ctor, file, env }) {
  const $m37 = ctor;
  $m37$match: {
    if ($m37.tag === "Ctor") {
      const args = $m37.args;
      const fields = $m37.fields;
      const span = $m37.span;
      const owner = ctor_def({ ctx: ctx, k: $defs.node_key({ file: file, tag: $defs.tag_expr, span: span }) });
      let fs = [];
      if (owner >= 0) {
        fs = fields_or({ o: $std_map.find({ d: ctx.fields, key: owner }) });
      }
      const $m38 = args;
      $m38$match: {
        if ($m38.tag === "Some") {
          const value = $m38.value;
          for (const a of value) {
            const [$r39, ev$7, ctx$7, env$7] = bind_sibling({ ev: ev, ctx: ctx, fs: fs, name: a.name.text, e: a.value, file: file, env: env });
            ev = ev$7;
            ctx = ctx$7;
            env = env$7;
            if (!$r39) {
              return [false, ev, ctx, env];
            }
          }
          break $m38$match;
        }
        if ($m38.tag === "None") {
          skip({  });
          break $m38$match;
        }
        $rt.unreachable();
      }
      const $m40 = fields;
      $m40$match: {
        if ($m40.tag === "Some") {
          const value = $m40.value;
          for (const f of value) {
            const [$r41, ev$8, ctx$8, env$8] = bind_sibling({ ev: ev, ctx: ctx, fs: fs, name: f.name.text, e: f.value, file: file, env: env });
            ev = ev$8;
            ctx = ctx$8;
            env = env$8;
            if (!$r41) {
              return [false, ev, ctx, env];
            }
          }
          break $m40$match;
        }
        if ($m40.tag === "None") {
          skip({  });
          break $m40$match;
        }
        $rt.unreachable();
      }
      return [true, ev, ctx, env];
      break $m37$match;
    }
    if (true) {
      return [true, ev, ctx, env];
      break $m37$match;
    }
    $rt.unreachable();
  }
}

export function bind_sibling({ ev, ctx, fs, name, e, file, env }) {
  const $m42 = find_field({ fs: fs, name: name });
  $m42$match: {
    if ($m42.tag === "None") {
      return [true, ev, ctx, env];
      break $m42$match;
    }
    if ($m42.tag === "Some") {
      const value = $m42.value;
      const [$r43, ev$9, ctx$9] = eval_const({ ev: ev, ctx: ctx, e: e, env: $std_map.dict({  }), file: file });
      ev = ev$9;
      ctx = ctx$9;
      const fv = $r43;
      if (fv.tag === "None") {
        return [false, ev, ctx, env];
      }
      const [, env$10] = $std_map.set({ d: env, key: value.def, value: value_or_unit({ o: fv }) });
      env = env$10;
      return [true, ev, ctx, env];
      break $m42$match;
    }
    $rt.unreachable();
  }
}

export function eval_pred({ fuel, ev, ctx, e, env, it_v, file }) {
  if (fuel === 0) {
    return [{ tag: "None" }, ev, ctx];
  }
  const $m45 = e;
  $m45$match: {
    if ($m45.tag === "And") {
      const operands = $m45.operands;
      for (const x of operands) {
        const [$r47, ev$11, ctx$11] = eval_value({ fuel: $rt.int.sub(fuel, 1, $ob6), ev: ev, ctx: ctx, e: x, env: env, it_v: it_v, file: file });
        ev = ev$11;
        ctx = ctx$11;
        const $m46 = bool_of({ o: $r47 });
        $m46$match: {
          if ($m46.tag === "None") {
            return [{ tag: "None" }, ev, ctx];
            break $m46$match;
          }
          if ($m46.tag === "Some") {
            const value = $m46.value;
            if (!value) {
              return [{ tag: "Some", value: false }, ev, ctx];
            }
            break $m46$match;
          }
          $rt.unreachable();
        }
      }
      return [{ tag: "Some", value: true }, ev, ctx];
      break $m45$match;
    }
    if ($m45.tag === "Or") {
      const operands = $m45.operands;
      for (const x of operands) {
        const [$r52, ev$12, ctx$12] = eval_value({ fuel: $rt.int.sub(fuel, 1, $ob7), ev: ev, ctx: ctx, e: x, env: env, it_v: it_v, file: file });
        ev = ev$12;
        ctx = ctx$12;
        const $m51 = bool_of({ o: $r52 });
        $m51$match: {
          if ($m51.tag === "None") {
            return [{ tag: "None" }, ev, ctx];
            break $m51$match;
          }
          if ($m51.tag === "Some") {
            const value = $m51.value;
            if (value) {
              return [{ tag: "Some", value: true }, ev, ctx];
            }
            break $m51$match;
          }
          $rt.unreachable();
        }
      }
      return [{ tag: "Some", value: false }, ev, ctx];
      break $m45$match;
    }
    if (true) {
      const [$r56, ev$13, ctx$13] = eval_value({ fuel: $rt.int.sub(fuel, 1, $ob8), ev: ev, ctx: ctx, e: e, env: env, it_v: it_v, file: file });
      ev = ev$13;
      ctx = ctx$13;
      return [bool_of({ o: $r56 }), ev, ctx];
      break $m45$match;
    }
    $rt.unreachable();
  }
}

export function mentions_it({ root }) {
  for (const n of $walk.nodes_in_expr({ e: root, into_verify: true })) {
    const $m57 = n;
    $m57$match: {
      if ($m57.tag === "NExpr") {
        const e = $m57.e;
        if (e.tag === "It") {
          return true;
        }
        break $m57$match;
      }
      if (true) {
        skip({  });
        break $m57$match;
      }
      $rt.unreachable();
    }
  }
  return false;
}

export function eval_value({ fuel, ev, ctx, e, env, it_v, file }) {
  if (fuel === 0) {
    return [{ tag: "None" }, ev, ctx];
  }
  const $m59 = e;
  $m59$match: {
    if ($m59.tag === "It") {
      return [{ tag: "Some", value: it_v }, ev, ctx];
      break $m59$match;
    }
    if ($m59.tag === "Binary") {
      const op = $m59.op;
      const left = $m59.left;
      const right = $m59.right;
      const [$r61, ev$14, ctx$14] = eval_value({ fuel: $rt.int.sub(fuel, 1, $ob9), ev: ev, ctx: ctx, e: left, env: env, it_v: it_v, file: file });
      ev = ev$14;
      ctx = ctx$14;
      const l = $r61;
      const [$r62, ev$15, ctx$15] = eval_value({ fuel: $rt.int.sub(fuel, 1, $ob10), ev: ev, ctx: ctx, e: right, env: env, it_v: it_v, file: file });
      ev = ev$15;
      ctx = ctx$15;
      const r = $r62;
      if (l.tag === "None" || r.tag === "None") {
        return [{ tag: "None" }, ev, ctx];
      }
      return [compare({ op: op, l: value_or_unit({ o: l }), r: value_or_unit({ o: r }) }), ev, ctx];
      break $m59$match;
    }
    if ($m59.tag === "Unary") {
      const op = $m59.op;
      const operand = $m59.operand;
      if (op === "not") {
        const [$r65, ev$16, ctx$16] = eval_value({ fuel: $rt.int.sub(fuel, 1, $ob11), ev: ev, ctx: ctx, e: operand, env: env, it_v: it_v, file: file });
        ev = ev$16;
        ctx = ctx$16;
        const $m64 = bool_of({ o: $r65 });
        $m64$match: {
          if ($m64.tag === "Some") {
            const value = $m64.value;
            return [{ tag: "Some", value: { tag: "BoolV", v: !value } }, ev, ctx];
            break $m64$match;
          }
          if ($m64.tag === "None") {
            return [{ tag: "None" }, ev, ctx];
            break $m64$match;
          }
          $rt.unreachable();
        }
      }
      const [$r69, ev$17, ctx$17] = eval_rest({ ev: ev, ctx: ctx, e: e, env: env, file: file });
      ev = ev$17;
      ctx = ctx$17;
      return [$r69, ev, ctx];
      break $m59$match;
    }
    if ($m59.tag === "And") {
      const [$r70, ev$18, ctx$18] = eval_pred({ fuel: $rt.int.sub(fuel, 1, $ob12), ev: ev, ctx: ctx, e: e, env: env, it_v: it_v, file: file });
      ev = ev$18;
      ctx = ctx$18;
      return [bool_value({ o: $r70 }), ev, ctx];
      break $m59$match;
    }
    if ($m59.tag === "Or") {
      const [$r71, ev$19, ctx$19] = eval_pred({ fuel: $rt.int.sub(fuel, 1, $ob13), ev: ev, ctx: ctx, e: e, env: env, it_v: it_v, file: file });
      ev = ev$19;
      ctx = ctx$19;
      return [bool_value({ o: $r71 }), ev, ctx];
      break $m59$match;
    }
    if (true) {
      const [$r72, ev$20, ctx$20] = eval_rest({ ev: ev, ctx: ctx, e: e, env: env, file: file });
      ev = ev$20;
      ctx = ctx$20;
      return [$r72, ev, ctx];
      break $m59$match;
    }
    $rt.unreachable();
  }
}

export function bool_value({ o }) {
  const $m73 = o;
  $m73$match: {
    if ($m73.tag === "Some") {
      const value = $m73.value;
      return { tag: "Some", value: { tag: "BoolV", v: value } };
      break $m73$match;
    }
    if ($m73.tag === "None") {
      return { tag: "None" };
      break $m73$match;
    }
    $rt.unreachable();
  }
}

export function eval_rest({ ev, ctx, e, env, file }) {
  if (mentions_it({ root: e })) {
    return [{ tag: "None" }, ev, ctx];
  }
  const [$r78, ev$21, ctx$21] = eval_const({ ev: ev, ctx: ctx, e: e, env: env, file: file });
  ev = ev$21;
  ctx = ctx$21;
  return [$r78, ev, ctx];
}

export function is_int_like({ v }) {
  const $m79 = v;
  $m79$match: {
    if ($m79.tag === "IntV") {
      return true;
      break $m79$match;
    }
    if ($m79.tag === "DurationV") {
      return true;
      break $m79$match;
    }
    if (true) {
      return false;
      break $m79$match;
    }
    $rt.unreachable();
  }
}

export function int_of({ x }) {
  const $m80 = x;
  $m80$match: {
    if ($m80.tag === "IntV") {
      const v = $m80.v;
      return v;
      break $m80$match;
    }
    if ($m80.tag === "DurationV") {
      const v = $m80.v;
      return v;
      break $m80$match;
    }
    if (true) {
      return 0;
      break $m80$match;
    }
    $rt.unreachable();
  }
}

export function float_of({ x }) {
  const $m81 = x;
  $m81$match: {
    if ($m81.tag === "FloatV") {
      const v = $m81.v;
      return v;
      break $m81$match;
    }
    if ($m81.tag === "IntV") {
      const v = $m81.v;
      return $std_float.of({ x: v });
      break $m81$match;
    }
    if ($m81.tag === "DurationV") {
      const v = $m81.v;
      return $std_float.of({ x: v });
      break $m81$match;
    }
    if (true) {
      return 0;
      break $m81$match;
    }
    $rt.unreachable();
  }
}

export function is_number({ v }) {
  const $m82 = v;
  $m82$match: {
    if ($m82.tag === "FloatV") {
      return true;
      break $m82$match;
    }
    if (true) {
      return is_int_like({ v: v });
      break $m82$match;
    }
    $rt.unreachable();
  }
}

export function compare({ op, l, r }) {
  if (op === "==") {
    return { tag: "Some", value: { tag: "BoolV", v: $values.equals({ a: l, b: r }) } };
  }
  if (op === "!=") {
    return { tag: "Some", value: { tag: "BoolV", v: !$values.equals({ a: l, b: r }) } };
  }
  if (!is_number({ v: l }) || !is_number({ v: r })) {
    return { tag: "None" };
  }
  if (is_int_like({ v: l }) && is_int_like({ v: r })) {
    const a = int_of({ x: l });
    const b = int_of({ x: r });
    if (op === "<") {
      return { tag: "Some", value: { tag: "BoolV", v: a < b } };
    }
    if (op === "<=") {
      return { tag: "Some", value: { tag: "BoolV", v: a <= b } };
    }
    if (op === ">") {
      return { tag: "Some", value: { tag: "BoolV", v: a > b } };
    }
    if (op === ">=") {
      return { tag: "Some", value: { tag: "BoolV", v: a >= b } };
    }
    if (op === "+") {
      const $m96 = $rt.recover(() => {
  return $rt.int.add(a, b, $ob14);
});
      $m96$match: {
        if ($m96.tag === "Ok") {
          const value = $m96.value;
          return { tag: "Some", value: { tag: "IntV", v: value } };
          break $m96$match;
        }
        if ($m96.tag === "Err") {
          return { tag: "None" };
          break $m96$match;
        }
        $rt.unreachable();
      }
    }
    if (op === "-") {
      const $m100 = $rt.recover(() => {
  return $rt.int.sub(a, b, $ob15);
});
      $m100$match: {
        if ($m100.tag === "Ok") {
          const value = $m100.value;
          return { tag: "Some", value: { tag: "IntV", v: value } };
          break $m100$match;
        }
        if ($m100.tag === "Err") {
          return { tag: "None" };
          break $m100$match;
        }
        $rt.unreachable();
      }
    }
    if (op === "*") {
      const $m104 = $rt.recover(() => {
  return $rt.int.mul(a, b, $ob16);
});
      $m104$match: {
        if ($m104.tag === "Ok") {
          const value = $m104.value;
          return { tag: "Some", value: { tag: "IntV", v: value } };
          break $m104$match;
        }
        if ($m104.tag === "Err") {
          return { tag: "None" };
          break $m104$match;
        }
        $rt.unreachable();
      }
    }
    return { tag: "None" };
  }
  const a = float_of({ x: l });
  const b = float_of({ x: r });
  if (op === "<") {
    return { tag: "Some", value: { tag: "BoolV", v: a < b } };
  }
  if (op === "<=") {
    return { tag: "Some", value: { tag: "BoolV", v: a <= b } };
  }
  if (op === ">") {
    return { tag: "Some", value: { tag: "BoolV", v: a > b } };
  }
  if (op === ">=") {
    return { tag: "Some", value: { tag: "BoolV", v: a >= b } };
  }
  if (l.tag === "FloatV") {
    if (op === "+") {
      return { tag: "Some", value: { tag: "FloatV", v: a + b } };
    }
    if (op === "-") {
      return { tag: "Some", value: { tag: "FloatV", v: a - b } };
    }
    if (op === "*") {
      return { tag: "Some", value: { tag: "FloatV", v: a * b } };
    }
  }
  return { tag: "None" };
}

export function requires_verdict({ ev, ctx, o, src }) {
  const call_e = $std_map.find({ d: ctx.expr_nodes, key: o.at });
  const clause = $std_map.find({ d: ctx.contract_nodes, key: src });
  if (call_e.tag === "None" || clause.tag === "None") {
    return [{ tag: "None" }, ev, ctx];
  }
  const $m125 = expr_or({ o: call_e });
  $m125$match: {
    if ($m125.tag === "Call") {
      const callee = $m125.callee;
      const args = $m125.args;
      const fn_id = callee_def({ ctx: ctx, k: $defs.node_key({ file: o.at_file, tag: $defs.tag_expr, span: $parser.span_of_expr({ e: callee }) }) });
      if (fn_id < 0) {
        return [{ tag: "None" }, ev, ctx];
      }
      const $m127 = $std_map.find({ d: ctx.signatures, key: fn_id });
      $m127$match: {
        if ($m127.tag === "None") {
          return [{ tag: "None" }, ev, ctx];
          break $m127$match;
        }
        if ($m127.tag === "Some") {
          const value = $m127.value;
          let env = $std_map.dict({  });
          let i = 0;
          for (const p of value.params) {
            if (i >= $std_list.len({ xs: value.param_defs })) {
              return [{ tag: "None" }, ev, ctx];
            }
            const pd = $std_list.get({ xs: value.param_defs, i: i });
            const a = find_arg({ args: args, name: p.name });
            if (a.tag === "None") {
              return [{ tag: "None" }, ev, ctx];
            }
            const [$r131, ev$22, ctx$22] = eval_const({ ev: ev, ctx: ctx, e: arg_or({ o: a }).value, env: $std_map.dict({  }), file: o.at_file });
            ev = ev$22;
            ctx = ctx$22;
            const av = $r131;
            if (av.tag === "None") {
              return [{ tag: "None" }, ev, ctx];
            }
            const [, env$23] = $std_map.set({ d: env, key: pd, value: value_or_unit({ o: av }) });
            env = env$23;
            i = $rt.int.add(i, 1, $ob17);
          }
          const c = contract_or({ o: clause });
          const [$r133, ev$24, ctx$24] = eval_const({ ev: ev, ctx: ctx, e: c.expr, env: env, file: $lower.pred_file({ k: src }) });
          ev = ev$24;
          ctx = ctx$24;
          return [bool_of({ o: $r133 }), ev, ctx];
          break $m127$match;
        }
        $rt.unreachable();
      }
      break $m125$match;
    }
    if (true) {
      return [{ tag: "None" }, ev, ctx];
      break $m125$match;
    }
    $rt.unreachable();
  }
}

export function contract_or({ o }) {
  const $m135 = o;
  $m135$match: {
    if ($m135.tag === "Some") {
      const value = $m135.value;
      return value;
      break $m135$match;
    }
    if ($m135.tag === "None") {
      return { clause: "", is_proved: false, expr: { tag: "Hole", span: { start: 0, end: 0 } }, span: { start: 0, end: 0 } };
      break $m135$match;
    }
    $rt.unreachable();
  }
}

export function arg_or({ o }) {
  const $m140 = o;
  $m140$match: {
    if ($m140.tag === "Some") {
      const value = $m140.value;
      return value;
      break $m140$match;
    }
    if ($m140.tag === "None") {
      return { name: { text: "", span: { start: 0, end: 0 } }, is_inout: false, value: { tag: "Hole", span: { start: 0, end: 0 } }, span: { start: 0, end: 0 } };
      break $m140$match;
    }
    $rt.unreachable();
  }
}

export function find_arg({ args, name }) {
  for (const a of args) {
    if (a.name.text === name) {
      return { tag: "Some", value: a };
    }
  }
  return { tag: "None" };
}

