// Generated by onus from module diagtext. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $std_list from "./std/list.js";
import * as $loc from "./loc.js";
import * as $codes from "./codes.js";
import * as $std_text from "./std/text.js";
import * as $context from "./context.js";
export function to_text({ ctx, tab, d }) {
  let lines = $std_list.builder({  });
  const [, lines$1] = $std_list.push({ b: lines, x: $loc.location_text({ ctx: ctx, tables: tab, file: d.file, span: d.span }) + ": " + d.code + " " + $codes.title({ code: d.code }) });
  lines = lines$1;
  const $m1 = d.def_name;
  $m1$match: {
    if ($m1.tag === "Some") {
      const value = $m1.value;
      const [, lines$2] = $std_list.push({ b: lines, x: "  in " + value });
      lines = lines$2;
      break $m1$match;
    }
    if ($m1.tag === "None") {
      skip({  });
      break $m1$match;
    }
    $rt.unreachable();
  }
  for (const c of d.context) {
    const [, lines$3] = $std_list.push({ b: lines, x: "  " + c });
    lines = lines$3;
  }
  const $m2 = d.obligation;
  $m2$match: {
    if ($m2.tag === "Some") {
      const value = $m2.value;
      const [, lines$4] = $std_list.push({ b: lines, x: "  obligation " + value.kind + ": " + value.text + " [" + value.status + "]" });
      lines = lines$4;
      break $m2$match;
    }
    if ($m2.tag === "None") {
      skip({  });
      break $m2$match;
    }
    $rt.unreachable();
  }
  const file_len = file_length({ ctx: ctx, file: d.file });
  for (const r of d.repairs) {
    if (r.span.start === 0 && r.span.end === file_len) {
      const [, lines$5] = $std_list.push({ b: lines, x: "  repair: replace the file with its canonical form (onus fmt)" });
      lines = lines$5;
    } else {
      const [, lines$6] = $std_list.push({ b: lines, x: "  repair (" + r.confidence + "): replace with `" + r.with_text + "`" });
      lines = lines$6;
    }
  }
  return $std_text.join({ parts: $std_list.finish({ b: lines }), sep: "\n" });
}

export function file_length({ ctx, file }) {
  if (file >= 0 && file < $context.file_count({ ctx: ctx })) {
    return $std_list.len({ xs: $context.file_at({ ctx: ctx, id: file }).cps });
  }
  return 0;
}

export function skip($args) {
  return undefined;
}

