// Generated by onus from module diagjson. Do not edit.
import * as $rt from "./onus-runtime/index.js";
import * as $std_list from "./std/list.js";
import * as $std_int from "./std/int.js";
import * as $json from "./json.js";
import * as $loc from "./loc.js";
import * as $codes from "./codes.js";
import * as $std_map from "./std/map.js";
import * as $std_hash from "./std/hash.js";
export function skip($args) {
  return undefined;
}

export function counterexample_json({ entries }) {
  let fields = $std_list.builder({  });
  for (const e of entries) {
    if (e.is_number && $std_int.parse({ t: e.value }).tag === "Some") {
      const [, fields$1] = $std_list.push({ b: fields, x: $json.field({ key: e.name, value: { tag: "JNumber", text: e.value } }) });
      fields = fields$1;
    } else {
      const [, fields$2] = $std_list.push({ b: fields, x: $json.field({ key: e.name, value: $json.text({ t: e.value }) }) });
      fields = fields$2;
    }
  }
  return { tag: "JObject", fields: $std_list.finish({ b: fields }) };
}

export function to_json({ ctx, tab, d }) {
  let repairs = $std_list.builder({  });
  for (const r of d.repairs) {
    const [, repairs$3] = $std_list.push({ b: repairs, x: { tag: "JObject", fields: [$json.field({ key: "kind", value: $json.text({ t: "replace" }) }), $json.field({ key: "span", value: $loc.span_json({ tables: tab, file: d.file, span: r.span }) }), $json.field({ key: "with", value: $json.text({ t: r.with_text }) }), $json.field({ key: "confidence", value: $json.text({ t: r.confidence }) })] } });
    repairs = repairs$3;
  }
  let fields = [$json.field({ key: "code", value: $json.text({ t: d.code }) }), $json.field({ key: "title", value: $json.text({ t: $codes.title({ code: d.code }) }) }), $json.field({ key: "location", value: { tag: "JObject", fields: [$json.field({ key: "file", value: $json.text({ t: $loc.path_of({ ctx: ctx, file: d.file }) }) }), $json.field({ key: "def", value: $json.text_or_null({ o: d.def_name }) }), $json.field({ key: "span", value: $loc.span_json({ tables: tab, file: d.file, span: d.span }) })] } }), $json.field({ key: "context", value: $json.texts({ ts: d.context }) }), $json.field({ key: "repairs", value: { tag: "JArray", items: $std_list.finish({ b: repairs }) } })];
  const $m6 = d.obligation;
  $m6$match: {
    if ($m6.tag === "Some") {
      const value = $m6.value;
      let counterexample = { tag: "JNull" };
      if (value.has_counterexample) {
        counterexample = counterexample_json({ entries: value.counterexample });
      }
      fields = $std_list.append({ xs: fields, x: $json.field({ key: "obligation", value: { tag: "JObject", fields: [$json.field({ key: "kind", value: $json.text({ t: value.kind }) }), $json.field({ key: "text", value: $json.text({ t: value.text }) }), $json.field({ key: "status", value: $json.text({ t: value.status }) }), $json.field({ key: "counterexample", value: counterexample })] } }) });
      break $m6$match;
    }
    if ($m6.tag === "None") {
      skip({  });
      break $m6$match;
    }
    $rt.unreachable();
  }
  const $m9 = $std_map.find({ d: ctx.canonical, key: d.file });
  $m9$match: {
    if ($m9.tag === "Some") {
      const value = $m9.value;
      fields = $std_list.append({ xs: fields, x: $json.field({ key: "canonical_hash", value: $json.text({ t: "b3:" + $std_hash.blake3_hex({ t: value }) }) }) });
      break $m9$match;
    }
    if ($m9.tag === "None") {
      skip({  });
      break $m9$match;
    }
    $rt.unreachable();
  }
  return { tag: "JObject", fields: fields };
}

