// Generated by onus from module effects. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $std_map from "./std/map.js";
import * as $effectset from "./effectset.js";
import * as $std_list from "./std/list.js";
import * as $context from "./context.js";
import * as $report from "./report.js";
import * as $defs from "./defs.js";
import * as $std_text from "./std/text.js";
import * as $parser from "./parser.js";
import * as $types from "./types.js";
import * as $std_int from "./std/int.js";
import * as $printer from "./printer.js";

const $ob1 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:160:20", def: "or_neg" };
const $ob2 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:169:20", def: "res_def" };
const $ob3 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:175:19", def: "res_def" };
const $ob4 = { kind: "overflow", text: "j + 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1223:13", def: "measure_key" };
const $ob5 = { kind: "overflow", text: "i - 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1228:48", def: "measure_key" };
const $ob6 = { kind: "overflow", text: "k + 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1235:13", def: "measure_key" };
const $ob7 = { kind: "overflow", text: "idx + 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1252:17", def: "measure_key" };
const $ob8 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1263:11", def: "measure_key" };
const $ob9 = { kind: "overflow", text: "tj.counter + 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1302:27", def: "strong" };
const $ob10 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1312:20", def: "strong" };
const $ob11 = { kind: "overflow", text: "guard - 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1332:15", def: "strong" };
const $ob12 = { kind: "overflow", text: "cycle + 1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1382:15", def: "recursion" };
const $ob13 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/effects.onus:1390:28", def: "recursion" };
export const alloc_e = { tag: "PrimEffect", name: "alloc" };

export const mutate_e = { tag: "PrimEffect", name: "mutate" };

export const diverge_e = { tag: "PrimEffect", name: "diverge" };

export const panic_e = { tag: "PrimEffect", name: "panic" };

export const max_graph = 1000000;

export function new_sites($args) {
  return { table: $std_map.dict({  }) };
}

export function add_site({ sites, e, span, why }) {
  const k = $effectset.effect_key({ e: e });
  if (!$std_map.contains({ d: sites.table, key: k })) {
    let t = sites.table;
    const [, t$1] = $std_map.set({ d: t, key: k, value: { effect: e, span: span, why: why } });
    t = t$1;
  }
  return undefined;
}

export function add_all({ sites, set, span, why }) {
  for (const e of $effectset.values({ s: set })) {
    add_site({ sites: sites, e: e, span: span, why: why });
  }
  return undefined;
}

export function set_of({ sites }) {
  let out = $std_list.builder({  });
  for (const s of $std_map.values({ d: sites.table })) {
    const [, out$2] = $std_list.push({ b: out, x: s.effect });
    out = out$2;
  }
  return $effectset.of_list({ effects: $std_list.finish({ b: out }) });
}

export function fresh_frame($args) {
  return { inout_params: $std_map.dict({  }), sites: new_sites({  }) };
}

export function skip($args) {
  return undefined;
}

export function rep({ ec, ctx, code, at, detail }) {
  const [, ctx$3] = $context.report({ ctx: ctx, d: $report.diagnostic({ code: code, file: ec.current_file, span: at, def_name: ec.current_def, detail: detail }) });
  ctx = ctx$3;
  return [undefined, ctx];
  return [undefined, ctx];
}

export function key({ ec, tag, span }) {
  return $defs.node_key({ file: ec.current_file, tag: tag, span: span });
}

export function show({ ctx, s }) {
  let names = $std_list.builder({  });
  for (const e of $effectset.values({ s: s })) {
    const $m4 = e;
    $m4$match: {
      if ($m4.tag === "PrimEffect") {
        const name = $m4.name;
        const [, names$4] = $std_list.push({ b: names, x: name });
        names = names$4;
        break $m4$match;
      }
      if ($m4.tag === "ResourceEffect") {
        const mod = $m4.mod;
        const name = $m4.name;
        const [, names$5] = $std_list.push({ b: names, x: name });
        names = names$5;
        break $m4$match;
      }
      if ($m4.tag === "ParamEffect") {
        const def = $m4.def;
        const [, names$6] = $std_list.push({ b: names, x: $context.get_def({ ctx: ctx, id: def }).name });
        names = names$6;
        break $m4$match;
      }
      $rt.unreachable();
    }
  }
  return $std_text.join({ parts: sort_texts({ xs: $std_list.finish({ b: names }) }), sep: ", " });
}

export function sort_texts({ xs }) {
  let out = [];
  for (const x of xs) {
    let inserted = false;
    let b = $std_list.builder({  });
    for (const y of out) {
      if (!inserted && $std_text.compare({ a: x, b: y }) < 0) {
        const [, b$7] = $std_list.push({ b: b, x: x });
        b = b$7;
        inserted = true;
      }
      const [, b$8] = $std_list.push({ b: b, x: y });
      b = b$8;
    }
    if (!inserted) {
      const [, b$9] = $std_list.push({ b: b, x: x });
      b = b$9;
    }
    out = $std_list.finish({ b: b });
  }
  return out;
}

export function or_neg({ o }) {
  const $m5 = o;
  $m5$match: {
    if ($m5.tag === "Some") {
      const value = $m5.value;
      return value;
      break $m5$match;
    }
    if ($m5.tag === "None") {
      return $rt.int.neg(1, $ob1);
      break $m5$match;
    }
    $rt.unreachable();
  }
}

export function def_of_key({ ctx, k }) {
  return or_neg({ o: $std_map.find({ d: ctx.def_of, key: k }) });
}

export function res_def({ ctx, k }) {
  const $m6 = $std_map.find({ d: ctx.refs, key: k });
  $m6$match: {
    if ($m6.tag === "None") {
      return $rt.int.neg(1, $ob2);
      break $m6$match;
    }
    if ($m6.tag === "Some") {
      const value = $m6.value;
      const $m7 = value;
      $m7$match: {
        if ($m7.tag === "DefRes") {
          const def = $m7.def;
          return def;
          break $m7$match;
        }
        if ($m7.tag === "CompanionRes") {
          const owner = $m7.owner;
          const fn_def = $m7.fn_def;
          return fn_def;
          break $m7$match;
        }
        if ($m7.tag === "IfaceFnRes") {
          const iface = $m7.iface;
          const fn_def = $m7.fn_def;
          return fn_def;
          break $m7$match;
        }
        if (true) {
          return $rt.int.neg(1, $ob3);
          break $m7$match;
        }
        $rt.unreachable();
      }
      break $m6$match;
    }
    $rt.unreachable();
  }
}

export function is_plain_def_res({ ctx, k }) {
  const $m8 = $std_map.find({ d: ctx.refs, key: k });
  $m8$match: {
    if ($m8.tag === "None") {
      return false;
      break $m8$match;
    }
    if ($m8.tag === "Some") {
      const value = $m8.value;
      return value.tag === "DefRes";
      break $m8$match;
    }
    $rt.unreachable();
  }
}

export function sig_of({ ctx, def }) {
  return $std_map.find({ d: ctx.signatures, key: def });
}

export function empty_sig({ def }) {
  return { def: def, tparams: [], params: [], param_defs: [], ret: { tag: "ErrorT" }, effects: $effectset.empty({  }), contracts: [], is_const_fn: false, is_intrinsic: false };
}

export function sig_or({ ctx, def }) {
  const $m11 = sig_of({ ctx: ctx, def: def });
  $m11$match: {
    if ($m11.tag === "Some") {
      const value = $m11.value;
      return value;
      break $m11$match;
    }
    if ($m11.tag === "None") {
      return empty_sig({ def: def });
      break $m11$match;
    }
    $rt.unreachable();
  }
}

export function expr_type({ ec, ctx, e }) {
  const $m12 = $std_map.find({ d: ctx.expr_types, key: key({ ec: ec, tag: $defs.tag_expr, span: $parser.span_of_expr({ e: e }) }) });
  $m12$match: {
    if ($m12.tag === "Some") {
      const value = $m12.value;
      return value;
      break $m12$match;
    }
    if ($m12.tag === "None") {
      return { tag: "ErrorT" };
      break $m12$match;
    }
    $rt.unreachable();
  }
}

export function containment({ ec, ctx, actual, declared, sites, what }) {
  for (const e of $effectset.minus({ a: actual, b: declared })) {
    const $m14 = $std_map.find({ d: sites.table, key: $effectset.effect_key({ e: e }) });
    $m14$match: {
      if ($m14.tag === "None") {
        skip({  });
        break $m14$match;
      }
      if ($m14.tag === "Some") {
        const value = $m14.value;
        const [, ctx$10] = rep({ ec: ec, ctx: ctx, code: "E0201", at: value.span, detail: value.why + " has effect `" + show({ ctx: ctx, s: $effectset.of_list({ effects: [e] }) }) + "`, which " + what + " does not declare" });
        ctx = ctx$10;
        break $m14$match;
      }
      $rt.unreachable();
    }
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function check_where({ ec, ctx, pred }) {
  const frame = fresh_frame({  });
  const [, ctx$11] = ef_expr({ ec: ec, ctx: ctx, e: pred, frame: frame, owner: { tag: "None" } });
  ctx = ctx$11;
  const [, ctx$12] = containment({ ec: ec, ctx: ctx, actual: set_of({ sites: frame.sites }), declared: $effectset.of_list({ effects: [alloc_e] }), sites: frame.sites, what: "a `where` clause" });
  ctx = ctx$12;
  return [undefined, ctx];
  return [undefined, ctx];
}

export function wheres_in_type({ ec, ctx, t }) {
  const $m16 = t;
  $m16$match: {
    if ($m16.tag === "FnType") {
      const params = $m16.params;
      const ret = $m16.ret;
      const [, ctx$13] = wheres_in_params({ ec: ec, ctx: ctx, ps: params });
      ctx = ctx$13;
      const [, ctx$14] = wheres_in_type({ ec: ec, ctx: ctx, t: ret });
      ctx = ctx$14;
      break $m16$match;
    }
    if ($m16.tag === "NamedType") {
      const args = $m16.args;
      const where_ = $m16.where_;
      for (const a of args) {
        const $m17 = a;
        $m17$match: {
          if ($m17.tag === "TypeArgType") {
            const ty = $m17.ty;
            const [, ctx$15] = wheres_in_type({ ec: ec, ctx: ctx, t: ty });
            ctx = ctx$15;
            break $m17$match;
          }
          if ($m17.tag === "TypeArgConst") {
            const expr = $m17.expr;
            const [, ctx$16] = wheres_in_expr({ ec: ec, ctx: ctx, e: expr });
            ctx = ctx$16;
            break $m17$match;
          }
          $rt.unreachable();
        }
      }
      const $m18 = where_;
      $m18$match: {
        if ($m18.tag === "Some") {
          const value = $m18.value;
          const [, ctx$17] = check_where({ ec: ec, ctx: ctx, pred: value });
          ctx = ctx$17;
          const [, ctx$18] = wheres_in_expr({ ec: ec, ctx: ctx, e: value });
          ctx = ctx$18;
          break $m18$match;
        }
        if ($m18.tag === "None") {
          skip({  });
          break $m18$match;
        }
        $rt.unreachable();
      }
      break $m16$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function wheres_in_params({ ec, ctx, ps }) {
  for (const p of ps) {
    const [, ctx$19] = wheres_in_type({ ec: ec, ctx: ctx, t: p.ty });
    ctx = ctx$19;
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function wheres_in_expr({ ec, ctx, e }) {
  const $m19 = e;
  $m19$match: {
    if ($m19.tag === "Ctor") {
      const args = $m19.args;
      const fields = $m19.fields;
      const $m20 = args;
      $m20$match: {
        if ($m20.tag === "Some") {
          const value = $m20.value;
          for (const a of value) {
            const [, ctx$20] = wheres_in_expr({ ec: ec, ctx: ctx, e: a.value });
            ctx = ctx$20;
          }
          break $m20$match;
        }
        if ($m20.tag === "None") {
          skip({  });
          break $m20$match;
        }
        $rt.unreachable();
      }
      const $m21 = fields;
      $m21$match: {
        if ($m21.tag === "Some") {
          const value = $m21.value;
          for (const f of value) {
            const [, ctx$21] = wheres_in_expr({ ec: ec, ctx: ctx, e: f.value });
            ctx = ctx$21;
          }
          break $m21$match;
        }
        if ($m21.tag === "None") {
          skip({  });
          break $m21$match;
        }
        $rt.unreachable();
      }
      break $m19$match;
    }
    if ($m19.tag === "RecordUpdate") {
      const base = $m19.base;
      const fields = $m19.fields;
      const [, ctx$22] = wheres_in_expr({ ec: ec, ctx: ctx, e: base });
      ctx = ctx$22;
      for (const f of fields) {
        const [, ctx$23] = wheres_in_expr({ ec: ec, ctx: ctx, e: f.value });
        ctx = ctx$23;
      }
      break $m19$match;
    }
    if ($m19.tag === "ListLit") {
      const elems = $m19.elems;
      for (const x of elems) {
        const [, ctx$24] = wheres_in_expr({ ec: ec, ctx: ctx, e: x });
        ctx = ctx$24;
      }
      break $m19$match;
    }
    if ($m19.tag === "Try") {
      const expr = $m19.expr;
      const else_ = $m19.else_;
      const [, ctx$25] = wheres_in_expr({ ec: ec, ctx: ctx, e: expr });
      ctx = ctx$25;
      const $m22 = else_;
      $m22$match: {
        if ($m22.tag === "Some") {
          const value = $m22.value;
          const [, ctx$26] = wheres_in_expr({ ec: ec, ctx: ctx, e: value.expr });
          ctx = ctx$26;
          break $m22$match;
        }
        if ($m22.tag === "None") {
          skip({  });
          break $m22$match;
        }
        $rt.unreachable();
      }
      break $m19$match;
    }
    if ($m19.tag === "Quantifier") {
      const ty = $m19.ty;
      const domain = $m19.domain;
      const where_ = $m19.where_;
      const body = $m19.body;
      const [, ctx$27] = wheres_in_type({ ec: ec, ctx: ctx, t: ty });
      ctx = ctx$27;
      const $m23 = domain;
      $m23$match: {
        if ($m23.tag === "Some") {
          const value = $m23.value;
          const $m24 = value;
          $m24$match: {
            if ($m24.tag === "RangeDomain") {
              const lo = $m24.lo;
              const hi = $m24.hi;
              const [, ctx$28] = wheres_in_expr({ ec: ec, ctx: ctx, e: lo });
              ctx = ctx$28;
              const [, ctx$29] = wheres_in_expr({ ec: ec, ctx: ctx, e: hi });
              ctx = ctx$29;
              break $m24$match;
            }
            if ($m24.tag === "InDomain") {
              const expr = $m24.expr;
              const [, ctx$30] = wheres_in_expr({ ec: ec, ctx: ctx, e: expr });
              ctx = ctx$30;
              break $m24$match;
            }
            $rt.unreachable();
          }
          break $m23$match;
        }
        if ($m23.tag === "None") {
          skip({  });
          break $m23$match;
        }
        $rt.unreachable();
      }
      const $m25 = where_;
      $m25$match: {
        if ($m25.tag === "Some") {
          const value = $m25.value;
          const [, ctx$31] = wheres_in_expr({ ec: ec, ctx: ctx, e: value });
          ctx = ctx$31;
          break $m25$match;
        }
        if ($m25.tag === "None") {
          skip({  });
          break $m25$match;
        }
        $rt.unreachable();
      }
      const [, ctx$32] = wheres_in_expr({ ec: ec, ctx: ctx, e: body });
      ctx = ctx$32;
      break $m19$match;
    }
    if ($m19.tag === "Closure") {
      const params = $m19.params;
      const ret = $m19.ret;
      const [, ctx$33] = wheres_in_params({ ec: ec, ctx: ctx, ps: params });
      ctx = ctx$33;
      const [, ctx$34] = wheres_in_type({ ec: ec, ctx: ctx, t: ret });
      ctx = ctx$34;
      break $m19$match;
    }
    if ($m19.tag === "Fake") {
      const fields = $m19.fields;
      for (const f of fields) {
        const [, ctx$35] = wheres_in_expr({ ec: ec, ctx: ctx, e: f.value });
        ctx = ctx$35;
      }
      break $m19$match;
    }
    if ($m19.tag === "FieldAccess") {
      const object = $m19.object;
      const [, ctx$36] = wheres_in_expr({ ec: ec, ctx: ctx, e: object });
      ctx = ctx$36;
      break $m19$match;
    }
    if ($m19.tag === "Call") {
      const callee = $m19.callee;
      const targs = $m19.targs;
      const args = $m19.args;
      const [, ctx$37] = wheres_in_expr({ ec: ec, ctx: ctx, e: callee });
      ctx = ctx$37;
      const $m26 = targs;
      $m26$match: {
        if ($m26.tag === "Some") {
          const value = $m26.value;
          for (const a of value) {
            const $m27 = a;
            $m27$match: {
              if ($m27.tag === "TypeArgType") {
                const ty = $m27.ty;
                const [, ctx$38] = wheres_in_type({ ec: ec, ctx: ctx, t: ty });
                ctx = ctx$38;
                break $m27$match;
              }
              if ($m27.tag === "TypeArgConst") {
                const expr = $m27.expr;
                const [, ctx$39] = wheres_in_expr({ ec: ec, ctx: ctx, e: expr });
                ctx = ctx$39;
                break $m27$match;
              }
              $rt.unreachable();
            }
          }
          break $m26$match;
        }
        if ($m26.tag === "None") {
          skip({  });
          break $m26$match;
        }
        $rt.unreachable();
      }
      for (const a of args) {
        const [, ctx$40] = wheres_in_expr({ ec: ec, ctx: ctx, e: a.value });
        ctx = ctx$40;
      }
      break $m19$match;
    }
    if ($m19.tag === "Unary") {
      const operand = $m19.operand;
      const [, ctx$41] = wheres_in_expr({ ec: ec, ctx: ctx, e: operand });
      ctx = ctx$41;
      break $m19$match;
    }
    if ($m19.tag === "Binary") {
      const left = $m19.left;
      const right = $m19.right;
      const [, ctx$42] = wheres_in_expr({ ec: ec, ctx: ctx, e: left });
      ctx = ctx$42;
      const [, ctx$43] = wheres_in_expr({ ec: ec, ctx: ctx, e: right });
      ctx = ctx$43;
      break $m19$match;
    }
    if ($m19.tag === "And") {
      const operands = $m19.operands;
      for (const o of operands) {
        const [, ctx$44] = wheres_in_expr({ ec: ec, ctx: ctx, e: o });
        ctx = ctx$44;
      }
      break $m19$match;
    }
    if ($m19.tag === "Or") {
      const operands = $m19.operands;
      for (const o of operands) {
        const [, ctx$45] = wheres_in_expr({ ec: ec, ctx: ctx, e: o });
        ctx = ctx$45;
      }
      break $m19$match;
    }
    if ($m19.tag === "Is") {
      const expr = $m19.expr;
      const pattern = $m19.pattern;
      const [, ctx$46] = wheres_in_expr({ ec: ec, ctx: ctx, e: expr });
      ctx = ctx$46;
      const [, ctx$47] = wheres_in_pattern({ ec: ec, ctx: ctx, p: pattern });
      ctx = ctx$47;
      break $m19$match;
    }
    if (true) {
      skip({  });
      break $m19$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function wheres_in_pattern({ ec, ctx, p }) {
  const $m28 = p;
  $m28$match: {
    if ($m28.tag === "LitPat") {
      const literal = $m28.literal;
      const [, ctx$48] = wheres_in_expr({ ec: ec, ctx: ctx, e: literal });
      ctx = ctx$48;
      break $m28$match;
    }
    if (true) {
      skip({  });
      break $m28$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function wheres_in_tparams({ ec, ctx, ps }) {
  for (const p of ps) {
    const $m29 = p;
    $m29$match: {
      if ($m29.tag === "ConstParam") {
        const ty = $m29.ty;
        const [, ctx$49] = wheres_in_type({ ec: ec, ctx: ctx, t: ty });
        ctx = ctx$49;
        break $m29$match;
      }
      if (true) {
        skip({  });
        break $m29$match;
      }
      $rt.unreachable();
    }
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function wheres_in_fn({ ec, ctx, f }) {
  const [, ctx$50] = wheres_in_tparams({ ec: ec, ctx: ctx, ps: f.tparams });
  ctx = ctx$50;
  const [, ctx$51] = wheres_in_params({ ec: ec, ctx: ctx, ps: f.params });
  ctx = ctx$51;
  const [, ctx$52] = wheres_in_type({ ec: ec, ctx: ctx, t: f.ret });
  ctx = ctx$52;
  for (const c of f.contracts) {
    const [, ctx$53] = wheres_in_expr({ ec: ec, ctx: ctx, e: c.expr });
    ctx = ctx$53;
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function pure_contracts({ ec, ctx, sig }) {
  for (const c of sig.contracts) {
    const frame = fresh_frame({  });
    const [, ctx$54] = ef_expr({ ec: ec, ctx: ctx, e: c.expr, frame: frame, owner: { tag: "None" } });
    ctx = ctx$54;
    const [, ctx$55] = containment({ ec: ec, ctx: ctx, actual: set_of({ sites: frame.sites }), declared: $effectset.of_list({ effects: [alloc_e] }), sites: frame.sites, what: "a `" + c.clause + "` clause" });
    ctx = ctx$55;
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function item_name({ item }) {
  const $m31 = item;
  $m31$match: {
    if ($m31.tag === "FnItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "TypeAliasItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "IntrinsicTypeItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "ConstItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "RecordItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "UnionItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "InterfaceItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "ImplItem") {
      const decl = $m31.decl;
      return decl.iface.text;
      break $m31$match;
    }
    if ($m31.tag === "ClaimItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "CapabilityItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "PathItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "PolicyItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "ExampleItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    if ($m31.tag === "PropertyItem") {
      const decl = $m31.decl;
      return decl.name.text;
      break $m31$match;
    }
    $rt.unreachable();
  }
}

export function iface_item_span({ member }) {
  const $m32 = member;
  $m32$match: {
    if ($m32.tag === "IfaceFnItem") {
      const decl = $m32.decl;
      return decl.span;
      break $m32$match;
    }
    if ($m32.tag === "LawItem") {
      const decl = $m32.decl;
      return decl.span;
      break $m32$match;
    }
    $rt.unreachable();
  }
}

export function or_error({ o }) {
  const $m33 = o;
  $m33$match: {
    if ($m33.tag === "Some") {
      const value = $m33.value;
      return value;
      break $m33$match;
    }
    if ($m33.tag === "None") {
      return { tag: "ErrorT" };
      break $m33$match;
    }
    $rt.unreachable();
  }
}

export function param_or({ o }) {
  const $m35 = o;
  $m35$match: {
    if ($m35.tag === "Some") {
      const value = $m35.value;
      return value;
      break $m35$match;
    }
    if ($m35.tag === "None") {
      return { name: "", is_inout: false, ty: { tag: "ErrorT" } };
      break $m35$match;
    }
    $rt.unreachable();
  }
}

export function find_iface_fn({ ctx, iface, name }) {
  const $hi38 = $context.def_count({ ctx: ctx });
  for (let i = 0; i < $hi38; i++) {
    const d = $context.get_def({ ctx: ctx, id: i });
    if ($rt.eq(d.kind, { tag: "IfaceFn" }) && d.name === name && $rt.eq(d.parent, { tag: "Some", value: iface })) {
      return { tag: "Some", value: d };
    }
  }
  return { tag: "None" };
}

export function ef_item({ ec, ctx, item }) {
  const $m43 = item;
  $m43$match: {
    if ($m43.tag === "FnItem") {
      const decl = $m43.decl;
      const [, ec$56, ctx$56] = ef_fn({ ec: ec, ctx: ctx, f: decl, iface_fn: { tag: "None" } });
      ec = ec$56;
      ctx = ctx$56;
      break $m43$match;
    }
    if ($m43.tag === "ImplItem") {
      const decl = $m43.decl;
      const iface = res_def({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_item, span: decl.span }) });
      for (const f of decl.fns) {
        ec = { ...ec, current_def: { tag: "Some", value: decl.iface.text + "." + f.name.text } };
        let want = { tag: "None" };
        if (iface >= 0) {
          want = find_iface_fn({ ctx: ctx, iface: iface, name: f.name.text });
        }
        const [, ec$57, ctx$57] = ef_fn({ ec: ec, ctx: ctx, f: f, iface_fn: want });
        ec = ec$57;
        ctx = ctx$57;
      }
      break $m43$match;
    }
    if ($m43.tag === "InterfaceItem") {
      const decl = $m43.decl;
      for (const member of decl.items) {
        if (member.tag === "IfaceFnItem") {
          const [, ctx$58] = pure_contracts({ ec: ec, ctx: ctx, sig: sig_or({ ctx: ctx, def: def_of_key({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_sig, span: iface_item_span({ member: member }) }) }) }) });
          ctx = ctx$58;
        }
      }
      break $m43$match;
    }
    if ($m43.tag === "TypeAliasItem") {
      const decl = $m43.decl;
      const [, ctx$59] = wheres_in_type({ ec: ec, ctx: ctx, t: decl.ty });
      ctx = ctx$59;
      break $m43$match;
    }
    if ($m43.tag === "RecordItem") {
      const decl = $m43.decl;
      const [, ctx$60] = wheres_in_tparams({ ec: ec, ctx: ctx, ps: decl.tparams });
      ctx = ctx$60;
      for (const f of decl.fields) {
        const [, ctx$61] = wheres_in_type({ ec: ec, ctx: ctx, t: f.ty });
        ctx = ctx$61;
      }
      break $m43$match;
    }
    if ($m43.tag === "UnionItem") {
      const decl = $m43.decl;
      const [, ctx$62] = wheres_in_tparams({ ec: ec, ctx: ctx, ps: decl.tparams });
      ctx = ctx$62;
      for (const v of decl.variants) {
        for (const f of v.fields) {
          const [, ctx$63] = wheres_in_type({ ec: ec, ctx: ctx, t: f.ty });
          ctx = ctx$63;
        }
      }
      break $m43$match;
    }
    if (true) {
      skip({  });
      break $m43$match;
    }
    $rt.unreachable();
  }
  return [undefined, ec, ctx];
  return [undefined, ec, ctx];
}

export function ef_fn({ ec, ctx, f, iface_fn }) {
  const def = def_of_key({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_item, span: f.span }) });
  const sig = sig_or({ ctx: ctx, def: def });
  if (f.is_const && $effectset.size({ s: $effectset.without({ a: sig.effects, e: alloc_e }) }) > 0) {
    const [, ctx$64] = rep({ ec: ec, ctx: ctx, code: "E0201", at: f.name.span, detail: "a `const fn` may only allocate; `" + f.name.text + "` declares " + show({ ctx: ctx, s: $effectset.without({ a: sig.effects, e: alloc_e }) }) });
    ctx = ctx$64;
  }
  const $m48 = iface_fn;
  $m48$match: {
    if ($m48.tag === "Some") {
      const value = $m48.value;
      const extra = $effectset.minus({ a: sig.effects, b: sig_or({ ctx: ctx, def: value.id }).effects });
      if ($std_list.len({ xs: extra }) > 0) {
        const [, ctx$65] = rep({ ec: ec, ctx: ctx, code: "E0334", at: f.name.span, detail: "`" + f.name.text + "` declares " + show({ ctx: ctx, s: $effectset.of_list({ effects: extra }) }) + ", which the interface does not admit" });
        ctx = ctx$65;
      }
      break $m48$match;
    }
    if ($m48.tag === "None") {
      skip({  });
      break $m48$match;
    }
    $rt.unreachable();
  }
  const [, ctx$66] = pure_contracts({ ec: ec, ctx: ctx, sig: sig });
  ctx = ctx$66;
  const [, ctx$67] = wheres_in_fn({ ec: ec, ctx: ctx, f: f });
  ctx = ctx$67;
  const $m49 = f.body;
  $m49$match: {
    if ($m49.tag === "None") {
      skip({  });
      break $m49$match;
    }
    if ($m49.tag === "Some") {
      const value = $m49.value;
      const frame = fresh_frame({  });
      for (const pd of sig.param_defs) {
        if ($context.get_def({ ctx: ctx, id: pd }).is_inout) {
          let ps = frame.inout_params;
          const [, ps$68] = $std_map.set({ d: ps, key: pd, value: true });
          ps = ps$68;
        }
      }
      const [, ctx$69] = ef_block({ ec: ec, ctx: ctx, b: value, frame: frame, owner: { tag: "Some", value: def } });
      ctx = ctx$69;
      const inferred = set_of({ sites: frame.sites });
      let table = ctx.inferred;
      const [, table$70] = $std_map.set({ d: table, key: def, value: inferred });
      table = table$70;
      const [, ctx$71] = containment({ ec: ec, ctx: ctx, actual: inferred, declared: sig.effects, sites: frame.sites, what: "`" + f.name.text + "`" });
      ctx = ctx$71;
      break $m49$match;
    }
    $rt.unreachable();
  }
  return [undefined, ec, ctx];
  return [undefined, ec, ctx];
}

export function ef_block({ ec, ctx, b, frame, owner }) {
  for (const s of b.stmts) {
    const [, ctx$72] = ef_stmt({ ec: ec, ctx: ctx, s: s, frame: frame, owner: owner });
    ctx = ctx$72;
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function has_decreases({ clauses }) {
  for (const c of clauses) {
    if (c.clause === "decreases") {
      return true;
    }
  }
  return false;
}

export function ef_stmt({ ec, ctx, s, frame, owner }) {
  const $m51 = s;
  $m51$match: {
    if ($m51.tag === "Let") {
      const name = $m51.name;
      const value = $m51.value;
      const span = $m51.span;
      const [, ctx$73] = ef_expr({ ec: ec, ctx: ctx, e: value, frame: frame, owner: owner });
      ctx = ctx$73;
      const declared = $std_map.find({ d: ctx.decl_types, key: def_of_key({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_stmt, span: span }) }) });
      if (declared.tag === "Some") {
        const [, ctx$74] = flow({ ec: ec, ctx: ctx, value: value, into: or_error({ o: declared }), what: "`" + name.text + "`" });
        ctx = ctx$74;
      }
      break $m51$match;
    }
    if ($m51.tag === "Var") {
      const name = $m51.name;
      const value = $m51.value;
      const span = $m51.span;
      const [, ctx$75] = ef_expr({ ec: ec, ctx: ctx, e: value, frame: frame, owner: owner });
      ctx = ctx$75;
      const declared = $std_map.find({ d: ctx.decl_types, key: def_of_key({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_stmt, span: span }) }) });
      if (declared.tag === "Some") {
        const [, ctx$76] = flow({ ec: ec, ctx: ctx, value: value, into: or_error({ o: declared }), what: "`" + name.text + "`" });
        ctx = ctx$76;
      }
      break $m51$match;
    }
    if ($m51.tag === "Assign") {
      const name = $m51.name;
      const value = $m51.value;
      const span = $m51.span;
      const target = res_def({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_stmt, span: span }) });
      if (target >= 0 && $std_map.contains({ d: frame.inout_params, key: target })) {
        add_site({ sites: frame.sites, e: mutate_e, span: span, why: "assigning to inout parameter `" + name.text + "`" });
      }
      const [, ctx$77] = ef_expr({ ec: ec, ctx: ctx, e: value, frame: frame, owner: owner });
      ctx = ctx$77;
      break $m51$match;
    }
    if ($m51.tag === "Return") {
      const value = $m51.value;
      const [, ctx$78] = ef_expr({ ec: ec, ctx: ctx, e: value, frame: frame, owner: owner });
      ctx = ctx$78;
      break $m51$match;
    }
    if ($m51.tag === "If") {
      const cond = $m51.cond;
      const then_block = $m51.then_block;
      const else_block = $m51.else_block;
      const [, ctx$79] = ef_expr({ ec: ec, ctx: ctx, e: cond, frame: frame, owner: owner });
      ctx = ctx$79;
      const [, ctx$80] = ef_block({ ec: ec, ctx: ctx, b: then_block, frame: frame, owner: owner });
      ctx = ctx$80;
      const $m52 = else_block;
      $m52$match: {
        if ($m52.tag === "Some") {
          const value = $m52.value;
          const [, ctx$81] = ef_block({ ec: ec, ctx: ctx, b: value, frame: frame, owner: owner });
          ctx = ctx$81;
          break $m52$match;
        }
        if ($m52.tag === "None") {
          skip({  });
          break $m52$match;
        }
        $rt.unreachable();
      }
      break $m51$match;
    }
    if ($m51.tag === "Match") {
      const scrutinee = $m51.scrutinee;
      const arms = $m51.arms;
      const [, ctx$82] = ef_expr({ ec: ec, ctx: ctx, e: scrutinee, frame: frame, owner: owner });
      ctx = ctx$82;
      for (const a of arms) {
        const $m53 = a.guard;
        $m53$match: {
          if ($m53.tag === "Some") {
            const value = $m53.value;
            const [, ctx$83] = ef_expr({ ec: ec, ctx: ctx, e: value, frame: frame, owner: owner });
            ctx = ctx$83;
            break $m53$match;
          }
          if ($m53.tag === "None") {
            skip({  });
            break $m53$match;
          }
          $rt.unreachable();
        }
        const $m54 = a.body;
        $m54$match: {
          if ($m54.tag === "ArmBlock") {
            const block = $m54.block;
            const [, ctx$84] = ef_block({ ec: ec, ctx: ctx, b: block, frame: frame, owner: owner });
            ctx = ctx$84;
            break $m54$match;
          }
          if ($m54.tag === "ArmStmt") {
            const stmt = $m54.stmt;
            const [, ctx$85] = ef_stmt({ ec: ec, ctx: ctx, s: stmt, frame: frame, owner: owner });
            ctx = ctx$85;
            break $m54$match;
          }
          $rt.unreachable();
        }
      }
      break $m51$match;
    }
    if ($m51.tag === "Loop") {
      const cond = $m51.cond;
      const clauses = $m51.clauses;
      const body = $m51.body;
      const span = $m51.span;
      const [, ctx$86] = ef_expr({ ec: ec, ctx: ctx, e: cond, frame: frame, owner: owner });
      ctx = ctx$86;
      for (const c of clauses) {
        const [, ctx$87] = ef_expr({ ec: ec, ctx: ctx, e: c.expr, frame: frame, owner: owner });
        ctx = ctx$87;
      }
      if (!has_decreases({ clauses: clauses })) {
        add_site({ sites: frame.sites, e: diverge_e, span: span, why: "a `loop while` without `decreases`" });
      }
      const [, ctx$88] = ef_block({ ec: ec, ctx: ctx, b: body, frame: frame, owner: owner });
      ctx = ctx$88;
      break $m51$match;
    }
    if ($m51.tag === "For") {
      const domain = $m51.domain;
      const body = $m51.body;
      const $m55 = domain;
      $m55$match: {
        if ($m55.tag === "RangeDomain") {
          const lo = $m55.lo;
          const hi = $m55.hi;
          const [, ctx$89] = ef_expr({ ec: ec, ctx: ctx, e: lo, frame: frame, owner: owner });
          ctx = ctx$89;
          const [, ctx$90] = ef_expr({ ec: ec, ctx: ctx, e: hi, frame: frame, owner: owner });
          ctx = ctx$90;
          break $m55$match;
        }
        if ($m55.tag === "InDomain") {
          const expr = $m55.expr;
          const [, ctx$91] = ef_expr({ ec: ec, ctx: ctx, e: expr, frame: frame, owner: owner });
          ctx = ctx$91;
          break $m55$match;
        }
        $rt.unreachable();
      }
      const [, ctx$92] = ef_block({ ec: ec, ctx: ctx, b: body, frame: frame, owner: owner });
      ctx = ctx$92;
      break $m51$match;
    }
    if ($m51.tag === "Assume") {
      const verify_block = $m51.verify_block;
      const $m56 = verify_block;
      $m56$match: {
        if ($m56.tag === "Some") {
          const value = $m56.value;
          const [, ctx$93] = ef_verify({ ec: ec, ctx: ctx, v: value, owner: owner });
          ctx = ctx$93;
          break $m56$match;
        }
        if ($m56.tag === "None") {
          skip({  });
          break $m56$match;
        }
        $rt.unreachable();
      }
      break $m51$match;
    }
    if ($m51.tag === "ExprStmt") {
      const expr = $m51.expr;
      const [, ctx$94] = ef_expr({ ec: ec, ctx: ctx, e: expr, frame: frame, owner: owner });
      ctx = ctx$94;
      break $m51$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function ef_expr({ ec, ctx, e, frame, owner }) {
  const $m57 = e;
  $m57$match: {
    if ($m57.tag === "Ctor") {
      const args = $m57.args;
      const fields = $m57.fields;
      const $m58 = args;
      $m58$match: {
        if ($m58.tag === "Some") {
          const value = $m58.value;
          for (const a of value) {
            const [, ctx$95] = ef_expr({ ec: ec, ctx: ctx, e: a.value, frame: frame, owner: owner });
            ctx = ctx$95;
          }
          break $m58$match;
        }
        if ($m58.tag === "None") {
          skip({  });
          break $m58$match;
        }
        $rt.unreachable();
      }
      const $m59 = fields;
      $m59$match: {
        if ($m59.tag === "Some") {
          const value = $m59.value;
          for (const f of value) {
            const [, ctx$96] = ef_expr({ ec: ec, ctx: ctx, e: f.value, frame: frame, owner: owner });
            ctx = ctx$96;
          }
          break $m59$match;
        }
        if ($m59.tag === "None") {
          skip({  });
          break $m59$match;
        }
        $rt.unreachable();
      }
      break $m57$match;
    }
    if ($m57.tag === "RecordUpdate") {
      const base = $m57.base;
      const fields = $m57.fields;
      const [, ctx$97] = ef_expr({ ec: ec, ctx: ctx, e: base, frame: frame, owner: owner });
      ctx = ctx$97;
      for (const f of fields) {
        const [, ctx$98] = ef_expr({ ec: ec, ctx: ctx, e: f.value, frame: frame, owner: owner });
        ctx = ctx$98;
      }
      break $m57$match;
    }
    if ($m57.tag === "ListLit") {
      const elems = $m57.elems;
      const span = $m57.span;
      add_site({ sites: frame.sites, e: alloc_e, span: span, why: "a list literal" });
      for (const x of elems) {
        const [, ctx$99] = ef_expr({ ec: ec, ctx: ctx, e: x, frame: frame, owner: owner });
        ctx = ctx$99;
      }
      break $m57$match;
    }
    if ($m57.tag === "Try") {
      const expr = $m57.expr;
      const else_ = $m57.else_;
      const [, ctx$100] = ef_expr({ ec: ec, ctx: ctx, e: expr, frame: frame, owner: owner });
      ctx = ctx$100;
      const $m60 = else_;
      $m60$match: {
        if ($m60.tag === "Some") {
          const value = $m60.value;
          const [, ctx$101] = ef_expr({ ec: ec, ctx: ctx, e: value.expr, frame: frame, owner: owner });
          ctx = ctx$101;
          break $m60$match;
        }
        if ($m60.tag === "None") {
          skip({  });
          break $m60$match;
        }
        $rt.unreachable();
      }
      break $m57$match;
    }
    if ($m57.tag === "Recover") {
      const body = $m57.body;
      const span = $m57.span;
      const inner = fresh_frame({  });
      const [, ctx$102] = ef_block({ ec: ec, ctx: ctx, b: body, frame: inner, owner: owner });
      ctx = ctx$102;
      add_all({ sites: frame.sites, set: $effectset.without({ a: set_of({ sites: inner.sites }), e: panic_e }), span: span, why: "this `recover` block" });
      break $m57$match;
    }
    if ($m57.tag === "Quantifier") {
      const domain = $m57.domain;
      const where_ = $m57.where_;
      const body = $m57.body;
      const $m61 = domain;
      $m61$match: {
        if ($m61.tag === "Some") {
          const value = $m61.value;
          const $m62 = value;
          $m62$match: {
            if ($m62.tag === "RangeDomain") {
              const lo = $m62.lo;
              const hi = $m62.hi;
              const [, ctx$103] = ef_expr({ ec: ec, ctx: ctx, e: lo, frame: frame, owner: owner });
              ctx = ctx$103;
              const [, ctx$104] = ef_expr({ ec: ec, ctx: ctx, e: hi, frame: frame, owner: owner });
              ctx = ctx$104;
              break $m62$match;
            }
            if ($m62.tag === "InDomain") {
              const expr = $m62.expr;
              const [, ctx$105] = ef_expr({ ec: ec, ctx: ctx, e: expr, frame: frame, owner: owner });
              ctx = ctx$105;
              break $m62$match;
            }
            $rt.unreachable();
          }
          break $m61$match;
        }
        if ($m61.tag === "None") {
          skip({  });
          break $m61$match;
        }
        $rt.unreachable();
      }
      const $m63 = where_;
      $m63$match: {
        if ($m63.tag === "Some") {
          const value = $m63.value;
          const [, ctx$106] = ef_expr({ ec: ec, ctx: ctx, e: value, frame: frame, owner: owner });
          ctx = ctx$106;
          break $m63$match;
        }
        if ($m63.tag === "None") {
          skip({  });
          break $m63$match;
        }
        $rt.unreachable();
      }
      const [, ctx$107] = ef_expr({ ec: ec, ctx: ctx, e: body, frame: frame, owner: owner });
      ctx = ctx$107;
      break $m57$match;
    }
    if ($m57.tag === "Closure") {
      const span = $m57.span;
      const [, ctx$108] = ef_closure({ ec: ec, ctx: ctx, e: e, owner: owner });
      ctx = ctx$108;
      add_site({ sites: frame.sites, e: alloc_e, span: span, why: "creating a closure" });
      break $m57$match;
    }
    if ($m57.tag === "FieldAccess") {
      const object = $m57.object;
      const span = $m57.span;
      if (!$std_map.contains({ d: ctx.refs, key: key({ ec: ec, tag: $defs.tag_expr, span: span }) })) {
        const [, ctx$109] = ef_expr({ ec: ec, ctx: ctx, e: object, frame: frame, owner: owner });
        ctx = ctx$109;
      }
      break $m57$match;
    }
    if ($m57.tag === "Call") {
      const [, ctx$110] = ef_call({ ec: ec, ctx: ctx, e: e, frame: frame, owner: owner });
      ctx = ctx$110;
      break $m57$match;
    }
    if ($m57.tag === "Unary") {
      const operand = $m57.operand;
      const [, ctx$111] = ef_expr({ ec: ec, ctx: ctx, e: operand, frame: frame, owner: owner });
      ctx = ctx$111;
      break $m57$match;
    }
    if ($m57.tag === "Binary") {
      const op = $m57.op;
      const left = $m57.left;
      const right = $m57.right;
      const span = $m57.span;
      if (op === "++") {
        add_site({ sites: frame.sites, e: alloc_e, span: span, why: "`++`" });
      }
      const [, ctx$112] = ef_expr({ ec: ec, ctx: ctx, e: left, frame: frame, owner: owner });
      ctx = ctx$112;
      const [, ctx$113] = ef_expr({ ec: ec, ctx: ctx, e: right, frame: frame, owner: owner });
      ctx = ctx$113;
      break $m57$match;
    }
    if ($m57.tag === "And") {
      const operands = $m57.operands;
      for (const o of operands) {
        const [, ctx$114] = ef_expr({ ec: ec, ctx: ctx, e: o, frame: frame, owner: owner });
        ctx = ctx$114;
      }
      break $m57$match;
    }
    if ($m57.tag === "Or") {
      const operands = $m57.operands;
      for (const o of operands) {
        const [, ctx$115] = ef_expr({ ec: ec, ctx: ctx, e: o, frame: frame, owner: owner });
        ctx = ctx$115;
      }
      break $m57$match;
    }
    if ($m57.tag === "Is") {
      const expr = $m57.expr;
      const [, ctx$116] = ef_expr({ ec: ec, ctx: ctx, e: expr, frame: frame, owner: owner });
      ctx = ctx$116;
      break $m57$match;
    }
    if (true) {
      skip({  });
      break $m57$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function ef_verify({ ec, ctx, v, owner }) {
  const vkey = key({ ec: ec, tag: $defs.tag_misc, span: v.span });
  let declared = $effectset.empty({  });
  const $m64 = $std_map.find({ d: ctx.verifies, key: vkey });
  $m64$match: {
    if ($m64.tag === "Some") {
      const value = $m64.value;
      declared = value.effects;
      break $m64$match;
    }
    if ($m64.tag === "None") {
      declared = $effectset.empty({  });
      break $m64$match;
    }
    $rt.unreachable();
  }
  const frame = fresh_frame({  });
  let block_owner = owner;
  const vdef = def_of_key({ ctx: ctx, k: vkey });
  if (vdef >= 0) {
    block_owner = { tag: "Some", value: vdef };
  }
  const [, ctx$117] = ef_block({ ec: ec, ctx: ctx, b: v.body, frame: frame, owner: block_owner });
  ctx = ctx$117;
  const [, ctx$118] = containment({ ec: ec, ctx: ctx, actual: set_of({ sites: frame.sites }), declared: declared, sites: frame.sites, what: "this verify block" });
  ctx = ctx$118;
  const $m66 = owner;
  $m66$match: {
    if ($m66.tag === "None") {
      skip({  });
      break $m66$match;
    }
    if ($m66.tag === "Some") {
      const value = $m66.value;
      if (sig_of({ ctx: ctx, def: value }).tag === "Some") {
        const sig = sig_or({ ctx: ctx, def: value });
        const extra = $effectset.minus({ a: declared, b: sig.effects });
        if ($std_list.len({ xs: extra }) > 0) {
          const [, ctx$119] = rep({ ec: ec, ctx: ctx, code: "E0207", at: v.span, detail: "this verify block declares " + show({ ctx: ctx, s: $effectset.of_list({ effects: extra }) }) + ", which `" + $context.get_def({ ctx: ctx, id: value }).name + "` does not declare; a verify block may not exceed its function's effects (§20.2)" });
          ctx = ctx$119;
        }
      }
      break $m66$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function ef_closure({ ec, ctx, e, owner }) {
  const $m67 = e;
  $m67$match: {
    if ($m67.tag === "Closure") {
      const params = $m67.params;
      const body = $m67.body;
      const span = $m67.span;
      const ckey = key({ ec: ec, tag: $defs.tag_expr, span: span });
      let declared = $effectset.empty({  });
      const $m68 = $std_map.find({ d: ctx.expr_types, key: ckey });
      $m68$match: {
        if ($m68.tag === "Some") {
          const value = $m68.value;
          if (value.tag === "FnT") {
            declared = $types.effects_of({ t: value });
          }
          break $m68$match;
        }
        if ($m68.tag === "None") {
          skip({  });
          break $m68$match;
        }
        $rt.unreachable();
      }
      const frame = fresh_frame({  });
      for (const p of params) {
        const pd = def_of_key({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_sig, span: p.span }) });
        if (pd >= 0 && p.is_inout) {
          let ps = frame.inout_params;
          const [, ps$120] = $std_map.set({ d: ps, key: pd, value: true });
          ps = ps$120;
        }
      }
      const [, ctx$121] = ef_block({ ec: ec, ctx: ctx, b: body, frame: frame, owner: owner });
      ctx = ctx$121;
      const inferred = set_of({ sites: frame.sites });
      let table = ctx.closure_effects;
      const [, table$122] = $std_map.set({ d: table, key: ckey, value: inferred });
      table = table$122;
      const [, ctx$123] = containment({ ec: ec, ctx: ctx, actual: inferred, declared: declared, sites: frame.sites, what: "this closure" });
      ctx = ctx$123;
      break $m67$match;
    }
    if (true) {
      skip({  });
      break $m67$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function callee_effects({ ctx, sig, call_key }) {
  let bindings = $std_map.dict({  });
  const $m69 = $std_map.find({ d: ctx.effect_bindings, key: call_key });
  $m69$match: {
    if ($m69.tag === "Some") {
      const value = $m69.value;
      bindings = value;
      break $m69$match;
    }
    if ($m69.tag === "None") {
      bindings = $std_map.dict({  });
      break $m69$match;
    }
    $rt.unreachable();
  }
  let out = $std_list.builder({  });
  for (const e of $effectset.values({ s: sig.effects })) {
    const $m70 = e;
    $m70$match: {
      if ($m70.tag === "ParamEffect") {
        const def = $m70.def;
        const $m71 = $std_map.find({ d: bindings, key: def });
        $m71$match: {
          if ($m71.tag === "Some") {
            const value = $m71.value;
            for (const x of $effectset.values({ s: value })) {
              const [, out$124] = $std_list.push({ b: out, x: x });
              out = out$124;
            }
            break $m71$match;
          }
          if ($m71.tag === "None") {
            const [, out$125] = $std_list.push({ b: out, x: e });
            out = out$125;
            break $m71$match;
          }
          $rt.unreachable();
        }
        break $m70$match;
      }
      if (true) {
        const [, out$126] = $std_list.push({ b: out, x: e });
        out = out$126;
        break $m70$match;
      }
      $rt.unreachable();
    }
  }
  return $effectset.of_list({ effects: $std_list.finish({ b: out }) });
}

export function add_edge({ ec, owner, callee }) {
  let current = [];
  const $m72 = $std_map.find({ d: ec.call_graph, key: owner });
  $m72$match: {
    if ($m72.tag === "Some") {
      const value = $m72.value;
      current = value;
      break $m72$match;
    }
    if ($m72.tag === "None") {
      current = [];
      break $m72$match;
    }
    $rt.unreachable();
  }
  if (!$std_list.contains({ xs: current, x: callee })) {
    let g = ec.call_graph;
    const [, g$127] = $std_map.set({ d: g, key: owner, value: $std_list.append({ xs: current, x: callee }) });
    g = g$127;
  }
  return undefined;
}

export function subst_at({ ctx, call_key, sig }) {
  let subst = $std_map.dict({  });
  let args = [];
  const $m73 = $std_map.find({ d: ctx.instantiations, key: call_key });
  $m73$match: {
    if ($m73.tag === "Some") {
      const value = $m73.value;
      args = value;
      break $m73$match;
    }
    if ($m73.tag === "None") {
      args = [];
      break $m73$match;
    }
    $rt.unreachable();
  }
  const $hi74 = $std_list.len({ xs: sig.tparams });
  for (let i = 0; i < $hi74; i++) {
    if (i < $std_list.len({ xs: args })) {
      const [, subst$128] = $std_map.set({ d: subst, key: $types.tparam_def({ p: $std_list.get({ xs: sig.tparams, i: i }) }), value: $std_list.get({ xs: args, i: i }) });
      subst = subst$128;
    }
  }
  return subst;
}

export function find_param({ params, name }) {
  for (const p of params) {
    if (p.name === name) {
      return { tag: "Some", value: p };
    }
  }
  return { tag: "None" };
}

export function ef_call({ ec, ctx, e, frame, owner }) {
  const $m77 = e;
  $m77$match: {
    if ($m77.tag === "Call") {
      const callee = $m77.callee;
      const args = $m77.args;
      const span = $m77.span;
      for (const a of args) {
        const [, ctx$129] = ef_expr({ ec: ec, ctx: ctx, e: a.value, frame: frame, owner: owner });
        ctx = ctx$129;
        if (a.is_inout && a.value.tag === "Name") {
          const target = res_def({ ctx: ctx, k: key({ ec: ec, tag: $defs.tag_expr, span: $parser.span_of_expr({ e: a.value }) }) });
          if (target >= 0 && $std_map.contains({ d: frame.inout_params, key: target })) {
            add_site({ sites: frame.sites, e: mutate_e, span: a.span, why: "passing inout parameter `" + expr_name({ e: a.value }) + "` on" });
          }
        }
      }
      const call_key = key({ ec: ec, tag: $defs.tag_expr, span: span });
      const callee_key = key({ ec: ec, tag: $defs.tag_expr, span: $parser.span_of_expr({ e: callee }) });
      const fn_id = res_def({ ctx: ctx, k: callee_key });
      let effects = $effectset.empty({  });
      let callee_name = "this call";
      let sig = { tag: "None" };
      if (fn_id >= 0) {
        const fn_def = $context.get_def({ ctx: ctx, id: fn_id });
        if ($rt.eq(fn_def.kind, { tag: "Fn" }) || $rt.eq(fn_def.kind, { tag: "IfaceFn" })) {
          const s = sig_or({ ctx: ctx, def: fn_id });
          sig = { tag: "Some", value: s };
          callee_name = "`" + fn_def.name + "`";
          effects = callee_effects({ ctx: ctx, sig: s, call_key: call_key });
          if ($rt.eq(fn_def.kind, { tag: "Fn" })) {
            const $m83 = owner;
            $m83$match: {
              if ($m83.tag === "Some") {
                const value = $m83.value;
                add_edge({ ec: ec, owner: value, callee: fn_id });
                break $m83$match;
              }
              if ($m83.tag === "None") {
                skip({  });
                break $m83$match;
              }
              $rt.unreachable();
            }
          }
        }
      }
      if (sig.tag === "None") {
        const [, ctx$130] = ef_expr({ ec: ec, ctx: ctx, e: callee, frame: frame, owner: owner });
        ctx = ctx$130;
        const ct = $types.strip({ t: expr_type({ ec: ec, ctx: ctx, e: callee }) });
        if (ct.tag === "FnT") {
          effects = $types.effects_of({ t: ct });
        }
      }
      const contributed = $effectset.without({ a: effects, e: mutate_e });
      let calls = ctx.effect_calls;
      const [, calls$131] = $std_map.set({ d: calls, key: call_key, value: contributed });
      calls = calls$131;
      add_all({ sites: frame.sites, set: contributed, span: span, why: "calling " + callee_name });
      const $m84 = sig;
      $m84$match: {
        if ($m84.tag === "Some") {
          const value = $m84.value;
          const subst = subst_at({ ctx: ctx, call_key: call_key, sig: value });
          for (const a of args) {
            const fp = find_param({ params: value.params, name: a.name.text });
            if (fp.tag === "Some") {
              const p = param_or({ o: fp });
              const [, ctx$132] = flow({ ec: ec, ctx: ctx, value: a.value, into: $types.substitute({ t: p.ty, subst: subst }), what: "parameter `" + p.name + "`" });
              ctx = ctx$132;
            }
          }
          break $m84$match;
        }
        if ($m84.tag === "None") {
          const ct = $types.strip({ t: expr_type({ ec: ec, ctx: ctx, e: callee }) });
          if (ct.tag === "FnT") {
            for (const a of args) {
              const fp = find_param({ params: $types.params_of({ t: ct }), name: a.name.text });
              if (fp.tag === "Some") {
                const p = param_or({ o: fp });
                const [, ctx$133] = flow({ ec: ec, ctx: ctx, value: a.value, into: p.ty, what: "parameter `" + p.name + "`" });
                ctx = ctx$133;
              }
            }
          }
          break $m84$match;
        }
        $rt.unreachable();
      }
      break $m77$match;
    }
    if (true) {
      skip({  });
      break $m77$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function expr_name({ e }) {
  const $m85 = e;
  $m85$match: {
    if ($m85.tag === "Name") {
      const name = $m85.name;
      return name.text;
      break $m85$match;
    }
    if (true) {
      return "";
      break $m85$match;
    }
    $rt.unreachable();
  }
}

export function show_fn({ ctx, t }) {
  if (!(t.tag === "FnT")) {
    return "?";
  }
  let eff = show({ ctx: ctx, s: $types.effects_of({ t: t }) });
  if (eff === "") {
    eff = "∅";
  }
  return "fn(...) -> … may " + eff;
}

export function flow({ ec, ctx, value, into, what }) {
  const target = $types.strip({ t: into });
  if (!(target.tag === "FnT")) {
    return [undefined, ctx];
  }
  const actual = $types.strip({ t: expr_type({ ec: ec, ctx: ctx, e: value }) });
  if (!(actual.tag === "FnT")) {
    return [undefined, ctx];
  }
  const extra = $effectset.minus({ a: $types.effects_of({ t: actual }), b: $types.effects_of({ t: target }) });
  if ($std_list.len({ xs: extra }) > 0) {
    const [, ctx$134] = rep({ ec: ec, ctx: ctx, code: "E0201", at: $parser.span_of_expr({ e: value }), detail: "this function has effects " + show({ ctx: ctx, s: $effectset.of_list({ effects: extra }) }) + " that " + what + " (" + show_fn({ ctx: ctx, t: target }) + ") does not admit" });
    ctx = ctx$134;
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function is_word_cp({ c }) {
  return c >= 48 && c <= 57 || c >= 65 && c <= 90 || c >= 97 && c <= 122 || c === 95;
}

export function measure_key({ text, params }) {
  const cps = $std_text.code_points({ t: text });
  const n = $std_list.len({ xs: cps });
  let out = $std_list.builder({  });
  let i = 0;
  while (i < n) {
    const c = $std_list.get({ xs: cps, i: i });
    if (is_word_cp({ c: c })) {
      let j = i;
      while (j < n && is_word_cp({ c: $std_list.get({ xs: cps, i: j }) })) {
        j = $rt.int.add(j, 1, $ob4);
      }
      const word = $std_text.of_code_points({ cps: $std_list.slice({ xs: cps, from: i, to: j }) });
      let preceded_by_dot = false;
      if (i > 0) {
        preceded_by_dot = $std_list.get({ xs: cps, i: $rt.int.sub(i, 1, $ob5) }) === 46;
      }
      let k = j;
      while (k < n && $std_list.get({ xs: cps, i: k }) === 32) {
        k = $rt.int.add(k, 1, $ob6);
      }
      let followed_by_colon = false;
      if (k < n) {
        followed_by_colon = $std_list.get({ xs: cps, i: k }) === 58;
      }
      let replaced = false;
      if (!preceded_by_dot && !followed_by_colon) {
        let idx = 0;
        for (const p of params) {
          if (!replaced && p.name === word) {
            replaced = true;
            const [, out$135] = $std_list.push({ b: out, x: 36 });
            out = out$135;
            for (const d of $std_text.code_points({ t: $std_int.to_text({ x: idx }) })) {
              const [, out$136] = $std_list.push({ b: out, x: d });
              out = out$136;
            }
          }
          idx = $rt.int.add(idx, 1, $ob7);
        }
      }
      if (!replaced) {
        for (const w of $std_list.slice({ xs: cps, from: i, to: j })) {
          const [, out$137] = $std_list.push({ b: out, x: w });
          out = out$137;
        }
      }
      i = j;
    } else {
      const [, out$138] = $std_list.push({ b: out, x: c });
      out = out$138;
      i = $rt.int.add(i, 1, $ob8);
    }
  }
  return $std_text.of_code_points({ cps: $std_list.finish({ b: out }) });
}

export function get_or({ d, k }) {
  const $m89 = $std_map.find({ d: d, key: k });
  $m89$match: {
    if ($m89.tag === "Some") {
      const value = $m89.value;
      return value;
      break $m89$match;
    }
    if ($m89.tag === "None") {
      return 0;
      break $m89$match;
    }
    $rt.unreachable();
  }
}

export function min({ a, b }) {
  if (a < b) {
    return a;
  }
  return b;
}

export function strong({ fuel, ec, tj, v }) {
  if (fuel === 0) {
    return [undefined, tj];
  }
  let index = tj.index;
  let low = tj.low;
  let on_stack = tj.on_stack;
  const [, index$139] = $std_map.set({ d: index, key: v, value: tj.counter });
  index = index$139;
  const [, low$140] = $std_map.set({ d: low, key: v, value: tj.counter });
  low = low$140;
  tj = { ...tj, counter: $rt.int.add(tj.counter, 1, $ob9) };
  let stack = tj.stack;
  const [, stack$141] = $std_list.push({ b: stack, x: v });
  stack = stack$141;
  const [, on_stack$142] = $std_map.set({ d: on_stack, key: v, value: true });
  on_stack = on_stack$142;
  let edges = [];
  const $m91 = $std_map.find({ d: ec.call_graph, key: v });
  $m91$match: {
    if ($m91.tag === "Some") {
      const value = $m91.value;
      edges = value;
      break $m91$match;
    }
    if ($m91.tag === "None") {
      edges = [];
      break $m91$match;
    }
    $rt.unreachable();
  }
  for (const w of edges) {
    if (!$std_map.contains({ d: index, key: w })) {
      const [, tj$143] = strong({ fuel: $rt.int.sub(fuel, 1, $ob10), ec: ec, tj: tj, v: w });
      tj = tj$143;
      const [, low$144] = $std_map.set({ d: low, key: v, value: min({ a: get_or({ d: low, k: v }), b: get_or({ d: low, k: w }) }) });
      low = low$144;
    } else {
      if ($std_map.contains({ d: on_stack, key: w })) {
        const [, low$145] = $std_map.set({ d: low, key: v, value: min({ a: get_or({ d: low, k: v }), b: get_or({ d: index, k: w }) }) });
        low = low$145;
      }
    }
  }
  if (get_or({ d: low, k: v }) === get_or({ d: index, k: v })) {
    let scc = $std_list.builder({  });
    let done = false;
    let guard = $std_list.built({ b: stack });
    while (!done && guard > 0) {
      guard = $rt.int.sub(guard, 1, $ob11);
      const [$r94, stack$146] = $std_list.pop({ b: stack });
      stack = stack$146;
      const $m93 = $r94;
      $m93$match: {
        if ($m93.tag === "None") {
          done = true;
          break $m93$match;
        }
        if ($m93.tag === "Some") {
          const value = $m93.value;
          const [, on_stack$147] = $std_map.remove({ d: on_stack, key: value });
          on_stack = on_stack$147;
          const [, scc$148] = $std_list.push({ b: scc, x: value });
          scc = scc$148;
          if (value === v) {
            done = true;
          }
          break $m93$match;
        }
        $rt.unreachable();
      }
    }
    let sccs = tj.sccs;
    const [, sccs$149] = $std_list.push({ b: sccs, x: $std_list.finish({ b: scc }) });
    sccs = sccs$149;
  }
  return [undefined, tj];
  return [undefined, tj];
}

export function decreases_clause({ sig }) {
  for (const c of sig.contracts) {
    if (c.clause === "decreases") {
      return { tag: "Some", value: c };
    }
  }
  return { tag: "None" };
}

export function recursion({ ec, ctx }) {
  let tj = { index: $std_map.dict({  }), low: $std_map.dict({  }), on_stack: $std_map.dict({  }), stack: $std_list.builder({  }), counter: 0, sccs: $std_list.builder({  }) };
  for (const v of $std_map.keys({ d: ec.call_graph })) {
    if (!$std_map.contains({ d: tj.index, key: v })) {
      const [, tj$150] = strong({ fuel: max_graph, ec: ec, tj: tj, v: v });
      tj = tj$150;
    }
  }
  let cycle = 0;
  for (const scc of $std_list.finish({ b: tj.sccs })) {
    let cyclic = $std_list.len({ xs: scc }) > 1;
    if ($std_list.len({ xs: scc }) === 1) {
      const first = $std_list.get({ xs: scc, i: 0 });
      const $m98 = $std_map.find({ d: ec.call_graph, key: first });
      $m98$match: {
        if ($m98.tag === "Some") {
          const value = $m98.value;
          cyclic = $std_list.contains({ xs: value, x: first });
          break $m98$match;
        }
        if ($m98.tag === "None") {
          cyclic = false;
          break $m98$match;
        }
        $rt.unreachable();
      }
    }
    if (cyclic) {
      cycle = $rt.int.add(cycle, 1, $ob12);
      for (const f of scc) {
        let cycles = ctx.cycles;
        const [, cycles$151] = $std_map.set({ d: cycles, key: f, value: cycle });
        cycles = cycles$151;
      }
      let measures = $std_map.dict({  });
      let first_key = "";
      let first_def = $rt.int.neg(1, $ob13);
      for (const f of scc) {
        const d = $context.get_def({ ctx: ctx, id: f });
        const sig = sig_or({ ctx: ctx, def: f });
        const $m99 = decreases_clause({ sig: sig });
        $m99$match: {
          if ($m99.tag === "None") {
            skip({  });
            break $m99$match;
          }
          if ($m99.tag === "Some") {
            const value = $m99.value;
            const k = measure_key({ text: $printer.print_expr({ e: value.expr }), params: sig.params });
            if (!$std_map.contains({ d: measures, key: k })) {
              if ($std_map.count({ d: measures }) > 0) {
                ec = { ...ec, current_def: { tag: "Some", value: d.name }, current_file: d.file };
                const [, ctx$152] = rep({ ec: ec, ctx: ctx, code: "E0320", at: value.span, detail: "`" + d.name + "` and `" + $context.get_def({ ctx: ctx, id: first_def }).name + "` are in one recursive cycle but declare different measures (`" + k + "` and `" + first_key + "`, parameters numbered by position); a cycle shares one measure" });
                ctx = ctx$152;
              } else {
                first_key = k;
                first_def = f;
              }
              const [, measures$153] = $std_map.set({ d: measures, key: k, value: f });
              measures = measures$153;
            }
            break $m99$match;
          }
          $rt.unreachable();
        }
      }
      for (const f of scc) {
        const d = $context.get_def({ ctx: ctx, id: f });
        const sig = sig_or({ ctx: ctx, def: f });
        const measured = decreases_clause({ sig: sig }).tag === "Some" || $effectset.has({ s: sig.effects, e: diverge_e });
        if (!measured) {
          ec = { ...ec, current_def: { tag: "Some", value: d.name }, current_file: d.file };
          let others = $std_list.builder({  });
          for (const x of scc) {
            if (x !== f) {
              const [, others$154] = $std_list.push({ b: others, x: "`" + $context.get_def({ ctx: ctx, id: x }).name + "`" });
              others = others$154;
            }
          }
          let with_text = "";
          if ($std_list.built({ b: others }) > 0) {
            with_text = " (with " + $std_text.join({ parts: $std_list.finish({ b: others }), sep: ", " }) + ")";
          }
          const [, ctx$155] = rep({ ec: ec, ctx: ctx, code: "E0320", at: d.span, detail: "`" + d.name + "` is recursive" + with_text + " and declares neither `decreases` nor `diverge`" });
          ctx = ctx$155;
        }
      }
    }
  }
  return [undefined, ec, ctx];
  return [undefined, ec, ctx];
}

export function effects_pass({ ctx }) {
  let ec = { current_def: { tag: "None" }, current_file: 0, call_graph: $std_map.dict({  }) };
  const $hi106 = ctx.module_count;
  for (let id = 0; id < $hi106; id++) {
    const $m107 = $std_map.find({ d: ctx.modules, key: id });
    $m107$match: {
      if ($m107.tag === "Some") {
        const value = $m107.value;
        ec = { ...ec, current_file: value.file };
        for (const item of value.tree.items) {
          ec = { ...ec, current_def: { tag: "Some", value: item_name({ item: item }) } };
          const [, ec$156, ctx$156] = ef_item({ ec: ec, ctx: ctx, item: item });
          ec = ec$156;
          ctx = ctx$156;
        }
        break $m107$match;
      }
      if ($m107.tag === "None") {
        skip({  });
        break $m107$match;
      }
      $rt.unreachable();
    }
  }
  ec = { ...ec, current_def: { tag: "None" } };
  const [, ec$157, ctx$157] = recursion({ ec: ec, ctx: ctx });
  ec = ec$157;
  ctx = ctx$157;
  return [undefined, ctx];
  return [undefined, ctx];
}

