// Generated by onus from module effectset. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $std_int from "./std/int.js";
import * as $std_map from "./std/map.js";
import * as $std_list from "./std/list.js";
export function effect_key({ e }) {
  const $m1 = e;
  $m1$match: {
    if ($m1.tag === "PrimEffect") {
      const name = $m1.name;
      return name;
      break $m1$match;
    }
    if ($m1.tag === "ResourceEffect") {
      const mod = $m1.mod;
      const name = $m1.name;
      return "resource:" + $std_int.to_text({ x: mod }) + ":" + name;
      break $m1$match;
    }
    if ($m1.tag === "ParamEffect") {
      const def = $m1.def;
      return "param:" + $std_int.to_text({ x: def });
      break $m1$match;
    }
    $rt.unreachable();
  }
}

export function empty($args) {
  return { items: [] };
}

export function of_list({ effects }) {
  let seen = $std_map.dict({  });
  let out = $std_list.builder({  });
  for (const e of effects) {
    const k = effect_key({ e: e });
    if (!$std_map.contains({ d: seen, key: k })) {
      const [, seen$1] = $std_map.set({ d: seen, key: k, value: true });
      seen = seen$1;
      const [, out$2] = $std_list.push({ b: out, x: e });
      out = out$2;
    }
  }
  return { items: $std_list.finish({ b: out }) };
}

export function has({ s, e }) {
  const k = effect_key({ e: e });
  for (const x of s.items) {
    if (effect_key({ e: x }) === k) {
      return true;
    }
  }
  return false;
}

export function size({ s }) {
  return $std_list.len({ xs: s.items });
}

export function values({ s }) {
  return s.items;
}

export function subset_of({ a, b }) {
  for (const x of a.items) {
    if (!has({ s: b, e: x })) {
      return false;
    }
  }
  return true;
}

export function join_sets({ a, b }) {
  let all = $std_list.builder({  });
  for (const x of a.items) {
    const [, all$3] = $std_list.push({ b: all, x: x });
    all = all$3;
  }
  for (const x of b.items) {
    const [, all$4] = $std_list.push({ b: all, x: x });
    all = all$4;
  }
  return of_list({ effects: $std_list.finish({ b: all }) });
}

export function minus({ a, b }) {
  let out = $std_list.builder({  });
  for (const x of a.items) {
    if (!has({ s: b, e: x })) {
      const [, out$5] = $std_list.push({ b: out, x: x });
      out = out$5;
    }
  }
  return $std_list.finish({ b: out });
}

export function without({ a, e }) {
  const k = effect_key({ e: e });
  let out = $std_list.builder({  });
  for (const x of a.items) {
    if (effect_key({ e: x }) !== k) {
      const [, out$6] = $std_list.push({ b: out, x: x });
      out = out$6;
    }
  }
  return { items: $std_list.finish({ b: out }) };
}

export function equals({ a, b }) {
  return subset_of({ a: a, b: b }) && subset_of({ a: b, b: a });
}

