// Generated by onus from module jsemit. Do not edit.
import * as $rt from "./onus-runtime/index.js";
import * as $std_list from "./std/list.js";
import * as $std_text from "./std/text.js";
import * as $std_map from "./std/map.js";
import * as $json from "./json.js";
import * as $std_int from "./std/int.js";
import * as $context from "./context.js";
import * as $std_float from "./std/float.js";
import * as $std_bool from "./std/bool.js";
import * as $types from "./types.js";
import * as $lowerir from "./lowerir.js";

const $ob1 = { kind: "overflow", text: "e.w.depth + 1 within Int", at: "self/jsemit.onus:191:37", def: "indent" };
const $ob2 = { kind: "overflow", text: "d - 1 within Int", at: "self/jsemit.onus:198:39", def: "dedent" };
const $ob3 = { kind: "overflow", text: "List.len(xs: from) - 1 within Int", at: "self/jsemit.onus:288:18", def: "relative_import" };
const $ob4 = { kind: "overflow", text: "Map.count(d: e.ob_refs) + 1 within Int", at: "self/jsemit.onus:336:44", def: "ob_ref" };
const $ob5 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:507:16", def: "block" };
const $ob6 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:529:33", def: "stmt" };
const $ob7 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:533:33", def: "stmt" };
const $ob8 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:537:33", def: "stmt" };
const $ob9 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:553:30", def: "stmt" };
const $ob10 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:556:17", def: "stmt" };
const $ob11 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:562:19", def: "stmt" };
const $ob12 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:569:31", def: "stmt" };
const $ob13 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:577:42", def: "stmt" };
const $ob14 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:582:34", def: "stmt" };
const $ob15 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:587:34", def: "stmt" };
const $ob16 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:590:21", def: "stmt" };
const $ob17 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:596:21", def: "stmt" };
const $ob18 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:607:30", def: "stmt" };
const $ob19 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:610:17", def: "stmt" };
const $ob20 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:616:33", def: "stmt" };
const $ob21 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:617:39", def: "stmt" };
const $ob22 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:623:17", def: "stmt" };
const $ob23 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:628:30", def: "stmt" };
const $ob24 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:631:17", def: "stmt" };
const $ob25 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:636:30", def: "stmt" };
const $ob26 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:641:30", def: "stmt" };
const $ob27 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:649:38", def: "stmt" };
const $ob28 = { kind: "overflow", text: "e.inout_seq + 1 within Int", at: "self/jsemit.onus:660:29", def: "stmt" };
const $ob29 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:670:30", def: "stmt" };
const $ob30 = { kind: "overflow", text: "i + 1 within Int", at: "self/jsemit.onus:686:11", def: "stmt" };
const $ob31 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:692:30", def: "stmt" };
const $ob32 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:719:21", def: "expr_code" };
const $ob33 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:744:35", def: "decoder_code" };
const $ob34 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:765:15", def: "inline" };
const $ob35 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:792:49", def: "exprs_code" };
const $ob36 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:812:52", def: "inits_code" };
const $ob37 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:871:21", def: "expr" };
const $ob38 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:888:21", def: "expr" };
const $ob39 = { kind: "overflow", text: "di + 1 within Int", at: "self/jsemit.onus:894:16", def: "expr" };
const $ob40 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:905:19", def: "expr" };
const $ob41 = { kind: "overflow", text: "ci + 1 within Int", at: "self/jsemit.onus:911:14", def: "expr" };
const $ob42 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:923:54", def: "expr" };
const $ob43 = { kind: "overflow", text: "i + 1 within Int", at: "self/jsemit.onus:925:11", def: "expr" };
const $ob44 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:930:44", def: "expr" };
const $ob45 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:939:36", def: "expr" };
const $ob46 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:942:33", def: "expr" };
const $ob47 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:950:31", def: "expr" };
const $ob48 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:956:45", def: "expr" };
const $ob49 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:966:36", def: "expr" };
const $ob50 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:969:33", def: "expr" };
const $ob51 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:976:28", def: "expr" };
const $ob52 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:983:31", def: "expr" };
const $ob53 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:989:31", def: "expr" };
const $ob54 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:990:31", def: "expr" };
const $ob55 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1000:31", def: "expr" };
const $ob56 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1001:31", def: "expr" };
const $ob57 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1046:36", def: "expr" };
const $ob58 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1047:36", def: "expr" };
const $ob59 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1051:31", def: "expr" };
const $ob60 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1060:36", def: "expr" };
const $ob61 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1061:36", def: "expr" };
const $ob62 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1065:31", def: "expr" };
const $ob63 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1066:31", def: "expr" };
const $ob64 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1084:35", def: "expr" };
const $ob65 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1089:31", def: "expr" };
const $ob66 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1096:31", def: "expr" };
const $ob67 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1102:36", def: "expr" };
const $ob68 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1103:36", def: "expr" };
const $ob69 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1108:21", def: "expr" };
const $ob70 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1114:31", def: "expr" };
const $ob71 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1124:39", def: "expr" };
const $ob72 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1160:17", def: "expr" };
const $ob73 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1161:30", def: "expr" };
const $ob74 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1172:13", def: "expr" };
const $ob75 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1176:34", def: "expr" };
const $ob76 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1177:47", def: "expr" };
const $ob77 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1179:13", def: "expr" };
const $ob78 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1186:38", def: "expr" };
const $ob79 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1193:23", def: "expr" };
const $ob80 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1196:23", def: "expr" };
const $ob81 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1225:17", def: "expr" };
const $ob82 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1227:17", def: "expr" };
const $ob83 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1241:31", def: "expr" };
const $ob84 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1247:30", def: "expr" };
const $ob85 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1248:33", def: "expr" };
const $ob86 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1274:31", def: "expr" };
const $ob87 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1288:41", def: "expr" };
const $ob88 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1335:56", def: "value_literal" };
const $ob89 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1340:31", def: "value_literal" };
const $ob90 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1346:29", def: "value_literal" };
const $ob91 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1387:61", def: "value_fields" };
const $ob92 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1497:41", def: "generator" };
const $ob93 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1540:11", def: "base_generator" };
const $ob94 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1546:29", def: "base_generator" };
const $ob95 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1555:35", def: "base_generator" };
const $ob96 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/jsemit.onus:1580:57", def: "gen_fields" };
export const reserved = ["await", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in", "instanceof", "new", "null", "return", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield", "let", "static", "implements", "interface", "package", "private", "protected", "public", "arguments", "eval", "undefined", "NaN", "Infinity"];

export const max_depth = 100000;

export const p_atom = 20;

export const p_call = 17;

export const p_unary = 14;

export const p_mul = 12;

export const p_add = 11;

export const p_cmp = 9;

export const p_eq = 8;

export const p_and = 4;

export const p_or = 3;

export const p_arrow = 2;

export function piece({ code, prec }) {
  return { code: code, prec: prec };
}

export function at({ p, min }) {
  if (p.prec >= min) {
    return p.code;
  }
  return "(" + p.code + ")";
}

export function new_writer($args) {
  return { lines: $std_list.builder({  }), depth: 0 };
}

export function writer_text({ w }) {
  return $std_text.join({ parts: $std_list.finish({ b: w.lines }), sep: "\n" });
}

export function skip($args) {
  return undefined;
}

export function line({ e, s }) {
  let lines = e.w.lines;
  if (s === "") {
    const [, lines$1] = $std_list.push({ b: lines, x: "" });
    lines = lines$1;
  } else {
    const [, lines$2] = $std_list.push({ b: lines, x: $std_text.repeat({ t: "  ", n: e.w.depth }) + s });
    lines = lines$2;
  }
  return [undefined, e];
  return [undefined, e];
}

export function indent({ e }) {
  e = { ...e, w: { ...e.w, depth: $rt.int.add(e.w.depth, 1, $ob1) } };
  return [undefined, e];
  return [undefined, e];
}

export function dedent({ e }) {
  const d = e.w.depth;
  if (d > 0) {
    e = { ...e, w: { ...e.w, depth: $rt.int.sub(d, 1, $ob2) } };
  }
  return [undefined, e];
  return [undefined, e];
}

export function copy_text_dict({ d }) {
  let out = $std_map.dict({  });
  for (const k of $std_map.keys({ d: d })) {
    const $m7 = $std_map.find({ d: d, key: k });
    $m7$match: {
      if ($m7.tag === "Some") {
        const value = $m7.value;
        const [, out$3] = $std_map.set({ d: out, key: k, value: value });
        out = out$3;
        break $m7$match;
      }
      if ($m7.tag === "None") {
        skip({  });
        break $m7$match;
      }
      $rt.unreachable();
    }
  }
  return out;
}

export function copy_int_dict({ d }) {
  let out = $std_map.dict({  });
  for (const k of $std_map.keys({ d: d })) {
    const $m8 = $std_map.find({ d: d, key: k });
    $m8$match: {
      if ($m8.tag === "Some") {
        const value = $m8.value;
        const [, out$4] = $std_map.set({ d: out, key: k, value: value });
        out = out$4;
        break $m8$match;
      }
      if ($m8.tag === "None") {
        skip({  });
        break $m8$match;
      }
      $rt.unreachable();
    }
  }
  return out;
}

export function emit_js({ ctx, m, opts }) {
  let e = { m: m.mod, w: new_writer({  }), imports: $std_map.dict({  }), ob_decls: [], ob_refs: $std_map.dict({  }), self_alias: { tag: "None" }, fn_ctx: { tag: "None" }, inout_seq: 0, assert_mode: "return-false", opts: opts };
  for (const item of m.items) {
    const [, e$5] = item_js({ e: e, ctx: ctx, item: item });
    e = e$5;
  }
  let verifies = $std_list.builder({  });
  for (const v of m.verifies) {
    const [$r12, e$6] = verify_function({ e: e, ctx: ctx, v: v });
    e = e$6;
    const [, verifies$7] = $std_list.push({ b: verifies, x: $r12 });
    verifies = verifies$7;
  }
  const body = writer_text({ w: e.w });
  let head = $std_list.builder({  });
  const [, head$8] = $std_list.push({ b: head, x: "// Generated by onus from module " + m.mod.name + ". Do not edit." });
  head = head$8;
  const [, head$9] = $std_list.push({ b: head, x: "import * as $rt from " + $json.quote({ t: opts.runtime }) + ";" });
  head = head$9;
  for (const id of $std_map.keys({ d: e.imports })) {
    const $m13 = $std_map.find({ d: e.imports, key: id });
    $m13$match: {
      if ($m13.tag === "Some") {
        const value = $m13.value;
        const [, head$10] = $std_list.push({ b: head, x: "import * as " + value + " from " + $json.quote({ t: relative_import({ e: e, ctx: ctx, id: id }) }) + ";" });
        head = head$10;
        break $m13$match;
      }
      if ($m13.tag === "None") {
        skip({  });
        break $m13$match;
      }
      $rt.unreachable();
    }
  }
  const [, head$11] = $std_list.push({ b: head, x: "" });
  head = head$11;
  for (const d of e.ob_decls) {
    const [, head$12] = $std_list.push({ b: head, x: d });
    head = head$12;
  }
  if ($std_list.len({ xs: e.ob_decls }) > 0) {
    const [, head$13] = $std_list.push({ b: head, x: "" });
    head = head$13;
  }
  let tests = { tag: "None" };
  const $m15 = m.tests;
  $m15$match: {
    if ($m15.tag === "Some") {
      const value = $m15.value;
      const [$r16, e$14] = tests_file({ e: e, ctx: ctx, tests: value });
      e = e$14;
      tests = { tag: "Some", value: $r16 };
      break $m15$match;
    }
    if ($m15.tag === "None") {
      skip({  });
      break $m15$match;
    }
    $rt.unreachable();
  }
  return { mod: m.mod, code: $std_text.join({ parts: $std_list.finish({ b: head }), sep: "\n" }) + body + "\n", verifies: $std_list.finish({ b: verifies }), tests: tests, main: m.main };
}

export function module_name({ ctx, id }) {
  const $m19 = $std_map.find({ d: ctx.modules, key: id });
  $m19$match: {
    if ($m19.tag === "Some") {
      const value = $m19.value;
      return value.name;
      break $m19$match;
    }
    if ($m19.tag === "None") {
      return "";
      break $m19$match;
    }
    $rt.unreachable();
  }
}

export function relative_import({ e, ctx, id }) {
  const from = $std_text.split({ t: e.m.name, sep: "." });
  const to = $std_text.split({ t: module_name({ ctx: ctx, id: id }), sep: "." });
  const ups = $rt.int.sub($std_list.len({ xs: from }), 1, $ob3);
  let prefix = "./";
  if (ups > 0) {
    prefix = $std_text.repeat({ t: "../", n: ups });
  }
  return prefix + $std_text.join({ parts: to, sep: "/" }) + ".js";
}

export function alias({ e, ctx, id }) {
  if (id === e.m.id && e.self_alias.tag === "Some") {
    return [text_or({ o: e.self_alias, dflt: "" }), e];
  }
  const $m20 = $std_map.find({ d: e.imports, key: id });
  $m20$match: {
    if ($m20.tag === "Some") {
      const value = $m20.value;
      return [value, e];
      break $m20$match;
    }
    if ($m20.tag === "None") {
      skip({  });
      break $m20$match;
    }
    $rt.unreachable();
  }
  const a = "$" + $std_text.replace({ t: module_name({ ctx: ctx, id: id }), from: ".", to: "_" });
  let imports = e.imports;
  const [, imports$15] = $std_map.set({ d: imports, key: id, value: a });
  imports = imports$15;
  return [a, e];
}

export function text_or({ o, dflt }) {
  const $m21 = o;
  $m21$match: {
    if ($m21.tag === "Some") {
      const value = $m21.value;
      return value;
      break $m21$match;
    }
    if ($m21.tag === "None") {
      return dflt;
      break $m21$match;
    }
    $rt.unreachable();
  }
}

export function local({ name }) {
  if ($std_list.contains({ xs: reserved, x: name })) {
    return name + "_";
  }
  return name;
}

export function qualified({ e, ctx, mod, name }) {
  const base = local({ name: name });
  if (mod === e.m.id && e.self_alias.tag === "None") {
    return [base, e];
  }
  const [$r22, e$16] = alias({ e: e, ctx: ctx, id: mod });
  e = e$16;
  return [$r22 + "." + base, e];
}

export function ob_ref({ e, o }) {
  const key = o.kind + "|" + o.text + "|" + o.at + "|" + o.def;
  const $m23 = $std_map.find({ d: e.ob_refs, key: key });
  $m23$match: {
    if ($m23.tag === "Some") {
      const value = $m23.value;
      return [value, e];
      break $m23$match;
    }
    if ($m23.tag === "None") {
      skip({  });
      break $m23$match;
    }
    $rt.unreachable();
  }
  const name = "$ob" + $std_int.to_text({ x: $rt.int.add($std_map.count({ d: e.ob_refs }), 1, $ob4) });
  let refs = e.ob_refs;
  const [, refs$17] = $std_map.set({ d: refs, key: key, value: name });
  refs = refs$17;
  const literal = "{ kind: " + $json.quote({ t: o.kind }) + ", text: " + $json.quote({ t: o.text }) + ", at: " + $json.quote({ t: o.at }) + ", def: " + $json.quote({ t: o.def }) + " }";
  e = { ...e, ob_decls: $std_list.append({ xs: e.ob_decls, x: "const " + name + " = " + literal + ";" }) };
  return [name, e];
}

export function item_js({ e, ctx, item }) {
  const $m25 = item;
  $m25$match: {
    if ($m25.tag === "FnItem") {
      const f = $m25.f;
      const [, e$18] = fn_decl({ e: e, ctx: ctx, f: f });
      e = e$18;
      break $m25$match;
    }
    if ($m25.tag === "ConstItem") {
      const def = $m25.def;
      const value = $m25.value;
      const [$r26, e$19] = expr({ fuel: max_depth, e: e, ctx: ctx, x: value });
      e = e$19;
      const code = $r26.code;
      const [, e$20] = line({ e: e, s: "export const " + local({ name: def.name }) + " = " + code + ";" });
      e = e$20;
      const [, e$21] = line({ e: e, s: "" });
      e = e$21;
      break $m25$match;
    }
    if ($m25.tag === "ImplItem") {
      const dict_name = $m25.dict_name;
      const fns = $m25.fns;
      const entries = $m25.entries;
      for (const f of fns) {
        const [, e$22] = fn_decl({ e: e, ctx: ctx, f: f });
        e = e$22;
      }
      let parts = $std_list.builder({  });
      for (const en of entries) {
        const [, parts$23] = $std_list.push({ b: parts, x: local({ name: en.name }) + ": " + local({ name: en.fn_ir.name }) });
        parts = parts$23;
      }
      const [, e$24] = line({ e: e, s: "export const " + dict_name + " = { " + $std_text.join({ parts: $std_list.finish({ b: parts }), sep: ", " }) + " };" });
      e = e$24;
      const [, e$25] = line({ e: e, s: "" });
      e = e$25;
      break $m25$match;
    }
    if (true) {
      skip({  });
      break $m25$match;
    }
    $rt.unreachable();
  }
  return [undefined, e];
  return [undefined, e];
}

export function fn_decl({ e, ctx, f }) {
  const is_select = f.intrinsic.tag === "Some" && $context.qualified_name({ ctx: ctx, id: f.def.id }) === "std.sql.select";
  let names = $std_list.builder({  });
  for (const d of f.dict_params) {
    const [, names$26] = $std_list.push({ b: names, x: d.name });
    names = names$26;
  }
  for (const c of f.const_params) {
    const [, names$27] = $std_list.push({ b: names, x: local({ name: c.name }) });
    names = names$27;
  }
  for (const p of f.params) {
    const [, names$28] = $std_list.push({ b: names, x: local({ name: p.name }) });
    names = names$28;
  }
  if (is_select) {
    const [, names$29] = $std_list.push({ b: names, x: "$decode" });
    names = names$29;
  }
  let destructure = "$args";
  if ($std_list.built({ b: names }) > 0) {
    destructure = "{ " + $std_text.join({ parts: $std_list.finish({ b: names }), sep: ", " }) + " }";
  }
  const $m27 = f.intrinsic;
  $m27$match: {
    if ($m27.tag === "Some") {
      const value = $m27.value;
      let args = $std_list.builder({  });
      for (const c of f.const_params) {
        const [, args$30] = $std_list.push({ b: args, x: local({ name: c.name }) });
        args = args$30;
      }
      for (const p of f.params) {
        const [, args$31] = $std_list.push({ b: args, x: local({ name: p.name }) });
        args = args$31;
      }
      if (is_select) {
        const [, args$32] = $std_list.push({ b: args, x: "$decode ?? null" });
        args = args$32;
      }
      const [, e$33] = line({ e: e, s: "export function " + local({ name: f.name }) + "(" + destructure + ") {" });
      e = e$33;
      const [, e$34] = indent({ e: e });
      e = e$34;
      const [, e$35] = line({ e: e, s: "return $rt." + value.ns + "." + value.name + "(" + $std_text.join({ parts: $std_list.finish({ b: args }), sep: ", " }) + ");" });
      e = e$35;
      const [, e$36] = dedent({ e: e });
      e = e$36;
      const [, e$37] = line({ e: e, s: "}" });
      e = e$37;
      const [, e$38] = line({ e: e, s: "" });
      e = e$38;
      return [undefined, e];
      break $m27$match;
    }
    if ($m27.tag === "None") {
      skip({  });
      break $m27$match;
    }
    $rt.unreachable();
  }
  const $m28 = f.body;
  $m28$match: {
    if ($m28.tag === "None") {
      return [undefined, e];
      break $m28$match;
    }
    if ($m28.tag === "Some") {
      const value = $m28.value;
      let inouts = $std_list.builder({  });
      for (const p of f.params) {
        if (p.is_inout) {
          const [, inouts$39] = $std_list.push({ b: inouts, x: p.name });
          inouts = inouts$39;
        }
      }
      e = { ...e, fn_ctx: { tag: "Some", value: { inout_names: $std_list.finish({ b: inouts }), ret: f.ret } } };
      const [, e$40] = line({ e: e, s: "export function " + local({ name: f.name }) + "(" + destructure + ") {" });
      e = e$40;
      const [, e$41] = indent({ e: e });
      e = e$41;
      const [, e$42] = block({ fuel: max_depth, e: e, ctx: ctx, b: f.entry_checks });
      e = e$42;
      const [, e$43] = early_open({ e: e, early: f.early_return });
      e = e$43;
      const [, e$44] = block({ fuel: max_depth, e: e, ctx: ctx, b: value });
      e = e$44;
      const [, e$45] = early_close({ e: e, early: f.early_return });
      e = e$45;
      const [, e$46] = dedent({ e: e });
      e = e$46;
      const [, e$47] = line({ e: e, s: "}" });
      e = e$47;
      const [, e$48] = line({ e: e, s: "" });
      e = e$48;
      e = { ...e, fn_ctx: { tag: "None" } };
      return [undefined, e];
      break $m28$match;
    }
    $rt.unreachable();
  }
  return [undefined, e];
}

export function early_open({ e, early }) {
  if (early) {
    const [, e$49] = line({ e: e, s: "try {" });
    e = e$49;
    const [, e$50] = indent({ e: e });
    e = e$50;
  }
  return [undefined, e];
  return [undefined, e];
}

export function early_close({ e, early }) {
  if (!early) {
    return [undefined, e];
  }
  const [, e$51] = dedent({ e: e });
  e = e$51;
  const [, e$52] = line({ e: e, s: "} catch ($e) {" });
  e = e$52;
  const [, e$53] = indent({ e: e });
  e = e$53;
  let inouts = $std_list.builder({  });
  const $m34 = e.fn_ctx;
  $m34$match: {
    if ($m34.tag === "Some") {
      const value = $m34.value;
      for (const n of value.inout_names) {
        const [, inouts$54] = $std_list.push({ b: inouts, x: local({ name: n }) });
        inouts = inouts$54;
      }
      break $m34$match;
    }
    if ($m34.tag === "None") {
      skip({  });
      break $m34$match;
    }
    $rt.unreachable();
  }
  if ($std_list.built({ b: inouts }) === 0) {
    const [, e$55] = line({ e: e, s: "if ($e instanceof $rt.EarlyReturn) return $e.value;" });
    e = e$55;
  } else {
    const [, e$56] = line({ e: e, s: "if ($e instanceof $rt.EarlyReturn) return [$e.value, " + $std_text.join({ parts: $std_list.finish({ b: inouts }), sep: ", " }) + "];" });
    e = e$56;
  }
  const [, e$57] = line({ e: e, s: "throw $e;" });
  e = e$57;
  const [, e$58] = dedent({ e: e });
  e = e$58;
  const [, e$59] = line({ e: e, s: "}" });
  e = e$59;
  return [undefined, e];
  return [undefined, e];
}

export function block({ fuel, e, ctx, b }) {
  if (fuel === 0) {
    return [undefined, e];
  }
  for (const s of b) {
    const [, e$60] = stmt({ fuel: $rt.int.sub(fuel, 1, $ob5), e: e, ctx: ctx, s: s });
    e = e$60;
  }
  return [undefined, e];
  return [undefined, e];
}

export function stmt({ fuel, e, ctx, s }) {
  if (fuel === 0) {
    return [undefined, e];
  }
  const $m35 = s;
  $m35$match: {
    if ($m35.tag === "Let") {
      const name = $m35.name;
      const mutable = $m35.mutable;
      const value = $m35.value;
      let kw = "const";
      if (mutable) {
        kw = "let";
      }
      const [$r36, e$61] = expr({ fuel: $rt.int.sub(fuel, 1, $ob6), e: e, ctx: ctx, x: value });
      e = e$61;
      const code = $r36.code;
      const [, e$62] = line({ e: e, s: kw + " " + local({ name: name }) + " = " + code + ";" });
      e = e$62;
      break $m35$match;
    }
    if ($m35.tag === "Assign") {
      const name = $m35.name;
      const value = $m35.value;
      const [$r37, e$63] = expr({ fuel: $rt.int.sub(fuel, 1, $ob7), e: e, ctx: ctx, x: value });
      e = e$63;
      const code = $r37.code;
      const [, e$64] = line({ e: e, s: local({ name: name }) + " = " + code + ";" });
      e = e$64;
      break $m35$match;
    }
    if ($m35.tag === "Return") {
      const value = $m35.value;
      const [$r38, e$65] = expr({ fuel: $rt.int.sub(fuel, 1, $ob8), e: e, ctx: ctx, x: value });
      e = e$65;
      const code = $r38.code;
      let inouts = [];
      if (e.fn_ctx.tag === "Some") {
        inouts = fn_ctx_or({ o: e.fn_ctx }).inout_names;
      }
      if ($std_list.len({ xs: inouts }) === 0) {
        const [, e$66] = line({ e: e, s: "return " + code + ";" });
        e = e$66;
      } else {
        let tail = "";
        for (const n of inouts) {
          tail = tail + ", " + local({ name: n });
        }
        const [, e$67] = line({ e: e, s: "return [" + code + tail + "];" });
        e = e$67;
      }
      break $m35$match;
    }
    if ($m35.tag === "If") {
      const cond = $m35.cond;
      const then_block = $m35.then_block;
      const else_block = $m35.else_block;
      const [$r39, e$68] = expr({ fuel: $rt.int.sub(fuel, 1, $ob9), e: e, ctx: ctx, x: cond });
      e = e$68;
      const c = $r39.code;
      const [, e$69] = line({ e: e, s: "if (" + c + ") {" });
      e = e$69;
      const [, e$70] = indent({ e: e });
      e = e$70;
      const [, e$71] = block({ fuel: $rt.int.sub(fuel, 1, $ob10), e: e, ctx: ctx, b: then_block });
      e = e$71;
      const [, e$72] = dedent({ e: e });
      e = e$72;
      const $m40 = else_block;
      $m40$match: {
        if ($m40.tag === "Some") {
          const value = $m40.value;
          const [, e$73] = line({ e: e, s: "} else {" });
          e = e$73;
          const [, e$74] = indent({ e: e });
          e = e$74;
          const [, e$75] = block({ fuel: $rt.int.sub(fuel, 1, $ob11), e: e, ctx: ctx, b: value });
          e = e$75;
          const [, e$76] = dedent({ e: e });
          e = e$76;
          const [, e$77] = line({ e: e, s: "}" });
          e = e$77;
          break $m40$match;
        }
        if ($m40.tag === "None") {
          const [, e$78] = line({ e: e, s: "}" });
          e = e$78;
          break $m40$match;
        }
        $rt.unreachable();
      }
      break $m35$match;
    }
    if ($m35.tag === "Match") {
      const tmp = $m35.tmp;
      const scrutinee = $m35.scrutinee;
      const arms = $m35.arms;
      const [$r41, e$79] = expr({ fuel: $rt.int.sub(fuel, 1, $ob12), e: e, ctx: ctx, x: scrutinee });
      e = e$79;
      const sc = $r41.code;
      const [, e$80] = line({ e: e, s: "const " + tmp + " = " + sc + ";" });
      e = e$80;
      const label = tmp + "$match";
      const [, e$81] = line({ e: e, s: label + ": {" });
      e = e$81;
      const [, e$82] = indent({ e: e });
      e = e$82;
      for (const arm of arms) {
        let test = "true";
        const $m42 = arm.pattern_test;
        $m42$match: {
          if ($m42.tag === "Some") {
            const value = $m42.value;
            const [$r43, e$83] = expr({ fuel: $rt.int.sub(fuel, 1, $ob13), e: e, ctx: ctx, x: value });
            e = e$83;
            test = $r43.code;
            break $m42$match;
          }
          if ($m42.tag === "None") {
            skip({  });
            break $m42$match;
          }
          $rt.unreachable();
        }
        const [, e$84] = line({ e: e, s: "if (" + test + ") {" });
        e = e$84;
        const [, e$85] = indent({ e: e });
        e = e$85;
        for (const bd of arm.bindings) {
          const [$r44, e$86] = expr({ fuel: $rt.int.sub(fuel, 1, $ob14), e: e, ctx: ctx, x: bd.value });
          e = e$86;
          const v = $r44.code;
          const [, e$87] = line({ e: e, s: "const " + local({ name: bd.name }) + " = " + v + ";" });
          e = e$87;
        }
        const $m45 = arm.guard;
        $m45$match: {
          if ($m45.tag === "Some") {
            const value = $m45.value;
            const [$r46, e$88] = expr({ fuel: $rt.int.sub(fuel, 1, $ob15), e: e, ctx: ctx, x: value });
            e = e$88;
            const g = $r46.code;
            const [, e$89] = line({ e: e, s: "if (" + g + ") {" });
            e = e$89;
            const [, e$90] = indent({ e: e });
            e = e$90;
            const [, e$91] = block({ fuel: $rt.int.sub(fuel, 1, $ob16), e: e, ctx: ctx, b: arm.body });
            e = e$91;
            const [, e$92] = line({ e: e, s: "break " + label + ";" });
            e = e$92;
            const [, e$93] = dedent({ e: e });
            e = e$93;
            const [, e$94] = line({ e: e, s: "}" });
            e = e$94;
            break $m45$match;
          }
          if ($m45.tag === "None") {
            const [, e$95] = block({ fuel: $rt.int.sub(fuel, 1, $ob17), e: e, ctx: ctx, b: arm.body });
            e = e$95;
            const [, e$96] = line({ e: e, s: "break " + label + ";" });
            e = e$96;
            break $m45$match;
          }
          $rt.unreachable();
        }
        const [, e$97] = dedent({ e: e });
        e = e$97;
        const [, e$98] = line({ e: e, s: "}" });
        e = e$98;
      }
      const [, e$99] = line({ e: e, s: "$rt.unreachable();" });
      e = e$99;
      const [, e$100] = dedent({ e: e });
      e = e$100;
      const [, e$101] = line({ e: e, s: "}" });
      e = e$101;
      break $m35$match;
    }
    if ($m35.tag === "Loop") {
      const cond = $m35.cond;
      const body = $m35.body;
      const [$r47, e$102] = expr({ fuel: $rt.int.sub(fuel, 1, $ob18), e: e, ctx: ctx, x: cond });
      e = e$102;
      const c = $r47.code;
      const [, e$103] = line({ e: e, s: "while (" + c + ") {" });
      e = e$103;
      const [, e$104] = indent({ e: e });
      e = e$104;
      const [, e$105] = block({ fuel: $rt.int.sub(fuel, 1, $ob19), e: e, ctx: ctx, b: body });
      e = e$105;
      const [, e$106] = dedent({ e: e });
      e = e$106;
      const [, e$107] = line({ e: e, s: "}" });
      e = e$107;
      break $m35$match;
    }
    if ($m35.tag === "ForRange") {
      const name = $m35.name;
      const lo = $m35.lo;
      const hi = $m35.hi;
      const body = $m35.body;
      const n = local({ name: name });
      const [$r48, e$108] = expr({ fuel: $rt.int.sub(fuel, 1, $ob20), e: e, ctx: ctx, x: lo });
      e = e$108;
      const lo_c = $r48.code;
      const [$r49, e$109] = expr({ fuel: $rt.int.sub(fuel, 1, $ob21), e: e, ctx: ctx, x: hi });
      e = e$109;
      const hi_c = at({ p: $r49, min: p_cmp + 1 });
      const [, e$110] = line({ e: e, s: "for (let " + n + " = " + lo_c + "; " + n + " < " + hi_c + "; " + n + "++) {" });
      e = e$110;
      const [, e$111] = indent({ e: e });
      e = e$111;
      const [, e$112] = block({ fuel: $rt.int.sub(fuel, 1, $ob22), e: e, ctx: ctx, b: body });
      e = e$112;
      const [, e$113] = dedent({ e: e });
      e = e$113;
      const [, e$114] = line({ e: e, s: "}" });
      e = e$114;
      break $m35$match;
    }
    if ($m35.tag === "ForEach") {
      const name = $m35.name;
      const list = $m35.list;
      const body = $m35.body;
      const [$r50, e$115] = expr({ fuel: $rt.int.sub(fuel, 1, $ob23), e: e, ctx: ctx, x: list });
      e = e$115;
      const l = $r50.code;
      const [, e$116] = line({ e: e, s: "for (const " + local({ name: name }) + " of " + l + ") {" });
      e = e$116;
      const [, e$117] = indent({ e: e });
      e = e$117;
      const [, e$118] = block({ fuel: $rt.int.sub(fuel, 1, $ob24), e: e, ctx: ctx, b: body });
      e = e$118;
      const [, e$119] = dedent({ e: e });
      e = e$119;
      const [, e$120] = line({ e: e, s: "}" });
      e = e$120;
      break $m35$match;
    }
    if ($m35.tag === "Check") {
      const cond = $m35.cond;
      const ob = $m35.ob;
      const [$r51, e$121] = expr({ fuel: $rt.int.sub(fuel, 1, $ob25), e: e, ctx: ctx, x: cond });
      e = e$121;
      const c = $r51.code;
      const [$r52, e$122] = ob_ref({ e: e, o: ob });
      e = e$122;
      const r = $r52;
      const [, e$123] = line({ e: e, s: "$rt.check(" + c + ", " + r + ");" });
      e = e$123;
      break $m35$match;
    }
    if ($m35.tag === "Assert") {
      const cond = $m35.cond;
      const [$r53, e$124] = expr({ fuel: $rt.int.sub(fuel, 1, $ob26), e: e, ctx: ctx, x: cond });
      e = e$124;
      const c = $r53.code;
      if (e.assert_mode === "expect") {
        const [, e$125] = line({ e: e, s: "expect(" + c + ").toBe(true);" });
        e = e$125;
      } else {
        const [, e$126] = line({ e: e, s: "if (!(" + c + ")) return false;" });
        e = e$126;
      }
      break $m35$match;
    }
    if ($m35.tag === "ExprStmt") {
      const expr = $m35.expr;
      const [$r54, e$127] = expr_code({ fuel: $rt.int.sub(fuel, 1, $ob27), e: e, ctx: ctx, x: expr });
      e = e$127;
      const code = $r54;
      if (code !== "") {
        const [, e$128] = line({ e: e, s: code + ";" });
        e = e$128;
      }
      break $m35$match;
    }
    if ($m35.tag === "CallInout") {
      const result_target = $m35.result_target;
      const call = $m35.call;
      const targets = $m35.targets;
      let names = $std_list.builder({  });
      for (const t of targets) {
        const [, names$129] = $std_list.push({ b: names, x: local({ name: t.name }) });
        names = names$129;
      }
      e = { ...e, inout_seq: $rt.int.add(e.inout_seq, 1, $ob28) };
      const seq = $std_int.to_text({ x: e.inout_seq });
      let tmps = $std_list.builder({  });
      for (const n of $std_list.finish({ b: names })) {
        const [, tmps$130] = $std_list.push({ b: tmps, x: n + "$" + seq });
        tmps = tmps$130;
      }
      let head = "";
      const $m56 = result_target;
      $m56$match: {
        if ($m56.tag === "Some") {
          const value = $m56.value;
          head = local({ name: value.name });
          break $m56$match;
        }
        if ($m56.tag === "None") {
          skip({  });
          break $m56$match;
        }
        $rt.unreachable();
      }
      const [$r57, e$131] = expr({ fuel: $rt.int.sub(fuel, 1, $ob29), e: e, ctx: ctx, x: call });
      e = e$131;
      const c = $r57.code;
      const [, e$132] = line({ e: e, s: "const [" + head + ", " + $std_text.join({ parts: $std_list.finish({ b: tmps }), sep: ", " }) + "] = " + c + ";" });
      e = e$132;
      let i = 0;
      const tmp_list = $std_list.finish({ b: tmps });
      for (const n of $std_list.finish({ b: names })) {
        let t = n;
        if (i < $std_list.len({ xs: tmp_list })) {
          t = $std_list.get({ xs: tmp_list, i: i });
        }
        const [, e$133] = line({ e: e, s: n + " = " + t + ";" });
        e = e$133;
        i = $rt.int.add(i, 1, $ob30);
      }
      break $m35$match;
    }
    if ($m35.tag === "Unreachable") {
      const [, e$134] = line({ e: e, s: "$rt.unreachable();" });
      e = e$134;
      break $m35$match;
    }
    if ($m35.tag === "Comment") {
      const text = $m35.text;
      const [, e$135] = line({ e: e, s: "// " + text });
      e = e$135;
      break $m35$match;
    }
    if ($m35.tag === "Reject") {
      const cond = $m35.cond;
      const column = $m35.column;
      const [$r58, e$136] = expr({ fuel: $rt.int.sub(fuel, 1, $ob31), e: e, ctx: ctx, x: cond });
      e = e$136;
      const c = $r58.code;
      const [, e$137] = line({ e: e, s: "if (!(" + c + ")) throw new $rt.sql.Rejected($row, " + $json.quote({ t: column }) + ");" });
      e = e$137;
      break $m35$match;
    }
    $rt.unreachable();
  }
  return [undefined, e];
  return [undefined, e];
}

export function fn_ctx_or({ o }) {
  const $m59 = o;
  $m59$match: {
    if ($m59.tag === "Some") {
      const value = $m59.value;
      return value;
      break $m59$match;
    }
    if ($m59.tag === "None") {
      return { inout_names: [], ret: { tag: "ErrorT" } };
      break $m59$match;
    }
    $rt.unreachable();
  }
}

export function expr_code({ fuel, e, ctx, x }) {
  if (fuel === 0) {
    return ["", e];
  }
  const [$r62, e$138] = expr({ fuel: $rt.int.sub(fuel, 1, $ob32), e: e, ctx: ctx, x: x });
  e = e$138;
  return [$r62.code, e];
}

export function decoder_code({ fuel, e, ctx, d }) {
  if (fuel === 0) {
    return ["", e];
  }
  const it_local = local({ name: d.it_name });
  let fields = $std_list.builder({  });
  for (const f of d.fields) {
    const [, fields$139] = $std_list.push({ b: fields, x: local({ name: f.name }) + ": $rt.sql.column(raw, " + $json.quote({ t: f.name }) + ", " + $json.quote({ t: f.kind }) + ", $row)" });
    fields = fields$139;
  }
  const [$r63, e$140] = inline({ fuel: $rt.int.sub(fuel, 1, $ob33), e: e, ctx: ctx, stmts: d.checks });
  e = e$140;
  const checks = $r63;
  return ["(raw, $row) => { const " + it_local + " = { " + $std_text.join({ parts: $std_list.finish({ b: fields }), sep: ", " }) + " }; " + checks + " return " + it_local + "; }", e];
}

export function inline({ fuel, e, ctx, stmts }) {
  if (fuel === 0) {
    return ["", e];
  }
  const outer = e.w;
  e = { ...e, w: new_writer({  }) };
  const [, e$141] = block({ fuel: $rt.int.sub(fuel, 1, $ob34), e: e, ctx: ctx, b: stmts });
  e = e$141;
  let parts = $std_list.builder({  });
  for (const l of $std_list.finish({ b: e.w.lines })) {
    const t = $std_text.trim({ t: l });
    if (t !== "") {
      const [, parts$142] = $std_list.push({ b: parts, x: t });
      parts = parts$142;
    }
  }
  e = { ...e, w: outer };
  return [$std_text.join({ parts: $std_list.finish({ b: parts }), sep: " " }), e];
}

export function exprs_code({ fuel, e, ctx, xs, min }) {
  if (fuel === 0) {
    return [[], e];
  }
  let out = $std_list.builder({  });
  for (const x of xs) {
    const [$r66, e$143] = expr({ fuel: $rt.int.sub(fuel, 1, $ob35), e: e, ctx: ctx, x: x });
    e = e$143;
    const [, out$144] = $std_list.push({ b: out, x: at({ p: $r66, min: min }) });
    out = out$144;
  }
  return [$std_list.finish({ b: out }), e];
}

export function inits_code({ fuel, e, ctx, fs }) {
  if (fuel === 0) {
    return [[], e];
  }
  let out = $std_list.builder({  });
  for (const f of fs) {
    const [$r67, e$145] = expr({ fuel: $rt.int.sub(fuel, 1, $ob36), e: e, ctx: ctx, x: f.value });
    e = e$145;
    const [, out$146] = $std_list.push({ b: out, x: local({ name: f.name }) + ": " + $r67.code });
    out = out$146;
  }
  return [$std_list.finish({ b: out }), e];
}

export function expr({ fuel, e, ctx, x }) {
  if (fuel === 0) {
    return [piece({ code: "undefined", prec: p_atom }), e];
  }
  const $m68 = x;
  $m68$match: {
    if ($m68.tag === "IntE") {
      const v = $m68.v;
      if (v < 0) {
        return [piece({ code: $std_int.to_text({ x: v }), prec: p_unary }), e];
      }
      return [piece({ code: $std_int.to_text({ x: v }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "FloatE") {
      const v = $m68.v;
      if (v < 0) {
        return [piece({ code: $std_float.to_text({ x: v }), prec: p_unary }), e];
      }
      return [piece({ code: $std_float.to_text({ x: v }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "TextE") {
      const v = $m68.v;
      return [piece({ code: $json.quote({ t: v }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "BoolE") {
      const v = $m68.v;
      return [piece({ code: $std_bool.to_text({ b: v }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "UnitE") {
      return [piece({ code: "undefined", prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "Local") {
      const name = $m68.name;
      return [piece({ code: local({ name: name }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "Global") {
      const def = $m68.def;
      const [$r69, e$147] = qualified({ e: e, ctx: ctx, mod: def.mod, name: def.name });
      e = e$147;
      return [piece({ code: $r69, prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "FnRef") {
      const def = $m68.def;
      const name = $m68.name;
      const sig = $m68.sig;
      let names = $std_list.builder({  });
      for (const p of sig.params) {
        const [, names$148] = $std_list.push({ b: names, x: local({ name: p.name }) });
        names = names$148;
      }
      const ns = $std_text.join({ parts: $std_list.finish({ b: names }), sep: ", " });
      const [$r70, e$149] = qualified({ e: e, ctx: ctx, mod: def.mod, name: name });
      e = e$149;
      return [piece({ code: "(" + ns + ") => " + $r70 + "({ " + ns + " })", prec: p_arrow }), e];
      break $m68$match;
    }
    if ($m68.tag === "Call") {
      const target = $m68.target;
      const sig = $m68.sig;
      const dicts = $m68.dicts;
      const consts = $m68.consts;
      const args = $m68.args;
      const decoder = $m68.decoder;
      let callee = "";
      const $m71 = target;
      $m71$match: {
        if ($m71.tag === "FnTarget") {
          const def = $m71.def;
          const name = $m71.name;
          const [$r72, e$150] = qualified({ e: e, ctx: ctx, mod: def.mod, name: name });
          e = e$150;
          callee = $r72;
          break $m71$match;
        }
        if ($m71.tag === "DictTarget") {
          const dict = $m71.dict;
          const name = $m71.name;
          const [$r73, e$151] = expr({ fuel: $rt.int.sub(fuel, 1, $ob37), e: e, ctx: ctx, x: dict });
          e = e$151;
          callee = at({ p: $r73, min: p_call }) + "." + local({ name: name });
          break $m71$match;
        }
        $rt.unreachable();
      }
      let parts = $std_list.builder({  });
      let di = 0;
      let ci = 0;
      for (const p of sig.tparams) {
        const $m74 = p;
        $m74$match: {
          if ($m74.tag === "TypeP") {
            const def = $m74.def;
            const bound = $m74.bound;
            if (bound.tag === "Some") {
              let d = { tag: "UnitE" };
              if (di < $std_list.len({ xs: dicts })) {
                d = $std_list.get({ xs: dicts, i: di });
              }
              const [$r76, e$152] = expr({ fuel: $rt.int.sub(fuel, 1, $ob38), e: e, ctx: ctx, x: d });
              e = e$152;
              const [, parts$153] = $std_list.push({ b: parts, x: "$dict_" + $context.get_def({ ctx: ctx, id: def }).name + ": " + $r76.code });
              parts = parts$153;
              di = $rt.int.add(di, 1, $ob39);
            }
            break $m74$match;
          }
          if ($m74.tag === "ConstP") {
            const def = $m74.def;
            let c = { tag: "UnitE" };
            if (ci < $std_list.len({ xs: consts })) {
              c = $std_list.get({ xs: consts, i: ci });
            }
            const [$r78, e$154] = expr({ fuel: $rt.int.sub(fuel, 1, $ob40), e: e, ctx: ctx, x: c });
            e = e$154;
            const [, parts$155] = $std_list.push({ b: parts, x: local({ name: $context.get_def({ ctx: ctx, id: def }).name }) + ": " + $r78.code });
            parts = parts$155;
            ci = $rt.int.add(ci, 1, $ob41);
            break $m74$match;
          }
          if (true) {
            skip({  });
            break $m74$match;
          }
          $rt.unreachable();
        }
      }
      let i = 0;
      for (const p of sig.params) {
        let a = { tag: "UnitE" };
        if (i < $std_list.len({ xs: args })) {
          a = $std_list.get({ xs: args, i: i });
        }
        const [$r80, e$156] = expr({ fuel: $rt.int.sub(fuel, 1, $ob42), e: e, ctx: ctx, x: a });
        e = e$156;
        const [, parts$157] = $std_list.push({ b: parts, x: local({ name: p.name }) + ": " + $r80.code });
        parts = parts$157;
        i = $rt.int.add(i, 1, $ob43);
      }
      const $m81 = decoder;
      $m81$match: {
        if ($m81.tag === "Some") {
          const value = $m81.value;
          const [$r82, e$158] = decoder_code({ fuel: $rt.int.sub(fuel, 1, $ob44), e: e, ctx: ctx, d: value });
          e = e$158;
          const [, parts$159] = $std_list.push({ b: parts, x: "$decode: " + $r82 });
          parts = parts$159;
          break $m81$match;
        }
        if ($m81.tag === "None") {
          skip({  });
          break $m81$match;
        }
        $rt.unreachable();
      }
      return [piece({ code: callee + "({ " + $std_text.join({ parts: $std_list.finish({ b: parts }), sep: ", " }) + " })", prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "CallValue") {
      const callee = $m68.callee;
      const args = $m68.args;
      const [$r83, e$160] = expr({ fuel: $rt.int.sub(fuel, 1, $ob45), e: e, ctx: ctx, x: callee });
      e = e$160;
      const c = at({ p: $r83, min: p_call });
      const [$r84, e$161] = exprs_code({ fuel: $rt.int.sub(fuel, 1, $ob46), e: e, ctx: ctx, xs: args, min: 0 });
      e = e$161;
      return [piece({ code: c + "(" + $std_text.join({ parts: $r84, sep: ", " }) + ")", prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "RecordE") {
      const fields = $m68.fields;
      const [$r85, e$162] = inits_code({ fuel: $rt.int.sub(fuel, 1, $ob47), e: e, ctx: ctx, fs: fields });
      e = e$162;
      return [piece({ code: "{ " + $std_text.join({ parts: $r85, sep: ", " }) + " }", prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "VariantE") {
      const def = $m68.def;
      const fields = $m68.fields;
      const [$r86, e$163] = inits_code({ fuel: $rt.int.sub(fuel, 1, $ob48), e: e, ctx: ctx, fs: fields });
      e = e$163;
      const rest = $r86;
      return [piece({ code: "{ " + $std_text.join({ parts: [...["tag: " + $json.quote({ t: def.name })], ...rest], sep: ", " }) + " }", prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "Update") {
      const base = $m68.base;
      const fields = $m68.fields;
      const [$r87, e$164] = expr({ fuel: $rt.int.sub(fuel, 1, $ob49), e: e, ctx: ctx, x: base });
      e = e$164;
      const b = at({ p: $r87, min: p_call });
      const [$r88, e$165] = inits_code({ fuel: $rt.int.sub(fuel, 1, $ob50), e: e, ctx: ctx, fs: fields });
      e = e$165;
      return [piece({ code: "{ ..." + b + ", " + $std_text.join({ parts: $r88, sep: ", " }) + " }", prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "FieldE") {
      const object = $m68.object;
      const name = $m68.name;
      const [$r89, e$166] = expr({ fuel: $rt.int.sub(fuel, 1, $ob51), e: e, ctx: ctx, x: object });
      e = e$166;
      return [piece({ code: at({ p: $r89, min: p_call }) + "." + local({ name: name }), prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "ListE") {
      const elems = $m68.elems;
      const [$r90, e$167] = exprs_code({ fuel: $rt.int.sub(fuel, 1, $ob52), e: e, ctx: ctx, xs: elems, min: 0 });
      e = e$167;
      return [piece({ code: "[" + $std_text.join({ parts: $r90, sep: ", " }) + "]", prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "Concat") {
      const left = $m68.left;
      const right = $m68.right;
      const is_text = $m68.is_text;
      const [$r91, e$168] = expr({ fuel: $rt.int.sub(fuel, 1, $ob53), e: e, ctx: ctx, x: left });
      e = e$168;
      const l = $r91;
      const [$r92, e$169] = expr({ fuel: $rt.int.sub(fuel, 1, $ob54), e: e, ctx: ctx, x: right });
      e = e$169;
      const r = $r92;
      if (is_text) {
        return [piece({ code: at({ p: l, min: p_add }) + " + " + at({ p: r, min: p_add + 1 }), prec: p_add }), e];
      }
      return [piece({ code: "[..." + at({ p: l, min: p_call }) + ", ..." + at({ p: r, min: p_call }) + "]", prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "IntOp") {
      const op = $m68.op;
      const left = $m68.left;
      const right = $m68.right;
      const ob = $m68.ob;
      const [$r93, e$170] = expr({ fuel: $rt.int.sub(fuel, 1, $ob55), e: e, ctx: ctx, x: left });
      e = e$170;
      const l = $r93;
      const [$r94, e$171] = expr({ fuel: $rt.int.sub(fuel, 1, $ob56), e: e, ctx: ctx, x: right });
      e = e$171;
      const r = $r94;
      const $m95 = ob;
      $m95$match: {
        if ($m95.tag === "Some") {
          const value = $m95.value;
          let fn_name = "add";
          if (op === "-") {
            fn_name = "sub";
          }
          if (op === "*") {
            fn_name = "mul";
          }
          if (op === "/") {
            fn_name = "div";
          }
          if (op === "%") {
            fn_name = "rem";
          }
          const [$r96, e$172] = ob_ref({ e: e, o: value });
          e = e$172;
          return [piece({ code: "$rt.int." + fn_name + "(" + l.code + ", " + r.code + ", " + $r96 + ")", prec: p_call }), e];
          break $m95$match;
        }
        if ($m95.tag === "None") {
          skip({  });
          break $m95$match;
        }
        $rt.unreachable();
      }
      if (op === "/") {
        return [piece({ code: "Math.trunc(" + at({ p: l, min: p_mul }) + " / " + at({ p: r, min: p_mul + 1 }) + ")", prec: p_call }), e];
      }
      let prec = p_mul;
      if (op === "+" || op === "-") {
        prec = p_add;
      }
      return [piece({ code: at({ p: l, min: prec }) + " " + op + " " + at({ p: r, min: prec + 1 }), prec: prec }), e];
      break $m68$match;
    }
    if ($m68.tag === "FloatOp") {
      const op = $m68.op;
      const left = $m68.left;
      const right = $m68.right;
      let prec = p_mul;
      if (op === "+" || op === "-") {
        prec = p_add;
      }
      const [$r97, e$173] = expr({ fuel: $rt.int.sub(fuel, 1, $ob57), e: e, ctx: ctx, x: left });
      e = e$173;
      const l = at({ p: $r97, min: prec });
      const [$r98, e$174] = expr({ fuel: $rt.int.sub(fuel, 1, $ob58), e: e, ctx: ctx, x: right });
      e = e$174;
      const r = at({ p: $r98, min: prec + 1 });
      return [piece({ code: l + " " + op + " " + r, prec: prec }), e];
      break $m68$match;
    }
    if ($m68.tag === "Neg") {
      const operand = $m68.operand;
      const ob = $m68.ob;
      const [$r99, e$175] = expr({ fuel: $rt.int.sub(fuel, 1, $ob59), e: e, ctx: ctx, x: operand });
      e = e$175;
      const v = $r99;
      const $m100 = ob;
      $m100$match: {
        if ($m100.tag === "Some") {
          const value = $m100.value;
          const [$r101, e$176] = ob_ref({ e: e, o: value });
          e = e$176;
          return [piece({ code: "$rt.int.neg(" + v.code + ", " + $r101 + ")", prec: p_call }), e];
          break $m100$match;
        }
        if ($m100.tag === "None") {
          return [piece({ code: "-" + at({ p: v, min: p_unary }), prec: p_unary }), e];
          break $m100$match;
        }
        $rt.unreachable();
      }
      break $m68$match;
    }
    if ($m68.tag === "Cmp") {
      const op = $m68.op;
      const left = $m68.left;
      const right = $m68.right;
      const [$r102, e$177] = expr({ fuel: $rt.int.sub(fuel, 1, $ob60), e: e, ctx: ctx, x: left });
      e = e$177;
      const l = at({ p: $r102, min: p_cmp + 1 });
      const [$r103, e$178] = expr({ fuel: $rt.int.sub(fuel, 1, $ob61), e: e, ctx: ctx, x: right });
      e = e$178;
      const r = at({ p: $r103, min: p_cmp + 1 });
      return [piece({ code: l + " " + op + " " + r, prec: p_cmp }), e];
      break $m68$match;
    }
    if ($m68.tag === "Eq") {
      const left = $m68.left;
      const right = $m68.right;
      const prim = $m68.prim;
      const negate = $m68.negate;
      const [$r104, e$179] = expr({ fuel: $rt.int.sub(fuel, 1, $ob62), e: e, ctx: ctx, x: left });
      e = e$179;
      const l = $r104;
      const [$r105, e$180] = expr({ fuel: $rt.int.sub(fuel, 1, $ob63), e: e, ctx: ctx, x: right });
      e = e$180;
      const r = $r105;
      if (prim) {
        let op = "===";
        if (negate) {
          op = "!==";
        }
        return [piece({ code: at({ p: l, min: p_eq + 1 }) + " " + op + " " + at({ p: r, min: p_eq + 1 }), prec: p_eq }), e];
      }
      const eq = "$rt.eq(" + l.code + ", " + r.code + ")";
      if (negate) {
        return [piece({ code: "!" + eq, prec: p_unary }), e];
      }
      return [piece({ code: eq, prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "Not") {
      const operand = $m68.operand;
      const [$r106, e$181] = expr({ fuel: $rt.int.sub(fuel, 1, $ob64), e: e, ctx: ctx, x: operand });
      e = e$181;
      return [piece({ code: "!" + at({ p: $r106, min: p_unary }), prec: p_unary }), e];
      break $m68$match;
    }
    if ($m68.tag === "And") {
      const operands = $m68.operands;
      const [$r107, e$182] = exprs_code({ fuel: $rt.int.sub(fuel, 1, $ob65), e: e, ctx: ctx, xs: operands, min: p_and + 1 });
      e = e$182;
      return [piece({ code: $std_text.join({ parts: $r107, sep: " && " }), prec: p_and }), e];
      break $m68$match;
    }
    if ($m68.tag === "Or") {
      const operands = $m68.operands;
      const [$r108, e$183] = exprs_code({ fuel: $rt.int.sub(fuel, 1, $ob66), e: e, ctx: ctx, xs: operands, min: p_or + 1 });
      e = e$183;
      return [piece({ code: $std_text.join({ parts: $r108, sep: " || " }), prec: p_or }), e];
      break $m68$match;
    }
    if ($m68.tag === "Implies") {
      const left = $m68.left;
      const right = $m68.right;
      const [$r109, e$184] = expr({ fuel: $rt.int.sub(fuel, 1, $ob67), e: e, ctx: ctx, x: left });
      e = e$184;
      const l = at({ p: $r109, min: p_unary });
      const [$r110, e$185] = expr({ fuel: $rt.int.sub(fuel, 1, $ob68), e: e, ctx: ctx, x: right });
      e = e$185;
      const r = at({ p: $r110, min: p_or + 1 });
      return [piece({ code: "!" + l + " || " + r, prec: p_or }), e];
      break $m68$match;
    }
    if ($m68.tag === "IsVariant") {
      const subject = $m68.subject;
      const variant = $m68.variant;
      const [$r111, e$186] = expr({ fuel: $rt.int.sub(fuel, 1, $ob69), e: e, ctx: ctx, x: subject });
      e = e$186;
      return [piece({ code: at({ p: $r111, min: p_call }) + ".tag === " + $json.quote({ t: variant.name }), prec: p_eq }), e];
      break $m68$match;
    }
    if ($m68.tag === "Try") {
      const operand = $m68.operand;
      const option = $m68.option;
      const outer_option = $m68.outer_option;
      const else_clause = $m68.else_clause;
      const raw = $m68.raw;
      const [$r112, e$187] = expr({ fuel: $rt.int.sub(fuel, 1, $ob70), e: e, ctx: ctx, x: operand });
      e = e$187;
      const op = $r112.code;
      const $m113 = else_clause;
      $m113$match: {
        if ($m113.tag === "None") {
          if (option && outer_option) {
            return [piece({ code: "$rt.unwrapOption(" + op + ")", prec: p_call }), e];
          }
          return [piece({ code: "$rt.unwrap(" + op + ")", prec: p_call }), e];
          break $m113$match;
        }
        if ($m113.tag === "Some") {
          const value = $m113.value;
          const name = local({ name: text_or({ o: value.name, dflt: "_" }) });
          const [$r114, e$188] = expr({ fuel: $rt.int.sub(fuel, 1, $ob71), e: e, ctx: ctx, x: value.value });
          e = e$188;
          const raw_code = $r114.code;
          let body = raw_code;
          if ($std_text.starts_with({ t: raw_code, prefix: "{" })) {
            body = "(" + raw_code + ")";
          }
          if (raw) {
            let f = "unwrapOr";
            if (option) {
              f = "unwrapOptionOr";
            }
            return [piece({ code: "$rt." + f + "(" + op + ", (" + name + ") => " + body + ")", prec: p_call }), e];
          }
          if (option) {
            return [piece({ code: "$rt.unwrapOptionElse(" + op + ", (" + name + ") => " + body + ")", prec: p_call }), e];
          }
          return [piece({ code: "$rt.unwrapElse(" + op + ", (" + name + ") => " + body + ")", prec: p_call }), e];
          break $m113$match;
        }
        $rt.unreachable();
      }
      break $m68$match;
    }
    if ($m68.tag === "Recover") {
      const body = $m68.body;
      const value = $m68.value;
      const saved = e.fn_ctx;
      if (saved.tag === "Some") {
        e = { ...e, fn_ctx: { tag: "Some", value: { inout_names: [], ret: { tag: "ErrorT" } } } };
      }
      const outer = e.w;
      e = { ...e, w: new_writer({  }) };
      const [, e$189] = indent({ e: e });
      e = e$189;
      const [, e$190] = block({ fuel: $rt.int.sub(fuel, 1, $ob72), e: e, ctx: ctx, b: body });
      e = e$190;
      const [$r120, e$191] = expr({ fuel: $rt.int.sub(fuel, 1, $ob73), e: e, ctx: ctx, x: value });
      e = e$191;
      const v = $r120.code;
      const [, e$192] = line({ e: e, s: "return " + v + ";" });
      e = e$192;
      const text = writer_text({ w: e.w });
      e = { ...e, w: outer, fn_ctx: saved };
      return [piece({ code: "$rt.recover(() => {\n" + text + "\n})", prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "Quantifier") {
      const quant = $m68.quant;
      const name = $m68.name;
      const domain = $m68.domain;
      const where_ = $m68.where_;
      const body = $m68.body;
      let dom = "[true, false]";
      const $m122 = domain;
      $m122$match: {
        if ($m122.tag === "BoolsD") {
          dom = "[true, false]";
          break $m122$match;
        }
        if ($m122.tag === "RangeD") {
          const lo = $m122.lo;
          const hi = $m122.hi;
          const [$r123, e$193] = expr({ fuel: $rt.int.sub(fuel, 1, $ob74), e: e, ctx: ctx, x: lo });
          e = e$193;
          const [$r124, e$194] = expr({ fuel: $rt.int.sub(fuel, 1, $ob75), e: e, ctx: ctx, x: hi });
          e = e$194;
          dom = "$rt.range(" + $r123.code + ", " + $r124.code + ")";
          break $m122$match;
        }
        if ($m122.tag === "ListD") {
          const expr = $m122.expr;
          const [$r125, e$195] = expr_code({ fuel: $rt.int.sub(fuel, 1, $ob76), e: e, ctx: ctx, x: expr });
          e = e$195;
          dom = $r125;
          break $m122$match;
        }
        if ($m122.tag === "OkListD") {
          const expr = $m122.expr;
          const [$r126, e$196] = expr_code({ fuel: $rt.int.sub(fuel, 1, $ob77), e: e, ctx: ctx, x: expr });
          e = e$196;
          dom = "$rt.okList(" + $r126 + ")";
          break $m122$match;
        }
        $rt.unreachable();
      }
      let body_code = "";
      const $m127 = where_;
      $m127$match: {
        if ($m127.tag === "None") {
          const [$r128, e$197] = expr({ fuel: $rt.int.sub(fuel, 1, $ob78), e: e, ctx: ctx, x: body });
          e = e$197;
          body_code = $r128.code;
          break $m127$match;
        }
        if ($m127.tag === "Some") {
          const value = $m127.value;
          let dflt = "false";
          if (quant === "forall") {
            dflt = "true";
          }
          const [$r129, e$198] = expr({ fuel: $rt.int.sub(fuel, 1, $ob79), e: e, ctx: ctx, x: value });
          e = e$198;
          const [$r130, e$199] = expr({ fuel: $rt.int.sub(fuel, 1, $ob80), e: e, ctx: ctx, x: body });
          e = e$199;
          body_code = at({ p: $r129, min: p_or + 1 }) + " ? " + at({ p: $r130, min: p_arrow + 1 }) + " : " + dflt;
          break $m127$match;
        }
        $rt.unreachable();
      }
      return [piece({ code: "$rt." + quant + "(" + dom + ", (" + local({ name: name }) + ") => " + body_code + ")", prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "Closure") {
      const params = $m68.params;
      const fn_type = $m68.fn_type;
      const entry_checks = $m68.entry_checks;
      const body = $m68.body;
      const early_return = $m68.early_return;
      let names = $std_list.builder({  });
      let inouts = $std_list.builder({  });
      for (const p of params) {
        const [, names$200] = $std_list.push({ b: names, x: local({ name: p.name }) });
        names = names$200;
        if (p.is_inout) {
          const [, inouts$201] = $std_list.push({ b: inouts, x: p.name });
          inouts = inouts$201;
        }
      }
      let ret = { tag: "ErrorT" };
      const $m132 = fn_type;
      $m132$match: {
        if ($m132.tag === "Some") {
          const value = $m132.value;
          ret = $types.ret_of({ t: value });
          break $m132$match;
        }
        if ($m132.tag === "None") {
          skip({  });
          break $m132$match;
        }
        $rt.unreachable();
      }
      const saved = e.fn_ctx;
      e = { ...e, fn_ctx: { tag: "Some", value: { inout_names: $std_list.finish({ b: inouts }), ret: ret } } };
      const outer = e.w;
      e = { ...e, w: new_writer({  }) };
      const [, e$202] = indent({ e: e });
      e = e$202;
      const [, e$203] = block({ fuel: $rt.int.sub(fuel, 1, $ob81), e: e, ctx: ctx, b: entry_checks });
      e = e$203;
      const [, e$204] = early_open({ e: e, early: early_return });
      e = e$204;
      const [, e$205] = block({ fuel: $rt.int.sub(fuel, 1, $ob82), e: e, ctx: ctx, b: body });
      e = e$205;
      const [, e$206] = early_close({ e: e, early: early_return });
      e = e$206;
      const text = writer_text({ w: e.w });
      e = { ...e, w: outer, fn_ctx: saved };
      return [piece({ code: "(" + $std_text.join({ parts: $std_list.finish({ b: names }), sep: ", " }) + ") => {\n" + text + "\n}", prec: p_arrow }), e];
      break $m68$match;
    }
    if ($m68.tag === "Fake") {
      const kind = $m68.kind;
      const fields = $m68.fields;
      const [$r138, e$207] = inits_code({ fuel: $rt.int.sub(fuel, 1, $ob83), e: e, ctx: ctx, fs: fields });
      e = e$207;
      return [piece({ code: "$rt.Capability.__fake(" + $json.quote({ t: kind }) + ", { " + $std_text.join({ parts: $r138, sep: ", " }) + " }, $rt.FAKE_TOKEN)", prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "Checked") {
      const value = $m68.value;
      const it_name = $m68.it_name;
      const checks = $m68.checks;
      const [$r139, e$208] = expr({ fuel: $rt.int.sub(fuel, 1, $ob84), e: e, ctx: ctx, x: value });
      e = e$208;
      const v = $r139.code;
      const [$r140, e$209] = inline({ fuel: $rt.int.sub(fuel, 1, $ob85), e: e, ctx: ctx, stmts: checks });
      e = e$209;
      const cs = $r140;
      return [piece({ code: "$rt.checked(" + v + ", (" + it_name + ") => { " + cs + " })", prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "TypeInfoE") {
      const name = $m68.name;
      const fields = $m68.fields;
      let fs = $std_list.builder({  });
      for (const f of fields) {
        const [, fs$210] = $std_list.push({ b: fs, x: "{ name: " + $json.quote({ t: f.name }) + ", type_name: " + $json.quote({ t: f.type_name }) + " }" });
        fs = fs$210;
      }
      return [piece({ code: "$rt.typeInfo(" + $json.quote({ t: name }) + ", [" + $std_text.join({ parts: $std_list.finish({ b: fs }), sep: ", " }) + "])", prec: p_call }), e];
      break $m68$match;
    }
    if ($m68.tag === "ConstE") {
      const value = $m68.value;
      return [piece({ code: const_literal({ ctx: ctx, c: value }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "ValueE") {
      const value = $m68.value;
      return [piece({ code: value_literal({ fuel: $rt.int.sub(fuel, 1, $ob86), ctx: ctx, val: value }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "DictE") {
      const mod = $m68.mod;
      const name = $m68.name;
      if (mod === e.m.id && e.self_alias.tag === "None") {
        return [piece({ code: local({ name: name }), prec: p_atom }), e];
      }
      const [$r141, e$211] = alias({ e: e, ctx: ctx, id: mod });
      e = e$211;
      return [piece({ code: $r141 + "." + local({ name: name }), prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "DictParamE") {
      const name = $m68.name;
      return [piece({ code: name, prec: p_atom }), e];
      break $m68$match;
    }
    if ($m68.tag === "Snapshot") {
      const value = $m68.value;
      const [$r142, e$212] = expr({ fuel: $rt.int.sub(fuel, 1, $ob87), e: e, ctx: ctx, x: value });
      e = e$212;
      return [piece({ code: "$rt.snapshot(" + $r142.code + ")", prec: p_call }), e];
      break $m68$match;
    }
    $rt.unreachable();
  }
}

export function const_literal({ ctx, c }) {
  const $m143 = c;
  $m143$match: {
    if ($m143.tag === "IntV") {
      const v = $m143.v;
      return $std_int.to_text({ x: v });
      break $m143$match;
    }
    if ($m143.tag === "DurationV") {
      const v = $m143.v;
      return $std_int.to_text({ x: v });
      break $m143$match;
    }
    if ($m143.tag === "FloatV") {
      const v = $m143.v;
      return $std_float.to_text({ x: v });
      break $m143$match;
    }
    if ($m143.tag === "BoolV") {
      const v = $m143.v;
      return $std_bool.to_text({ b: v });
      break $m143$match;
    }
    if ($m143.tag === "TextV") {
      const v = $m143.v;
      return $json.quote({ t: v });
      break $m143$match;
    }
    if ($m143.tag === "UnitV") {
      return "undefined";
      break $m143$match;
    }
    if ($m143.tag === "VariantV") {
      const def = $m143.def;
      return "{ tag: " + $json.quote({ t: $context.get_def({ ctx: ctx, id: def }).name }) + " }";
      break $m143$match;
    }
    if ($m143.tag === "SymV") {
      const def = $m143.def;
      return local({ name: $context.get_def({ ctx: ctx, id: def }).name });
      break $m143$match;
    }
    if ($m143.tag === "ErrorV") {
      return "undefined";
      break $m143$match;
    }
    $rt.unreachable();
  }
}

export function value_literal({ fuel, ctx, val }) {
  if (fuel === 0) {
    return "undefined";
  }
  const $m144 = val;
  $m144$match: {
    if ($m144.tag === "IntV") {
      const v = $m144.v;
      return $std_int.to_text({ x: v });
      break $m144$match;
    }
    if ($m144.tag === "FloatV") {
      const v = $m144.v;
      return $std_float.to_text({ x: v });
      break $m144$match;
    }
    if ($m144.tag === "DurationV") {
      const v = $m144.v;
      return $std_int.to_text({ x: v });
      break $m144$match;
    }
    if ($m144.tag === "BoolV") {
      const v = $m144.v;
      return $std_bool.to_text({ b: v });
      break $m144$match;
    }
    if ($m144.tag === "TextV") {
      const v = $m144.v;
      return $json.quote({ t: v });
      break $m144$match;
    }
    if ($m144.tag === "UnitV") {
      return "undefined";
      break $m144$match;
    }
    if ($m144.tag === "BytesV") {
      const bytes = $m144.bytes;
      let parts = $std_list.builder({  });
      for (const b of bytes) {
        const [, parts$213] = $std_list.push({ b: parts, x: $std_int.to_text({ x: b }) });
        parts = parts$213;
      }
      return "new Uint8Array([" + $std_text.join({ parts: $std_list.finish({ b: parts }), sep: ", " }) + "])";
      break $m144$match;
    }
    if ($m144.tag === "ListV") {
      const items = $m144.items;
      let parts = $std_list.builder({  });
      for (const item of items) {
        const [, parts$214] = $std_list.push({ b: parts, x: value_literal({ fuel: $rt.int.sub(fuel, 1, $ob88), ctx: ctx, val: item }) });
        parts = parts$214;
      }
      return "[" + $std_text.join({ parts: $std_list.finish({ b: parts }), sep: ", " }) + "]";
      break $m144$match;
    }
    if ($m144.tag === "RecordV") {
      const fields = $m144.fields;
      return "{ " + $std_text.join({ parts: value_fields({ fuel: $rt.int.sub(fuel, 1, $ob89), ctx: ctx, fields: fields }), sep: ", " }) + " }";
      break $m144$match;
    }
    if ($m144.tag === "VariantV") {
      const def = $m144.def;
      const fields = $m144.fields;
      const parts = [...["tag: " + $json.quote({ t: $context.get_def({ ctx: ctx, id: def }).name })], ...value_fields({ fuel: $rt.int.sub(fuel, 1, $ob90), ctx: ctx, fields: fields })];
      return "{ " + $std_text.join({ parts: parts, sep: ", " }) + " }";
      break $m144$match;
    }
    if ($m144.tag === "TypeInfoV") {
      const owner = $m144.owner;
      const $m145 = owner;
      $m145$match: {
        if ($m145.tag === "PrimOwner") {
          const name = $m145.name;
          return "$rt.typeInfo(" + $json.quote({ t: name }) + ", [])";
          break $m145$match;
        }
        if ($m145.tag === "DefOwner") {
          const def = $m145.def;
          let fs = $std_list.builder({  });
          const $m146 = $std_map.find({ d: ctx.fields, key: def });
          $m146$match: {
            if ($m146.tag === "Some") {
              const value = $m146.value;
              for (const f of value) {
                const [, fs$215] = $std_list.push({ b: fs, x: "{ name: " + $json.quote({ t: f.name }) + ", type_name: " + $json.quote({ t: $lowerir.type_slug({ fuel: 1000, ctx: ctx, t: f.ty }) }) + " }" });
                fs = fs$215;
              }
              break $m146$match;
            }
            if ($m146.tag === "None") {
              skip({  });
              break $m146$match;
            }
            $rt.unreachable();
          }
          return "$rt.typeInfo(" + $json.quote({ t: $context.get_def({ ctx: ctx, id: def }).name }) + ", [" + $std_text.join({ parts: $std_list.finish({ b: fs }), sep: ", " }) + "])";
          break $m145$match;
        }
        $rt.unreachable();
      }
      break $m144$match;
    }
    $rt.unreachable();
  }
}

export function value_fields({ fuel, ctx, fields }) {
  if (fuel === 0) {
    return [];
  }
  let out = $std_list.builder({  });
  for (const f of fields) {
    const [, out$216] = $std_list.push({ b: out, x: local({ name: f.name }) + ": " + value_literal({ fuel: $rt.int.sub(fuel, 1, $ob91), ctx: ctx, val: f.value }) });
    out = out$216;
  }
  return $std_list.finish({ b: out });
}

export function tests_file({ e, ctx, tests }) {
  const outer = e.w;
  const saved_imports = copy_int_dict({ d: e.imports });
  const saved_decls = e.ob_decls;
  const saved_refs = copy_text_dict({ d: e.ob_refs });
  let fresh_imports = $std_map.dict({  });
  const [, fresh_imports$217] = $std_map.set({ d: fresh_imports, key: e.m.id, value: "$self" });
  fresh_imports = fresh_imports$217;
  const fresh_w = new_writer({  });
  e = { ...e, w: fresh_w, imports: fresh_imports, self_alias: { tag: "Some", value: "$self" }, ob_decls: [], ob_refs: $std_map.dict({  }), fn_ctx: { tag: "None" } };
  const [, e$218] = line({ e: e, s: "import { test, expect, afterAll } from 'vitest';" });
  e = e$218;
  const [, e$219] = line({ e: e, s: "import * as fc from 'fast-check';" });
  e = e$219;
  for (const ex of tests.examples) {
    e = { ...e, assert_mode: "expect" };
    const [, e$220] = line({ e: e, s: "test(" + $json.quote({ t: ex.name }) + ", () => {" });
    e = e$220;
    const [, e$221] = indent({ e: e });
    e = e$221;
    const [, e$222] = block({ fuel: max_depth, e: e, ctx: ctx, b: ex.body });
    e = e$222;
    const [, e$223] = dedent({ e: e });
    e = e$223;
    const [, e$224] = line({ e: e, s: "});" });
    e = e$224;
  }
  e = { ...e, assert_mode: "return-false" };
  for (const p of tests.properties) {
    let gens = $std_list.builder({  });
    let names = $std_list.builder({  });
    for (const gp of p.params) {
      const [$r152, e$225] = generator({ fuel: max_depth, e: e, ctx: ctx, g: gp.gen });
      e = e$225;
      const [, gens$226] = $std_list.push({ b: gens, x: $r152 });
      gens = gens$226;
      const [, names$227] = $std_list.push({ b: names, x: local({ name: gp.name }) });
      names = names$227;
    }
    const [, e$228] = line({ e: e, s: "test(" + $json.quote({ t: p.label }) + ", () => {" });
    e = e$228;
    const [, e$229] = indent({ e: e });
    e = e$229;
    const [, e$230] = line({ e: e, s: "fc.assert(fc.property(" + $std_text.join({ parts: $std_list.finish({ b: gens }), sep: ", " }) + ", (" + $std_text.join({ parts: $std_list.finish({ b: names }), sep: ", " }) + ") => {" });
    e = e$230;
    const [, e$231] = indent({ e: e });
    e = e$231;
    const [, e$232] = block({ fuel: max_depth, e: e, ctx: ctx, b: p.body });
    e = e$232;
    const [, e$233] = line({ e: e, s: "return true;" });
    e = e$233;
    const [, e$234] = dedent({ e: e });
    e = e$234;
    const [, e$235] = line({ e: e, s: "}));" });
    e = e$235;
    const [, e$236] = dedent({ e: e });
    e = e$236;
    const [, e$237] = line({ e: e, s: "});" });
    e = e$237;
  }
  let head = $std_list.builder({  });
  const [, head$238] = $std_list.push({ b: head, x: "// Generated by onus: tests of module " + e.m.name + "." });
  head = head$238;
  const [, head$239] = $std_list.push({ b: head, x: "import * as $rt from " + $json.quote({ t: e.opts.runtime }) + ";" });
  head = head$239;
  for (const id of $std_map.keys({ d: e.imports })) {
    let path = "";
    if (id === e.m.id) {
      let last = "";
      for (const seg of $std_text.split({ t: e.m.name, sep: "." })) {
        last = seg;
      }
      path = "./" + last + ".js";
    } else {
      path = relative_import({ e: e, ctx: ctx, id: id });
    }
    const [, head$240] = $std_list.push({ b: head, x: "import * as " + text_or({ o: $std_map.find({ d: e.imports, key: id }), dflt: "" }) + " from " + $json.quote({ t: path }) + ";" });
    head = head$240;
  }
  const [, head$241] = $std_list.push({ b: head, x: "" });
  head = head$241;
  for (const d of e.ob_decls) {
    const [, head$242] = $std_list.push({ b: head, x: d });
    head = head$242;
  }
  const [, e$243] = line({ e: e, s: "afterAll(() => $rt.coverage.flush());" });
  e = e$243;
  const text = $std_text.join({ parts: $std_list.finish({ b: head }), sep: "\n" }) + "\n" + writer_text({ w: e.w }) + "\n";
  e = { ...e, w: outer, self_alias: { tag: "None" }, imports: saved_imports, ob_decls: saved_decls, ob_refs: saved_refs };
  return [text, e];
}

export function generator({ fuel, e, ctx, g }) {
  if (fuel === 0) {
    return ["", e];
  }
  const [$r155, e$244] = base_generator({ fuel: $rt.int.sub(fuel, 1, $ob92), e: e, ctx: ctx, b: g.base });
  e = e$244;
  const base = $r155;
  if ($std_list.len({ xs: g.filters }) === 0) {
    return [base, e];
  }
  let it_name = "$it";
  let conds = $std_list.builder({  });
  let first = true;
  for (const f of g.filters) {
    if (first) {
      it_name = f.it_name;
      first = false;
    }
    const [$r156, e$245] = expr({ fuel: fuel, e: e, ctx: ctx, x: f.cond });
    e = e$245;
    const [, conds$246] = $std_list.push({ b: conds, x: at({ p: $r156, min: p_and + 1 }) });
    conds = conds$246;
  }
  return [base + ".filter((" + it_name + ") => " + $std_text.join({ parts: $std_list.finish({ b: conds }), sep: " && " }) + ")", e];
}

export function base_generator({ fuel, e, ctx, b }) {
  if (fuel === 0) {
    return ["fc.constant(undefined)", e];
  }
  const $m157 = b;
  $m157$match: {
    if ($m157.tag === "IntG") {
      return ["fc.integer({ min: -1000000, max: 1000000 })", e];
      break $m157$match;
    }
    if ($m157.tag === "FloatG") {
      return ["fc.double({ noNaN: true, noDefaultInfinity: true })", e];
      break $m157$match;
    }
    if ($m157.tag === "DurationG") {
      return ["fc.integer({ min: 0, max: 1000000000 })", e];
      break $m157$match;
    }
    if ($m157.tag === "BoolG") {
      return ["fc.boolean()", e];
      break $m157$match;
    }
    if ($m157.tag === "TextG") {
      return ["fc.string()", e];
      break $m157$match;
    }
    if ($m157.tag === "UnitG") {
      return ["fc.constant(undefined)", e];
      break $m157$match;
    }
    if ($m157.tag === "UnknownG") {
      return ["fc.constant(undefined)", e];
      break $m157$match;
    }
    if ($m157.tag === "ListG") {
      const elem = $m157.elem;
      const [$r158, e$247] = generator({ fuel: $rt.int.sub(fuel, 1, $ob93), e: e, ctx: ctx, g: elem });
      e = e$247;
      return ["fc.array(" + $r158 + ", { maxLength: 8 })", e];
      break $m157$match;
    }
    if ($m157.tag === "RecordG") {
      const fields = $m157.fields;
      const [$r159, e$248] = gen_fields({ fuel: $rt.int.sub(fuel, 1, $ob94), e: e, ctx: ctx, fields: fields });
      e = e$248;
      return ["fc.record({ " + $std_text.join({ parts: $r159, sep: ", " }) + " })", e];
      break $m157$match;
    }
    if ($m157.tag === "UnionG") {
      const variants = $m157.variants;
      let parts = $std_list.builder({  });
      for (const v of variants) {
        let inner = "tag: fc.constant(" + $json.quote({ t: v.name }) + ")";
        if ($std_list.len({ xs: v.fields }) > 0) {
          const [$r160, e$249] = gen_fields({ fuel: $rt.int.sub(fuel, 1, $ob95), e: e, ctx: ctx, fields: v.fields });
          e = e$249;
          inner = inner + ", " + $std_text.join({ parts: $r160, sep: ", " });
        }
        const [, parts$250] = $std_list.push({ b: parts, x: "fc.record({ " + inner + " })" });
        parts = parts$250;
      }
      return ["fc.oneof(" + $std_text.join({ parts: $std_list.finish({ b: parts }), sep: ", " }) + ")", e];
      break $m157$match;
    }
    $rt.unreachable();
  }
}

export function gen_fields({ fuel, e, ctx, fields }) {
  if (fuel === 0) {
    return [[], e];
  }
  let out = $std_list.builder({  });
  for (const f of fields) {
    const [$r161, e$251] = generator({ fuel: $rt.int.sub(fuel, 1, $ob96), e: e, ctx: ctx, g: f.gen });
    e = e$251;
    const [, out$252] = $std_list.push({ b: out, x: local({ name: f.name }) + ": " + $r161 });
    out = out$252;
  }
  return [$std_list.finish({ b: out }), e];
}

export function verify_function({ e, ctx, v }) {
  let names = $std_list.builder({  });
  for (const p of v.params) {
    const [, names$253] = $std_list.push({ b: names, x: local({ name: p.name }) });
    names = names$253;
  }
  let destructure = "$args";
  if ($std_list.built({ b: names }) > 0) {
    destructure = "{ " + $std_text.join({ parts: $std_list.finish({ b: names }), sep: ", " }) + " }";
  }
  e = { ...e, fn_ctx: { tag: "Some", value: { inout_names: [], ret: { tag: "Prim", name: "Bool" } } }, assert_mode: "return-false" };
  const [, e$254] = line({ e: e, s: "export function " + local({ name: v.name }) + "(" + destructure + ") {" });
  e = e$254;
  const [, e$255] = indent({ e: e });
  e = e$255;
  const [, e$256] = early_open({ e: e, early: v.early_return });
  e = e$256;
  const [, e$257] = block({ fuel: max_depth, e: e, ctx: ctx, b: v.body });
  e = e$257;
  const [, e$258] = line({ e: e, s: "return true;" });
  e = e$258;
  const [, e$259] = early_close({ e: e, early: v.early_return });
  e = e$259;
  const [, e$260] = dedent({ e: e });
  e = e$260;
  const [, e$261] = line({ e: e, s: "}" });
  e = e$261;
  const [, e$262] = line({ e: e, s: "" });
  e = e$262;
  e = { ...e, fn_ctx: { tag: "None" } };
  return [{ name: v.name, key: v.key, claim: v.claim, def: v.def, at: v.at, params: v.params }, e];
}

