// Generated by onus from module modcache. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $std_map from "./std/map.js";
import * as $std_list from "./std/list.js";
import * as $std_int from "./std/int.js";
import * as $std_hash from "./std/hash.js";
import * as $std_text from "./std/text.js";
import * as $std_io from "./std/io.js";
import * as $obligations from "./obligations.js";

const $ob1 = { kind: "overflow", text: "ctx.module_count + 1 within Int", at: "/Users/jamesrandall/code/onus/self/modcache.onus:45:13", def: "module_keys" };
const $ob2 = { kind: "overflow", text: "fuel - 1 within Int", at: "/Users/jamesrandall/code/onus/self/modcache.onus:95:15", def: "key_of" };
const $ob3 = { kind: "overflow", text: "-1 within Int", at: "/Users/jamesrandall/code/onus/self/modcache.onus:176:20", def: "parse_entry" };
const $ob4 = { kind: "overflow", text: "j + 1 within Int", at: "/Users/jamesrandall/code/onus/self/modcache.onus:199:13", def: "parse_entry" };
const $ob5 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/modcache.onus:210:9", def: "parse_entry" };
export const format = 2;

export function skip($args) {
  return undefined;
}

export function module_keys({ ctx, compiler, solver_version, budget_ms }) {
  let keys = $std_map.dict({  });
  let visiting = $std_map.dict({  });
  const $hi1 = ctx.module_count;
  for (let mid = 0; mid < $hi1; mid++) {
    const [$r2, keys$1, visiting$1] = key_of({ fuel: $rt.int.add(ctx.module_count, 1, $ob1), ctx: ctx, id: mid, compiler: compiler, solver_version: solver_version, budget_ms: budget_ms, keys: keys, visiting: visiting });
    keys = keys$1;
    visiting = visiting$1;
    const k = $r2;
  }
  return keys;
}

export function key_of({ fuel, ctx, id, compiler, solver_version, budget_ms, keys, visiting }) {
  if (fuel === 0) {
    return [{ tag: "None" }, keys, visiting];
  }
  const $m4 = $std_map.find({ d: keys, key: id });
  $m4$match: {
    if ($m4.tag === "Some") {
      const value = $m4.value;
      return [{ tag: "Some", value: value }, keys, visiting];
      break $m4$match;
    }
    if ($m4.tag === "None") {
      skip({  });
      break $m4$match;
    }
    $rt.unreachable();
  }
  if ($std_map.contains({ d: visiting, key: id })) {
    return [{ tag: "None" }, keys, visiting];
  }
  const [, visiting$2] = $std_map.set({ d: visiting, key: id, value: true });
  visiting = visiting$2;
  const $m7 = $std_map.find({ d: ctx.modules, key: id });
  $m7$match: {
    if ($m7.tag === "None") {
      return [{ tag: "None" }, keys, visiting];
      break $m7$match;
    }
    if ($m7.tag === "Some") {
      const value = $m7.value;
      const text = $std_map.find({ d: ctx.canonical, key: value.file });
      if (text.tag === "None") {
        return [{ tag: "None" }, keys, visiting];
      }
      let parts = $std_list.builder({  });
      const [, parts$3] = $std_list.push({ b: parts, x: "onus-modcache " + $std_int.to_text({ x: format }) });
      parts = parts$3;
      const [, parts$4] = $std_list.push({ b: parts, x: compiler });
      parts = parts$4;
      const [, parts$5] = $std_list.push({ b: parts, x: solver_version });
      parts = parts$5;
      const [, parts$6] = $std_list.push({ b: parts, x: $std_int.to_text({ x: budget_ms }) });
      parts = parts$6;
      const [, parts$7] = $std_list.push({ b: parts, x: value.name });
      parts = parts$7;
      for (const imp of value.imports) {
        const [$r10, keys$8, visiting$8] = key_of({ fuel: $rt.int.sub(fuel, 1, $ob2), ctx: ctx, id: imp.mod, compiler: compiler, solver_version: solver_version, budget_ms: budget_ms, keys: keys, visiting: visiting });
        keys = keys$8;
        visiting = visiting$8;
        const k = $r10;
        if (k.tag === "None") {
          return [{ tag: "None" }, keys, visiting];
        }
        const [, parts$9] = $std_list.push({ b: parts, x: module_name({ ctx: ctx, mod: imp.mod }) + " " + text_or_empty({ o: k }) });
        parts = parts$9;
      }
      const [, parts$10] = $std_list.push({ b: parts, x: text_or_empty({ o: text }) });
      parts = parts$10;
      const key = $std_hash.blake3_hex({ t: $std_text.join({ parts: $std_list.finish({ b: parts }), sep: "\n" }) });
      const [, keys$11] = $std_map.set({ d: keys, key: id, value: key });
      keys = keys$11;
      return [{ tag: "Some", value: key }, keys, visiting];
      break $m7$match;
    }
    $rt.unreachable();
  }
}

export function module_name({ ctx, mod }) {
  const $m13 = $std_map.find({ d: ctx.modules, key: mod });
  $m13$match: {
    if ($m13.tag === "Some") {
      const value = $m13.value;
      return value.name;
      break $m13$match;
    }
    if ($m13.tag === "None") {
      return "";
      break $m13$match;
    }
    $rt.unreachable();
  }
}

export function text_or_empty({ o }) {
  const $m14 = o;
  $m14$match: {
    if ($m14.tag === "Some") {
      const value = $m14.value;
      return value;
      break $m14$match;
    }
    if ($m14.tag === "None") {
      return "";
      break $m14$match;
    }
    $rt.unreachable();
  }
}

export function entry_path({ dir, key }) {
  return dir + "/" + key + ".module.txt";
}

export function status_of_text({ t }) {
  if (t === "proved") {
    return { tag: "Some", value: { tag: "Proved" } };
  }
  if (t === "checked") {
    return { tag: "Some", value: { tag: "Checked" } };
  }
  if (t === "assumed") {
    return { tag: "Some", value: { tag: "Assumed" } };
  }
  if (t === "failed") {
    return { tag: "Some", value: { tag: "Failed" } };
  }
  if (t === "pending") {
    return { tag: "Some", value: { tag: "Pending" } };
  }
  return { tag: "None" };
}

export function get({ files, dir, key }) {
  if (dir.tag === "None") {
    return { tag: "None" };
  }
  const $m27 = $std_io.read({ files: files, path: entry_path({ dir: text_or_empty({ o: dir }), key: key }) });
  $m27$match: {
    if ($m27.tag === "Err") {
      return { tag: "None" };
      break $m27$match;
    }
    if ($m27.tag === "Ok") {
      const value = $m27.value;
      return parse_entry({ text: value });
      break $m27$match;
    }
    $rt.unreachable();
  }
}

export function parse_entry({ text }) {
  const lines = $std_text.split({ t: text, sep: "\n" });
  if ($std_list.len({ xs: lines }) < 2) {
    return { tag: "None" };
  }
  if ($std_list.get({ xs: lines, i: 0 }) !== "onus-modcache " + $std_int.to_text({ x: format })) {
    return { tag: "None" };
  }
  let count = $rt.int.neg(1, $ob3);
  const $m31 = $std_int.parse({ t: $std_list.get({ xs: lines, i: 1 }) });
  $m31$match: {
    if ($m31.tag === "Some") {
      const value = $m31.value;
      count = value;
      break $m31$match;
    }
    if ($m31.tag === "None") {
      return { tag: "None" };
      break $m31$match;
    }
    $rt.unreachable();
  }
  let out = $std_list.builder({  });
  let i = 0;
  for (const line of lines) {
    if (i >= 2 && $std_list.built({ b: out }) < count) {
      const parts = $std_text.split({ t: line, sep: "\t" });
      if ($std_list.len({ xs: parts }) !== 2) {
        return { tag: "None" };
      }
      let by = { tag: "None" };
      let status = { tag: "None" };
      let second = "";
      let j = 0;
      for (const p of parts) {
        if (j === 0) {
          status = status_of_text({ t: p });
        }
        if (j === 1) {
          second = p;
        }
        j = $rt.int.add(j, 1, $ob4);
      }
      const $m36 = status;
      $m36$match: {
        if ($m36.tag === "None") {
          return { tag: "None" };
          break $m36$match;
        }
        if ($m36.tag === "Some") {
          const value = $m36.value;
          if (second !== "-") {
            by = { tag: "Some", value: second };
          }
          const [, out$12] = $std_list.push({ b: out, x: { status: value, by: by } });
          out = out$12;
          break $m36$match;
        }
        $rt.unreachable();
      }
    }
    i = $rt.int.add(i, 1, $ob5);
  }
  if ($std_list.built({ b: out }) !== count) {
    return { tag: "None" };
  }
  return { tag: "Some", value: $std_list.finish({ b: out }) };
}

export function set({ files, dir, key, obs }) {
  if (dir.tag === "None") {
    return undefined;
  }
  const d = text_or_empty({ o: dir });
  const made = $std_io.mkdir({ files: files, path: d });
  let lines = $std_list.builder({  });
  const [, lines$13] = $std_list.push({ b: lines, x: "onus-modcache " + $std_int.to_text({ x: format }) });
  lines = lines$13;
  const [, lines$14] = $std_list.push({ b: lines, x: $std_int.to_text({ x: $std_list.len({ xs: obs }) }) });
  lines = lines$14;
  for (const o of obs) {
    let by = "-";
    const $m42 = o.by;
    $m42$match: {
      if ($m42.tag === "Some") {
        const value = $m42.value;
        by = $std_text.replace({ t: $std_text.replace({ t: value, from: "\n", to: " " }), from: "\t", to: " " });
        break $m42$match;
      }
      if ($m42.tag === "None") {
        skip({  });
        break $m42$match;
      }
      $rt.unreachable();
    }
    const [, lines$15] = $std_list.push({ b: lines, x: $obligations.status_text({ s: o.status }) + "\t" + by });
    lines = lines$15;
  }
  const $m43 = $std_io.create({ files: files, path: entry_path({ dir: d, key: key }) });
  $m43$match: {
    if ($m43.tag === "Err") {
      return undefined;
      break $m43$match;
    }
    if ($m43.tag === "Ok") {
      const value = $m43.value;
      const written = $std_io.write({ file: value, text: $std_text.join({ parts: $std_list.finish({ b: lines }), sep: "\n" }) });
      return undefined;
      break $m43$match;
    }
    $rt.unreachable();
  }
}

