// Generated by onus from module report. Do not edit.
import * as $rt from "./onus-runtime/index.js";
export function diagnostic({ code, file, span, def_name, detail }) {
  return { code: code, file: file, span: span, def_name: def_name, context: [detail], obligation: { tag: "None" }, repairs: [] };
}

export function diagnostic_repair({ code, file, span, detail, repair }) {
  return { code: code, file: file, span: span, def_name: { tag: "None" }, context: [detail], obligation: { tag: "None" }, repairs: [repair] };
}

export function diagnostic_for({ code, file, span, def_name, detail, obligation }) {
  return { code: code, file: file, span: span, def_name: def_name, context: [detail], obligation: { tag: "Some", value: obligation }, repairs: [] };
}

