// Generated by onus: launches cli.main.
import * as $rt from "./onus-runtime/index.js";
import { main } from "./cli.js";
process.exitCode = $rt.runMain(main, {"roots":{"files":"Files","console":"Console","process":"Process","env":"Env"},"args":"args"}, process.argv.slice(2));
