// Generated by onus: tests of module tokens.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $self from "./tokens.js";
import * as $std_text from "./std/text.js";

import { test, expect, afterAll } from 'vitest';
import * as fc from 'fast-check';
test("predicates", () => {
  expect($self.is_keyword({ word: "fn" })).toBe(true);
  expect(!$self.is_keyword({ word: "fnord" })).toBe(true);
  expect($self.is_name({ cps: $std_text.code_points({ t: "snake_case2" }) })).toBe(true);
  expect(!$self.is_name({ cps: $std_text.code_points({ t: "xValue" }) })).toBe(true);
  expect($self.is_type_name({ cps: $std_text.code_points({ t: "Viewport" }) })).toBe(true);
  expect($self.is_continuation({ kind: { tag: "Punct", text: "->" } })).toBe(true);
  expect(!$self.is_continuation({ kind: { tag: "Newline" } })).toBe(true);
});
afterAll(() => $rt.coverage.flush());
