// Generated by onus from module vc. Do not edit.
import * as $rt from "./onus-runtime/index.js";
import * as $formula from "./formula.js";
import * as $std_map from "./std/map.js";
import * as $obligations from "./obligations.js";
import * as $defs from "./defs.js";
import * as $parser from "./parser.js";
import * as $std_list from "./std/list.js";
import * as $std_text from "./std/text.js";
import * as $context from "./context.js";
import * as $lower from "./lower.js";
import * as $walk from "./walk.js";
import * as $types from "./types.js";
import * as $report from "./report.js";

const $ob1 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:75:20", def: "or_neg" };
const $ob2 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:162:20", def: "ref_def" };
const $ob3 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:166:19", def: "ref_def" };
const $ob4 = { kind: "overflow", text: "i + 1 within Int", at: "self/vc.onus:191:9", def: "drop" };
const $ob5 = { kind: "overflow", text: "i + 1 within Int", at: "self/vc.onus:390:9", def: "fn_body_sig" };
const $ob6 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:551:18", def: "assigned" };
const $ob7 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:651:22", def: "w_block" };
const $ob8 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:670:11", def: "w_stmt" };
const $ob9 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:679:11", def: "w_stmt" };
const $ob10 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:688:11", def: "w_stmt" };
const $ob11 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:697:11", def: "w_stmt" };
const $ob12 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:705:11", def: "w_stmt" };
const $ob13 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:714:11", def: "w_stmt" };
const $ob14 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:723:11", def: "w_stmt" };
const $ob15 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:734:11", def: "w_stmt" };
const $ob16 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:745:11", def: "w_stmt" };
const $ob17 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:774:11", def: "let_stmt" };
const $ob18 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:813:11", def: "assign_stmt" };
const $ob19 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:853:11", def: "return_stmt" };
const $ob20 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:904:11", def: "if_stmt" };
const $ob21 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:913:21", def: "if_stmt" };
const $ob22 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:925:23", def: "if_stmt" };
const $ob23 = { kind: "overflow", text: "List.len(xs: before_facts) + 1 within Int", at: "self/vc.onus:949:8", def: "if_stmt" };
const $ob24 = { kind: "overflow", text: "List.len(xs: before_facts) + 1 within Int", at: "self/vc.onus:953:8", def: "if_stmt" };
const $ob25 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1019:11", def: "match_stmt" };
const $ob26 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1051:15", def: "match_stmt" };
const $ob27 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1072:25", def: "match_stmt" };
const $ob28 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1076:24", def: "match_stmt" };
const $ob29 = { kind: "overflow", text: "i + 1 within Int", at: "self/vc.onus:1127:13", def: "match_stmt" };
const $ob30 = { kind: "overflow", text: "i + 1 within Int", at: "self/vc.onus:1142:9", def: "match_stmt" };
const $ob31 = { kind: "overflow", text: "i + 1 within Int", at: "self/vc.onus:1234:15", def: "variant_facts" };
const $ob32 = { kind: "overflow", text: "i + 1 within Int", at: "self/vc.onus:1236:38", def: "variant_facts" };
const $ob33 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:1301:10", def: "find_source" };
const $ob34 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1360:11", def: "loop_stmt" };
const $ob35 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:1368:20", def: "loop_stmt" };
const $ob36 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1380:13", def: "loop_stmt" };
const $ob37 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1390:21", def: "loop_stmt" };
const $ob38 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1466:13", def: "for_stmt" };
const $ob39 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1473:13", def: "for_stmt" };
const $ob40 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1494:13", def: "for_stmt" };
const $ob41 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1526:21", def: "for_stmt" };
const $ob42 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1616:11", def: "expr_stmt" };
const $ob43 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:1646:17", def: "node_key" };
const $ob44 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1719:31", def: "expr_obligations" };
const $ob45 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1816:11", def: "discharge_under" };
const $ob46 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1824:11", def: "discharge_under" };
const $ob47 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1833:33", def: "discharge_under" };
const $ob48 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1838:33", def: "discharge_under" };
const $ob49 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1844:31", def: "discharge_under" };
const $ob50 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1845:31", def: "discharge_under" };
const $ob51 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1866:31", def: "discharge_under" };
const $ob52 = { kind: "overflow", text: "fuel - 1 within Int", at: "self/vc.onus:1886:31", def: "junction" };
const $ob53 = { kind: "overflow", text: "-1 within Int", at: "self/vc.onus:2202:20", def: "field_obligations" };
export const safe_max = 9007199254740991;

export function skip($args) {
  return undefined;
}

export function or_neg({ o }) {
  const $m1 = o;
  $m1$match: {
    if ($m1.tag === "Some") {
      const value = $m1.value;
      return value;
      break $m1$match;
    }
    if ($m1.tag === "None") {
      return $rt.int.neg(1, $ob1);
      break $m1$match;
    }
    $rt.unreachable();
  }
}

export function type_or({ o }) {
  const $m2 = o;
  $m2$match: {
    if ($m2.tag === "Some") {
      const value = $m2.value;
      return value;
      break $m2$match;
    }
    if ($m2.tag === "None") {
      return { tag: "ErrorT" };
      break $m2$match;
    }
    $rt.unreachable();
  }
}

export function formula_or({ o }) {
  const $m4 = o;
  $m4$match: {
    if ($m4.tag === "Some") {
      const value = $m4.value;
      return value;
      break $m4$match;
    }
    if ($m4.tag === "None") {
      return $formula.true_f;
      break $m4$match;
    }
    $rt.unreachable();
  }
}

export function ids_or({ o }) {
  const $m5 = o;
  $m5$match: {
    if ($m5.tag === "Some") {
      const value = $m5.value;
      return value;
      break $m5$match;
    }
    if ($m5.tag === "None") {
      return [];
      break $m5$match;
    }
    $rt.unreachable();
  }
}

export function fields_or({ o }) {
  const $m6 = o;
  $m6$match: {
    if ($m6.tag === "Some") {
      const value = $m6.value;
      return value;
      break $m6$match;
    }
    if ($m6.tag === "None") {
      return [];
      break $m6$match;
    }
    $rt.unreachable();
  }
}

export function binding_or({ o }) {
  const $m7 = o;
  $m7$match: {
    if ($m7.tag === "Some") {
      const value = $m7.value;
      return value;
      break $m7$match;
    }
    if ($m7.tag === "None") {
      return { term: $formula.true_f, ty: { tag: "ErrorT" } };
      break $m7$match;
    }
    $rt.unreachable();
  }
}

export function info_or({ o }) {
  const $m10 = o;
  $m10$match: {
    if ($m10.tag === "Some") {
      const value = $m10.value;
      return value;
      break $m10$match;
    }
    if ($m10.tag === "None") {
      return { args: $std_map.dict({  }), param_types: $std_map.dict({  }), subst: $std_map.dict({  }) };
      break $m10$match;
    }
    $rt.unreachable();
  }
}

export function zero_span($args) {
  return { start: 0, end: 0 };
}

export function contract_or({ o }) {
  const $m13 = o;
  $m13$match: {
    if ($m13.tag === "Some") {
      const value = $m13.value;
      return value;
      break $m13$match;
    }
    if ($m13.tag === "None") {
      return { clause: "", is_proved: false, expr: { tag: "Hole", span: zero_span({  }) }, span: zero_span({  }) };
      break $m13$match;
    }
    $rt.unreachable();
  }
}

export function clause_expr({ o }) {
  const $m16 = o;
  $m16$match: {
    if ($m16.tag === "Some") {
      const value = $m16.value;
      return value.expr;
      break $m16$match;
    }
    if ($m16.tag === "None") {
      return { tag: "Hole", span: zero_span({  }) };
      break $m16$match;
    }
    $rt.unreachable();
  }
}

export function same_kind({ a, b }) {
  return $obligations.kind_text({ k: a }) === $obligations.kind_text({ k: b });
}

export function key({ w, tag, span }) {
  return $defs.node_key({ file: w.file, tag: tag, span: span });
}

export function expr_key({ w, e }) {
  return key({ w: w, tag: $defs.tag_expr, span: $parser.span_of_expr({ e: e }) });
}

export function app_true($args) {
  return $formula.app({ fn_name: "true", args: [], sort: { tag: "BoolS" } });
}

export function app_false($args) {
  return $formula.app({ fn_name: "false", args: [], sort: { tag: "BoolS" } });
}

export function cmp({ op, a, b }) {
  return $formula.app({ fn_name: op, args: [a, b], sort: { tag: "BoolS" } });
}

export function ref_def({ o }) {
  const $m21 = o;
  $m21$match: {
    if ($m21.tag === "None") {
      return $rt.int.neg(1, $ob2);
      break $m21$match;
    }
    if ($m21.tag === "Some") {
      const value = $m21.value;
      const $m22 = value;
      $m22$match: {
        if ($m22.tag === "DefRes") {
          const def = $m22.def;
          return def;
          break $m22$match;
        }
        if (true) {
          return $rt.int.neg(1, $ob3);
          break $m22$match;
        }
        $rt.unreachable();
      }
      break $m21$match;
    }
    $rt.unreachable();
  }
}

export function conj({ fs }) {
  if ($std_list.len({ xs: fs }) === 0) {
    return $formula.true_f;
  }
  if ($std_list.len({ xs: fs }) === 1) {
    for (const f of fs) {
      return f;
    }
  }
  return $formula.and_f({ xs: fs });
}

export function drop({ xs, n }) {
  let out = $std_list.builder({  });
  let i = 0;
  for (const x of xs) {
    if (i >= n) {
      const [, out$1] = $std_list.push({ b: out, x: x });
      out = out$1;
    }
    i = $rt.int.add(i, 1, $ob4);
  }
  return $std_list.finish({ b: out });
}

export function negations({ fs }) {
  let out = $std_list.builder({  });
  for (const f of fs) {
    const [, out$2] = $std_list.push({ b: out, x: $formula.not_f({ x: f }) });
    out = out$2;
  }
  return $std_list.finish({ b: out });
}

export function measure_text({ t }) {
  for (const p of $std_text.split({ t: t, sep: " at the call to " })) {
    return p;
  }
  return t;
}

export function build_vcs({ ctx, skip_modules, mutation }) {
  const out = { built: $std_map.dict({  }), skipped: $std_map.dict({  }) };
  let by_def = $std_map.dict({  });
  let order = $std_list.builder({  });
  const $hi24 = ctx.obligation_count;
  for (let i = 0; i < $hi24; i++) {
    const o = $context.get_obligation({ ctx: ctx, id: i });
    if (!(o.kind.tag === "Law") && !(o.kind.tag === "Property") && !$std_map.contains({ d: skip_modules, key: $context.get_def({ ctx: ctx, id: o.def }).mod })) {
      const $m25 = $std_map.find({ d: by_def, key: o.def });
      $m25$match: {
        if ($m25.tag === "Some") {
          const value = $m25.value;
          const [, by_def$3] = $std_map.set({ d: by_def, key: o.def, value: $std_list.append({ xs: value, x: i }) });
          by_def = by_def$3;
          break $m25$match;
        }
        if ($m25.tag === "None") {
          const [, order$4] = $std_list.push({ b: order, x: o.def });
          order = order$4;
          const [, by_def$5] = $std_map.set({ d: by_def, key: o.def, value: [i] });
          by_def = by_def$5;
          break $m25$match;
        }
        $rt.unreachable();
      }
    }
  }
  for (const def of $std_list.finish({ b: order })) {
    const d = $context.get_def({ ctx: ctx, id: def });
    let pending = $std_map.dict({  });
    for (const id of ids_or({ o: $std_map.find({ d: by_def, key: def }) })) {
      const [, pending$6] = $std_map.set({ d: pending, key: id, value: true });
      pending = pending$6;
    }
    let lw = $lower.new_lw({ file: d.file, mutation: mutation });
    let w = { def: d, file: d.file, env: $std_map.dict({  }), facts: [], names: $std_map.dict({  }), pending: pending, ret: { tag: "None" }, post: [], measure0: { tag: "None" }, built: out.built, skipped: out.skipped };
    const [$r30, w$7, lw$7, ctx$7] = walk_def({ w: w, lw: lw, ctx: ctx, d: d });
    w = w$7;
    lw = lw$7;
    ctx = ctx$7;
    const $m29 = $r30;
    $m29$match: {
      if ($m29.tag === "Ok") {
        skip({  });
        break $m29$match;
      }
      if ($m29.tag === "Err") {
        const error = $m29.error;
        skip_all({ w: w, reason: error });
        break $m29$match;
      }
      $rt.unreachable();
    }
  }
  return [out, ctx];
}

export function walk_def({ w, lw, ctx, d }) {
  const $m31 = d.node;
  $m31$match: {
    if ($m31.tag === "FnNode") {
      const decl = $m31.decl;
      const $m32 = decl.body;
      $m32$match: {
        if ($m32.tag === "Some") {
          const value = $m32.value;
          const [$r33, w$8, lw$8, ctx$8] = fn_body({ w: w, lw: lw, ctx: ctx, decl: decl, body: value });
          w = w$8;
          lw = lw$8;
          ctx = ctx$8;
          return [$r33, w, lw, ctx];
          break $m32$match;
        }
        if ($m32.tag === "None") {
          skip_all({ w: w, reason: "no body" });
          break $m32$match;
        }
        $rt.unreachable();
      }
      break $m31$match;
    }
    if ($m31.tag === "ExampleNode") {
      const decl = $m31.decl;
      const [$r34, w$9, lw$9, ctx$9] = assertion_body({ w: w, lw: lw, ctx: ctx, params: [], body: decl.body });
      w = w$9;
      lw = lw$9;
      ctx = ctx$9;
      return [$r34, w, lw, ctx];
      break $m31$match;
    }
    if ($m31.tag === "PropertyNode") {
      const decl = $m31.decl;
      const [$r35, w$10, lw$10, ctx$10] = assertion_body({ w: w, lw: lw, ctx: ctx, params: decl.params, body: decl.body });
      w = w$10;
      lw = lw$10;
      ctx = ctx$10;
      return [$r35, w, lw, ctx];
      break $m31$match;
    }
    if ($m31.tag === "LawNode") {
      const decl = $m31.decl;
      const [$r36, w$11, lw$11, ctx$11] = assertion_body({ w: w, lw: lw, ctx: ctx, params: decl.params, body: decl.body });
      w = w$11;
      lw = lw$11;
      ctx = ctx$11;
      return [$r36, w, lw, ctx];
      break $m31$match;
    }
    if ($m31.tag === "VerifyNode") {
      const decl = $m31.decl;
      const [$r37, w$12, lw$12, ctx$12] = assertion_body({ w: w, lw: lw, ctx: ctx, params: decl.params, body: decl.body });
      w = w$12;
      lw = lw$12;
      ctx = ctx$12;
      return [$r37, w, lw, ctx];
      break $m31$match;
    }
    if ($m31.tag === "ConstNode") {
      const decl = $m31.decl;
      const [$r38, w$13, lw$13, ctx$13] = const_body({ w: w, lw: lw, ctx: ctx, decl: decl });
      w = w$13;
      lw = lw$13;
      ctx = ctx$13;
      return [$r38, w, lw, ctx];
      break $m31$match;
    }
    if ($m31.tag === "ImplNode") {
      skip_all({ w: w, reason: "laws are run under generated inputs" });
      break $m31$match;
    }
    if (true) {
      skip_all({ w: w, reason: "no body" });
      break $m31$match;
    }
    $rt.unreachable();
  }
  return [{ tag: "Ok", value: undefined }, w, lw, ctx];
}

export function fn_body({ w, lw, ctx, decl, body }) {
  const $m40 = $std_map.find({ d: ctx.signatures, key: w.def.id });
  $m40$match: {
    if ($m40.tag === "None") {
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
      break $m40$match;
    }
    if ($m40.tag === "Some") {
      const value = $m40.value;
      const [$r42, w$14, lw$14, ctx$14] = fn_body_sig({ w: w, lw: lw, ctx: ctx, decl: decl, body: body, sig: value });
      w = w$14;
      lw = lw$14;
      ctx = ctx$14;
      return [$r42, w, lw, ctx];
      break $m40$match;
    }
    $rt.unreachable();
  }
}

export function fn_body_sig({ w, lw, ctx, decl, body, sig }) {
  try {
    let post = $std_list.builder({  });
    for (const c of decl.contracts) {
      if (c.clause === "ensures") {
        const [, post$15] = $std_list.push({ b: post, x: c });
        post = post$15;
      }
    }
    w = { ...w, ret: { tag: "Some", value: sig.ret }, post: $std_list.finish({ b: post }) };
    for (const p of sig.tparams) {
      const $m45 = p;
      $m45$match: {
        if ($m45.tag === "ConstP") {
          const def = $m45.def;
          const ty = $m45.ty;
          const [$r47, w$16, lw$16] = bind({ w: w, lw: lw, ctx: ctx, def: def, name: $context.get_def({ ctx: ctx, id: def }).name, ty: ty, init: { tag: "None" } });
          w = w$16;
          lw = lw$16;
          const t = $rt.unwrap($r47);
          break $m45$match;
        }
        if (true) {
          skip({  });
          break $m45$match;
        }
        $rt.unreachable();
      }
    }
    let i = 0;
    for (const p of sig.params) {
      if (i < $std_list.len({ xs: sig.param_defs })) {
        const pd = $std_list.get({ xs: sig.param_defs, i: i });
        const [$r49, w$17, lw$17] = bind({ w: w, lw: lw, ctx: ctx, def: pd, name: p.name, ty: p.ty, init: { tag: "None" } });
        w = w$17;
        lw = lw$17;
        const term = $rt.unwrap($r49);
        let olds = lw.olds;
        const [, olds$18] = $std_map.set({ d: olds, key: pd, value: term });
        olds = olds$18;
        const [, w$19, lw$19] = representation_goals({ w: w, lw: lw, ctx: ctx, at: $context.get_def({ ctx: ctx, id: pd }).key, ty: p.ty });
        w = w$19;
        lw = lw$19;
      }
      i = $rt.int.add(i, 1, $ob5);
    }
    for (const c of decl.contracts) {
      if (c.clause === "requires") {
        const [$r51, lw$20] = $lower.lower({ fuel: $lower.max_depth, lw: lw, ctx: ctx, e: c.expr, env: w.env });
        lw = lw$20;
        const $m50 = $r51;
        $m50$match: {
          if ($m50.tag === "Ok") {
            const value = $m50.value;
            const [, w$21] = push_fact({ w: w, f: value });
            w = w$21;
            break $m50$match;
          }
          if ($m50.tag === "Err") {
            skip({  });
            break $m50$match;
          }
          $rt.unreachable();
        }
      }
    }
    for (const c of decl.contracts) {
      if (c.clause === "decreases") {
        const [$r53, lw$22] = $lower.lower({ fuel: $lower.max_depth, lw: lw, ctx: ctx, e: c.expr, env: w.env });
        lw = lw$22;
        const $m52 = $r53;
        $m52$match: {
          if ($m52.tag === "Ok") {
            const value = $m52.value;
            w = { ...w, measure0: { tag: "Some", value: value } };
            break $m52$match;
          }
          if ($m52.tag === "Err") {
            skip({  });
            break $m52$match;
          }
          $rt.unreachable();
        }
        for (const o of obligations_at({ w: w, ctx: ctx, at: key({ w: w, tag: $defs.tag_sig, span: c.span }), kind: { tag: "Decreases" } })) {
          const $m57 = w.measure0;
          $m57$match: {
            if ($m57.tag === "None") {
              skip_one({ w: w, o: o, reason: "measure not lowered" });
              break $m57$match;
            }
            if ($m57.tag === "Some") {
              const value = $m57.value;
              emit({ w: w, lw: lw, o: o, goal: cmp({ op: ">=", a: value, b: $formula.int_f({ v: 0 }) }) });
              break $m57$match;
            }
            $rt.unreachable();
          }
        }
      }
    }
    const [$r58, w$23, lw$23, ctx$23] = w_block({ fuel: $lower.max_depth, w: w, lw: lw, ctx: ctx, b: body });
    w = w$23;
    lw = lw$23;
    ctx = ctx$23;
    $rt.unwrap($r58);
    skip_all({ w: w, reason: "not reached by the walk" });
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function assertion_body({ w, lw, ctx, params, body }) {
  try {
    for (const p of params) {
      const pd = or_neg({ o: $std_map.find({ d: ctx.def_of, key: key({ w: w, tag: $defs.tag_sig, span: p.span }) }) });
      if (pd >= 0) {
        const $m60 = $std_map.find({ d: ctx.decl_types, key: pd });
        $m60$match: {
          if ($m60.tag === "Some") {
            const value = $m60.value;
            const [$r62, w$24, lw$24] = bind({ w: w, lw: lw, ctx: ctx, def: pd, name: p.name.text, ty: value, init: { tag: "None" } });
            w = w$24;
            lw = lw$24;
            const t = $rt.unwrap($r62);
            break $m60$match;
          }
          if ($m60.tag === "None") {
            skip({  });
            break $m60$match;
          }
          $rt.unreachable();
        }
      }
    }
    const [$r63, w$25, lw$25, ctx$25] = w_block({ fuel: $lower.max_depth, w: w, lw: lw, ctx: ctx, b: body });
    w = w$25;
    lw = lw$25;
    ctx = ctx$25;
    $rt.unwrap($r63);
    skip_all({ w: w, reason: "not reached by the walk" });
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function const_body({ w, lw, ctx, decl }) {
  try {
    const [$r65, w$26, lw$26, ctx$26] = expr_obligations({ fuel: $lower.max_depth, w: w, lw: lw, ctx: ctx, e: decl.value });
    w = w$26;
    lw = lw$26;
    ctx = ctx$26;
    const v = $rt.unwrap($r65);
    skip_all({ w: w, reason: "not reached by the walk" });
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function push_fact({ w, f }) {
  w = { ...w, facts: $std_list.append({ xs: w.facts, x: f }) };
  return [undefined, w];
  return [undefined, w];
}

export function bind({ w, lw, ctx, def, name, ty, init }) {
  try {
    const sort = $rt.unwrap($lower.sort_of({ lw: lw, ctx: ctx, t: ty }));
    const [$r68, lw$27] = $lower.fresh_const({ lw: lw, prefix: name, sort: sort });
    lw = lw$27;
    const term = $r68;
    if (term.tag === "VarF") {
      let names = w.names;
      const [, names$28] = $std_map.set({ d: names, key: $formula.var_name({ f: term }), value: name });
      names = names$28;
    }
    const $m69 = init;
    $m69$match: {
      if ($m69.tag === "Some") {
        const value = $m69.value;
        const [, w$29] = push_fact({ w: w, f: $formula.eq({ a: term, b: value }) });
        w = w$29;
        if (term.tag === "VarF") {
          let aliases = lw.aliases;
          const [, aliases$30] = $std_map.set({ d: aliases, key: $formula.var_name({ f: term }), value: value });
          aliases = aliases$30;
        }
        break $m69$match;
      }
      if ($m69.tag === "None") {
        skip({  });
        break $m69$match;
      }
      $rt.unreachable();
    }
    let env = w.env;
    const [, env$31] = $std_map.set({ d: env, key: def, value: { term: term, ty: ty } });
    env = env$31;
    const [, lw$32] = $lower.type_facts({ fuel: $lower.max_depth, lw: lw, ctx: ctx, term: term, ty: ty, env: w.env });
    lw = lw$32;
    return [{ tag: "Ok", value: term }, w, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function havoc({ w, lw, ctx, ds }) {
  try {
    for (const d of ds) {
      const $m72 = $std_map.find({ d: w.env, key: d });
      $m72$match: {
        if ($m72.tag === "None") {
          skip({  });
          break $m72$match;
        }
        if ($m72.tag === "Some") {
          const value = $m72.value;
          const [$r74, w$33, lw$33] = bind({ w: w, lw: lw, ctx: ctx, def: d, name: $context.get_def({ ctx: ctx, id: d }).name, ty: value.ty, init: { tag: "None" } });
          w = w$33;
          lw = lw$33;
          const t = $rt.unwrap($r74);
          break $m72$match;
        }
        $rt.unreachable();
      }
    }
    return [{ tag: "Ok", value: undefined }, w, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function stmt_nodes({ s }) {
  return $walk.nodes_in_block({ b: { stmts: [s], elided: false, span: $parser.span_of_stmt({ st: s }) }, into_verify: false });
}

export function assigned({ ctx, w, nodes }) {
  let seen = $std_map.dict({  });
  let out = $std_list.builder({  });
  for (const n of nodes) {
    let k = $rt.int.neg(1, $ob6);
    const $m77 = n;
    $m77$match: {
      if ($m77.tag === "NStmt") {
        const s = $m77.s;
        const $m78 = s;
        $m78$match: {
          if ($m78.tag === "Assign") {
            const span = $m78.span;
            k = key({ w: w, tag: $defs.tag_stmt, span: span });
            break $m78$match;
          }
          if (true) {
            skip({  });
            break $m78$match;
          }
          $rt.unreachable();
        }
        break $m77$match;
      }
      if ($m77.tag === "NExpr") {
        const e = $m77.e;
        const $m79 = e;
        $m79$match: {
          if ($m79.tag === "Call") {
            const args = $m79.args;
            for (const a of args) {
              if (a.is_inout) {
                const $m80 = a.value;
                $m80$match: {
                  if ($m80.tag === "Name") {
                    const span = $m80.span;
                    const d = ref_def({ o: $std_map.find({ d: ctx.refs, key: key({ w: w, tag: $defs.tag_expr, span: span }) }) });
                    if (d >= 0 && !$std_map.contains({ d: seen, key: d })) {
                      const [, seen$34] = $std_map.set({ d: seen, key: d, value: true });
                      seen = seen$34;
                      const [, out$35] = $std_list.push({ b: out, x: d });
                      out = out$35;
                    }
                    break $m80$match;
                  }
                  if (true) {
                    skip({  });
                    break $m80$match;
                  }
                  $rt.unreachable();
                }
              }
            }
            break $m79$match;
          }
          if (true) {
            skip({  });
            break $m79$match;
          }
          $rt.unreachable();
        }
        break $m77$match;
      }
      if (true) {
        skip({  });
        break $m77$match;
      }
      $rt.unreachable();
    }
    if (k >= 0) {
      const d = ref_def({ o: $std_map.find({ d: ctx.refs, key: k }) });
      if (d >= 0 && !$std_map.contains({ d: seen, key: d })) {
        const [, seen$36] = $std_map.set({ d: seen, key: d, value: true });
        seen = seen$36;
        const [, out$37] = $std_list.push({ b: out, x: d });
        out = out$37;
      }
    }
  }
  return $std_list.finish({ b: out });
}

export function lower_e({ w, lw, ctx, e }) {
  try {
    const [$r81, lw$38] = $lower.lower({ fuel: $lower.max_depth, lw: lw, ctx: ctx, e: e, env: w.env });
    lw = lw$38;
    const f = $rt.unwrap($r81);
    w = { ...w, facts: [...w.facts, ...$lower.take_learned({ lw: lw })] };
    for (const r of $lower.take_rebound({ lw: lw })) {
      const $m83 = $std_map.find({ d: w.env, key: r.def });
      $m83$match: {
        if ($m83.tag === "Some") {
          const value = $m83.value;
          const [$r85, w$39, lw$39] = bind({ w: w, lw: lw, ctx: ctx, def: r.def, name: $context.get_def({ ctx: ctx, id: r.def }).name, ty: value.ty, init: { tag: "Some", value: r.term } });
          w = w$39;
          lw = lw$39;
          const t = $rt.unwrap($r85);
          break $m83$match;
        }
        if ($m83.tag === "None") {
          skip({  });
          break $m83$match;
        }
        $rt.unreachable();
      }
    }
    return [{ tag: "Ok", value: f }, w, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function push_maybe({ w, lw, ctx, e }) {
  const [$r88, w$40, lw$40] = lower_e({ w: w, lw: lw, ctx: ctx, e: e });
  w = w$40;
  lw = lw$40;
  const $m87 = $r88;
  $m87$match: {
    if ($m87.tag === "Ok") {
      const value = $m87.value;
      const [, w$41] = push_fact({ w: w, f: value });
      w = w$41;
      break $m87$match;
    }
    if ($m87.tag === "Err") {
      skip({  });
      break $m87$match;
    }
    $rt.unreachable();
  }
  return [undefined, w, lw];
  return [undefined, w, lw];
}

export function w_block({ fuel, w, lw, ctx, b }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    for (const s of b.stmts) {
      const [$r90, w$42, lw$42, ctx$42] = w_stmt({ fuel: $rt.int.sub(fuel, 1, $ob7), w: w, lw: lw, ctx: ctx, s: s });
      w = w$42;
      lw = lw$42;
      ctx = ctx$42;
      $rt.unwrap($r90);
    }
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function w_stmt({ fuel, w, lw, ctx, s }) {
  if (fuel === 0) {
    return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
  }
  const $m93 = s;
  $m93$match: {
    if ($m93.tag === "Let") {
      const name = $m93.name;
      const value = $m93.value;
      const span = $m93.span;
      const [$r94, w$43, lw$43, ctx$43] = let_stmt({ fuel: $rt.int.sub(fuel, 1, $ob8), w: w, lw: lw, ctx: ctx, name: name.text, e: value, at: span });
      w = w$43;
      lw = lw$43;
      ctx = ctx$43;
      return [$r94, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "Var") {
      const name = $m93.name;
      const value = $m93.value;
      const span = $m93.span;
      const [$r95, w$44, lw$44, ctx$44] = let_stmt({ fuel: $rt.int.sub(fuel, 1, $ob9), w: w, lw: lw, ctx: ctx, name: name.text, e: value, at: span });
      w = w$44;
      lw = lw$44;
      ctx = ctx$44;
      return [$r95, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "Assign") {
      const name = $m93.name;
      const value = $m93.value;
      const span = $m93.span;
      const [$r96, w$45, lw$45, ctx$45] = assign_stmt({ fuel: $rt.int.sub(fuel, 1, $ob10), w: w, lw: lw, ctx: ctx, name: name.text, e: value, at: span });
      w = w$45;
      lw = lw$45;
      ctx = ctx$45;
      return [$r96, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "Return") {
      const value = $m93.value;
      const span = $m93.span;
      const [$r97, w$46, lw$46, ctx$46] = return_stmt({ fuel: $rt.int.sub(fuel, 1, $ob11), w: w, lw: lw, ctx: ctx, e: value, at: span });
      w = w$46;
      lw = lw$46;
      ctx = ctx$46;
      return [$r97, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "If") {
      const cond = $m93.cond;
      const then_block = $m93.then_block;
      const else_block = $m93.else_block;
      const [$r98, w$47, lw$47, ctx$47] = if_stmt({ fuel: $rt.int.sub(fuel, 1, $ob12), w: w, lw: lw, ctx: ctx, cond: cond, then_block: then_block, else_block: else_block });
      w = w$47;
      lw = lw$47;
      ctx = ctx$47;
      return [$r98, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "Match") {
      const scrutinee = $m93.scrutinee;
      const arms = $m93.arms;
      const [$r99, w$48, lw$48, ctx$48] = match_stmt({ fuel: $rt.int.sub(fuel, 1, $ob13), w: w, lw: lw, ctx: ctx, s: s, scrutinee: scrutinee, arms: arms });
      w = w$48;
      lw = lw$48;
      ctx = ctx$48;
      return [$r99, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "Loop") {
      const cond = $m93.cond;
      const clauses = $m93.clauses;
      const body = $m93.body;
      const span = $m93.span;
      const [$r100, w$49, lw$49, ctx$49] = loop_stmt({ fuel: $rt.int.sub(fuel, 1, $ob14), w: w, lw: lw, ctx: ctx, s: s, cond: cond, clauses: clauses, body: body, at: span });
      w = w$49;
      lw = lw$49;
      ctx = ctx$49;
      return [$r100, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "For") {
      const name = $m93.name;
      const domain = $m93.domain;
      const body = $m93.body;
      const span = $m93.span;
      const [$r101, w$50, lw$50, ctx$50] = for_stmt({ fuel: $rt.int.sub(fuel, 1, $ob15), w: w, lw: lw, ctx: ctx, name: name.text, domain: domain, body: body, at: span });
      w = w$50;
      lw = lw$50;
      ctx = ctx$50;
      return [$r101, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "Assume") {
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
      break $m93$match;
    }
    if ($m93.tag === "ExprStmt") {
      const expr = $m93.expr;
      const [$r103, w$51, lw$51, ctx$51] = expr_stmt({ fuel: $rt.int.sub(fuel, 1, $ob16), w: w, lw: lw, ctx: ctx, e: expr });
      w = w$51;
      lw = lw$51;
      ctx = ctx$51;
      return [$r103, w, lw, ctx];
      break $m93$match;
    }
    $rt.unreachable();
  }
}

export function let_stmt({ fuel, w, lw, ctx, name, e, at }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const at_key = key({ w: w, tag: $defs.tag_stmt, span: at });
    const def = or_neg({ o: $std_map.find({ d: ctx.def_of, key: at_key }) });
    let ty = { tag: "None" };
    if (def >= 0) {
      ty = $std_map.find({ d: ctx.decl_types, key: def });
    }
    const [$r106, w$52, lw$52, ctx$52] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob17), w: w, lw: lw, ctx: ctx, e: e });
    w = w$52;
    lw = lw$52;
    ctx = ctx$52;
    const v = $rt.unwrap($r106);
    if (def >= 0 && ty.tag === "Some") {
      const t = type_or({ o: ty });
      const [, w$53, lw$53] = flow_goal({ w: w, lw: lw, ctx: ctx, e: e, term: v, ty: t });
      w = w$53;
      lw = lw$53;
      const [$r108, w$54, lw$54] = bind({ w: w, lw: lw, ctx: ctx, def: def, name: name, ty: t, init: { tag: "Some", value: v } });
      w = w$54;
      lw = lw$54;
      const b = $rt.unwrap($r108);
      const [, w$55, lw$55] = representation_goals({ w: w, lw: lw, ctx: ctx, at: at_key, ty: t });
      w = w$55;
      lw = lw$55;
    }
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function assign_stmt({ fuel, w, lw, ctx, name, e, at }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const def = ref_def({ o: $std_map.find({ d: ctx.refs, key: key({ w: w, tag: $defs.tag_stmt, span: at }) }) });
    const [$r111, w$56, lw$56, ctx$56] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob18), w: w, lw: lw, ctx: ctx, e: e });
    w = w$56;
    lw = lw$56;
    ctx = ctx$56;
    const v = $rt.unwrap($r111);
    if (def < 0) {
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
    }
    const $m113 = $std_map.find({ d: ctx.decl_types, key: def });
    $m113$match: {
      if ($m113.tag === "None") {
        return [{ tag: "Ok", value: undefined }, w, lw, ctx];
        break $m113$match;
      }
      if ($m113.tag === "Some") {
        const value = $m113.value;
        const [, w$57, lw$57] = flow_goal({ w: w, lw: lw, ctx: ctx, e: e, term: v, ty: value });
        w = w$57;
        lw = lw$57;
        const [$r116, w$58, lw$58] = bind({ w: w, lw: lw, ctx: ctx, def: def, name: name, ty: value, init: { tag: "Some", value: v } });
        w = w$58;
        lw = lw$58;
        const b = $rt.unwrap($r116);
        break $m113$match;
      }
      $rt.unreachable();
    }
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function return_stmt({ fuel, w, lw, ctx, e, at }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const [$r119, w$59, lw$59, ctx$59] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob19), w: w, lw: lw, ctx: ctx, e: e });
    w = w$59;
    lw = lw$59;
    ctx = ctx$59;
    const v = $rt.unwrap($r119);
    if (w.ret.tag === "None") {
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
    }
    const rt = type_or({ o: w.ret });
    const [, w$60, lw$60] = flow_goal({ w: w, lw: lw, ctx: ctx, e: e, term: v, ty: rt });
    w = w$60;
    lw = lw$60;
    for (const o of obligations_at({ w: w, ctx: ctx, at: key({ w: w, tag: $defs.tag_stmt, span: at }), kind: { tag: "Ensures" } })) {
      const src = or_neg({ o: $context.get_obligation({ ctx: ctx, id: o }).source });
      for (const c of w.post) {
        if (key({ w: w, tag: $defs.tag_sig, span: c.span }) === src) {
          lw = { ...lw, result_term: { tag: "Some", value: v } };
          const [$r124, lw$61] = $lower.lower({ fuel: $lower.max_depth, lw: lw, ctx: ctx, e: c.expr, env: w.env });
          lw = lw$61;
          const r = $r124;
          lw = { ...lw, result_term: { tag: "None" } };
          try_goal({ w: w, lw: lw, o: o, goal: r });
        }
      }
    }
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function if_stmt({ fuel, w, lw, ctx, cond, then_block, else_block }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const [$r129, w$62, lw$62, ctx$62] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob20), w: w, lw: lw, ctx: ctx, e: cond });
    w = w$62;
    lw = lw$62;
    ctx = ctx$62;
    const c = $rt.unwrap($r129);
    const before_env = $lower.copy_env({ env: w.env });
    const before_facts = w.facts;
    const [, w$63] = push_fact({ w: w, f: c });
    w = w$63;
    const [$r130, w$64, lw$64, ctx$64] = w_block({ fuel: $rt.int.sub(fuel, 1, $ob21), w: w, lw: lw, ctx: ctx, b: then_block });
    w = w$64;
    lw = lw$64;
    ctx = ctx$64;
    $rt.unwrap($r130);
    const then_returns = block_returns({ b: then_block });
    const after_then_env = $lower.copy_env({ env: w.env });
    const after_then_facts = w.facts;
    w = { ...w, env: $lower.copy_env({ env: before_env }), facts: $std_list.append({ xs: before_facts, x: $formula.not_f({ x: c }) }) };
    let else_returns = false;
    let else_nodes = [];
    const $m132 = else_block;
    $m132$match: {
      if ($m132.tag === "Some") {
        const value = $m132.value;
        const [$r133, w$65, lw$65, ctx$65] = w_block({ fuel: $rt.int.sub(fuel, 1, $ob22), w: w, lw: lw, ctx: ctx, b: value });
        w = w$65;
        lw = lw$65;
        ctx = ctx$65;
        $rt.unwrap($r133);
        else_returns = block_returns({ b: value });
        else_nodes = $walk.nodes_in_block({ b: value, into_verify: false });
        break $m132$match;
      }
      if ($m132.tag === "None") {
        skip({  });
        break $m132$match;
      }
      $rt.unreachable();
    }
    const after_else_env = $lower.copy_env({ env: w.env });
    const after_else_facts = w.facts;
    if (then_returns && !else_returns) {
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
    }
    if (else_returns && !then_returns) {
      w = { ...w, env: after_then_env, facts: after_then_facts };
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
    }
    const assigned_defs = assigned({ ctx: ctx, w: w, nodes: [...$walk.nodes_in_block({ b: then_block, into_verify: false }), ...else_nodes] });
    const then_new = drop({ xs: after_then_facts, n: $rt.int.add($std_list.len({ xs: before_facts }), 1, $ob23) });
    const else_new = drop({ xs: after_else_facts, n: $rt.int.add($std_list.len({ xs: before_facts }), 1, $ob24) });
    w = { ...w, env: $lower.copy_env({ env: before_env }), facts: before_facts };
    let then_eqs = $std_list.builder({  });
    let else_eqs = $std_list.builder({  });
    for (const d of assigned_defs) {
      const $m138 = $std_map.find({ d: before_env, key: d });
      $m138$match: {
        if ($m138.tag === "None") {
          skip({  });
          break $m138$match;
        }
        if ($m138.tag === "Some") {
          const value = $m138.value;
          const t1 = $std_map.find({ d: after_then_env, key: d });
          const t2 = $std_map.find({ d: after_else_env, key: d });
          const [$r140, w$66, lw$66] = bind({ w: w, lw: lw, ctx: ctx, def: d, name: $context.get_def({ ctx: ctx, id: d }).name, ty: value.ty, init: { tag: "None" } });
          w = w$66;
          lw = lw$66;
          const fresh = $rt.unwrap($r140);
          if (t1.tag === "Some") {
            const [, then_eqs$67] = $std_list.push({ b: then_eqs, x: $formula.eq({ a: fresh, b: binding_or({ o: t1 }).term }) });
            then_eqs = then_eqs$67;
          }
          if (t2.tag === "Some") {
            const [, else_eqs$68] = $std_list.push({ b: else_eqs, x: $formula.eq({ a: fresh, b: binding_or({ o: t2 }).term }) });
            else_eqs = else_eqs$68;
          }
          break $m138$match;
        }
        $rt.unreachable();
      }
    }
    const [, w$69] = push_fact({ w: w, f: $formula.implies_f({ a: c, b: conj({ fs: [...then_new, ...$std_list.finish({ b: then_eqs })] }) }) });
    w = w$69;
    const [, w$70] = push_fact({ w: w, f: $formula.implies_f({ a: $formula.not_f({ x: c }), b: conj({ fs: [...else_new, ...$std_list.finish({ b: else_eqs })] }) }) });
    w = w$70;
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function list_or({ o }) {
  const $m142 = o;
  $m142$match: {
    if ($m142.tag === "Some") {
      const value = $m142.value;
      return value;
      break $m142$match;
    }
    if ($m142.tag === "None") {
      return [];
      break $m142$match;
    }
    $rt.unreachable();
  }
}

export function match_stmt({ fuel, w, lw, ctx, s, scrutinee, arms }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const [$r144, w$71, lw$71, ctx$71] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob25), w: w, lw: lw, ctx: ctx, e: scrutinee });
    w = w$71;
    lw = lw$71;
    ctx = ctx$71;
    const subject = $rt.unwrap($r144);
    const st = type_or({ o: $std_map.find({ d: ctx.expr_types, key: expr_key({ w: w, e: scrutinee }) }) });
    const before_env = $lower.copy_env({ env: w.env });
    const before_facts = w.facts;
    let earlier = [];
    let takens = $std_list.builder({  });
    let all_return = $std_list.len({ xs: arms }) > 0;
    for (const arm of arms) {
      const failed = negations({ fs: earlier });
      w = { ...w, env: $lower.copy_env({ env: before_env }), facts: [...before_facts, ...failed] };
      let test = app_true({  });
      const [$r147, w$72, lw$72] = pattern_facts({ w: w, lw: lw, ctx: ctx, p: arm.pattern, subject: subject, ty: st });
      w = w$72;
      lw = lw$72;
      const $m146 = $r147;
      $m146$match: {
        if ($m146.tag === "Ok") {
          const value = $m146.value;
          test = value;
          break $m146$match;
        }
        if ($m146.tag === "Err") {
          test = app_true({  });
          break $m146$match;
        }
        $rt.unreachable();
      }
      const [, w$73] = push_fact({ w: w, f: test });
      w = w$73;
      let guard_f = { tag: "None" };
      const $m149 = arm.guard;
      $m149$match: {
        if ($m149.tag === "Some") {
          const value = $m149.value;
          const [$r150, w$74, lw$74, ctx$74] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob26), w: w, lw: lw, ctx: ctx, e: value });
          w = w$74;
          lw = lw$74;
          ctx = ctx$74;
          const g = $rt.unwrap($r150);
          const [, w$75] = push_fact({ w: w, f: g });
          w = w$75;
          guard_f = { tag: "Some", value: g };
          break $m149$match;
        }
        if ($m149.tag === "None") {
          skip({  });
          break $m149$match;
        }
        $rt.unreachable();
      }
      let cond_parts = [...failed, ...[test]];
      const $m152 = guard_f;
      $m152$match: {
        if ($m152.tag === "None") {
          earlier = $std_list.append({ xs: earlier, x: test });
          break $m152$match;
        }
        if ($m152.tag === "Some") {
          const value = $m152.value;
          earlier = $std_list.append({ xs: earlier, x: $formula.and_f({ xs: [test, value] }) });
          cond_parts = [...cond_parts, ...[value]];
          break $m152$match;
        }
        $rt.unreachable();
      }
      const cond = conj({ fs: cond_parts });
      let returns = false;
      const $m153 = arm.body;
      $m153$match: {
        if ($m153.tag === "ArmBlock") {
          const block = $m153.block;
          const [$r154, w$76, lw$76, ctx$76] = w_block({ fuel: $rt.int.sub(fuel, 1, $ob27), w: w, lw: lw, ctx: ctx, b: block });
          w = w$76;
          lw = lw$76;
          ctx = ctx$76;
          $rt.unwrap($r154);
          returns = block_returns({ b: block });
          break $m153$match;
        }
        if ($m153.tag === "ArmStmt") {
          const stmt = $m153.stmt;
          const [$r155, w$77, lw$77, ctx$77] = w_stmt({ fuel: $rt.int.sub(fuel, 1, $ob28), w: w, lw: lw, ctx: ctx, s: stmt });
          w = w$77;
          lw = lw$77;
          ctx = ctx$77;
          $rt.unwrap($r155);
          returns = stmt_returns({ s: stmt });
          break $m153$match;
        }
        $rt.unreachable();
      }
      if (!returns) {
        all_return = false;
        const [, takens$78] = $std_list.push({ b: takens, x: { cond: cond, env: $lower.copy_env({ env: w.env }), learned: drop({ xs: w.facts, n: $std_list.len({ xs: before_facts }) }) } });
        takens = takens$78;
      }
    }
    w = { ...w, env: $lower.copy_env({ env: before_env }), facts: before_facts };
    if (all_return) {
      const [, w$79] = push_fact({ w: w, f: app_false({  }) });
      w = w$79;
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
    }
    const taken_list = $std_list.finish({ b: takens });
    let eqs = $std_map.dict({  });
    for (const d of assigned({ ctx: ctx, w: w, nodes: stmt_nodes({ s: s }) })) {
      const $m159 = $std_map.find({ d: before_env, key: d });
      $m159$match: {
        if ($m159.tag === "None") {
          skip({  });
          break $m159$match;
        }
        if ($m159.tag === "Some") {
          const value = $m159.value;
          const [$r161, w$80, lw$80] = bind({ w: w, lw: lw, ctx: ctx, def: d, name: $context.get_def({ ctx: ctx, id: d }).name, ty: value.ty, init: { tag: "None" } });
          w = w$80;
          lw = lw$80;
          const fresh = $rt.unwrap($r161);
          let i = 0;
          for (const t of taken_list) {
            const tb = $std_map.find({ d: t.env, key: d });
            if (tb.tag === "Some") {
              const [, eqs$81] = $std_map.set({ d: eqs, key: i, value: $std_list.append({ xs: list_or({ o: $std_map.find({ d: eqs, key: i }) }), x: $formula.eq({ a: fresh, b: binding_or({ o: tb }).term }) }) });
              eqs = eqs$81;
            }
            i = $rt.int.add(i, 1, $ob29);
          }
          break $m159$match;
        }
        $rt.unreachable();
      }
    }
    let conds = $std_list.builder({  });
    let i = 0;
    for (const t of taken_list) {
      const [, w$82] = push_fact({ w: w, f: $formula.implies_f({ a: t.cond, b: conj({ fs: [...t.learned, ...list_or({ o: $std_map.find({ d: eqs, key: i }) })] }) }) });
      w = w$82;
      const [, conds$83] = $std_list.push({ b: conds, x: t.cond });
      conds = conds$83;
      i = $rt.int.add(i, 1, $ob30);
    }
    const [, w$84] = push_fact({ w: w, f: $formula.or_f({ xs: $std_list.finish({ b: conds }) }) });
    w = w$84;
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function pattern_facts({ w, lw, ctx, p, subject, ty }) {
  try {
    const $m163 = p;
    $m163$match: {
      if ($m163.tag === "WildcardPat") {
        return [{ tag: "Ok", value: app_true({  }) }, w, lw];
        break $m163$match;
      }
      if ($m163.tag === "BindPat") {
        const name = $m163.name;
        const span = $m163.span;
        const def = or_neg({ o: $std_map.find({ d: ctx.def_of, key: key({ w: w, tag: $defs.tag_pattern, span: span }) }) });
        if (def >= 0) {
          const [$r166, w$85, lw$85] = bind({ w: w, lw: lw, ctx: ctx, def: def, name: name.text, ty: ty, init: { tag: "Some", value: subject } });
          w = w$85;
          lw = lw$85;
          const t = $rt.unwrap($r166);
        }
        return [{ tag: "Ok", value: app_true({  }) }, w, lw];
        break $m163$match;
      }
      if ($m163.tag === "LitPat") {
        const literal = $m163.literal;
        const [$r168, w$86, lw$86] = lower_e({ w: w, lw: lw, ctx: ctx, e: literal });
        w = w$86;
        lw = lw$86;
        return [{ tag: "Ok", value: $formula.eq({ a: subject, b: $rt.unwrap($r168) }) }, w, lw];
        break $m163$match;
      }
      if ($m163.tag === "VariantPat") {
        const fields = $m163.fields;
        const span = $m163.span;
        const [$r170, w$87, lw$87] = variant_facts({ w: w, lw: lw, ctx: ctx, fields: fields, at: span, subject: subject, ty: ty });
        w = w$87;
        lw = lw$87;
        return [$r170, w, lw];
        break $m163$match;
      }
      $rt.unreachable();
    }
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function variant_facts({ w, lw, ctx, fields, at, subject, ty }) {
  try {
    const def = ref_def({ o: $std_map.find({ d: ctx.refs, key: key({ w: w, tag: $defs.tag_pattern, span: at }) }) });
    if (def < 0) {
      return [{ tag: "Err", error: "unresolved pattern" }, w, lw];
    }
    const test = $rt.unwrap($lower.is_variant({ lw: lw, ctx: ctx, term: subject, ty: ty, variant: def }));
    const $m172 = fields;
    $m172$match: {
      if ($m172.tag === "None") {
        skip({  });
        break $m172$match;
      }
      if ($m172.tag === "Some") {
        const value = $m172.value;
        const fs = fields_or({ o: $std_map.find({ d: ctx.fields, key: def }) });
        let i = 0;
        let stop = false;
        for (const pf of value) {
          if (!stop) {
            const $m173 = pf;
            $m173$match: {
              if ($m173.tag === "PatFieldRest") {
                stop = true;
                break $m173$match;
              }
              if ($m173.tag === "PatFieldName") {
                const name = $m173.name;
                const span = $m173.span;
                if (i < $std_list.len({ xs: fs })) {
                  const [$r174, w$88, lw$88] = bind_field({ w: w, lw: lw, ctx: ctx, name: name.text, at: span, f: $std_list.get({ xs: fs, i: i }), subject: subject, ty: ty, owner: def });
                  w = w$88;
                  lw = lw$88;
                  $rt.unwrap($r174);
                }
                i = $rt.int.add(i, 1, $ob31);
                break $m173$match;
              }
              if ($m173.tag === "PatFieldSkip") {
                i = $rt.int.add(i, 1, $ob32);
                break $m173$match;
              }
              $rt.unreachable();
            }
          }
        }
        break $m172$match;
      }
      $rt.unreachable();
    }
    return [{ tag: "Ok", value: test }, w, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function bind_field({ w, lw, ctx, name, at, f, subject, ty, owner }) {
  try {
    const fdef = or_neg({ o: $std_map.find({ d: ctx.def_of, key: key({ w: w, tag: $defs.tag_pattern, span: at }) }) });
    let lookup = f.def;
    if (fdef >= 0) {
      lookup = fdef;
    }
    let ft = f.ty;
    const $m176 = $std_map.find({ d: ctx.decl_types, key: lookup });
    $m176$match: {
      if ($m176.tag === "Some") {
        const value = $m176.value;
        ft = value;
        break $m176$match;
      }
      if ($m176.tag === "None") {
        skip({  });
        break $m176$match;
      }
      $rt.unreachable();
    }
    if (fdef >= 0) {
      const proj = $rt.unwrap($lower.projection_of({ lw: lw, ctx: ctx, term: subject, ty: ty, owner: owner, field: f.name, field_type: ft }));
      const [$r178, w$89, lw$89] = bind({ w: w, lw: lw, ctx: ctx, def: fdef, name: name, ty: ft, init: { tag: "Some", value: proj } });
      w = w$89;
      lw = lw$89;
      const b = $rt.unwrap($r178);
    }
    return [{ tag: "Ok", value: undefined }, w, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function find_source({ w, ctx, at, kind, src }) {
  for (const o of obligations_at({ w: w, ctx: ctx, at: at, kind: kind })) {
    if (or_neg({ o: $context.get_obligation({ ctx: ctx, id: o }).source }) === src) {
      return o;
    }
  }
  return $rt.int.neg(1, $ob33);
}

export function loop_stmt({ fuel, w, lw, ctx, s, cond, clauses, body, at }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const at_key = key({ w: w, tag: $defs.tag_stmt, span: at });
    let invariants = $std_list.builder({  });
    let dec_clause = { tag: "None" };
    for (const c of clauses) {
      if (c.clause === "invariant") {
        const [, invariants$90] = $std_list.push({ b: invariants, x: c });
        invariants = invariants$90;
      }
      if (c.clause === "decreases" && dec_clause.tag === "None") {
        dec_clause = { tag: "Some", value: c };
      }
    }
    const invs = $std_list.finish({ b: invariants });
    for (const inv of invs) {
      const o = find_source({ w: w, ctx: ctx, at: at_key, kind: { tag: "InvariantEntry" }, src: key({ w: w, tag: $defs.tag_sig, span: inv.span }) });
      if (o >= 0) {
        const [$r184, w$91, lw$91] = lower_e({ w: w, lw: lw, ctx: ctx, e: inv.expr });
        w = w$91;
        lw = lw$91;
        const g = $r184;
        try_goal({ w: w, lw: lw, o: o, goal: g });
      }
    }
    const assigned_defs = assigned({ ctx: ctx, w: w, nodes: stmt_nodes({ s: s }) });
    const before_env = $lower.copy_env({ env: w.env });
    const before_facts = w.facts;
    const [$r185, w$92, lw$92] = havoc({ w: w, lw: lw, ctx: ctx, ds: assigned_defs });
    w = w$92;
    lw = lw$92;
    $rt.unwrap($r185);
    for (const inv of invs) {
      const [, w$93, lw$93] = push_maybe({ w: w, lw: lw, ctx: ctx, e: inv.expr });
      w = w$93;
      lw = lw$93;
    }
    const [$r186, w$94, lw$94, ctx$94] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob34), w: w, lw: lw, ctx: ctx, e: cond });
    w = w$94;
    lw = lw$94;
    ctx = ctx$94;
    const c = $rt.unwrap($r186);
    const [, w$95] = push_fact({ w: w, f: c });
    w = w$95;
    let m0 = { tag: "None" };
    let dec_o = $rt.int.neg(1, $ob35);
    const $m188 = dec_clause;
    $m188$match: {
      if ($m188.tag === "Some") {
        const value = $m188.value;
        dec_o = find_source({ w: w, ctx: ctx, at: at_key, kind: { tag: "Decreases" }, src: key({ w: w, tag: $defs.tag_sig, span: value.span }) });
        break $m188$match;
      }
      if ($m188.tag === "None") {
        skip({  });
        break $m188$match;
      }
      $rt.unreachable();
    }
    if (dec_clause.tag === "Some" && dec_o >= 0) {
      const [$r190, w$96, lw$96, ctx$96] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob36), w: w, lw: lw, ctx: ctx, e: clause_expr({ o: dec_clause }) });
      w = w$96;
      lw = lw$96;
      ctx = ctx$96;
      const measure = $rt.unwrap($r190);
      const [$r192, lw$97] = $lower.fresh_const({ lw: lw, prefix: "measure", sort: { tag: "IntS" } });
      lw = lw$97;
      const m = $r192;
      const [, w$98] = push_fact({ w: w, f: $formula.eq({ a: m, b: measure }) });
      w = w$98;
      m0 = { tag: "Some", value: m };
    }
    const [$r194, w$99, lw$99, ctx$99] = w_block({ fuel: $rt.int.sub(fuel, 1, $ob37), w: w, lw: lw, ctx: ctx, b: body });
    w = w$99;
    lw = lw$99;
    ctx = ctx$99;
    $rt.unwrap($r194);
    for (const inv of invs) {
      const o = find_source({ w: w, ctx: ctx, at: at_key, kind: { tag: "InvariantStep" }, src: key({ w: w, tag: $defs.tag_sig, span: inv.span }) });
      if (o >= 0) {
        const [$r196, w$100, lw$100] = lower_e({ w: w, lw: lw, ctx: ctx, e: inv.expr });
        w = w$100;
        lw = lw$100;
        const g = $r196;
        try_goal({ w: w, lw: lw, o: o, goal: g });
      }
    }
    if (dec_clause.tag === "Some" && dec_o >= 0 && m0.tag === "Some") {
      const m = formula_or({ o: m0 });
      const [$r198, w$101, lw$101] = lower_e({ w: w, lw: lw, ctx: ctx, e: clause_expr({ o: dec_clause }) });
      w = w$101;
      lw = lw$101;
      const $m197 = $r198;
      $m197$match: {
        if ($m197.tag === "Ok") {
          const value = $m197.value;
          emit({ w: w, lw: lw, o: dec_o, goal: $formula.and_f({ xs: [cmp({ op: ">=", a: m, b: $formula.int_f({ v: 0 }) }), cmp({ op: "<", a: value, b: m })] }) });
          break $m197$match;
        }
        if ($m197.tag === "Err") {
          const error = $m197.error;
          skip_one({ w: w, o: dec_o, reason: error });
          break $m197$match;
        }
        $rt.unreachable();
      }
    }
    w = { ...w, env: $lower.copy_env({ env: before_env }), facts: before_facts };
    const [$r200, w$102, lw$102] = havoc({ w: w, lw: lw, ctx: ctx, ds: assigned_defs });
    w = w$102;
    lw = lw$102;
    $rt.unwrap($r200);
    for (const inv of invs) {
      const [, w$103, lw$103] = push_maybe({ w: w, lw: lw, ctx: ctx, e: inv.expr });
      w = w$103;
      lw = lw$103;
    }
    const [$r202, w$104, lw$104] = lower_e({ w: w, lw: lw, ctx: ctx, e: cond });
    w = w$104;
    lw = lw$104;
    const $m201 = $r202;
    $m201$match: {
      if ($m201.tag === "Ok") {
        const value = $m201.value;
        const [, w$105] = push_fact({ w: w, f: $formula.not_f({ x: value }) });
        w = w$105;
        break $m201$match;
      }
      if ($m201.tag === "Err") {
        skip({  });
        break $m201$match;
      }
      $rt.unreachable();
    }
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function for_stmt({ fuel, w, lw, ctx, name, domain, body, at }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const def = or_neg({ o: $std_map.find({ d: ctx.def_of, key: key({ w: w, tag: $defs.tag_stmt, span: at }) }) });
    if (def < 0) {
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
    }
    const ty_opt = $std_map.find({ d: ctx.decl_types, key: def });
    if (ty_opt.tag === "None") {
      return [{ tag: "Ok", value: undefined }, w, lw, ctx];
    }
    const ty = type_or({ o: ty_opt });
    const assigned_defs = assigned({ ctx: ctx, w: w, nodes: $walk.nodes_in_block({ b: body, into_verify: false }) });
    const $m207 = domain;
    $m207$match: {
      if ($m207.tag === "RangeDomain") {
        const lo = $m207.lo;
        const hi = $m207.hi;
        const [$r208, w$106, lw$106, ctx$106] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob38), w: w, lw: lw, ctx: ctx, e: lo });
        w = w$106;
        lw = lw$106;
        ctx = ctx$106;
        const lo_f = $rt.unwrap($r208);
        const [$r209, w$107, lw$107, ctx$107] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob39), w: w, lw: lw, ctx: ctx, e: hi });
        w = w$107;
        lw = lw$107;
        ctx = ctx$107;
        const hi_f = $rt.unwrap($r209);
        const [$r210, w$108, lw$108] = havoc({ w: w, lw: lw, ctx: ctx, ds: assigned_defs });
        w = w$108;
        lw = lw$108;
        $rt.unwrap($r210);
        const [$r212, w$109, lw$109] = bind({ w: w, lw: lw, ctx: ctx, def: def, name: name, ty: ty, init: { tag: "None" } });
        w = w$109;
        lw = lw$109;
        const x = $rt.unwrap($r212);
        const [, w$110] = push_fact({ w: w, f: cmp({ op: "<=", a: lo_f, b: x }) });
        w = w$110;
        const [, w$111] = push_fact({ w: w, f: cmp({ op: "<", a: x, b: hi_f }) });
        w = w$111;
        break $m207$match;
      }
      if ($m207.tag === "InDomain") {
        const expr = $m207.expr;
        const [$r213, w$112, lw$112, ctx$112] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob40), w: w, lw: lw, ctx: ctx, e: expr });
        w = w$112;
        lw = lw$112;
        ctx = ctx$112;
        const xs = $rt.unwrap($r213);
        const xs_type = type_or({ o: $std_map.find({ d: ctx.expr_types, key: expr_key({ w: w, e: expr }) }) });
        const [$r214, w$113, lw$113] = havoc({ w: w, lw: lw, ctx: ctx, ds: assigned_defs });
        w = w$113;
        lw = lw$113;
        $rt.unwrap($r214);
        const [$r216, w$114, lw$114] = for_in_bind({ w: w, lw: lw, ctx: ctx, def: def, name: name, ty: ty, xs: xs, xs_type: xs_type, e: expr });
        w = w$114;
        lw = lw$114;
        const $m215 = $r216;
        $m215$match: {
          if ($m215.tag === "Ok") {
            skip({  });
            break $m215$match;
          }
          if ($m215.tag === "Err") {
            const [$r218, w$115, lw$115] = bind({ w: w, lw: lw, ctx: ctx, def: def, name: name, ty: ty, init: { tag: "None" } });
            w = w$115;
            lw = lw$115;
            const b = $rt.unwrap($r218);
            break $m215$match;
          }
          $rt.unreachable();
        }
        break $m207$match;
      }
      $rt.unreachable();
    }
    const [$r219, w$116, lw$116, ctx$116] = w_block({ fuel: $rt.int.sub(fuel, 1, $ob41), w: w, lw: lw, ctx: ctx, b: body });
    w = w$116;
    lw = lw$116;
    ctx = ctx$116;
    $rt.unwrap($r219);
    const [$r220, w$117, lw$117] = havoc({ w: w, lw: lw, ctx: ctx, ds: assigned_defs });
    w = w$117;
    lw = lw$117;
    $rt.unwrap($r220);
    let env = w.env;
    const [, env$118] = $std_map.remove({ d: env, key: def });
    env = env$118;
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function for_in_bind({ w, lw, ctx, def, name, ty, xs, xs_type, e }) {
  try {
    const [$r223, lw$119] = $lower.fresh_const({ lw: lw, prefix: "k", sort: { tag: "IntS" } });
    lw = lw$119;
    const k = $r223;
    const elem = $rt.unwrap($lower.list_get({ lw: lw, ctx: ctx, term: xs, ty: xs_type, index: k }));
    const len = $rt.unwrap($lower.list_len({ lw: lw, ctx: ctx, term: xs, ty: xs_type }));
    const [, w$120] = push_fact({ w: w, f: cmp({ op: "<=", a: $formula.int_f({ v: 0 }), b: k }) });
    w = w$120;
    const [, w$121] = push_fact({ w: w, f: cmp({ op: "<", a: k, b: len }) });
    w = w$121;
    for (const o of obligations_at({ w: w, ctx: ctx, at: expr_key({ w: w, e: e }), kind: { tag: "Refinement" } })) {
      const [$r225, lw$122] = element_goal({ w: w, lw: lw, ctx: ctx, ty: ty, xs: xs, xs_type: xs_type });
      lw = lw$122;
      const g = $r225;
      try_goal({ w: w, lw: lw, o: o, goal: g });
    }
    const [$r227, w$123, lw$123] = bind({ w: w, lw: lw, ctx: ctx, def: def, name: name, ty: ty, init: { tag: "Some", value: elem } });
    w = w$123;
    lw = lw$123;
    const b = $rt.unwrap($r227);
    return [{ tag: "Ok", value: undefined }, w, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function element_goal({ w, lw, ctx, ty, xs, xs_type }) {
  try {
    const [$r230, lw$124] = $lower.fresh_const({ lw: lw, prefix: "kk", sort: { tag: "IntS" } });
    lw = lw$124;
    const kk = $r230;
    const len = $rt.unwrap($lower.list_len({ lw: lw, ctx: ctx, term: xs, ty: xs_type }));
    const in_range = $formula.and_f({ xs: [cmp({ op: "<=", a: $formula.int_f({ v: 0 }), b: kk }), cmp({ op: "<", a: kk, b: len })] });
    const got = $rt.unwrap($lower.list_get({ lw: lw, ctx: ctx, term: xs, ty: xs_type, index: kk }));
    const [$r231, lw$125] = $lower.refinement_of({ fuel: $lower.max_depth, lw: lw, ctx: ctx, ty: ty, term: got, env: w.env });
    lw = lw$125;
    const r = $rt.unwrap($r231);
    return [{ tag: "Ok", value: $formula.implies_f({ a: in_range, b: r }) }, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, lw];
    throw $e;
  }
}

export function expr_stmt({ fuel, w, lw, ctx, e }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const [$r234, w$126, lw$126, ctx$126] = expr_obligations({ fuel: $rt.int.sub(fuel, 1, $ob42), w: w, lw: lw, ctx: ctx, e: e });
    w = w$126;
    lw = lw$126;
    ctx = ctx$126;
    const v = $rt.unwrap($r234);
    const assertions = obligations_at({ w: w, ctx: ctx, at: expr_key({ w: w, e: e }), kind: { tag: "Assertion" } });
    for (const o of assertions) {
      emit({ w: w, lw: lw, o: o, goal: v });
    }
    if ($std_list.len({ xs: assertions }) > 0) {
      const [, w$127] = push_fact({ w: w, f: v });
      w = w$127;
    }
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function node_key({ w, n }) {
  const $m237 = n;
  $m237$match: {
    if ($m237.tag === "NExpr") {
      const e = $m237.e;
      return expr_key({ w: w, e: e });
      break $m237$match;
    }
    if ($m237.tag === "NStmt") {
      const s = $m237.s;
      return key({ w: w, tag: $defs.tag_stmt, span: $parser.span_of_stmt({ st: s }) });
      break $m237$match;
    }
    if ($m237.tag === "NContract") {
      const c = $m237.c;
      return key({ w: w, tag: $defs.tag_sig, span: c.span });
      break $m237$match;
    }
    if ($m237.tag === "NParam") {
      const p = $m237.p;
      return key({ w: w, tag: $defs.tag_sig, span: p.span });
      break $m237$match;
    }
    if (true) {
      return $rt.int.neg(1, $ob43);
      break $m237$match;
    }
    $rt.unreachable();
  }
}

export function skip_under({ w, ctx, e, reason, inner }) {
  let first = true;
  for (const n of $walk.nodes_in_expr({ e: e, into_verify: true })) {
    if (!(first && inner)) {
      const k = node_key({ w: w, n: n });
      if (k >= 0) {
        for (const o of ids_or({ o: $std_map.find({ d: ctx.obligations_at, key: k }) })) {
          if ($std_map.contains({ d: w.pending, key: o })) {
            skip_one({ w: w, o: o, reason: reason });
          }
        }
      }
    }
    first = false;
  }
  return undefined;
}

export function safe_sort({ lw, ctx, w, e }) {
  const $m238 = $lower.sort_of({ lw: lw, ctx: ctx, t: type_or({ o: $std_map.find({ d: ctx.expr_types, key: expr_key({ w: w, e: e }) }) }) });
  $m238$match: {
    if ($m238.tag === "Ok") {
      const value = $m238.value;
      return value;
      break $m238$match;
    }
    if ($m238.tag === "Err") {
      return { tag: "IntS" };
      break $m238$match;
    }
    $rt.unreachable();
  }
}

export function term_of({ lw, w, e }) {
  return $std_map.find({ d: lw.terms, key: expr_key({ w: w, e: e }) });
}

export function expr_obligations({ fuel, w, lw, ctx, e }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const [$r242, w$128, lw$128] = lower_e({ w: w, lw: lw, ctx: ctx, e: e });
    w = w$128;
    lw = lw$128;
    const $m241 = $r242;
    $m241$match: {
      if ($m241.tag === "Err") {
        const error = $m241.error;
        skip_under({ w: w, ctx: ctx, e: e, reason: error, inner: false });
        const [$r243, lw$129] = $lower.fresh_const({ lw: lw, prefix: "unlowered", sort: safe_sort({ lw: lw, ctx: ctx, w: w, e: e }) });
        lw = lw$129;
        return [{ tag: "Ok", value: $r243 }, w, lw, ctx];
        break $m241$match;
      }
      if ($m241.tag === "Ok") {
        const value = $m241.value;
        const [$r245, w$130, lw$130, ctx$130] = discharge_under({ fuel: $rt.int.sub(fuel, 1, $ob44), w: w, lw: lw, ctx: ctx, e: e });
        w = w$130;
        lw = lw$130;
        ctx = ctx$130;
        $rt.unwrap($r245);
        return [{ tag: "Ok", value: value }, w, lw, ctx];
        break $m241$match;
      }
      $rt.unreachable();
    }
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function child_exprs({ e }) {
  let out = $std_list.builder({  });
  const $m247 = e;
  $m247$match: {
    if ($m247.tag === "Ctor") {
      const args = $m247.args;
      const fields = $m247.fields;
      const $m248 = args;
      $m248$match: {
        if ($m248.tag === "Some") {
          const value = $m248.value;
          for (const a of value) {
            const [, out$131] = $std_list.push({ b: out, x: a.value });
            out = out$131;
          }
          break $m248$match;
        }
        if ($m248.tag === "None") {
          skip({  });
          break $m248$match;
        }
        $rt.unreachable();
      }
      const $m249 = fields;
      $m249$match: {
        if ($m249.tag === "Some") {
          const value = $m249.value;
          for (const f of value) {
            const [, out$132] = $std_list.push({ b: out, x: f.value });
            out = out$132;
          }
          break $m249$match;
        }
        if ($m249.tag === "None") {
          skip({  });
          break $m249$match;
        }
        $rt.unreachable();
      }
      break $m247$match;
    }
    if ($m247.tag === "RecordUpdate") {
      const base = $m247.base;
      const fields = $m247.fields;
      const [, out$133] = $std_list.push({ b: out, x: base });
      out = out$133;
      for (const f of fields) {
        const [, out$134] = $std_list.push({ b: out, x: f.value });
        out = out$134;
      }
      break $m247$match;
    }
    if ($m247.tag === "ListLit") {
      const elems = $m247.elems;
      for (const x of elems) {
        const [, out$135] = $std_list.push({ b: out, x: x });
        out = out$135;
      }
      break $m247$match;
    }
    if ($m247.tag === "Try") {
      const expr = $m247.expr;
      const else_ = $m247.else_;
      const [, out$136] = $std_list.push({ b: out, x: expr });
      out = out$136;
      const $m250 = else_;
      $m250$match: {
        if ($m250.tag === "Some") {
          const value = $m250.value;
          const [, out$137] = $std_list.push({ b: out, x: value.expr });
          out = out$137;
          break $m250$match;
        }
        if ($m250.tag === "None") {
          skip({  });
          break $m250$match;
        }
        $rt.unreachable();
      }
      break $m247$match;
    }
    if ($m247.tag === "Fake") {
      const fields = $m247.fields;
      for (const f of fields) {
        const [, out$138] = $std_list.push({ b: out, x: f.value });
        out = out$138;
      }
      break $m247$match;
    }
    if ($m247.tag === "FieldAccess") {
      const object = $m247.object;
      const [, out$139] = $std_list.push({ b: out, x: object });
      out = out$139;
      break $m247$match;
    }
    if ($m247.tag === "Call") {
      const callee = $m247.callee;
      const args = $m247.args;
      const [, out$140] = $std_list.push({ b: out, x: callee });
      out = out$140;
      for (const a of args) {
        const [, out$141] = $std_list.push({ b: out, x: a.value });
        out = out$141;
      }
      break $m247$match;
    }
    if ($m247.tag === "Unary") {
      const operand = $m247.operand;
      const [, out$142] = $std_list.push({ b: out, x: operand });
      out = out$142;
      break $m247$match;
    }
    if ($m247.tag === "Binary") {
      const left = $m247.left;
      const right = $m247.right;
      const [, out$143] = $std_list.push({ b: out, x: left });
      out = out$143;
      const [, out$144] = $std_list.push({ b: out, x: right });
      out = out$144;
      break $m247$match;
    }
    if ($m247.tag === "And") {
      const operands = $m247.operands;
      for (const x of operands) {
        const [, out$145] = $std_list.push({ b: out, x: x });
        out = out$145;
      }
      break $m247$match;
    }
    if ($m247.tag === "Or") {
      const operands = $m247.operands;
      for (const x of operands) {
        const [, out$146] = $std_list.push({ b: out, x: x });
        out = out$146;
      }
      break $m247$match;
    }
    if ($m247.tag === "Is") {
      const expr = $m247.expr;
      const pattern = $m247.pattern;
      const [, out$147] = $std_list.push({ b: out, x: expr });
      out = out$147;
      const $m251 = pattern;
      $m251$match: {
        if ($m251.tag === "LitPat") {
          const literal = $m251.literal;
          const [, out$148] = $std_list.push({ b: out, x: literal });
          out = out$148;
          break $m251$match;
        }
        if (true) {
          skip({  });
          break $m251$match;
        }
        $rt.unreachable();
      }
      break $m247$match;
    }
    if (true) {
      skip({  });
      break $m247$match;
    }
    $rt.unreachable();
  }
  return $std_list.finish({ b: out });
}

export function discharge_under({ fuel, w, lw, ctx, e }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const $m253 = e;
    $m253$match: {
      if ($m253.tag === "And") {
        const operands = $m253.operands;
        const [$r254, w$149, lw$149, ctx$149] = junction({ fuel: $rt.int.sub(fuel, 1, $ob45), w: w, lw: lw, ctx: ctx, operands: operands, negate: false });
        w = w$149;
        lw = lw$149;
        ctx = ctx$149;
        return [$r254, w, lw, ctx];
        break $m253$match;
      }
      if ($m253.tag === "Or") {
        const operands = $m253.operands;
        const [$r255, w$150, lw$150, ctx$150] = junction({ fuel: $rt.int.sub(fuel, 1, $ob46), w: w, lw: lw, ctx: ctx, operands: operands, negate: true });
        w = w$150;
        lw = lw$150;
        ctx = ctx$150;
        return [$r255, w, lw, ctx];
        break $m253$match;
      }
      if ($m253.tag === "Binary") {
        const op = $m253.op;
        const left = $m253.left;
        const right = $m253.right;
        if (op === "implies") {
          const [$r256, w$151, lw$151, ctx$151] = discharge_under({ fuel: $rt.int.sub(fuel, 1, $ob47), w: w, lw: lw, ctx: ctx, e: left });
          w = w$151;
          lw = lw$151;
          ctx = ctx$151;
          $rt.unwrap($r256);
          const saved = w.facts;
          const $m257 = term_of({ lw: lw, w: w, e: left });
          $m257$match: {
            if ($m257.tag === "Some") {
              const value = $m257.value;
              const [, w$152] = push_fact({ w: w, f: value });
              w = w$152;
              break $m257$match;
            }
            if ($m257.tag === "None") {
              skip({  });
              break $m257$match;
            }
            $rt.unreachable();
          }
          const [$r258, w$153, lw$153, ctx$153] = discharge_under({ fuel: $rt.int.sub(fuel, 1, $ob48), w: w, lw: lw, ctx: ctx, e: right });
          w = w$153;
          lw = lw$153;
          ctx = ctx$153;
          $rt.unwrap($r258);
          w = { ...w, facts: saved };
          overflow_obligation({ w: w, lw: lw, ctx: ctx, e: e });
          return [{ tag: "Ok", value: undefined }, w, lw, ctx];
        }
        overflow_obligation({ w: w, lw: lw, ctx: ctx, e: e });
        const [$r261, w$154, lw$154, ctx$154] = discharge_under({ fuel: $rt.int.sub(fuel, 1, $ob49), w: w, lw: lw, ctx: ctx, e: left });
        w = w$154;
        lw = lw$154;
        ctx = ctx$154;
        $rt.unwrap($r261);
        const [$r262, w$155, lw$155, ctx$155] = discharge_under({ fuel: $rt.int.sub(fuel, 1, $ob50), w: w, lw: lw, ctx: ctx, e: right });
        w = w$155;
        lw = lw$155;
        ctx = ctx$155;
        $rt.unwrap($r262);
        return [{ tag: "Ok", value: undefined }, w, lw, ctx];
        break $m253$match;
      }
      if ($m253.tag === "Closure") {
        skip_under({ w: w, ctx: ctx, e: e, reason: "inside a quantifier or closure", inner: true });
        return [{ tag: "Ok", value: undefined }, w, lw, ctx];
        break $m253$match;
      }
      if ($m253.tag === "Quantifier") {
        skip_under({ w: w, ctx: ctx, e: e, reason: "inside a quantifier or closure", inner: true });
        return [{ tag: "Ok", value: undefined }, w, lw, ctx];
        break $m253$match;
      }
      if ($m253.tag === "Recover") {
        skip_under({ w: w, ctx: ctx, e: e, reason: "inside a quantifier or closure", inner: true });
        return [{ tag: "Ok", value: undefined }, w, lw, ctx];
        break $m253$match;
      }
      if ($m253.tag === "Call") {
        const [$r267, w$156, lw$156, ctx$156] = call_obligations({ w: w, lw: lw, ctx: ctx, e: e });
        w = w$156;
        lw = lw$156;
        ctx = ctx$156;
        $rt.unwrap($r267);
        break $m253$match;
      }
      if ($m253.tag === "Ctor") {
        const [$r268, w$157, lw$157] = field_obligations({ w: w, lw: lw, ctx: ctx, e: e });
        w = w$157;
        lw = lw$157;
        $rt.unwrap($r268);
        break $m253$match;
      }
      if ($m253.tag === "RecordUpdate") {
        const [$r269, w$158, lw$158] = field_obligations({ w: w, lw: lw, ctx: ctx, e: e });
        w = w$158;
        lw = lw$158;
        $rt.unwrap($r269);
        break $m253$match;
      }
      if (true) {
        skip({  });
        break $m253$match;
      }
      $rt.unreachable();
    }
    for (const c of child_exprs({ e: e })) {
      const [$r270, w$159, lw$159, ctx$159] = discharge_under({ fuel: $rt.int.sub(fuel, 1, $ob51), w: w, lw: lw, ctx: ctx, e: c });
      w = w$159;
      lw = lw$159;
      ctx = ctx$159;
      $rt.unwrap($r270);
    }
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function junction({ fuel, w, lw, ctx, operands, negate }) {
  try {
    if (fuel === 0) {
      return [{ tag: "Err", error: "walk too deep" }, w, lw, ctx];
    }
    const saved = w.facts;
    for (const operand of operands) {
      const [$r273, w$160, lw$160, ctx$160] = discharge_under({ fuel: $rt.int.sub(fuel, 1, $ob52), w: w, lw: lw, ctx: ctx, e: operand });
      w = w$160;
      lw = lw$160;
      ctx = ctx$160;
      $rt.unwrap($r273);
      const $m274 = term_of({ lw: lw, w: w, e: operand });
      $m274$match: {
        if ($m274.tag === "Some") {
          const value = $m274.value;
          if (negate) {
            const [, w$161] = push_fact({ w: w, f: $formula.not_f({ x: value }) });
            w = w$161;
          } else {
            const [, w$162] = push_fact({ w: w, f: value });
            w = w$162;
          }
          break $m274$match;
        }
        if ($m274.tag === "None") {
          skip({  });
          break $m274$match;
        }
        $rt.unreachable();
      }
    }
    w = { ...w, facts: saved };
    return [{ tag: "Ok", value: undefined }, w, lw, ctx];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw, ctx];
    throw $e;
  }
}

export function lower_callee({ lw, ctx, e, file, subst, env }) {
  const [, lw$163] = $lower.push_subst({ lw: lw, subst: subst });
  lw = lw$163;
  const saved = lw.file;
  lw = { ...lw, file: file };
  const [$r278, lw$164] = $lower.lower({ fuel: $lower.max_depth, lw: lw, ctx: ctx, e: e, env: env });
  lw = lw$164;
  const r = $r278;
  lw = { ...lw, file: saved };
  const [, lw$165] = $lower.pop_subst({ lw: lw });
  lw = lw$165;
  return [r, lw];
}

export function call_obligations({ w, lw, ctx, e }) {
  const $m280 = e;
  $m280$match: {
    if ($m280.tag === "Call") {
      const args = $m280.args;
      const span = $m280.span;
      const call_key = key({ w: w, tag: $defs.tag_expr, span: span });
      const info = $std_map.find({ d: lw.calls, key: call_key });
      for (const o of obligations_at({ w: w, ctx: ctx, at: call_key, kind: { tag: "Decreases" } })) {
        const [, lw$166, ctx$166] = call_decreases({ w: w, lw: lw, ctx: ctx, o: o, info: info, at: span });
        lw = lw$166;
        ctx = ctx$166;
      }
      for (const o of obligations_at({ w: w, ctx: ctx, at: call_key, kind: { tag: "Requires" } })) {
        const [, lw$167] = call_requires({ w: w, lw: lw, ctx: ctx, o: o, info: info });
        lw = lw$167;
      }
      for (const a of args) {
        for (const o of obligations_at({ w: w, ctx: ctx, at: expr_key({ w: w, e: a.value }), kind: { tag: "Refinement" } })) {
          const [, lw$168] = arg_refinement({ w: w, lw: lw, ctx: ctx, o: o, info: info, a: a });
          lw = lw$168;
        }
      }
      break $m280$match;
    }
    if (true) {
      skip({  });
      break $m280$match;
    }
    $rt.unreachable();
  }
  return [{ tag: "Ok", value: undefined }, w, lw, ctx];
}

export function clause_of({ ctx, o }) {
  const src = or_neg({ o: $context.get_obligation({ ctx: ctx, id: o }).source });
  if (src < 0) {
    return { tag: "None" };
  }
  return $std_map.find({ d: ctx.contract_nodes, key: src });
}

export function call_decreases({ w, lw, ctx, o, info, at }) {
  const ob = $context.get_obligation({ ctx: ctx, id: o });
  const clause = clause_of({ ctx: ctx, o: o });
  if (info.tag === "None" || clause.tag === "None") {
    skip_one({ w: w, o: o, reason: "call not lowered" });
    return [undefined, lw, ctx];
  }
  if (w.measure0.tag === "None") {
    skip_one({ w: w, o: o, reason: "measure not lowered" });
    return [undefined, lw, ctx];
  }
  const ci = info_or({ o: info });
  const c = contract_or({ o: clause });
  const m0 = formula_or({ o: w.measure0 });
  const src = or_neg({ o: ob.source });
  const callee_file = $lower.pred_file({ k: src });
  const mt = $std_map.find({ d: ctx.expr_types, key: $defs.node_key({ file: callee_file, tag: $defs.tag_expr, span: $parser.span_of_expr({ e: c.expr }) }) });
  let structural = false;
  const $m286 = mt;
  $m286$match: {
    if ($m286.tag === "Some") {
      const value = $m286.value;
      const ms = $types.strip({ t: value });
      structural = !(ms.tag === "Prim" && ($types.prim_name({ t: ms }) === "Int" || $types.prim_name({ t: ms }) === "Duration"));
      break $m286$match;
    }
    if ($m286.tag === "None") {
      skip({  });
      break $m286$match;
    }
    $rt.unreachable();
  }
  const [$r287, lw$169] = lower_callee({ lw: lw, ctx: ctx, e: c.expr, file: callee_file, subst: ci.subst, env: ci.args });
  lw = lw$169;
  const arg_term = $r287;
  if (structural) {
    let verdict = 2;
    const $m288 = arg_term;
    $m288$match: {
      if ($m288.tag === "Ok") {
        const value = $m288.value;
        if ($lower.is_proper_part({ lw: lw, term: value, whole: m0 })) {
          verdict = 0;
        } else {
          if ($lower.is_same_part({ lw: lw, term: value, whole: m0 })) {
            verdict = 1;
          }
        }
        break $m288$match;
      }
      if ($m288.tag === "Err") {
        verdict = 2;
        break $m288$match;
      }
      $rt.unreachable();
    }
    if (verdict === 0) {
      const [, ctx$170] = $context.set_obligation({ ctx: ctx, o: { ...ob, status: { tag: "Proved" }, by: { tag: "Some", value: "structural order" } } });
      ctx = ctx$170;
    } else {
      if (verdict === 1) {
        const [, ctx$171] = $context.set_obligation({ ctx: ctx, o: { ...ob, status: { tag: "Checked" }, by: { tag: "Some", value: "equal argument" } } });
        ctx = ctx$171;
      } else {
        const [, ctx$172] = $context.set_obligation({ ctx: ctx, o: { ...ob, status: { tag: "Failed" }, by: { tag: "Some", value: "not a part of the measure" } } });
        ctx = ctx$172;
        const [, ctx$173] = $context.report({ ctx: ctx, d: $report.diagnostic_for({ code: "E0344", file: w.file, span: at, def_name: { tag: "Some", value: w.def.name }, detail: "the argument of this recursive call is not a field, or an element of a list field, of the measure `" + measure_text({ t: ob.text }) + "` reached by pattern matching or field access (§5.1)", obligation: { kind: $obligations.kind_text({ k: ob.kind }), text: ob.text, status: "unprovable", has_counterexample: false, counterexample: [] } }) });
        ctx = ctx$173;
      }
    }
    return [undefined, lw, ctx];
  }
  const $m300 = arg_term;
  $m300$match: {
    if ($m300.tag === "Ok") {
      const value = $m300.value;
      emit({ w: w, lw: lw, o: o, goal: cmp({ op: "<", a: value, b: m0 }) });
      break $m300$match;
    }
    if ($m300.tag === "Err") {
      const error = $m300.error;
      skip_one({ w: w, o: o, reason: error });
      break $m300$match;
    }
    $rt.unreachable();
  }
  return [undefined, lw, ctx];
  return [undefined, lw, ctx];
}

export function call_requires({ w, lw, ctx, o, info }) {
  const clause = clause_of({ ctx: ctx, o: o });
  if (info.tag === "None" || clause.tag === "None") {
    skip_one({ w: w, o: o, reason: "call not lowered" });
    return [undefined, lw];
  }
  const ci = info_or({ o: info });
  const c = contract_or({ o: clause });
  const src = or_neg({ o: $context.get_obligation({ ctx: ctx, id: o }).source });
  const [$r301, lw$174] = lower_callee({ lw: lw, ctx: ctx, e: c.expr, file: $lower.pred_file({ k: src }), subst: ci.subst, env: ci.args });
  lw = lw$174;
  const g = $r301;
  try_goal({ w: w, lw: lw, o: o, goal: g });
  return [undefined, lw];
  return [undefined, lw];
}

export function arg_refinement({ w, lw, ctx, o, info, a }) {
  const term = term_of({ lw: lw, w: w, e: a.value });
  let target = { tag: "None" };
  const $m303 = info;
  $m303$match: {
    if ($m303.tag === "Some") {
      const value = $m303.value;
      target = $std_map.find({ d: value.param_types, key: a.name.text });
      break $m303$match;
    }
    if ($m303.tag === "None") {
      skip({  });
      break $m303$match;
    }
    $rt.unreachable();
  }
  if (term.tag === "None" || target.tag === "None" || info.tag === "None") {
    skip_one({ w: w, o: o, reason: "argument not lowered" });
    return [undefined, lw];
  }
  const ci = info_or({ o: info });
  let callee_env = $lower.copy_env({ env: w.env });
  for (const pd of $std_map.keys({ d: ci.args })) {
    const $m304 = $std_map.find({ d: ci.args, key: pd });
    $m304$match: {
      if ($m304.tag === "Some") {
        const value = $m304.value;
        const [, callee_env$175] = $std_map.set({ d: callee_env, key: pd, value: value });
        callee_env = callee_env$175;
        break $m304$match;
      }
      if ($m304.tag === "None") {
        skip({  });
        break $m304$match;
      }
      $rt.unreachable();
    }
  }
  const [, lw$176] = $lower.push_subst({ lw: lw, subst: ci.subst });
  lw = lw$176;
  const [$r305, lw$177] = $lower.refinement_of({ fuel: $lower.max_depth, lw: lw, ctx: ctx, ty: type_or({ o: target }), term: formula_or({ o: term }), env: callee_env });
  lw = lw$177;
  const g = $r305;
  const [, lw$178] = $lower.pop_subst({ lw: lw });
  lw = lw$178;
  try_goal({ w: w, lw: lw, o: o, goal: g });
  return [undefined, lw];
  return [undefined, lw];
}

export function overflow_obligation({ w, lw, ctx, e }) {
  const $m306 = e;
  $m306$match: {
    if ($m306.tag === "Binary") {
      const op = $m306.op;
      const right = $m306.right;
      const span = $m306.span;
      for (const o of obligations_at({ w: w, ctx: ctx, at: key({ w: w, tag: $defs.tag_expr, span: span }), kind: { tag: "Overflow" } })) {
        const term = term_of({ lw: lw, w: w, e: e });
        const r = term_of({ lw: lw, w: w, e: right });
        if (term.tag === "None" || r.tag === "None") {
          skip_one({ w: w, o: o, reason: "arithmetic not lowered" });
        } else {
          if (op === "/" || op === "%") {
            emit({ w: w, lw: lw, o: o, goal: $formula.not_f({ x: $formula.eq({ a: formula_or({ o: r }), b: $formula.int_f({ v: 0 }) }) }) });
          } else {
            const t = formula_or({ o: term });
            emit({ w: w, lw: lw, o: o, goal: $formula.and_f({ xs: [cmp({ op: "<=", a: { tag: "LitF", text: "(- 9007199254740992)" }, b: t }), cmp({ op: "<=", a: t, b: { tag: "LitF", text: "9007199254740992" } })] }) });
          }
        }
      }
      break $m306$match;
    }
    if (true) {
      skip({  });
      break $m306$match;
    }
    $rt.unreachable();
  }
  return undefined;
}

export function find_field({ fs, name }) {
  for (const f of fs) {
    if (f.name === name) {
      return { tag: "Some", value: f };
    }
  }
  return { tag: "None" };
}

export function field_obligations({ w, lw, ctx, e }) {
  try {
    const ctor_term = term_of({ lw: lw, w: w, e: e });
    const ty_opt = $std_map.find({ d: ctx.expr_types, key: expr_key({ w: w, e: e }) });
    let inits = $std_list.builder({  });
    let owner = $rt.int.neg(1, $ob53);
    const $m312 = e;
    $m312$match: {
      if ($m312.tag === "Ctor") {
        const args = $m312.args;
        const fields = $m312.fields;
        const span = $m312.span;
        const $m313 = args;
        $m313$match: {
          if ($m313.tag === "Some") {
            const value = $m313.value;
            for (const a of value) {
              const [, inits$179] = $std_list.push({ b: inits, x: { name: a.name.text, value: a.value } });
              inits = inits$179;
            }
            break $m313$match;
          }
          if ($m313.tag === "None") {
            skip({  });
            break $m313$match;
          }
          $rt.unreachable();
        }
        const $m315 = fields;
        $m315$match: {
          if ($m315.tag === "Some") {
            const value = $m315.value;
            for (const f of value) {
              const [, inits$180] = $std_list.push({ b: inits, x: { name: f.name.text, value: f.value } });
              inits = inits$180;
            }
            break $m315$match;
          }
          if ($m315.tag === "None") {
            skip({  });
            break $m315$match;
          }
          $rt.unreachable();
        }
        owner = ref_def({ o: $std_map.find({ d: ctx.refs, key: key({ w: w, tag: $defs.tag_expr, span: span }) }) });
        break $m312$match;
      }
      if ($m312.tag === "RecordUpdate") {
        const fields = $m312.fields;
        for (const f of fields) {
          const [, inits$181] = $std_list.push({ b: inits, x: { name: f.name.text, value: f.value } });
          inits = inits$181;
        }
        const $m318 = ty_opt;
        $m318$match: {
          if ($m318.tag === "Some") {
            const value = $m318.value;
            const s = $types.strip({ t: value });
            if (s.tag === "RecordT") {
              owner = $types.def_of({ t: s });
            }
            break $m318$match;
          }
          if ($m318.tag === "None") {
            skip({  });
            break $m318$match;
          }
          $rt.unreachable();
        }
        break $m312$match;
      }
      if (true) {
        return [{ tag: "Ok", value: undefined }, w, lw];
        break $m312$match;
      }
      $rt.unreachable();
    }
    for (const init of $std_list.finish({ b: inits })) {
      for (const o of obligations_at({ w: w, ctx: ctx, at: expr_key({ w: w, e: init.value }), kind: { tag: "Refinement" } })) {
        const value_term = term_of({ lw: lw, w: w, e: init.value });
        if (ctor_term.tag === "None" || value_term.tag === "None" || owner < 0 || ty_opt.tag === "None") {
          skip_one({ w: w, o: o, reason: "constructor not lowered" });
        } else {
          const fs = fields_or({ o: $std_map.find({ d: ctx.fields, key: owner }) });
          const $m321 = find_field({ fs: fs, name: init.name });
          $m321$match: {
            if ($m321.tag === "None") {
              skip_one({ w: w, o: o, reason: "unknown field" });
              break $m321$match;
            }
            if ($m321.tag === "Some") {
              const value = $m321.value;
              let field_env = $lower.copy_env({ env: w.env });
              for (const f of fs) {
                const proj = $rt.unwrap($lower.projection_of({ lw: lw, ctx: ctx, term: formula_or({ o: ctor_term }), ty: type_or({ o: ty_opt }), owner: owner, field: f.name, field_type: f.ty }));
                const [, field_env$182] = $std_map.set({ d: field_env, key: f.def, value: { term: proj, ty: f.ty } });
                field_env = field_env$182;
              }
              const [$r323, lw$183] = $lower.refinement_of({ fuel: $lower.max_depth, lw: lw, ctx: ctx, ty: value.ty, term: formula_or({ o: value_term }), env: field_env });
              lw = lw$183;
              const g = $r323;
              try_goal({ w: w, lw: lw, o: o, goal: g });
              break $m321$match;
            }
            $rt.unreachable();
          }
        }
      }
    }
    return [{ tag: "Ok", value: undefined }, w, lw];
  } catch ($e) {
    if ($e instanceof $rt.EarlyReturn) return [$e.value, w, lw];
    throw $e;
  }
}

export function flow_goal({ w, lw, ctx, e, term, ty }) {
  for (const o of obligations_at({ w: w, ctx: ctx, at: expr_key({ w: w, e: e }), kind: { tag: "Refinement" } })) {
    const [$r326, lw$184] = $lower.refinement_of({ fuel: $lower.max_depth, lw: lw, ctx: ctx, ty: ty, term: term, env: w.env });
    lw = lw$184;
    const g = $r326;
    try_goal({ w: w, lw: lw, o: o, goal: g });
  }
  return [undefined, w, lw];
  return [undefined, w, lw];
}

export function representation_goals({ w, lw, ctx, at, ty }) {
  for (const o of obligations_at({ w: w, ctx: ctx, at: at, kind: { tag: "Representation" } })) {
    const [$r329, lw$185] = $lower.fresh_const({ lw: lw, prefix: "rep", sort: { tag: "IntS" } });
    lw = lw$185;
    const x = $r329;
    const [, lw$186] = $lower.type_facts({ fuel: $lower.max_depth, lw: lw, ctx: ctx, term: x, ty: ty, env: w.env });
    lw = lw$186;
    emit({ w: w, lw: lw, o: o, goal: $formula.and_f({ xs: [cmp({ op: ">=", a: x, b: $formula.int_f({ v: 0 - safe_max }) }), cmp({ op: "<=", a: x, b: $formula.int_f({ v: safe_max }) })] }) });
  }
  return [undefined, w, lw];
  return [undefined, w, lw];
}

export function obligations_at({ w, ctx, at, kind }) {
  let out = $std_list.builder({  });
  for (const id of ids_or({ o: $std_map.find({ d: ctx.obligations_at, key: at }) })) {
    if ($std_map.contains({ d: w.pending, key: id }) && same_kind({ a: $context.get_obligation({ ctx: ctx, id: id }).kind, b: kind })) {
      const [, out$187] = $std_list.push({ b: out, x: id });
      out = out$187;
    }
  }
  return $std_list.finish({ b: out });
}

export function try_goal({ w, lw, o, goal }) {
  const $m330 = goal;
  $m330$match: {
    if ($m330.tag === "Ok") {
      const value = $m330.value;
      emit({ w: w, lw: lw, o: o, goal: value });
      break $m330$match;
    }
    if ($m330.tag === "Err") {
      const error = $m330.error;
      skip_one({ w: w, o: o, reason: error });
      break $m330$match;
    }
    $rt.unreachable();
  }
  return undefined;
}

export function emit({ w, lw, o, goal }) {
  if (!$std_map.contains({ d: w.pending, key: o })) {
    return undefined;
  }
  let pending = w.pending;
  const [, pending$188] = $std_map.remove({ d: pending, key: o });
  pending = pending$188;
  let built = w.built;
  const [, built$189] = $std_map.set({ d: built, key: o, value: { id: o, lw: lw, facts: w.facts, goal: goal, names: w.names } });
  built = built$189;
  return undefined;
}

export function skip_one({ w, o, reason }) {
  if (!$std_map.contains({ d: w.pending, key: o })) {
    return undefined;
  }
  let pending = w.pending;
  const [, pending$190] = $std_map.remove({ d: pending, key: o });
  pending = pending$190;
  let skipped = w.skipped;
  const [, skipped$191] = $std_map.set({ d: skipped, key: o, value: reason });
  skipped = skipped$191;
  return undefined;
}

export function skip_all({ w, reason }) {
  let skipped = w.skipped;
  for (const o of $std_map.keys({ d: w.pending })) {
    if (!$std_map.contains({ d: w.built, key: o })) {
      const [, skipped$192] = $std_map.set({ d: skipped, key: o, value: reason });
      skipped = skipped$192;
    }
  }
  return undefined;
}

export function stmt_returns({ s }) {
  const $m332 = s;
  $m332$match: {
    if ($m332.tag === "Return") {
      return true;
      break $m332$match;
    }
    if ($m332.tag === "If") {
      const then_block = $m332.then_block;
      const else_block = $m332.else_block;
      const $m333 = else_block;
      $m333$match: {
        if ($m333.tag === "Some") {
          const value = $m333.value;
          return block_returns({ b: then_block }) && block_returns({ b: value });
          break $m333$match;
        }
        if ($m333.tag === "None") {
          return false;
          break $m333$match;
        }
        $rt.unreachable();
      }
      break $m332$match;
    }
    if ($m332.tag === "Match") {
      const arms = $m332.arms;
      if ($std_list.len({ xs: arms }) === 0) {
        return false;
      }
      for (const a of arms) {
        const $m334 = a.body;
        $m334$match: {
          if ($m334.tag === "ArmBlock") {
            const block = $m334.block;
            if (!block_returns({ b: block })) {
              return false;
            }
            break $m334$match;
          }
          if ($m334.tag === "ArmStmt") {
            const stmt = $m334.stmt;
            if (!stmt_returns({ s: stmt })) {
              return false;
            }
            break $m334$match;
          }
          $rt.unreachable();
        }
      }
      return true;
      break $m332$match;
    }
    if (true) {
      return false;
      break $m332$match;
    }
    $rt.unreachable();
  }
}

export function block_returns({ b }) {
  for (const s of b.stmts) {
    if (stmt_returns({ s: s })) {
      return true;
    }
  }
  return false;
}

