// Generated by onus from module verifier. Do not edit.
import * as $rt from "./onus-runtime/index.js";
import * as $obligations from "./obligations.js";
import * as $std_list from "./std/list.js";
import * as $context from "./context.js";
import * as $z3 from "./z3.js";
import * as $std_map from "./std/map.js";
import * as $modcache from "./modcache.js";
import * as $vc from "./vc.js";
import * as $std_io from "./std/io.js";
import * as $constant from "./constant.js";
import * as $report from "./report.js";
import * as $formula from "./formula.js";
import * as $std_int from "./std/int.js";
import * as $std_text from "./std/text.js";
import * as $lower from "./lower.js";
import * as $std_float from "./std/float.js";
import * as $effectset from "./effectset.js";

const $ob1 = { kind: "overflow", text: "-1 within Int", at: "self/verifier.onus:49:20", def: "or_neg" };
const $ob2 = { kind: "overflow", text: "i + 1 within Int", at: "self/verifier.onus:226:9", def: "store" };
const $ob3 = { kind: "overflow", text: "List.len(xs: all) + 2 within Int", at: "self/verifier.onus:341:62", def: "equal_measure_calls" };
const $ob4 = { kind: "overflow", text: "guard - 1 within Int", at: "self/verifier.onus:389:13", def: "reaches" };
export const default_budget_ms = 500;

export function skip($args) {
  return undefined;
}

export function or_neg({ o }) {
  const $m1 = o;
  $m1$match: {
    if ($m1.tag === "Some") {
      const value = $m1.value;
      return value;
      break $m1$match;
    }
    if ($m1.tag === "None") {
      return $rt.int.neg(1, $ob1);
      break $m1$match;
    }
    $rt.unreachable();
  }
}

export function text_or({ o, dflt }) {
  const $m2 = o;
  $m2$match: {
    if ($m2.tag === "Some") {
      const value = $m2.value;
      return value;
      break $m2$match;
    }
    if ($m2.tag === "None") {
      return dflt;
      break $m2$match;
    }
    $rt.unreachable();
  }
}

export function is_test_kind({ k }) {
  return k.tag === "Law" || k.tag === "Property";
}

export function info({ o, status, counterexample }) {
  return { kind: $obligations.kind_text({ k: o.kind }), text: o.text, status: status, has_counterexample: $std_list.len({ xs: counterexample }) > 0, counterexample: counterexample };
}

export function set_status({ ctx, o, status, by }) {
  const [, ctx$1] = $context.set_obligation({ ctx: ctx, o: { ...o, status: status, by: { tag: "Some", value: by } } });
  ctx = ctx$1;
  return [undefined, ctx];
  return [undefined, ctx];
}

export function set_by({ ctx, o, by }) {
  const [, ctx$2] = $context.set_obligation({ ctx: ctx, o: { ...o, by: { tag: "Some", value: by } } });
  ctx = ctx$2;
  return [undefined, ctx];
  return [undefined, ctx];
}

export function verify_pass({ ctx, process, files, console, opts }) {
  const solver = $z3.find_z3({ process: process, explicit: opts.z3_path });
  let keys = $std_map.dict({  });
  let replayed = $std_map.dict({  });
  const $m8 = solver;
  $m8$match: {
    if ($m8.tag === "Some") {
      const value = $m8.value;
      keys = $modcache.module_keys({ ctx: ctx, compiler: "self", solver_version: value.version, budget_ms: opts.budget_ms });
      const [, ctx$3, replayed$3] = replay({ ctx: ctx, files: files, dir: opts.cache_dir, keys: keys, replayed: replayed });
      ctx = ctx$3;
      replayed = replayed$3;
      break $m8$match;
    }
    if ($m8.tag === "None") {
      skip({  });
      break $m8$match;
    }
    $rt.unreachable();
  }
  const reported = $std_list.built({ b: ctx.diagnostics });
  const [$r10, ctx$4] = $vc.build_vcs({ ctx: ctx, skip_modules: replayed, mutation: { tag: "None" } });
  ctx = ctx$4;
  const vcs = $r10;
  const [, ctx$5] = equal_measure_calls({ ctx: ctx });
  ctx = ctx$5;
  const $m11 = solver;
  $m11$match: {
    if ($m11.tag === "None") {
      $std_io.eprint({ console: console, text: "onus: z3 not found on PATH; every obligation is checked at runtime\n" });
      const $hi12 = ctx.obligation_count;
      for (let i = 0; i < $hi12; i++) {
        const o = $context.get_obligation({ ctx: ctx, id: i });
        if (o.status.tag === "Checked") {
          const [, ctx$6] = set_by({ ctx: ctx, o: o, by: "z3 not available" });
          ctx = ctx$6;
        }
      }
      break $m11$match;
    }
    if ($m11.tag === "Some") {
      const value = $m11.value;
      const [, ctx$7] = run_all({ ctx: ctx, process: process, files: files, vcs: vcs, solver: value, opts: opts, replayed: replayed });
      ctx = ctx$7;
      break $m11$match;
    }
    $rt.unreachable();
  }
  const [, ctx$8] = rules({ ctx: ctx });
  ctx = ctx$8;
  if (solver.tag === "Some") {
    store({ ctx: ctx, files: files, dir: opts.cache_dir, keys: keys, replayed: replayed, reported: reported });
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function module_obligations({ ctx, mod }) {
  let out = $std_list.builder({  });
  const $hi13 = ctx.obligation_count;
  for (let i = 0; i < $hi13; i++) {
    const o = $context.get_obligation({ ctx: ctx, id: i });
    if ($context.get_def({ ctx: ctx, id: o.def }).mod === mod) {
      const [, out$9] = $std_list.push({ b: out, x: i });
      out = out$9;
    }
  }
  return $std_list.finish({ b: out });
}

export function replay({ ctx, files, dir, keys, replayed }) {
  for (const mid of $std_map.keys({ d: keys })) {
    const entry = $modcache.get({ files: files, dir: dir, key: text_or({ o: $std_map.find({ d: keys, key: mid }), dflt: "" }) });
    if (entry.tag === "Some") {
      const statuses = statuses_or({ o: entry });
      const own = module_obligations({ ctx: ctx, mod: mid });
      if ($std_list.len({ xs: statuses }) === $std_list.len({ xs: own })) {
        const $hi14 = $std_list.len({ xs: own });
        for (let i = 0; i < $hi14; i++) {
          const o = $context.get_obligation({ ctx: ctx, id: $std_list.get({ xs: own, i: i }) });
          const c = $std_list.get({ xs: statuses, i: i });
          const [, ctx$10] = $context.set_obligation({ ctx: ctx, o: { ...o, status: c.status, by: c.by } });
          ctx = ctx$10;
        }
        const [, replayed$11] = $std_map.set({ d: replayed, key: mid, value: true });
        replayed = replayed$11;
      }
    }
  }
  return [undefined, ctx, replayed];
  return [undefined, ctx, replayed];
}

export function statuses_or({ o }) {
  const $m16 = o;
  $m16$match: {
    if ($m16.tag === "Some") {
      const value = $m16.value;
      return value;
      break $m16$match;
    }
    if ($m16.tag === "None") {
      return [];
      break $m16$match;
    }
    $rt.unreachable();
  }
}

export function store({ ctx, files, dir, keys, replayed, reported }) {
  let noisy = $std_map.dict({  });
  let i = 0;
  for (const d of $std_list.finish({ b: ctx.diagnostics })) {
    if (i >= reported) {
      const [, noisy$12] = $std_map.set({ d: noisy, key: d.file, value: true });
      noisy = noisy$12;
    }
    i = $rt.int.add(i, 1, $ob2);
  }
  for (const mid of $std_map.keys({ d: keys })) {
    if (!$std_map.contains({ d: replayed, key: mid })) {
      const $m17 = $std_map.find({ d: ctx.modules, key: mid });
      $m17$match: {
        if ($m17.tag === "None") {
          skip({  });
          break $m17$match;
        }
        if ($m17.tag === "Some") {
          const value = $m17.value;
          if (!$std_map.contains({ d: noisy, key: value.file })) {
            let obs = $std_list.builder({  });
            for (const id of module_obligations({ ctx: ctx, mod: mid })) {
              const [, obs$13] = $std_list.push({ b: obs, x: $context.get_obligation({ ctx: ctx, id: id }) });
              obs = obs$13;
            }
            $modcache.set({ files: files, dir: dir, key: text_or({ o: $std_map.find({ d: keys, key: mid }), dflt: "" }), obs: $std_list.finish({ b: obs }) });
          }
          break $m17$match;
        }
        $rt.unreachable();
      }
    }
  }
  return undefined;
}

export function run_all({ ctx, process, files, vcs, solver, opts, replayed }) {
  const $hi18 = ctx.obligation_count;
  for (let i = 0; i < $hi18; i++) {
    const o = $context.get_obligation({ ctx: ctx, id: i });
    if (o.status.tag === "Checked" && !is_test_kind({ k: o.kind }) && !$std_map.contains({ d: replayed, key: $context.get_def({ ctx: ctx, id: o.def }).mod })) {
      const $m19 = $std_map.find({ d: vcs.built, key: i });
      $m19$match: {
        if ($m19.tag === "None") {
          const [$r20, ctx$14] = $constant.const_discharge({ ctx: ctx, o: o });
          ctx = ctx$14;
          if (is_true({ o: $r20 })) {
            const [, ctx$15] = set_status({ ctx: ctx, o: o, status: { tag: "Proved" }, by: "constant evaluation" });
            ctx = ctx$15;
          } else {
            const [, ctx$16] = set_by({ ctx: ctx, o: o, by: text_or({ o: $std_map.find({ d: vcs.skipped, key: i }), dflt: "no condition" }) });
            ctx = ctx$16;
          }
          break $m19$match;
        }
        if ($m19.tag === "Some") {
          const value = $m19.value;
          const [, ctx$17] = discharge({ ctx: ctx, process: process, files: files, o: o, v: value, solver: solver, opts: opts });
          ctx = ctx$17;
          const after = $context.get_obligation({ ctx: ctx, id: i });
          const [$r22, ctx$18] = $constant.const_discharge({ ctx: ctx, o: after });
          ctx = ctx$18;
          if (after.status.tag === "Checked" && !after.pinned && is_true({ o: $r22 })) {
            const [, ctx$19] = set_status({ ctx: ctx, o: after, status: { tag: "Proved" }, by: "constant evaluation" });
            ctx = ctx$19;
          }
          break $m19$match;
        }
        $rt.unreachable();
      }
    }
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function is_true({ o }) {
  const $m24 = o;
  $m24$match: {
    if ($m24.tag === "Some") {
      const value = $m24.value;
      return value;
      break $m24$match;
    }
    if ($m24.tag === "None") {
      return false;
      break $m24$match;
    }
    $rt.unreachable();
  }
}

export function equal_measure_calls({ ctx }) {
  let pending = $std_list.builder({  });
  let edges = $std_map.dict({  });
  const $hi25 = ctx.obligation_count;
  for (let i = 0; i < $hi25; i++) {
    const o = $context.get_obligation({ ctx: ctx, id: i });
    if (o.kind.tag === "Decreases" && o.status.tag === "Checked" && text_or({ o: o.by, dflt: "" }) === "equal argument" && o.callee.tag === "Some") {
      const [, pending$20] = $std_list.push({ b: pending, x: o });
      pending = pending$20;
      const callee = or_neg({ o: o.callee });
      const $m26 = $std_map.find({ d: edges, key: o.def });
      $m26$match: {
        if ($m26.tag === "Some") {
          const value = $m26.value;
          if (!$std_list.contains({ xs: value, x: callee })) {
            const [, edges$21] = $std_map.set({ d: edges, key: o.def, value: $std_list.append({ xs: value, x: callee }) });
            edges = edges$21;
          }
          break $m26$match;
        }
        if ($m26.tag === "None") {
          const [, edges$22] = $std_map.set({ d: edges, key: o.def, value: [callee] });
          edges = edges$22;
          break $m26$match;
        }
        $rt.unreachable();
      }
    }
  }
  const all = $std_list.finish({ b: pending });
  for (const o of all) {
    const callee = or_neg({ o: o.callee });
    if (reaches({ edges: edges, from: callee, to: o.def, bound: $rt.int.add($std_list.len({ xs: all }), 2, $ob3) })) {
      const [, ctx$23] = $context.set_obligation({ ctx: ctx, o: { ...o, status: { tag: "Failed" }, by: { tag: "Some", value: "the calls passing the measure unchanged form a cycle" } } });
      ctx = ctx$23;
      const [, ctx$24] = $context.report({ ctx: ctx, d: $report.diagnostic_for({ code: "E0344", file: o.at_file, span: o.at_span, def_name: { tag: "Some", value: $context.get_def({ ctx: ctx, id: o.def }).name }, detail: "this call passes the measure `" + $vc.measure_text({ t: o.text }) + "` on unchanged, and the calls that do so form a cycle; one of them must pass a proper part (§5.1)", obligation: info({ o: o, status: "unprovable", counterexample: [] }) }) });
      ctx = ctx$24;
    } else {
      const [, ctx$25] = set_status({ ctx: ctx, o: o, status: { tag: "Proved" }, by: "structural order (passed on unchanged here; every cycle takes a proper part)" });
      ctx = ctx$25;
    }
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function reaches({ edges, from, to, bound }) {
  let seen = $std_map.dict({  });
  let stack = $std_list.builder({  });
  const [, stack$26] = $std_list.push({ b: stack, x: from });
  stack = stack$26;
  let guard = bound;
  while ($std_list.built({ b: stack }) > 0 && guard > 0) {
    guard = $rt.int.sub(guard, 1, $ob4);
    const [$r34, stack$27] = $std_list.pop({ b: stack });
    stack = stack$27;
    const $m33 = $r34;
    $m33$match: {
      if ($m33.tag === "None") {
        guard = 0;
        break $m33$match;
      }
      if ($m33.tag === "Some") {
        const value = $m33.value;
        if (value === to) {
          return true;
        }
        if (!$std_map.contains({ d: seen, key: value })) {
          const [, seen$28] = $std_map.set({ d: seen, key: value, value: true });
          seen = seen$28;
          for (const w of next_of({ edges: edges, v: value })) {
            const [, stack$29] = $std_list.push({ b: stack, x: w });
            stack = stack$29;
          }
        }
        break $m33$match;
      }
      $rt.unreachable();
    }
  }
  return false;
}

export function next_of({ edges, v }) {
  const $m35 = $std_map.find({ d: edges, key: v });
  $m35$match: {
    if ($m35.tag === "Some") {
      const value = $m35.value;
      return value;
      break $m35$match;
    }
    if ($m35.tag === "None") {
      return [];
      break $m35$match;
    }
    $rt.unreachable();
  }
}

export function discharge({ ctx, process, files, o, v, solver, opts }) {
  const problem = problem_text({ v: v, budget_ms: opts.budget_ms });
  const $m36 = opts.dump_dir;
  $m36$match: {
    if ($m36.tag === "Some") {
      const value = $m36.value;
      dump({ files: files, dir: value, o: o, def_name: $context.get_def({ ctx: ctx, id: o.def }).name, problem: problem });
      break $m36$match;
    }
    if ($m36.tag === "None") {
      skip({  });
      break $m36$match;
    }
    $rt.unreachable();
  }
  const key = $z3.cache_key({ problem: problem, version: solver.version, budget_ms: opts.budget_ms });
  let outcome_r = { outcome: { tag: "Failure" }, model: [], detail: "" };
  const $m39 = $z3.cache_get({ files: files, dir: opts.cache_dir, key: key });
  $m39$match: {
    if ($m39.tag === "Some") {
      const value = $m39.value;
      outcome_r = value;
      break $m39$match;
    }
    if ($m39.tag === "None") {
      outcome_r = $z3.run_z3({ process: process, solver: solver, problem: problem, budget_ms: opts.budget_ms });
      $z3.cache_set({ files: files, dir: opts.cache_dir, key: key, r: outcome_r });
      break $m39$match;
    }
    $rt.unreachable();
  }
  const def_name = $context.get_def({ ctx: ctx, id: o.def }).name;
  const $m40 = outcome_r.outcome;
  $m40$match: {
    if ($m40.tag === "Unsat") {
      const [, ctx$30] = set_status({ ctx: ctx, o: o, status: { tag: "Proved" }, by: "z3" });
      ctx = ctx$30;
      break $m40$match;
    }
    if ($m40.tag === "Sat") {
      if (o.pinned) {
        let code = "E0342";
        if (o.kind.tag === "Ensures") {
          code = "E0302";
        }
        const [, ctx$31] = $context.set_obligation({ ctx: ctx, o: { ...o, status: { tag: "Failed" }, by: { tag: "Some", value: "z3: counterexample" } } });
        ctx = ctx$31;
        const [, ctx$32] = $context.report({ ctx: ctx, d: $report.diagnostic_for({ code: code, file: o.at_file, span: o.at_span, def_name: { tag: "Some", value: def_name }, detail: "`" + $obligations.kind_text({ k: o.kind }) + " proved " + o.text + "` does not hold on every path", obligation: { kind: $obligations.kind_text({ k: o.kind }), text: o.text, status: "unprovable", has_counterexample: true, counterexample: counterexample({ r: outcome_r, v: v }) } }) });
        ctx = ctx$32;
      } else {
        if (o.kind.tag === "Assertion") {
          const [, ctx$33] = set_by({ ctx: ctx, o: o, by: "run as a test" });
          ctx = ctx$33;
        } else {
          const [, ctx$34] = set_by({ ctx: ctx, o: o, by: "z3: not provable" });
          ctx = ctx$34;
        }
      }
      break $m40$match;
    }
    if ($m40.tag === "Failure") {
      const [, ctx$35] = $context.report({ ctx: ctx, d: $report.diagnostic({ code: "E0999", file: o.at_file, span: o.at_span, def_name: { tag: "Some", value: def_name }, detail: "z3 rejected the problem for `" + $obligations.kind_text({ k: o.kind }) + " " + o.text + "`: " + outcome_r.detail }) });
      ctx = ctx$35;
      const [, ctx$36] = set_by({ ctx: ctx, o: o, by: "z3: error" });
      ctx = ctx$36;
      break $m40$match;
    }
    if (true) {
      let nonlinear = $formula.is_nonlinear({ f: v.goal });
      for (const f of v.facts) {
        if ($formula.is_nonlinear({ f: f })) {
          nonlinear = true;
        }
      }
      if (nonlinear && !o.pinned) {
        const [, ctx$37] = set_by({ ctx: ctx, o: o, by: "z3: nonlinear, budget exceeded" });
        ctx = ctx$37;
      } else {
        let why = "";
        if (nonlinear) {
          why = " (nonlinear arithmetic)";
        }
        const [, ctx$38] = $context.report({ ctx: ctx, d: $report.diagnostic_for({ code: "E0501", file: o.at_file, span: o.at_span, def_name: { tag: "Some", value: def_name }, detail: "z3 gave up on `" + $obligations.kind_text({ k: o.kind }) + " " + o.text + "` within " + $std_int.to_text({ x: opts.budget_ms }) + " ms" + why + "; raise the budget or simplify the contract", obligation: info({ o: o, status: "unprovable", counterexample: [] }) }) });
        ctx = ctx$38;
        let status = o.status;
        if (o.pinned) {
          status = { tag: "Failed" };
        }
        const [, ctx$39] = $context.set_obligation({ ctx: ctx, o: { ...o, status: status, by: { tag: "Some", value: "z3: budget exceeded" } } });
        ctx = ctx$39;
      }
      break $m40$match;
    }
    $rt.unreachable();
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function dump({ files, dir, o, def_name, problem }) {
  const made = $std_io.mkdir({ files: files, path: dir });
  const path = dir + "/" + $std_int.to_text({ x: o.id }) + "_" + def_name + "_" + $obligations.kind_text({ k: o.kind }) + ".smt2";
  const $m52 = $std_io.create({ files: files, path: path });
  $m52$match: {
    if ($m52.tag === "Ok") {
      const value = $m52.value;
      const written = $std_io.write({ file: value, text: problem });
      break $m52$match;
    }
    if ($m52.tag === "Err") {
      skip({  });
      break $m52$match;
    }
    $rt.unreachable();
  }
  return undefined;
}

export function problem_text({ v, budget_ms }) {
  let lines = $std_list.builder({  });
  const [, lines$40] = $std_list.push({ b: lines, x: "(set-logic ALL)" });
  lines = lines$40;
  const [, lines$41] = $std_list.push({ b: lines, x: "(set-option :timeout " + $std_int.to_text({ x: budget_ms }) + ")" });
  lines = lines$41;
  const [, lines$42] = $std_list.push({ b: lines, x: "(set-option :produce-models true)" });
  lines = lines$42;
  for (const s of $std_map.keys({ d: v.lw.sorts })) {
    const [, lines$43] = $std_list.push({ b: lines, x: "(declare-sort " + s + " 0)" });
    lines = lines$43;
  }
  for (const name of $std_map.keys({ d: v.lw.fns })) {
    const $m53 = $std_map.find({ d: v.lw.fns, key: name });
    $m53$match: {
      if ($m53.tag === "Some") {
        const value = $m53.value;
        let args = $std_list.builder({  });
        for (const a of value.args) {
          const [, args$44] = $std_list.push({ b: args, x: $formula.sort_text({ s: a }) });
          args = args$44;
        }
        const [, lines$45] = $std_list.push({ b: lines, x: "(declare-fun " + name + " (" + $std_text.join({ parts: $std_list.finish({ b: args }), sep: " " }) + ") " + $formula.sort_text({ s: value.ret }) + ")" });
        lines = lines$45;
        break $m53$match;
      }
      if ($m53.tag === "None") {
        skip({  });
        break $m53$match;
      }
      $rt.unreachable();
    }
  }
  for (const a of $std_list.finish({ b: v.lw.sort_axioms })) {
    const [, lines$46] = $std_list.push({ b: lines, x: "(assert " + $formula.smt({ f: a }) + ")" });
    lines = lines$46;
  }
  const $m54 = $lower.text_distinctness({ lw: v.lw });
  $m54$match: {
    if ($m54.tag === "Some") {
      const value = $m54.value;
      const [, lines$47] = $std_list.push({ b: lines, x: "(assert " + $formula.smt({ f: value }) + ")" });
      lines = lines$47;
      break $m54$match;
    }
    if ($m54.tag === "None") {
      skip({  });
      break $m54$match;
    }
    $rt.unreachable();
  }
  for (const a of $std_list.finish({ b: v.lw.axioms })) {
    const [, lines$48] = $std_list.push({ b: lines, x: "(assert " + $formula.smt({ f: a }) + ")" });
    lines = lines$48;
  }
  for (const f of v.facts) {
    const [, lines$49] = $std_list.push({ b: lines, x: "(assert " + $formula.smt({ f: f }) + ")" });
    lines = lines$49;
  }
  const [, lines$50] = $std_list.push({ b: lines, x: "(assert " + $formula.smt({ f: $formula.app({ fn_name: "not", args: [v.goal], sort: { tag: "BoolS" } }) }) + ")" });
  lines = lines$50;
  const [, lines$51] = $std_list.push({ b: lines, x: "(check-sat)" });
  lines = lines$51;
  const [, lines$52] = $std_list.push({ b: lines, x: "(get-model)" });
  lines = lines$52;
  return $std_text.join({ parts: $std_list.finish({ b: lines }), sep: "\n" }) + "\n";
}

export function counterexample({ r, v }) {
  let out = $std_list.builder({  });
  for (const e of r.model) {
    const $m56 = $std_map.find({ d: v.names, key: e.name });
    $m56$match: {
      if ($m56.tag === "Some") {
        const value = $m56.value;
        const [, out$53] = $std_list.push({ b: out, x: { name: value, value: e.value, is_number: $std_int.parse({ t: e.value }).tag === "Some" || $std_float.parse({ t: e.value }).tag === "Some" } });
        out = out$53;
        break $m56$match;
      }
      if ($m56.tag === "None") {
        skip({  });
        break $m56$match;
      }
      $rt.unreachable();
    }
  }
  return $std_list.finish({ b: out });
}

export function rules({ ctx }) {
  let by_def = $std_map.dict({  });
  let order = $std_list.builder({  });
  const $hi58 = ctx.obligation_count;
  for (let i = 0; i < $hi58; i++) {
    const o = $context.get_obligation({ ctx: ctx, id: i });
    const $m59 = $std_map.find({ d: by_def, key: o.def });
    $m59$match: {
      if ($m59.tag === "Some") {
        const value = $m59.value;
        const [, by_def$54] = $std_map.set({ d: by_def, key: o.def, value: $std_list.append({ xs: value, x: i }) });
        by_def = by_def$54;
        break $m59$match;
      }
      if ($m59.tag === "None") {
        const [, order$55] = $std_list.push({ b: order, x: o.def });
        order = order$55;
        const [, by_def$56] = $std_map.set({ d: by_def, key: o.def, value: [i] });
        by_def = by_def$56;
        break $m59$match;
      }
      $rt.unreachable();
    }
  }
  for (const def of $std_list.finish({ b: order })) {
    const d = $context.get_def({ ctx: ctx, id: def });
    if ($rt.eq(d.kind, { tag: "Fn" }) || $rt.eq(d.kind, { tag: "Verify" })) {
      let effects = { tag: "None" };
      let const_fn = false;
      let has_body = true;
      const $m63 = d.node;
      $m63$match: {
        if ($m63.tag === "VerifyNode") {
          const $m64 = $std_map.find({ d: ctx.verifies, key: d.key });
          $m64$match: {
            if ($m64.tag === "Some") {
              const value = $m64.value;
              effects = { tag: "Some", value: value.effects };
              break $m64$match;
            }
            if ($m64.tag === "None") {
              skip({  });
              break $m64$match;
            }
            $rt.unreachable();
          }
          break $m63$match;
        }
        if ($m63.tag === "FnNode") {
          const decl = $m63.decl;
          const $m66 = $std_map.find({ d: ctx.signatures, key: def });
          $m66$match: {
            if ($m66.tag === "Some") {
              const value = $m66.value;
              effects = { tag: "Some", value: value.effects };
              break $m66$match;
            }
            if ($m66.tag === "None") {
              skip({  });
              break $m66$match;
            }
            $rt.unreachable();
          }
          const_fn = decl.is_const;
          has_body = decl.body.tag === "Some";
          break $m63$match;
        }
        if (true) {
          skip({  });
          break $m63$match;
        }
        $rt.unreachable();
      }
      if (effects.tag === "Some" && has_body) {
        const has_panic = $effectset.has({ s: set_or_empty({ o: effects }), e: { tag: "PrimEffect", name: "panic" } });
        for (const id of ids_or({ o: $std_map.find({ d: by_def, key: def }) })) {
          const [, ctx$57] = rule_for({ ctx: ctx, id: id, d: d, const_fn: const_fn, has_panic: has_panic });
          ctx = ctx$57;
        }
      }
    }
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

export function set_or_empty({ o }) {
  const $m69 = o;
  $m69$match: {
    if ($m69.tag === "Some") {
      const value = $m69.value;
      return value;
      break $m69$match;
    }
    if ($m69.tag === "None") {
      return $effectset.empty({  });
      break $m69$match;
    }
    $rt.unreachable();
  }
}

export function ids_or({ o }) {
  const $m70 = o;
  $m70$match: {
    if ($m70.tag === "Some") {
      const value = $m70.value;
      return value;
      break $m70$match;
    }
    if ($m70.tag === "None") {
      return [];
      break $m70$match;
    }
    $rt.unreachable();
  }
}

export function rule_for({ ctx, id, d, const_fn, has_panic }) {
  const o = $context.get_obligation({ ctx: ctx, id: id });
  if (!(o.status.tag === "Checked") || is_test_kind({ k: o.kind })) {
    return [undefined, ctx];
  }
  if (o.kind.tag === "Representation" || o.kind.tag === "Overflow") {
    return [undefined, ctx];
  }
  const head = "`" + $obligations.kind_text({ k: o.kind }) + " " + o.text + "`";
  if (const_fn) {
    const [, ctx$58] = $context.report({ ctx: ctx, d: $report.diagnostic_for({ code: "E0703", file: o.at_file, span: o.at_span, def_name: { tag: "Some", value: d.name }, detail: "`" + d.name + "` is a `const fn`, so " + head + " must be proved; " + text_or({ o: o.by, dflt: "it was not" }), obligation: info({ o: o, status: "checked", counterexample: [] }) }) });
    ctx = ctx$58;
    return [undefined, ctx];
  }
  if (!has_panic) {
    const [, ctx$59] = $context.report({ ctx: ctx, d: $report.diagnostic_for({ code: "E0343", file: o.at_file, span: o.at_span, def_name: { tag: "Some", value: d.name }, detail: head + " is checked at runtime (" + text_or({ o: o.by, dflt: "not proved" }) + "), so `" + d.name + "` must declare `panic` or the obligation must be proved", obligation: info({ o: o, status: "checked", counterexample: [] }) }) });
    ctx = ctx$59;
  }
  return [undefined, ctx];
  return [undefined, ctx];
}

