// Generated by onus: tests of module z3.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $self from "./z3.js";

import { test, expect, afterAll } from 'vitest';
import * as fc from 'fast-check';
test("model_parsing", () => {
  expect($rt.eq($self.parse_model({ text: "sat\n(model\n  (define-fun x () Int 3)\n  (define-fun y () Int (- 2))\n  (define-fun b () Bool true)\n)" }), [{ name: "x", value: "3" }, { name: "y", value: "-2" }, { name: "b", value: "true" }])).toBe(true);
  expect($rt.eq($self.model_value({ model: $self.parse_model({ text: "(define-fun n () Int 7)" }), name: "n" }), { tag: "Some", value: "7" })).toBe(true);
});
afterAll(() => $rt.coverage.flush());
