// Generated by onus from module z3. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
import * as $std_io from "./std/io.js";
import * as $std_text from "./std/text.js";
import * as $std_int from "./std/int.js";
import * as $std_list from "./std/list.js";
import * as $std_hash from "./std/hash.js";

const $ob1 = { kind: "overflow", text: "budget_ms * 4 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:104:17", def: "run_z3" };
const $ob2 = { kind: "overflow", text: "budget_ms * 4 + 2000 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:104:17", def: "run_z3" };
const $ob3 = { kind: "overflow", text: "j + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:172:9", def: "token_end" };
const $ob4 = { kind: "overflow", text: "j + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:183:9", def: "skip_spaces" };
const $ob5 = { kind: "overflow", text: "i + m within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:210:14", def: "parse_model" };
const $ob6 = { kind: "overflow", text: "i + k within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:216:43", def: "parse_model" };
const $ob7 = { kind: "overflow", text: "i + m within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:221:54", def: "parse_model" };
const $ob8 = { kind: "overflow", text: "p + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:226:17", def: "parse_model" };
const $ob9 = { kind: "overflow", text: "p + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:226:86", def: "parse_model" };
const $ob10 = { kind: "overflow", text: "p + 2 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:227:38", def: "parse_model" };
const $ob11 = { kind: "overflow", text: "p + 3 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:241:22", def: "parse_model" };
const $ob12 = { kind: "overflow", text: "p + 3 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:242:68", def: "parse_model" };
const $ob13 = { kind: "overflow", text: "close + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:243:17", def: "parse_model" };
const $ob14 = { kind: "overflow", text: "i + m within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:262:11", def: "parse_model" };
const $ob15 = { kind: "overflow", text: "i + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:264:11", def: "parse_model" };
const $ob16 = { kind: "overflow", text: "j + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:276:9", def: "find_close" };
const $ob17 = { kind: "overflow", text: "value + 1 within Int", at: "/Users/jamesrandall/code/onus/self/z3.onus:349:46", def: "parse_cached" };
export function outcome_text({ o }) {
  const $m1 = o;
  $m1$match: {
    if ($m1.tag === "Unsat") {
      return "unsat";
      break $m1$match;
    }
    if ($m1.tag === "Sat") {
      return "sat";
      break $m1$match;
    }
    if ($m1.tag === "Unknown") {
      return "unknown";
      break $m1$match;
    }
    if ($m1.tag === "Timeout") {
      return "timeout";
      break $m1$match;
    }
    if ($m1.tag === "Failure") {
      return "error";
      break $m1$match;
    }
    $rt.unreachable();
  }
}

export function outcome_of_text({ t }) {
  if (t === "unsat") {
    return { tag: "Unsat" };
  }
  if (t === "sat") {
    return { tag: "Sat" };
  }
  if (t === "unknown") {
    return { tag: "Unknown" };
  }
  if (t === "timeout") {
    return { tag: "Timeout" };
  }
  return { tag: "Failure" };
}

export function find_z3({ process, explicit }) {
  let path = "z3";
  const $m7 = explicit;
  $m7$match: {
    if ($m7.tag === "Some") {
      const value = $m7.value;
      path = value;
      break $m7$match;
    }
    if ($m7.tag === "None") {
      path = "z3";
      break $m7$match;
    }
    $rt.unreachable();
  }
  const $m8 = $std_io.run({ process: process, program: path, args: ["--version"], stdin: "", timeout_ms: 10000 });
  $m8$match: {
    if ($m8.tag === "Err") {
      const error = $m8.error;
      return { tag: "None" };
      break $m8$match;
    }
    if ($m8.tag === "Ok") {
      const value = $m8.value;
      if (value.status !== 0) {
        return { tag: "None" };
      }
      return { tag: "Some", value: { path: path, version: $std_text.trim({ t: value.stdout }) } };
      break $m8$match;
    }
    $rt.unreachable();
  }
}

export function is_verdict({ line }) {
  return line === "sat" || line === "unsat" || line === "unknown" || line === "timeout" || $std_text.starts_with({ t: line, prefix: "(error" });
}

export function run_z3({ process, solver, problem, budget_ms }) {
  const $m13 = $std_io.run({ process: process, program: solver.path, args: ["-in", "-smt2", "-t:" + $std_int.to_text({ x: budget_ms })], stdin: problem, timeout_ms: $rt.int.add($rt.int.mul(budget_ms, 4, $ob1), 2000, $ob2) });
  $m13$match: {
    if ($m13.tag === "Err") {
      const error = $m13.error;
      const $m14 = error;
      $m14$match: {
        if ($m14.tag === "Other") {
          const detail = $m14.detail;
          if ($std_text.contains({ t: detail, needle: "did not finish" })) {
            return { outcome: { tag: "Timeout" }, model: [], detail: "process timeout" };
          }
          return { outcome: { tag: "Failure" }, model: [], detail: detail };
          break $m14$match;
        }
        if ($m14.tag === "NotFound") {
          const path = $m14.path;
          return { outcome: { tag: "Failure" }, model: [], detail: "`" + path + "` not found" };
          break $m14$match;
        }
        if ($m14.tag === "Denied") {
          const path = $m14.path;
          return { outcome: { tag: "Failure" }, model: [], detail: "`" + path + "` denied" };
          break $m14$match;
        }
        $rt.unreachable();
      }
      break $m13$match;
    }
    if ($m13.tag === "Ok") {
      const value = $m13.value;
      const out = value.stdout + value.stderr;
      let first = "";
      let found = false;
      for (const raw of $std_text.split({ t: out, sep: "\n" })) {
        const line = $std_text.trim({ t: raw });
        if (!found && line !== "" && is_verdict({ line: line })) {
          first = line;
          found = true;
        }
      }
      if (first === "unsat") {
        return { outcome: { tag: "Unsat" }, model: [], detail: "" };
      }
      if (first === "sat") {
        return { outcome: { tag: "Sat" }, model: parse_model({ text: out }), detail: "" };
      }
      if (first === "unknown" || first === "timeout") {
        let detail = "unknown";
        if (first === "timeout" || $std_text.contains({ t: out, needle: "timeout" })) {
          detail = "solver timeout";
        }
        return { outcome: { tag: "Timeout" }, model: [], detail: detail };
      }
      let detail = out;
      if ($std_text.count({ t: out }) > 500) {
        detail = $std_text.slice({ t: out, from: 0, to: 500 });
      }
      return { outcome: { tag: "Failure" }, model: [], detail: detail };
      break $m13$match;
    }
    $rt.unreachable();
  }
}

export function is_space({ c }) {
  return c === 32 || c === 10 || c === 13 || c === 9;
}

export function is_token_char({ c }) {
  return !is_space({ c: c }) && c !== 40 && c !== 41;
}

export function token_end({ cps, i }) {
  let j = i;
  while (j < $std_list.len({ xs: cps }) && is_token_char({ c: $std_list.get({ xs: cps, i: j }) })) {
    j = $rt.int.add(j, 1, $ob3);
  }
  return j;
}

export function skip_spaces({ cps, i }) {
  let j = i;
  while (j < $std_list.len({ xs: cps }) && is_space({ c: $std_list.get({ xs: cps, i: j }) })) {
    j = $rt.int.add(j, 1, $ob4);
  }
  return j;
}

export function slice_text({ cps, from, to }) {
  let out = $std_list.builder({  });
  if (from < 0 || to > $std_list.len({ xs: cps }) || to < from) {
    return "";
  }
  for (let i = from; i < to; i++) {
    const c = $std_list.get({ xs: cps, i: i });
    if (c >= 0 && c <= 1114111) {
      const [, out$1] = $std_list.push({ b: out, x: c });
      out = out$1;
    }
  }
  return $std_text.of_code_points({ cps: $std_list.finish({ b: out }) });
}

export function parse_model({ text }) {
  const cps = $std_text.code_points({ t: text });
  const n = $std_list.len({ xs: cps });
  const marker = $std_text.code_points({ t: "(define-fun " });
  const m = $std_list.len({ xs: marker });
  let out = $std_list.builder({  });
  let i = 0;
  while ($rt.int.add(i, m, $ob5) <= n) {
    let matches = true;
    for (let k = 0; k < m; k++) {
      if (matches && $std_list.get({ xs: cps, i: $rt.int.add(i, k, $ob6) }) !== $std_list.get({ xs: marker, i: k })) {
        matches = false;
      }
    }
    if (matches) {
      const name_start = skip_spaces({ cps: cps, i: $rt.int.add(i, m, $ob7) });
      const name_end = token_end({ cps: cps, i: name_start });
      let p = skip_spaces({ cps: cps, i: name_end });
      let ok = name_end > name_start;
      if (ok && $rt.int.add(p, 1, $ob8) < n && $std_list.get({ xs: cps, i: p }) === 40 && $std_list.get({ xs: cps, i: $rt.int.add(p, 1, $ob9) }) === 41) {
        p = skip_spaces({ cps: cps, i: $rt.int.add(p, 2, $ob10) });
      } else {
        ok = false;
      }
      if (ok) {
        const sort_end = token_end({ cps: cps, i: p });
        ok = sort_end > p;
        p = skip_spaces({ cps: cps, i: sort_end });
      }
      if (ok && p < n) {
        let value = "";
        if ($std_list.get({ xs: cps, i: p }) === 40) {
          const close = find_close({ cps: cps, i: p });
          if (close > $rt.int.add(p, 3, $ob11)) {
            value = "-" + $std_text.trim({ t: slice_text({ cps: cps, from: $rt.int.add(p, 3, $ob12), to: close }) });
            p = $rt.int.add(close, 1, $ob13);
          } else {
            ok = false;
          }
        } else {
          const value_end = token_end({ cps: cps, i: p });
          value = slice_text({ cps: cps, from: p, to: value_end });
          p = value_end;
        }
        if (ok && p < n && $std_list.get({ xs: cps, i: p }) === 41) {
          const [, out$2] = $std_list.push({ b: out, x: { name: slice_text({ cps: cps, from: name_start, to: name_end }), value: value } });
          out = out$2;
        }
      }
      i = $rt.int.add(i, m, $ob14);
    } else {
      i = $rt.int.add(i, 1, $ob15);
    }
  }
  return $std_list.finish({ b: out });
}

export function find_close({ cps, i }) {
  let j = i;
  while (j < $std_list.len({ xs: cps }) && $std_list.get({ xs: cps, i: j }) !== 41) {
    j = $rt.int.add(j, 1, $ob16);
  }
  return j;
}

export function model_value({ model, name }) {
  for (const e of model) {
    if (e.name === name) {
      return { tag: "Some", value: e.value };
    }
  }
  return { tag: "None" };
}

export function cache_key({ problem, version, budget_ms }) {
  return $std_hash.blake3_hex({ t: version + "\n" + $std_int.to_text({ x: budget_ms }) + "\n" + problem });
}

export function cache_path({ dir, key }) {
  return dir + "/" + key + ".onus-proof";
}

export function text_or_empty({ o }) {
  const $m38 = o;
  $m38$match: {
    if ($m38.tag === "Some") {
      const value = $m38.value;
      return value;
      break $m38$match;
    }
    if ($m38.tag === "None") {
      return "";
      break $m38$match;
    }
    $rt.unreachable();
  }
}

export function read_or_none({ files, path }) {
  const $m39 = $std_io.read({ files: files, path: path });
  $m39$match: {
    if ($m39.tag === "Ok") {
      const value = $m39.value;
      return { tag: "Some", value: value };
      break $m39$match;
    }
    if ($m39.tag === "Err") {
      const error = $m39.error;
      return { tag: "None" };
      break $m39$match;
    }
    $rt.unreachable();
  }
}

export function cache_get({ files, dir, key }) {
  if (dir.tag === "None") {
    return { tag: "None" };
  }
  const text = read_or_none({ files: files, path: cache_path({ dir: text_or_empty({ o: dir }), key: key }) });
  if (text.tag === "None") {
    return { tag: "None" };
  }
  return parse_cached({ text: text_or_empty({ o: text }) });
}

export function parse_cached({ text }) {
  const lines = $std_text.split({ t: text, sep: "\n" });
  if ($std_list.len({ xs: lines }) < 2) {
    return { tag: "None" };
  }
  const outcome = outcome_of_text({ t: $std_list.get({ xs: lines, i: 0 }) });
  if (!$rt.eq(outcome, { tag: "Unsat" }) && !$rt.eq(outcome, { tag: "Sat" })) {
    return { tag: "None" };
  }
  let model = $std_list.builder({  });
  const $hi48 = $std_list.len({ xs: lines });
  for (let i = 2; i < $hi48; i++) {
    const line = $std_list.get({ xs: lines, i: i });
    const $m49 = $std_text.index_of({ t: line, needle: " ", from: 0 });
    $m49$match: {
      if ($m49.tag === "Some") {
        const value = $m49.value;
        if (value < $std_text.count({ t: line })) {
          const [, model$3] = $std_list.push({ b: model, x: { name: $std_text.slice({ t: line, from: 0, to: value }), value: $std_text.slice({ t: line, from: $rt.int.add(value, 1, $ob17), to: $std_text.count({ t: line }) }) } });
          model = model$3;
        }
        break $m49$match;
      }
      if ($m49.tag === "None") {
        skip({  });
        break $m49$match;
      }
      $rt.unreachable();
    }
  }
  return { tag: "Some", value: { outcome: outcome, model: $std_list.finish({ b: model }), detail: $std_list.get({ xs: lines, i: 1 }) } };
}

export function skip($args) {
  return undefined;
}

export function cache_set({ files, dir, key, r }) {
  if (dir.tag === "None" || !$rt.eq(r.outcome, { tag: "Unsat" }) && !$rt.eq(r.outcome, { tag: "Sat" })) {
    return undefined;
  }
  const d = text_or_empty({ o: dir });
  const made = $std_io.mkdir({ files: files, path: d });
  let lines = $std_list.builder({  });
  const [, lines$4] = $std_list.push({ b: lines, x: outcome_text({ o: r.outcome }) });
  lines = lines$4;
  const [, lines$5] = $std_list.push({ b: lines, x: $std_text.replace({ t: r.detail, from: "\n", to: " " }) });
  lines = lines$5;
  for (const e of r.model) {
    const [, lines$6] = $std_list.push({ b: lines, x: e.name + " " + e.value });
    lines = lines$6;
  }
  const $m55 = $std_io.create({ files: files, path: cache_path({ dir: d, key: key }) });
  $m55$match: {
    if ($m55.tag === "Err") {
      const error = $m55.error;
      return undefined;
      break $m55$match;
    }
    if ($m55.tag === "Ok") {
      const value = $m55.value;
      const written = $std_io.write({ file: value, text: $std_text.join({ parts: $std_list.finish({ b: lines }), sep: "\n" }) });
      return undefined;
      break $m55$match;
    }
    $rt.unreachable();
  }
}

