// Generated by onus from module std.duration. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
export function nanos({ d }) {
  return $rt.duration.nanos(d);
}

export function of_millis({ ms }) {
  return $rt.duration.of_millis(ms);
}

