// Generated by onus from module std.float. Do not edit.
import * as $rt from "../onus-runtime/index.js";
export function of({ x }) {
  return $rt.float.of(x);
}

export function classify({ x }) {
  return $rt.float.classify(x);
}

export function to_text({ x }) {
  return $rt.float.to_text(x);
}

export function parse({ t }) {
  return $rt.float.parse(t);
}

