// Generated by onus from module std.grid. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
export function filled({ value, width, height }) {
  return $rt.grid.filled(value, width, height);
}

export function get({ w, h, grid, x, y }) {
  return $rt.grid.get(w, h, grid, x, y);
}

export function set({ w, h, grid, x, y, value }) {
  return $rt.grid.set(w, h, grid, x, y, value);
}

