// Generated by onus from module std.int. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";

const $ob1 = { kind: "overflow", text: "-x within Int", at: "/Users/jamesrandall/code/onus/packages/stdlib/std/int.onus:15:12", def: "abs" };
export function to_text({ x }) {
  return $rt.int.to_text(x);
}

export function floor({ x }) {
  return $rt.int.floor(x);
}

export function abs({ x }) {
  if (x < 0) {
    return $rt.int.neg(x, $ob1);
  }
  return x;
}

export function parse({ t }) {
  return $rt.int.parse(t);
}

