// Generated by onus from module std.list. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";

const $ob1 = { kind: "overflow", text: "len(xs: xs) - 1 within Int", at: "/Users/jamesrandall/code/onus/packages/stdlib/std/list.onus:95:40", def: "reverse" };
const $ob2 = { kind: "overflow", text: "len(xs: xs) - 1 - i within Int", at: "/Users/jamesrandall/code/onus/packages/stdlib/std/list.onus:95:40", def: "reverse" };
export function len({ xs }) {
  return $rt.list.len(xs);
}

export function get({ xs, i }) {
  return $rt.list.get(xs, i);
}

export function is_empty({ xs }) {
  return len({ xs: xs }) === 0;
}

export function replicate({ value, count }) {
  return $rt.list.replicate(value, count);
}

export function append({ xs, x }) {
  return $rt.list.append(xs, x);
}

export function slice({ xs, from, to }) {
  return $rt.list.slice(xs, from, to);
}

export function builder($args) {
  return $rt.list.builder();
}

export function built({ b }) {
  return $rt.list.built(b);
}

export function push({ b, x }) {
  return $rt.list.push(b, x);
}

export function finish({ b }) {
  return $rt.list.finish(b);
}

export function at({ b, i }) {
  return $rt.list.at(b, i);
}

export function pop({ b }) {
  return $rt.list.pop(b);
}

export function map({ xs, f }) {
  let b = builder({  });
  for (const x of xs) {
    const [, b$1] = push({ b: b, x: f(x) });
    b = b$1;
  }
  return finish({ b: b });
}

export function filter({ xs, keep }) {
  let b = builder({  });
  for (const x of xs) {
    if (keep(x)) {
      const [, b$2] = push({ b: b, x: x });
      b = b$2;
    }
  }
  return finish({ b: b });
}

export function fold({ xs, init, step }) {
  let acc = init;
  for (const x of xs) {
    acc = step(acc, x);
  }
  return acc;
}

export function index_of({ xs, x }) {
  const $hi1 = len({ xs: xs });
  for (let i = 0; i < $hi1; i++) {
    if ($rt.eq(get({ xs: xs, i: i }), x)) {
      return { tag: "Some", value: i };
    }
  }
  return { tag: "None" };
}

export function contains({ xs, x }) {
  return index_of({ xs: xs, x: x }).tag === "Some";
}

export function reverse({ xs }) {
  let b = builder({  });
  const $hi4 = len({ xs: xs });
  for (let i = 0; i < $hi4; i++) {
    const [, b$3] = push({ b: b, x: get({ xs: xs, i: $rt.int.sub($rt.int.sub(len({ xs: xs }), 1, $ob1), i, $ob2) }) });
    b = b$3;
  }
  return finish({ b: b });
}

