// Generated by onus from module std.map. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
export function empty($args) {
  return $rt.map.empty();
}

export function size({ m }) {
  return $rt.map.size(m);
}

export function get({ m, key }) {
  return $rt.map.get(m, key);
}

export function put({ m, key, value }) {
  return $rt.map.put(m, key, value);
}

export function dict($args) {
  return $rt.map.dict();
}

export function count({ d }) {
  return $rt.map.count(d);
}

export function set({ d, key, value }) {
  return $rt.map.set(d, key, value);
}

export function find({ d, key }) {
  return $rt.map.find(d, key);
}

export function contains({ d, key }) {
  return $rt.map.contains(d, key);
}

export function remove({ d, key }) {
  return $rt.map.remove(d, key);
}

export function keys({ d }) {
  return $rt.map.keys(d);
}

export function values({ d }) {
  return $rt.map.values(d);
}

