// Generated by onus from module std.option. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
export function is_some({ o }) {
  const $m1 = o;
  $m1$match: {
    if ($m1.tag === "Some") {
      return true;
      break $m1$match;
    }
    if ($m1.tag === "None") {
      return false;
      break $m1$match;
    }
    $rt.unreachable();
  }
}

