// Generated by onus from module std.text. Do not edit.
import * as $rt from "/Users/jamesrandall/code/onus/packages/runtime/dist/index.js";
export function len({ t }) {
  return $rt.text.len(t);
}

export function graphemes({ t }) {
  return $rt.text.graphemes(t);
}

export function bytes({ t }) {
  return $rt.text.bytes(t);
}

export function starts_with({ t, prefix }) {
  return $rt.text.starts_with(t, prefix);
}

export function lower({ t }) {
  return $rt.text.lower(t);
}

export function trim({ t }) {
  return $rt.text.trim(t);
}

export function count({ t }) {
  return $rt.text.count(t);
}

export function code_points({ t }) {
  return $rt.text.code_points(t);
}

export function of_code_points({ cps }) {
  return $rt.text.of_code_points(cps);
}

export function of_code_point({ cp }) {
  return $rt.text.of_code_point(cp);
}

export function slice({ t, from, to }) {
  return $rt.text.slice(t, from, to);
}

export function index_of({ t, needle, from }) {
  return $rt.text.index_of(t, needle, from);
}

export function contains({ t, needle }) {
  return $rt.text.contains(t, needle);
}

export function ends_with({ t, suffix }) {
  return $rt.text.ends_with(t, suffix);
}

export function split({ t, sep }) {
  return $rt.text.split(t, sep);
}

export function join({ parts, sep }) {
  return $rt.text.join(parts, sep);
}

export function repeat({ t, n }) {
  return $rt.text.repeat(t, n);
}

export function replace({ t, from, to }) {
  return $rt.text.replace(t, from, to);
}

export function compare({ a, b }) {
  return $rt.text.compare(a, b);
}

export function upper({ t }) {
  return $rt.text.upper(t);
}

