// Generates packages/runtime/native/unicode_tables.h from the Unicode Character
// Database (16.0.0, the version spec §19.1 pins): grapheme cluster break
// properties, Extended_Pictographic, InCB, Cased and Case_Ignorable, the
// characters JavaScript's `trim` removes, and the default case mappings
// (UnicodeData simple mappings plus SpecialCasing's unconditional ones).
//   node scripts/unicode-tables.mjs <ucd-dir>
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = process.argv[2];
if (dir === undefined) throw new Error('usage: unicode-tables.mjs <ucd-dir>');
const lines = (f) => readFileSync(join(dir, f), 'utf8').split('\n').map((l) => l.split('#')[0].trim()).filter((l) => l.length > 0);
const range = (s) => { const [a, b] = s.split('..'); return [parseInt(a, 16), parseInt(b ?? a, 16)]; };

function ranges(file, pick) {
  const out = [];
  for (const l of lines(file)) {
    const parts = l.split(';').map((x) => x.trim());
    const v = pick(parts);
    if (v === null) continue;
    const [lo, hi] = range(parts[0]);
    out.push([lo, hi, v]);
  }
  out.sort((x, y) => x[0] - y[0]);
  // merge adjacent ranges with the same value
  const merged = [];
  for (const r of out) {
    const last = merged[merged.length - 1];
    if (last !== undefined && last[2] === r[2] && last[1] + 1 === r[0]) last[1] = r[1];
    else merged.push([...r]);
  }
  return merged;
}

const GCB = { Other: 0, CR: 1, LF: 2, Control: 3, Extend: 4, ZWJ: 5, Regional_Indicator: 6, Prepend: 7, SpacingMark: 8, L: 9, V: 10, T: 11, LV: 12, LVT: 13 };
const gcb = ranges('GraphemeBreakProperty.txt', (p) => (p[1] in GCB ? GCB[p[1]] : null));
const extpict = ranges('emoji-data.txt', (p) => (p[1] === 'Extended_Pictographic' ? 1 : null));
const INCB = { Consonant: 1, Extend: 2, Linker: 3 };
const incb = ranges('DerivedCoreProperties.txt', (p) => (p[1] === 'InCB' && p[2] in INCB ? INCB[p[2]] : null));
const cased = ranges('DerivedCoreProperties.txt', (p) => (p[1] === 'Cased' ? 1 : null));
const caseIgnorable = ranges('DerivedCoreProperties.txt', (p) => (p[1] === 'Case_Ignorable' ? 1 : null));

// JavaScript `trim`: WhiteSpace (Zs, TAB, VT, FF, ZWNBSP) and LineTerminator (LF, CR, LS, PS).
const space = [];
for (const l of lines('UnicodeData.txt')) {
  const p = l.split(';');
  if (p[2] === 'Zs') space.push([parseInt(p[0], 16), parseInt(p[0], 16), 1]);
}
for (const cp of [0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x2028, 0x2029, 0xfeff]) space.push([cp, cp, 1]);
space.sort((x, y) => x[0] - y[0]);

const lower = [];
const upper = [];
for (const l of lines('UnicodeData.txt')) {
  const p = l.split(';');
  const cp = parseInt(p[0], 16);
  if (p[12] !== '') upper.push([cp, parseInt(p[12], 16)]);
  if (p[13] !== '') lower.push([cp, parseInt(p[13], 16)]);
}
const lowerSpecial = [];
const upperSpecial = [];
for (const l of lines('SpecialCasing.txt')) {
  const p = l.split(';').map((x) => x.trim());
  if (p.length < 4) continue;
  if (p.length >= 5 && p[4] !== '') continue; // conditional: language-specific, or Final_Sigma handled in code
  const cp = parseInt(p[0], 16);
  const lo = p[1].split(' ').filter((x) => x).map((x) => parseInt(x, 16));
  const up = p[3].split(' ').filter((x) => x).map((x) => parseInt(x, 16));
  if (lo.length !== 1 || lo[0] !== cp) lowerSpecial.push([cp, lo]);
  if (up.length !== 1 || up[0] !== cp) upperSpecial.push([cp, up]);
}
lowerSpecial.sort((a, b) => a[0] - b[0]);
upperSpecial.sort((a, b) => a[0] - b[0]);

const hex = (n) => `0x${n.toString(16).toUpperCase()}`;
const rangeTable = (name, rs) => `static const onus_urange ${name}[] = {\n${rs.map(([lo, hi, v]) => `  {${hex(lo)}, ${hex(hi)}, ${v}},`).join('\n')}\n};\nstatic const int ${name}_n = ${rs.length};\n`;
const mapTable = (name, ms) => `static const onus_umap ${name}[] = {\n${ms.map(([cp, to]) => `  {${hex(cp)}, ${hex(to)}},`).join('\n')}\n};\nstatic const int ${name}_n = ${ms.length};\n`;
const specialTable = (name, ms) => `static const onus_uspecial ${name}[] = {\n${ms.map(([cp, to]) => `  {${hex(cp)}, ${to.length}, {${[to[0] ?? 0, to[1] ?? 0, to[2] ?? 0].map(hex).join(', ')}}},`).join('\n')}\n};\nstatic const int ${name}_n = ${ms.length};\n`;

const out = `/* Generated by scripts/unicode-tables.mjs from the Unicode Character Database 16.0.0. Do not edit. */
#ifndef ONUS_UNICODE_TABLES_H
#define ONUS_UNICODE_TABLES_H
#include <stdint.h>

typedef struct { uint32_t lo; uint32_t hi; uint8_t v; } onus_urange;
typedef struct { uint32_t cp; uint32_t to; } onus_umap;
typedef struct { uint32_t cp; uint8_t n; uint32_t to[3]; } onus_uspecial;

/* Grapheme_Cluster_Break: 0 Other, 1 CR, 2 LF, 3 Control, 4 Extend, 5 ZWJ, 6 Regional_Indicator, 7 Prepend, 8 SpacingMark, 9 L, 10 V, 11 T, 12 LV, 13 LVT. */
${rangeTable('onus_gcb', gcb)}
${rangeTable('onus_extpict', extpict)}
/* InCB: 1 Consonant, 2 Extend, 3 Linker. */
${rangeTable('onus_incb', incb)}
${rangeTable('onus_cased', cased)}
${rangeTable('onus_caseign', caseIgnorable)}
${rangeTable('onus_space', space)}
${mapTable('onus_lower', lower)}
${mapTable('onus_upper', upper)}
${specialTable('onus_lower_special', lowerSpecial)}
${specialTable('onus_upper_special', upperSpecial)}
#endif
`;
writeFileSync(new URL('../packages/runtime/native/unicode_tables.h', import.meta.url), out);
console.log('gcb', gcb.length, 'extpict', extpict.length, 'incb', incb.length, 'cased', cased.length, 'caseign', caseIgnorable.length, 'space', space.length, 'lower', lower.length, 'upper', upper.length, 'lowerSpecial', lowerSpecial.length, 'upperSpecial', upperSpecial.length);
